### ISSUE TITLE
FIGUUR: Onderkaaklengte per jaar slider incorrect

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/reporting-rshiny-grofwildjacht#100]
The graph displaying lower jaw length of *roedeer* does not react correctly to changes in the slider. 
When you switch the source it says it will display the data from 2002 till 2019 but it only shows data from 2014 onwards. When you switch back to the only INBO source the slider is correct again.

Additionally I think the data per source is incorrect. "lengte_mm" is from INBO, "onderkaaklengte_links" is from meldingsformulier en "onderkaaklengte_comp" is for both.
The data from inbo should be from 2002 till 2019 while the data from the meldingsformulier should be from 2014 onwards. 

- [ ] Set correct slider interval 
- [ ] Set correct graph title 
- [ ] Check datasources

**Comment by mvarewyck** [comment]
Apparently, `onderkaaklengte_comp` and `onderkaaklengte_comp_bron` are always missing before 2014, although values for `lengte_mm` exist (see below). That's why the slider currently seems to be incorrect.

```
> xtabs(~ onderkaaklengte_comp_bron + afschotjaar, addNA = TRUE, data = reeEcoData)
                         afschotjaar
onderkaaklengte_comp_bron 2002 2003 2004 2005 2006 2007 2008 2009 2010 2011
        inbo                 0    0    0    0    0    0    0    0    0    0
        meldingsformulier    0    0    0    0    0    0    0    0    0    0
        <NA>              2234 3551 3220 3800 4099 4172 4271 4506 4900 4972
                         afschotjaar
onderkaaklengte_comp_bron 2012 2013 2014 2015 2016 2017 2018 2019
        inbo                 0    0  116  967 2926 1940 1948 1317
        meldingsformulier    0    0 4917 4627 2861 3758 4365 4428
        <NA>              4837 5296  272  176  111   85  135   37
> # Similarly: xtabs(~ is.na(onderkaaklengte_comp) + afschotjaar, data = reeEcoData)
# Values before 2014 are lost in the comp variables
> table(reeEcoData[!is.na(reeEcoData$lengte_mm), "afschotjaar"])

2002 2003 2004 2005 2006 2007 2008 2009 2010 2011 2012 2013 2014 2015 2016 2017 
 640 1185 1239 1589 1683 1608 1804 1645 1878 1844 1732 1891  116  967 2929 1941 
2018 2019 
1948 1317 
```

I checked and data source in code is correct: "lengte_mm" is from INBO, "onderkaaklengte_links" is from meldingsformulier en "onderkaaklengte_comp" is for both.

**Comment by SanderDevisscher** [comment]
@mvarewyck dat zit het probleem in de data prep => ik zal nog eens checken

**Comment by SanderDevisscher** [comment]
> The data from inbo should be from 2002 till 2019 while the data from the meldingsformulier should be from 2014 onwards.

This is incorrect both should be from 2002 onwards

**Comment by eadriaensen** [comment]
For completeness, this concerns Ree, bio-indicator plot: onderkaaklengte per jaar

**Comment by eadriaensen** [comment]
Currently, the following date ranges apply:
* inbo: (`lengte_mm`)
  * 2002-2019
* meldingsformulier: (`onderkaaklengte_links`)
  * 2014-2020 
* both: (`onderkaaklengte_comp`)
  * 2002-2020 - as expected

```
> table(reeEcoData[!is.na(reeEcoData$lengte_mm), "afschotjaar"])

2002 2003 2004 2005 2006 2007 2008 2009 2010 2011 2012 2013 2014 2015 2016 2017 
 640 1185 1239 1589 1683 1608 1804 1645 1878 1844 1732 1891  116  967 2926 1941 
2018 2019 
1948 1335 

> table(reeEcoData[!is.na(reeEcoData$onderkaaklengte_links), "afschotjaar"])

2014 2015 2016 2017 2018 2019 2020 
4994 5494 5558 5588 6208 6333  558 

> table(reeEcoData[!is.na(reeEcoData$onderkaaklengte_comp), "afschotjaar"])

2002 2003 2004 2005 2006 2007 2008 2009 2010 2011 2012 2013 2014 2015 2016 2017 
 640 1185 1239 1589 1683 1608 1804 1645 1878 1844 1732 1891 4960 5572 5787 5695 
2018 2019 2020 
6308 6340  557 
```

Hence, what is shown in the app when selecting `INBO` as data source will be adjusted. (currently ranges from 2014-2019)

**Comment by SanderDevisscher** [comment]
Looks ok, no jaws have been measured yet this year

**Comment by eadriaensen** [comment]
Slider intervals now adjust their minimum value based on the data. I.e. what I reported before:

> inbo: (lengte_mm)
2002-2019
meldingsformulier: (onderkaaklengte_links)
2014-2020
both: (onderkaaklengte_comp)
2002-2020 - as expected

**Comment by SanderDevisscher** [comment]
Ok in docker

**Comment by SanderDevisscher** [comment]
@jimcasaer en @SanderDevisscher zullen de oorsprong van de data opnieuw bekijken => loopt nog steeds iets fout.

@mvarewyck @eadriaensen dit is normaal iets aan de data kant. als de jaarrange datadriven is zou dat automatisch moeten worden aangepast. Correct ?

**Comment by eadriaensen** [comment]
> @mvarewyck @eadriaensen dit is normaal iets aan de data kant. als de jaarrange datadriven is zou dat automatisch moeten worden aangepast. Correct ?

Inderdaad, het minimum van de '_Periode_' slider bij deze grafiek geeft het minimum jaartal weer dat in de data gevonden wordt na filteren op de gekozen '_Data bron voor onderkaaklengte_'

**Comment by SanderDevisscher** [comment]
@eadriaensen we hebben een tijdelijke fix uitgewerkt aan de data kant. Deze houd in dat de historische onderkaaklengtes, waarvan we atm niet weten of ze uit het labo of meldingsformulieren komen, weggeschreven worden in onderkaaklengte_comp. Dit zorgt ervoor dat de data van zowel meldingsformulier als labo van 2014 tot nu lopen terwijl die van de combinatie van 2002 tot nu. 
Tijdens het testen van de app bleek zich echter het volgende voor te doen. De grafieken van INBO en Meldingsformulieren zijn ok, maar de gecombineerde grafiek heeft de juiste titel (2002 tot 2020) maar de foute data (2014 tot 2020). Zou het kunnen dat voor de data onderkaaklengte_comp o.b.v. de data in ecology herberekend wordt ? en de titel niet ?

**Comment by eadriaensen** [comment]
@SanderDevisscher 
Dit zou opgelost moeten zijn.
Zoals de app aangeeft werden enkel die observaties waarvan de bron "inbo" of "meldingsformulier" is, weergegeven in de grafiek wanneer `INBO en meldingsformulier` wordt gekozen.
Observaties waarvoor bron ongekend is, werden eruit gefilterd. I.e. alle observaties van 2002 tot 2014.

Van jouw verduidelijking hierboven leid ik af dat de figuur wel degelijk ook de observaties moet bevatten waarvoor de bron missing is (`NA`) wanneer men `INBO en meldingsformulier` kiest. Dat is hoe ik het momenteel heb geimplementeerd.
Eventueel die keuze updaten naar `INBO, meldingsformulier en ongekend` ter verduidelijking vanwaar de data van voor 2014 komt? 
Laat maar weten of/hoe ik dat moet aanpassen.

FYI: de titel werd bepaald voor het wegfilteren van de `NA` values voor bron, waardoor deze wel de correcte range (2002-2020) weergaf.

**Comment by SanderDevisscher** [comment]
@eadriaensen feitelijk zijn de NA's niet onbekend, ze zijn ofwel afkomstig van INBO ofwel van de meldingsformulieren.  Deze werden in analogie met de kolom onderkaaklengte_comp samengevoegd (als inbo-data voorhanden dan inbo-data anders meldingsformulier-data). Alleen kunnen we van de historische gegevens (voorlopig) niet meer achterhalen wat de bron van onderkaaklengte is. Dit werd ook nergens beschreven met dit als gevolg.  De keuze voor `INBO en meldingsformulier` is dus correct. Ik hoop tegen de volgende update de historische data terug opgebouwd te hebben gebaseerd op de ruwe data. Dit vergt wel een hoop werk en testen om zeker te zijn dat er geen te grote verschillen zijn met de huidige data. 
Misschien kunnen we onder de tekst een disclaimer toevoegen in de aard van `Opmerking: Van de historische data (2002 - 2013) kan de bron momenteel niet achterhaald worden.`
@jimcasaer @RuttenAnneleen wat denken jullie ?

**Comment by eadriaensen** [comment]
@SanderDevisscher 
Momenteel zo, inclusief jouw disclaimer:

![onderkaaklengteINBO](https://user-images.githubusercontent.com/40824010/79362524-fe5a7200-7f46-11ea-8667-df9db32ec740.png)

**Comment by SanderDevisscher** [comment]
ok now
