### ISSUE TITLE
schadedata provincie voeren

### ISSUE THREAD

**Issue by mvarewyck** [inbo/reporting-rshiny-grofwildjacht#101]
There are 3 subjects in schadedata with provincie "Voeren". These are all for "wild zwijn". 
Currently:
* In the barplot, Voeren is shown as separate province category. 
* In the maps, Voeren is not shown as a separate province. This because the user can select multiple "wildsoort" and Voeren makes only sense for "wild zwijn".

Questions:
* Is it confusing to have different provinces for the map and bar plot?
* Can the province be renamed to "Limburg" or keep "Voeren"?

![image](https://user-images.githubusercontent.com/22143743/69150825-bb9c8700-0ad9-11ea-9b05-0b86a93d4c02.png)

**Comment by SanderDevisscher** [comment]
Voeren as a provincie is an artifact from the shooting - data (also only Valwild if I'm correct).

This gives 2 options:

1. Remove Voeren as option and set it as Limburg
2. Re-Georef non-valwild data to Voeren 

@jimcasaer what do you prefer?

**Comment by jimcasaer** [comment]
@SanderDevisscher I would suggest we drop Voeren - given the fact that it s also a municipality so data can be visualised seperatly when needed
