### ISSUE TITLE
Start with all types of Gewas selected

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/reporting-rshiny-grofwildjacht#104]
Currently the website opens with only Silomais selected.
I think it is best to initially select all Gewas types or at least the top 5 damaged crops.

Atm the list is very long but with the implementation of [#331](https://github.com/inbo/backoffice-wild-analyse/issues/331) of the backoffice-wild-analyse - repo this should be greatly reduced.

@jimcasaer what do you prefer; 

- [x] All
- [ ] Top 5
- [ ] As is (only silomais)

**Comment by jimcasaer** [comment]
indicated preference for all as start
