### ISSUE TITLE
Write texts for wildschade 

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/reporting-rshiny-grofwildjacht#105]
spreekt voor zich

**Comment by SanderDevisscher** [comment]
@jimcasaer ik ben de door de [tekst](https://drive.google.com/open?id=1RC66JFVXXC5ZapRWca9X8GozUyinZVS9) voor de wildschade app gegaan. 

je vind hem hier terug: https://drive.google.com/open?id=1RC66JFVXXC5ZapRWca9X8GozUyinZVS9 

gelieve verder werken in dit drive bestand zodat we geen VersieN_final_vx_af_...  krijgen

**Comment by eadriaensen** [comment]
@jimcasaer @SanderDevisscher 
Kunnen jullie mij iets laten weten van zodra de tekstjes definitief zijn? Dan zet ik ze dan pas tussen de code.

**Comment by jimcasaer** [comment]
Eva,

De tekstjes worden hier vandaag en morgen nog eens doorgenomen en gecorrigeerd door wat collega's.

Ok voor jou als je ze donderdag in de loop van de voormiddag krijgt ?

**Comment by eadriaensen** [comment]
oke, prima.

**Comment by eadriaensen** [comment]
FYI: ik de screenshot van de tabel ivm types gewas schade vervangen door de meer up to date versie.

**Comment by SanderDevisscher** [comment]
@eadriaensen de tekst is afgewerkt

**Comment by eadriaensen** [comment]
@SanderDevisscher ok!
