### ISSUE TITLE
Wettelijk bepaalde schade indicatoren

### ISSUE THREAD

**Issue by jimcasaer** [inbo/reporting-rshiny-grofwildjacht#107]
Het MB van 2017 legt in het kader van de FBZ volgende indicatoren
best eens kijken of en hoe we die kunnen visualiseren (zie ook ideeën in ppt
hier staat wel per hok van vijf op vijf maar ik zou het zeker ook visualiseren zoals we het nu doen op kaart en in grafieken

![image](https://user-images.githubusercontent.com/17747176/70353307-68faf300-186d-11ea-88a8-1ddfe1ff0d06.png)

**Comment by SanderDevisscher** [comment]
Voor stvz ivm UTM 5x5 weergave van de schadegevallen zie issue [#372](https://github.com/inbo/backoffice-wild-analyse/issues/372)

**Comment by SanderDevisscher** [comment]
pull request staat klaar voor review in backoffice

**Comment by mvarewyck** [comment]
When will these data be available for us to include in the app?

**Comment by eadriaensen** [comment]
5x5 UTM is beschikbaar in de map.
TODO: voeg provinciegrenzen toe aan map igv 5x5 UTM

**Comment by eadriaensen** [comment]
- Added province borders 
- Download data: replaced column "value" by "aantal" (everywhere in wildschade)

**Comment by eadriaensen** [comment]
TODO: how to deal with Brussels? Set grey or adjust shape file 5x5 utm

**Comment by SanderDevisscher** [comment]
remaining indicators can not be calculated based on current data
