### ISSUE TITLE
Table wildschade per voertuig & gewas

### ISSUE THREAD

**Issue by mvarewyck** [inbo/reporting-rshiny-grofwildjacht#109]
Add new table to wildschade tab, similar to tableProvince.R
![wildschade](https://user-images.githubusercontent.com/22143743/71819180-746b5500-308b-11ea-874b-fe2aa6374a1d.png)

Option to select year and region: Vlaanderen, Provincie, FBZ
Report number of cases per level of "schadeCode": Voertuig - PERSLTSL, GNPERSLTSL, ONBEKEND; Gewas - WLSCHD, VRTSCHD

**Comment by eadriaensen** [comment]
- [ ] Always show all columns of the filtered selection
- [x] Slider for period instead of for 1 year
- [x] Download not working? Or due to Sander's computer? Fixed by rearranging code structure for datatable creation.
- [x] Update labels to more readable ones VRTG -> voertuig
