### ISSUE TITLE
Default file-naming of the `download`

### ISSUE THREAD

**Issue by stijnvanhoey** [inbo/reporting-rshiny-grofwildjacht#11]
Currently, `plotx-dataDownload` (with x=1,2,...) could be improved by providing a more illustrative file naming.

**Comment by mvarewyck** [comment]
It is easy for us to name it as "data_<name of the plot function>.csv". Is this ok - names will have English part then..

**Comment by mvarewyck** [comment]
Correction: `"data_<name of the plot function>.csv"`

**Comment by stijnvanhoey** [comment]
That would be good.
