### ISSUE TITLE
Error when testing grofwild app

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/reporting-rshiny-grofwildjacht#113]
Ik heb de data voor de app upgedate en in de [Update_Source_Data_050220](https://github.com/inbo/reporting-rshiny-grofwildjacht/tree/Update_Source_Data_050220) upgeload. 
Deze branch is op de wildschade branch gebaseerd. 

Als ik probeer de app lokaal te testen krijg ik onderstaande error:

> Error in if (any(rawData$onderkaaklengte_comp[rawData$ageGender == "Geit"] >  : 
>   missing value where TRUE/FALSE needed
> Called from: loadRawData(dataDir = dataDir, type = "eco")

Zouden jullie eens kunnen testen of de error zich ook voordoet bij jullie ? 

Ik ben ondertussen aan het pogen docker aan de praat te krijgen om rariteiten op vlak van packages uit te sluiten.

**Comment by mvarewyck** [comment]
Ok, I will check what's going on.
