### ISSUE TITLE
Error: no table for gerapporteerd aantal schadegevallen per gewas

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/reporting-rshiny-grofwildjacht#115]
Als ik deze settings gebruik
![image](https://user-images.githubusercontent.com/16779320/73853309-f1c3ea00-4830-11ea-90ba-950d645033d4.png)

krijg ik deze error:
![image](https://user-images.githubusercontent.com/16779320/73853255-de188380-4830-11ea-839c-5d5b6a4b3126.png)

terwijl er een tabel getoond zou moeten worden.

**Comment by eadriaensen** [comment]
Dag Sander,

Deze tabel is nog in progress.
De betreffende (niet-werkende) code heb ik gepushed ivm de nieuwe branch met nieuwe data te kunnen binnen halen. 
In een volgende commit zou deze tabel prima moeten werken.
