### ISSUE TITLE
ERROR: Rare tekens in de tekstjes 

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/reporting-rshiny-grofwildjacht#117]
Lokaal loopt er nog iets mis met rare tekens in de tekstjes zie onder:
![image](https://user-images.githubusercontent.com/16779320/74011548-75441f00-4988-11ea-84a8-8bcbbbe0379d.png)

![image](https://user-images.githubusercontent.com/16779320/74011602-8db43980-4988-11ea-8b3c-56d9ca3ac9cc.png)

![image](https://user-images.githubusercontent.com/16779320/74011877-306cb800-4989-11ea-8e57-144d1179312c.png)

**Comment by eadriaensen** [comment]
@SanderDevisscher kan je de drie errors checken of het is opgelost zo?

**Comment by SanderDevisscher** [comment]
@eadriaensen issue is opgelost

**Comment by SanderDevisscher** [comment]
@eadriaensen ik heb nog een set rare tekens gevonden:
![image](https://user-images.githubusercontent.com/16779320/74036874-67f55780-49bd-11ea-9cc6-422b429f1854.png)
