### ISSUE TITLE
Landkaart 1  - wildzwijn 2020 error

### ISSUE THREAD

**Issue by eadriaensen** [inbo/reporting-rshiny-grofwildjacht#118]
Voor filter op 2020 geeft landkaart 1 (en niet landkaart 2) een error.
Enkel voor Wild zwijn zijn er reeds meldingen van 2020 beschikbaar, het probleem doet zich enkel daar voor.

![wildZwijn2020](https://user-images.githubusercontent.com/40824010/74015092-416cf780-4990-11ea-865d-a6cd0270f76b.png)

**Comment by SanderDevisscher** [comment]
@eadriaensen @mvarewyck enig idee hoe dit komt ? ligt het aan de data ?

**Comment by eadriaensen** [comment]
@mvarewyck werkt eraan. o.a. verschil in hoofdlettergebruik van gemeenten

**Comment by mvarewyck** [comment]
`Herk-De-Stad` in wildschade data versus `Herk-de-Stad` in shape data. Ik overschrijf nu de locatie namen met die uit shape data. Extra tests geschreven om dit te voorkomen. Lijkt nu te werken.

**Comment by SanderDevisscher** [comment]
Welke kolom gebruik je dan voor de gemeentenaam ? De kolom "GemNaam_Georef" is volledig in uppercase. of herberekenen jullie dat obv de Niscode ?

**Comment by mvarewyck** [comment]
Ik heb de code beetje opgekuist. We gebruikten een file gemeentecodes.csv om postcode en niscode te matchen bij geo data voor grofwild, maar nu was die (verkeerdelijk) ook gebruikt om de gemeente naam uit te halen. Nu is het als volgt geimplementeerd voor zowel geo data (grofwild) en wildschade data:

1. Create shape data in `readShapeData()`. For file gemeentecodes.csv, this will update the gemeente NAAM according to those used shape data, matching based on NIS code.
2. Read geo data grofwild. Match postcode to gemeente NAAM using gemeentecodes.csv
3. Read wildschade data. Match niscode to gemeente NAAM using gemeentecodes.csv

I also updated the `tests/testData.R` such that when testing the R package it will throw an error if any of the names in the loaded geo or wildschade data does not match the gemeente NAAM used in the shape data.

**Comment by SanderDevisscher** [comment]
Seems to work now
