### ISSUE TITLE
Error: Type - field does not work 

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/reporting-rshiny-grofwildjacht#120]
@eadriaensen @mvarewyck tijdens het testen van de grofwildapp in de testomgeving (UAT) blijkt het type veld bij de FIGUUR: Gewicht per jaar niet meer te werken. Normaal kan je hier kiezen uit bvb jaarlingbok maar het veld blijft maagdelijk leeg.

![image](https://user-images.githubusercontent.com/16779320/74160479-c456b200-4c1d-11ea-8b42-bbaa429ec713.png)

**Comment by mvarewyck** [comment]
Apparently some variables were renamed, I'll update the code.

**Comment by mvarewyck** [comment]
I found following (small) inconsistency between the two bio-indicator plots:
* Figuur: Onderkaaklengte per jaar - user can only choose between 3 types (Reekits, Bokkits, Geitkits)
* Figuur: Gewicht per jaar - user can choose between all types of Ree
Please let me know if this should be changed.

**Comment by jimcasaer** [comment]
This inconsistency can stay - is related to a slightly different question and possible anwers - is ok like this

**Comment by SanderDevisscher** [comment]
Lokaal lijkt de issue opgelost. Maar ik moet nog testen in de UAT.
