### ISSUE TITLE
Add download knop landkaart 2

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/reporting-rshiny-grofwildjacht#121]
Is er een reden waarom landkaart 2 niet van download knop is voorzien ?

**Comment by eadriaensen** [comment]
.png file beschikbaar stellen van de map is straightforward.
Maar bij het downloaden van de bijhorende data: hoe willen jullie dit en welke kolommen moeten er beschikbaar zijn?
Enkele opties:
1) een rij per schadegeval met gemeente - postcode - niscode - provincie - wildsoort - seizoen
2) een rij per gemeente/wildsoort/seizoen combinatie met gemeente - postcode - niscode - provincie - wildsoort - seizoen - aantal gevallen
3) deze data niet beschikbaar maken
4) ...

**Comment by SanderDevisscher** [comment]
@eadriaensen gezien de info die nu weergegeven wordt in de popup zou ik kiezen voor optie 1 uitgebreid met het schade type (decrypted, zie #127). 

wat denk jij @jimcasaer ?

**Comment by eadriaensen** [comment]
Downloads van figuur en data is nu mogelijk.
TODO: include postcode in datadownload & schade type decrypted.

**Comment by eadriaensen** [comment]
TODO: schade type decrypted.

**Comment by SanderDevisscher** [comment]
Data download works locally 
Map download does not

**Comment by eadriaensen** [comment]
Can you re-test with latest commit? And try out different options/wildsoorten/..?
For me, locally, everything seems to work fine.

**Comment by SanderDevisscher** [comment]
@eadriaensen the problem still persist (with all maps) for me locally.  
However I think there is still a huge difference between your "locally" and mine. 
I have not yet managed to run the app using docker and still use R-studio to do testing.
Whenever I run the app "locally" I get the following question, which I ignore : 


```
These packages have more recent versions available.
Which would you like to update?
 1: All                                                
 2: CRAN packages only                                 
 3: None                                               
 4: sp          (1.3-2        -> 1.4-0       ) [CRAN]  
 5: plotly      (4.9.1        -> 4.9.2       ) [CRAN]  
 6: INBOtheme   (a22da7b60... -> 24f14a9c2...) [GitHub]
 7: devtools    (2.2.1        -> 2.2.2       ) [CRAN]  
 8: DT          (0.11         -> 0.12        ) [CRAN]  
 9: mime        (0.8          -> 0.9         ) [CRAN]  
10: digest      (0.6.23       -> 0.6.25      ) [CRAN]  
11: rlang       (0.4.3        -> 0.4.4       ) [CRAN]  
12: scales      (1.0.0        -> 1.1.0       ) [CRAN]  
13: tidyr       (1.0.0        -> 1.0.2       ) [CRAN]  
14: hexbin      (1.28.0       -> 1.28.1      ) [CRAN]  
15: dplyr       (0.8.3        -> 0.8.4       ) [CRAN]  
16: data.table  (1.12.6       -> 1.12.8      ) [CRAN]  
17: callr       (3.3.2        -> 3.4.2       ) [CRAN]  
18: cli         (1.1.0        -> 2.0.1       ) [CRAN]  
19: covr        (3.3.2        -> 3.4.0       ) [CRAN]  
20: remotes     (2.1.0        -> 2.1.1       ) [CRAN]  
21: roxygen2    (7.0.0        -> 7.0.2       ) [CRAN]  
22: rstudioapi  (0.10         -> 0.11        ) [CRAN]  
23: rversions   (2.0.0        -> 2.0.1       ) [CRAN]  
24: testthat    (2.3.0        -> 2.3.1       ) [CRAN]  
25: BH          (1.69.0-1     -> 1.72.0-3    ) [CRAN]  
26: farver      (2.0.1        -> 2.0.3       ) [CRAN]  
27: fansi       (0.4.0        -> 0.4.1       ) [CRAN]  
28: pillar      (1.4.2        -> 1.4.3       ) [CRAN]  
29: vctrs       (0.2.0        -> 0.2.3       ) [CRAN]  
30: stringi     (1.4.3        -> 1.4.6       ) [CRAN]  
31: curl        (4.2          -> 4.3         ) [CRAN]  
32: yaml        (2.2.0        -> 2.2.1       ) [CRAN]  
33: tidyselect  (0.2.5        -> 1.0.0       ) [CRAN]  
34: gh          (1.0.1        -> 1.1.0       ) [CRAN]  
35: processx    (3.4.1        -> 3.4.2       ) [CRAN]  
36: ps          (1.3.0        -> 1.3.2       ) [CRAN]  
37: prettyunits (1.0.2        -> 1.1.1       ) [CRAN]  
38: xfun        (0.11         -> 0.12        ) [CRAN]  
```

**Comment by eadriaensen** [comment]
@SanderDevisscher 

This is a nice Docker tutorial for beginners:
https://docker-curriculum.com/

It's also worth having a look at https://www.shinyproxy.io/deploying-apps/ with some info on using docker specifically within shinyproxy.

I will check your R session info later to see if I can pinpoint to an exact package that might be worth updating.

**Comment by SanderDevisscher** [comment]
> This is a nice Docker tutorial for beginners:
> https://docker-curriculum.com/

Thanks

**Comment by mvarewyck** [comment]
Good to know: there is a script available (/scripts/reporting-rshiny-grofwildjacht.sh) with all commands to build the latest docker image

**Comment by eadriaensen** [comment]
@SanderDevisscher 

> Probably the "error" stems from anyone of these packages not being up to date.

This could be an explanation, but not necessarily since you are able to download other maps without problems.

An educated guess (based on the involved packages and their dependencies for the map and download) would be to update the `sp` package and the `scales` package, but I don't have high hopes that this would fix it.

```
install.packages("sp")
install.packages("scales")
```

**Comment by SanderDevisscher** [comment]
issue is fixed locally (in docker)
