### ISSUE TITLE
ERROR: Regio-schaal grafiek faunabeheerzones

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/reporting-rshiny-grofwildjacht#122]
@mvarewyck @eadriaensen 
Wanneer je de periode veranderd van de standaard 2014-2020 naar bvb 2014 - 2019 krijg je onderstaande error.  
De error doet zich enkel voor als je het eindjaar aanpast. Als je de periode later laat beginnen bvb 2015-2020 is er geen probleem. 2015-2019 geeft dezelfde error. 
De error komt ook enkel voor bij de faunabeheerzones weergave. Andere weergaven inclu. gemeenten in faunabeheerzone geven deze error niet. 

![image](https://user-images.githubusercontent.com/16779320/74219788-1515eb80-4cae-11ea-83d6-a449fd3f5bf8.png)

Laten jullie weten of dit op te lossen is tegen deze middag ? Zoniet verhuizen we de issue naar volgende update (17/2).

**Comment by SanderDevisscher** [comment]
PS: error is niet faunabeheerzone specifiek

**Comment by mvarewyck** [comment]
@SanderDevisscher I will investigate now

**Comment by SanderDevisscher** [comment]
@mvarewyck is het in orde ?

**Comment by mvarewyck** [comment]
ja, afschotjaar was factor ipv numeric, heb ik aangepast.
ik heb alle regio-schalen en species getest, geeft geen errors meer

**Comment by SanderDevisscher** [comment]
Net lokaal getest is in orde
