### ISSUE TITLE
Jaren in grafieken als discrete waardes

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/reporting-rshiny-grofwildjacht#123]
@mvarewyck @eadriaensen nu dat je de jaren veranderd hebt van factor nr numeric worden de jaren weergegeven als continue variabele.  

![image](https://user-images.githubusercontent.com/16779320/74238857-eceeb280-4cd6-11ea-8b9d-5371d4ec0f7a.png)

Dit is een issue die niet voor de release opgelost moet worden => Nieuwe branch

**Comment by mvarewyck** [comment]
Seems not to throw an error anymore when using the factor again. Other reason for issue #122? I can't reproduce anymore..

**Comment by SanderDevisscher** [comment]
Can't reproduce #122 locally 
#123 is fixed locally
