### ISSUE TITLE
FIGUUR: Gerapporteerd aantal schadegevallen per jaar en variabele: Cryptische legenda vervangen

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/reporting-rshiny-grofwildjacht#124]
De cryptische legenda's die nu weergegeven worden zouden in analogie met "TABEL: Gerapporteerde aantal schadegevallen per type schade" moeten vervangen worden.

**Comment by eadriaensen** [comment]
This is fixed now.

**Comment by SanderDevisscher** [comment]
fixed locally
