### ISSUE TITLE
Teksten wildschade layouten

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/reporting-rshiny-grofwildjacht#125]
Voorlopige placeholder issue
in overleg met @jimcasaer

**Comment by SanderDevisscher** [comment]
@jimcasaer hier moeten we dringend eens voor samenzitten

**Comment by SanderDevisscher** [comment]
@jimcasaer tenzij we hier volgende week nog ergens tijd voor maken => update van april

**Comment by SanderDevisscher** [comment]
@mvarewyck @eadriaensen kunnen jullie een gdoc aanmaken waar de huidige tekstjes in staan zodat jim er eens door kan gaan ?

kunnen jullie dan ook de layout overpakken ?

**Comment by eadriaensen** [comment]
oke

**Comment by eadriaensen** [comment]
Vind hier de link naar het document:
https://docs.google.com/document/d/1_dikYcRU8JnKqb3E6khZPGZnSrW56Hd-kY0BJBI_8oU/edit?usp=sharing

Ik heb met headings gewerkt, dus normaal staat er links een overzichtelijke inhoudstafel.
Layout zoals momenteel in de app (i.e. laatste versie van fbz-overleg branch die nu met master is gemerged).
Via de link kan je normaal editen. Laat maar weten moest dat delen niet gelukt zijn.

Reminder: bio-indicatoren enkel van toepassing wanneer je ree selecteert.

**Comment by mvarewyck** [comment]
@berthuygens Hebben jullie bij INBO een css-file? We zouden deze eenvoudig kunnen toevoegen aan R shiny. De css file beschrijft hoe titels moeten gekleurd en gestyled worden volgens jullie huisstijl.

**Comment by SanderDevisscher** [comment]
@jimcasaer we moeten nog een stukje uitleg voorzien voor de aangepaste filter

**Comment by SanderDevisscher** [comment]
> stukje tekst aanpassen zodat mensen weten dat ze soort en type schade moeten kiezen voor het opmaken van figuren
> @RuttenAnneleen : zie jij het zitten van hier een voorstel voor te doen ?
dat is gelinkt aan deze issue

**Comment by SanderDevisscher** [comment]
@eadriaensen we hebben de aanpassingen aan de tekst afgerond. 
In de .gdoc staan enkele zaken tss */* deze zijn dynamische velden die ofwel data driven (zoals de beschikbare gegevens) of keuze afhankelijk zijn (zoals de namen van de geselecteerde regio's).
Gewone / staat voor stukken zonder tekst.

**Comment by SanderDevisscher** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Aanpassen  tekst voor wildschade online](https://trello.com/c/1SlCo8mk/71-aanpassen-tekst-voor-wildschade-online)

**Comment by eadriaensen** [comment]
> ![](https://camo.githubusercontent.com/193766a3b9959c5f4ed5cd8cf3251d015e839d51/68747470733a2f2f6769746875622e7472656c6c6f2e73657276696365732f696d616765732f6d696e692d7472656c6c6f2d69636f6e2e706e67) [Aanpassen tekst voor wildschade online](https://trello.com/c/1SlCo8mk/71-aanpassen-tekst-voor-wildschade-online)

De link werkt niet voor mij.
Is daar essentiele informatie te vinden?

![trelloError](https://user-images.githubusercontent.com/40824010/78261829-05719100-7500-11ea-83fc-fade8b9d4e3d.png)

**Comment by SanderDevisscher** [comment]
> > ![](https://camo.githubusercontent.com/193766a3b9959c5f4ed5cd8cf3251d015e839d51/68747470733a2f2f6769746875622e7472656c6c6f2e73657276696365732f696d616765732f6d696e692d7472656c6c6f2d69636f6e2e706e67) [Aanpassen tekst voor wildschade online](https://trello.com/c/1SlCo8mk/71-aanpassen-tekst-voor-wildschade-online)
> 
> De link werkt niet voor mij.
> Is daar essentiele informatie te vinden?

Neen dat is onze project mangement - tool blijkbaar als je deze issue vermeld plaatst die hier een link.

**Comment by eadriaensen** [comment]
De teksten zijn nu volledig aangepast.

**Comment by SanderDevisscher** [comment]
> De teksten zijn nu volledig aangepast.

ik zal het volgende week eens bekijken.

**Comment by SanderDevisscher** [comment]
@eadriaensen de subtitel "Schademeldingen" staat nu onder de overzicht tabellen, boven Landkaart 1. Terwijl we dit bedoelden tussen het Keuzemenu en de overzicht tabellen.  Kan je die nog verplaatsen.

**Comment by SanderDevisscher** [comment]
done
