### ISSUE TITLE
UTM 5x5 ook voor afschot

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/reporting-rshiny-grofwildjacht#126]
- [x] @SanderDevisscher issue [#394](https://github.com/inbo/backoffice-wild-analyse/issues/394) van backoffice
- [x] @SanderDevisscher afschotdata + utm5 uploaden
- [x] @mvarewyck @eadriaensen zodra vorige stap afgerond is code voorzien om utm 5 weer te geven

**Comment by eadriaensen** [comment]
5x5 UTM niveau nu ook beschikbaar voor afschot. Volledig analoog met wildschade.

![INBOgrofwild5x5UTM](https://user-images.githubusercontent.com/40824010/75173859-d3665580-572f-11ea-83cb-1349af02e6f8.png)

**Comment by SanderDevisscher** [comment]
fixed locally
