### ISSUE TITLE
Gerapporteerd aantal schadegevallen: popup info cryptische schade types vertalen

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/reporting-rshiny-grofwildjacht#127]
Momenteel staat er nog bvb VRTG bij schade type in de info popup. deze zou in analogie met TABEL: Gerapporteerde aantal schadegevallen per type schade vertaald moeten worden.

**Comment by eadriaensen** [comment]
TODO: decrypt in landkaart 2

**Comment by eadriaensen** [comment]
This is fixed now.

**Comment by SanderDevisscher** [comment]
fixed locally
