### ISSUE TITLE
Subtitel Landkaart 2 klopt niet

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/reporting-rshiny-grofwildjacht#128]
Bij landkaart 2 wordt dezelfde subtitel gebruikt als bij landkaart 1, namelijk
_"Gerapporteerd aantal schadegevallen voor wild zwijn, ree (2018 tot 2020)"._
Op dit kaartje worden echter geen aantallen weergegeven. 
Daarom stel ik voor de subtitel te vervangen in bvb:
_"Schadegevallen van wild zwijn, ree per seizoen (2018 tot 2020)"_

@jimcasaer wat denk jij ?

**Comment by eadriaensen** [comment]
Subtitel aangepast zoals voorgesteld.

**Comment by SanderDevisscher** [comment]
fixed locally
