### ISSUE TITLE
Add kaartje in type schade

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/reporting-rshiny-grofwildjacht#129]
@jimcasaer 
Mij lijkt het interessant om in analogie met of als optie van landkaart 2 een kaartje te maken waar de types schade (vrtg, gewas, ...) weergegeven worden.

**Comment by SanderDevisscher** [comment]
@mvarewyck @eadriaensen dit kaartje mag toegevoegd worden als keuzeoptie (seizoen of schadetype) bij landkaart 2 in analogie met aantal & aantal/ha bij landkaart 1.
Als titel stel ik "Schadegevallen van wild zwijn, ree per type (2018 tot 2020)" voor.
Als detail niveau stel ik het niveau van persoonletsel voor.

@jimcasaer ben je het hier mee eens ?

**Comment by eadriaensen** [comment]
Momenteel geimplementeerd zoals hieronder weergegeven.
Alternatieve keuze voor Variabele is 'Seizoen' wat de map zoals eerst weergeeft.

Titel is momenteel "Schadegevallen van wild zwijn, ree per variabele (2018 tot 2020)" naar analogie met klikbare figuur 2: Gerapporteerd aantal schadegevallen per jaar en variabele.

![INBOscreenshotLandkaart2](https://user-images.githubusercontent.com/40824010/74927560-25c61000-53d8-11ea-8dbd-cd41662c0d12.png)


@SanderDevisscher De bijhorende teskt van Landkaart 2 dient nog aangepast te worden obv deze veranderingen. Laat maar weten wat dat moet worden.
Andere feedback ook welkom

**Comment by SanderDevisscher** [comment]
@eadriaensen dat ziet er al heel goed uit. 

wat bedoel je met 
> Titel is momenteel "Schadegevallen van wild zwijn, ree per variabele (2018 tot 2020)"
wil dit zeggen dat je het nog gaat aanpassen om per seizoen/per schadetype te worden ? 

@eadriaensen kan je de popup ook zo aanpassen dat wanneer je schadetype selecteert het seizoen in de popup weergegeven wordt en visa versa ?

Voorstel nieuwe tekstje:
De onderstaande kaart geeft de geografische spreiding van de individuele schadegevallen _**per variabele**_ weer. **_Mogelijke variabelen zijn seizoen & schadetype_**. Welke schadegevallen getoond worden, hangt af van je filterkeuzes in het hoofdmenu.

Voor deze kaart kan je bovendien zelf de periode bepalen die je wil weergeven. Door met de muis een bepaald schadegeval te selecteren, krijg je verdere informatie over dit schadegeval (jaar, wildsoort, gemeente, **_schadetype/seizoen_**).

@jimcasaer wat denk jij ivm het tekstje ?

**Comment by eadriaensen** [comment]
Titel aangepast zodat die mee verandert afhankelijk van de gekozen variabele.

Tekst aangepast zoals voorgesteld. Latere aanpassingen altijd mogelijk.

Pop-up voor **seizoen** voorlopig niet gewijzigd:
* Jaar
* Wildsoort
* Gemeente
* Schade type _[dit is de basiscode]_
![inboLandkaart2Seizoen](https://user-images.githubusercontent.com/40824010/74941186-ea850a80-53f2-11ea-89e6-3515769f9b52.png)

Pop-up in geval van **Type Schade** zoals hierboven, inclusief seizoen:
* Jaar
* Wildsoort
* Gemeente
* Schade type _[dit is de basiscode]_
* Seizoen
![inboLandkaart2TypeSchade](https://user-images.githubusercontent.com/40824010/74941366-2e780f80-53f3-11ea-9134-7fd567becaa2.png)

**Comment by SanderDevisscher** [comment]
fixed locally
