### ISSUE TITLE
Hoe worden frisling verdeeld in FIGUUR: Leeggewicht per leeftijdscategorie ??

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/reporting-rshiny-grofwildjacht#130]
Hoe wordt er atm met frislingen uit het e-loket (is.na(leeftijd_maanden) & leeftijd_comp == "frisling") omgegaan? 
Worden deze verwijderd ? => tekst aanpassen 
Worden deze in een frisling categorie ondergebracht ? => script & tekst aanpassen 

Is het mogelijk een bron optie toe te voegen in analogie met de reeën ?
waarvoor geld:

| Leeftijd_Maanden | leeftijd_comp | leeftijd_categorie_inbo | leeftijd_categorie_meldingsformulier | leeftijd_categorie_inbo & meldingsformulier |
|------------------|---------------|-------------------------|--------------------------------------|---------------------------------------------|
| 0-5              | Frisling      | Frisling(<6m)           | Frisling                             | Frisling                                    |
| 6-11             | Frisling      | Frisling(>6m)           | Frisling                             | Frisling                                    |
| 12-24            | Overloper     | Overloper               | Overloper                            | Overloper                                   |
| 24+              | Volwassen     | Volwassen               | Volwassen                            | Volwassen                                   |
| NA               | Frisling      | NULL                    | Frisling                             | Frisling                                    |
| NA               | Overloper     | NULL                    | Overloper                            | Overloper                                   |
| NA               | Volwassen     | NULL                    | Volwassen                            | Volwassen                                   |

@jimcasaer correct ?

**Comment by mvarewyck** [comment]
Momenteel worden deze verwijderd, 1928 cases (in boxAgeWeight.R):
Opsplitsing Frisling:
- Als `leeftijd_maanden` < 6 dan is `leeftijd_comp` "Frisling (<6m)" anders "Frisling (>6m)".
- Als `leeftijd_maanden` NA dan is `leeftijd_comp` NA.

@SanderDevisscher Ik vond ook groot aantal met `leeftijd_maanden` gekend, maar `leeftijd_comp` "Onbekend"?

```
> toInspect <- with(ecoData, which(leeftijd_comp == "Onbekend" & !is.na(leeftijd_maanden)))
> ecoData[head(toInspect), 
c("wildsoort", "afschotjaar", "leeftijd_maanden", "leeftijd_comp", "leeftijd_comp_bron")]

      wildsoort afschotjaar leeftijd_maanden leeftijd_comp leeftijd_comp_bron
1830 Wild zwijn        2014               18      Onbekend               <NA>
1831 Wild zwijn        2014                6      Onbekend               <NA>
1832 Wild zwijn        2014                4      Onbekend               <NA>
1833 Wild zwijn        2014                4      Onbekend               <NA>
1834 Wild zwijn        2014                5      Onbekend               <NA>
1835 Wild zwijn        2014               60      Onbekend               <NA>

> xtabs(~ afschotjaar + wildsoort, ecoData[toInspect, ])
           wildsoort
afschotjaar Damhert Wild zwijn
       2014       2        234
       2015       0        238
       2016       0          3
       2017       0          1

> xtabs(~ afschotjaar + leeftijd_comp_bron, ecoData[toInspect, ], addNA = TRUE)
           leeftijd_comp_bron
afschotjaar <NA>
       2014  236
       2015  238
       2016    3
       2017    1
```

**Comment by SanderDevisscher** [comment]
@mvarewyck can you test if large number of leeftijd_maanden gekend, maar leeftijd_comp "Onbekend" still remain after upload of new data?

**Comment by eadriaensen** [comment]
Only three such cases (Damhert) remain in the newly uploaded data:

```
toInspect <- with(ecoData, which(leeftijd_comp == "Onbekend" & !is.na(leeftijd_maanden)))
ecoData[toInspect, c("wildsoort", "afschotjaar", "leeftijd_maanden", "leeftijd_comp", "leeftijd_comp_bron")]

      wildsoort afschotjaar leeftijd_maanden leeftijd_comp leeftijd_comp_bron
2476    Damhert        2015               25      Onbekend               <NA>
16015   Damhert        2014               15      Onbekend               <NA>
16016   Damhert        2014               15      Onbekend               <NA>
```

**Comment by SanderDevisscher** [comment]
I still have to determine the correct age classes for damhert with @jimcasaer but this is less urgent because damhert does not yet have a age distribution graph.
