### ISSUE TITLE
Dringend: wildschade pagina voor deze release te voorzien van watermerk

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/reporting-rshiny-grofwildjacht#131]
Is het mogelijk om de wildschade pagina te voorzien van "Voorlopige versie" - watermerk en een grijze achtergrond ? Zoja kunnen jullie dat zo snel mogelijk uitrollen ?

**Comment by jimcasaer** [comment]
nog even verduidelijken : gaat over een licht grijs watermerk schuin over
pagina (cfr worddocumenten) - kan dat in webpagina ?


Op wo 12 feb. 2020 18:36 schreef Sander Devisscher <notifications@github.com

**Comment by mvarewyck** [comment]
Huidig voorstel in master branch

![watermark](https://user-images.githubusercontent.com/22143743/74374736-48a46300-4ddf-11ea-94b5-c77eb7b867d2.png)

**Comment by SanderDevisscher** [comment]
Ok voor mij, @jimcasaer ?

**Comment by jimcasaer** [comment]
ok !

Op wo 12 feb. 2020 22:59 schreef Sander Devisscher <notifications@github.com

**Comment by SanderDevisscher** [comment]
@mvarewyck @eadriaensen 

door de watermark kan ik geen tabellen of grafieken meer openklikken of landkaarten toevoegen

**Comment by eadriaensen** [comment]
Can reproduce, investigating now.

**Comment by eadriaensen** [comment]
should be fixed now. Can you confirm?

**Comment by SanderDevisscher** [comment]
testing locally

**Comment by SanderDevisscher** [comment]
fixed locally => deploying to UAT

**Comment by SanderDevisscher** [comment]
issue persists in UAT :-(

**Comment by SanderDevisscher** [comment]
> issue persists in UAT :-(

at least on my desktop, on my laptop everything runs ok :-/

**Comment by eadriaensen** [comment]
Kan je wat meer info geven over de UAT server?
Hoe oud is die?

Gebruik je dezelfde webbrowser om de app te viewen op UAT als locaal?
Is er een mogelijkheid om op UAT te bekijken op het probleem zich ook voordoet met andere webbrowsers?

Mogelijk alternatief:
Een grote, rode disclaimer bovenaan de pagina "Dit is een tijdelijke versie" en het watermerk terug weghalen.

**Comment by jimcasaer** [comment]
nadeel van zo een disclaimer is dat je die niet meer ziet als je naar beneden scrollt - niet ?

**Comment by eadriaensen** [comment]
> nadeel van zo een disclaimer is dat je die niet meer ziet als je naar beneden scrollt - niet ?

Klopt..

**Comment by SanderDevisscher** [comment]
@eadriaensen Ik heb mijn desktop herstart en de issue is van de baan, dit duidt volgens mij op een cache issue bij chrome. 

> Kan je wat meer info geven over de UAT server?
Hoe oud is die?

geen idee @berthuygens ?

> Gebruik je dezelfde webbrowser om de app te viewen op UAT als locaal?

nee, lokaal run ik de app in Rstudio met deze code:
```
devtools::install_github("inbo/reporting-rshiny-grofwildjacht@Update_Source_Data_ddmmjj", subdir = "reporting-grofwild")
devtools::build(pkg = "reporting-grofwild")
devtools::install(pkg = "reporting-grofwild")
library(reportingGrofwild)
reportingGrofwild::runWildApp()
```
en voor de UAT gebruik ik deze link https://grofwildjacht-dev.inbo.be/

> Is er een mogelijkheid om op UAT te bekijken op het probleem zich ook voordoet met andere webbrowsers?

Chrome => na restart geen issue meer
Firefox => geen issue 
internet explorer => geen issue

=> in orde dus

**Comment by eadriaensen** [comment]
Prima.
