### ISSUE TITLE
aanpassen start waarden tijdreeks en jaar 

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/reporting-rshiny-grofwildjacht#132]
Momenteel wordt de site geopend met alle data geselecteerd voor de tijd reeksen en 2016 (Landkaart 1 bij afschot) of het laatste jaar als default jaar keuze.

Aangezien we meestal nog niet over alle data van het laatste jaar beschikken en het niet nuttig is deze niet raadpleegbaar te maken. Stel ik het volgende voor:
- De default tijdreeks wordt voor alle grafieken/tabellen "eerste jaar <-> huidigjaar -1" 
- De default jaar - keuze wordt "huidig jaar - 1"

**Comment by eadriaensen** [comment]
> en het niet nuttig is deze niet raadpleegbaar te maken

@SanderDevisscher  Begrijp ik het goed dat de data van huidigejaar nergens beschikbaar dient te zijn? Niet in keuze voor tijdsreeksen, noch in de overzichtstabelletjes bovenaan (wildschade), noch in data beschikbaar voor download?

**Comment by SanderDevisscher** [comment]
@eadriaensen neen, de data van het huidige jaar moet **wel beschikbaar blijven**, zowel als keuze voor tijdreeksen, voor overzichttabellen, als jaar keuze en als data om te downloaden.

De default (als je de site opent) moet veranderd worden in "huidig jaar -1" zodat je op eerste zicht een "correct" beeld krijgt van de evolutie van de meldingen en niet direct geconfronteerd wordt met het feit dat er data ontbreekt van het huidige jaar (sterke daling aantal meldingen voor huidig jaar). Maar wel met behoud van de mogelijkheid, om door de jaar- keuzes of tijdreeksen te wijzigen, de gegevens die reeds opgenomen zijn voor het huidige jaar raad te plegen.

**Comment by eadriaensen** [comment]
Oke, bedankt voor de verduidelijking.

**Comment by eadriaensen** [comment]
Ik heb dit aangepast.

Huidige aanpak is om de default geselecteerde waardes/maximum waardes te zetten op `defaultYear`.
 
`defaultYear` ("huidig jaar -1") wordt globaal bepaald. Dit op basis van `datum (jaar) van raadplegen app - 1`.
 
Dit kan ook gemakkelijk manueel op een bepaald jaar gezet worden moest de huidige aanpak niet ideaal zijn tijdens einde jaar / begin nieuwe jaar, maar dit vergt manueel onderhoud).

**Comment by SanderDevisscher** [comment]
fixed locally
