### ISSUE TITLE
INBO in header off screen

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/reporting-rshiny-grofwildjacht#133]
Het stukje tekst "INBO" bovenaan links van de pagina is niet volledig zichtbaar (zowel firefox als chrome) 

![Chrome](https://user-images.githubusercontent.com/16779320/74776277-91549400-5297-11ea-9363-5356e87d7677.png)

![Firefox](https://user-images.githubusercontent.com/16779320/74776337-a7faeb00-5297-11ea-9edd-f4f643d80b5c.png)

**Comment by eadriaensen** [comment]
Can reproduce (tested in Chrome and Firefox) by enlarging and minimizing window to different sizes. Tabs remain visible at all times, INBO header should act same way.

**Comment by SanderDevisscher** [comment]
Do you mean you can't reproduce?

Ifso will check on other device.


Op wo 19 feb. 2020 09:40 schreef eadriaensen <notifications@github.com>:

**Comment by eadriaensen** [comment]
I can indeed reproduce, when I change window size. (by default no issues for me, but I have very wide screens.) I think this issue is related to screen width. Anyhow, solution would be that text  remains visible irrespective of window size.

This was mainly info for future me, when working on it.

**Comment by SanderDevisscher** [comment]
fixed locally
