### ISSUE TITLE
error when building to docker

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/reporting-rshiny-grofwildjacht#135]
When trying to build the app to docker using powershell and executing the following code:

1. `cd documents/github/reporting-rshiny-grofwildjacht` (local map synced with github desktop)
2. `docker build -t openanalytics/wildapp .`

I get this error:
> Step 11/16 : COPY $latestApp /root/
> COPY failed: stat /var/lib/docker/tmp/docker-builder581853135/reporting-grofwild.tar.gz: no such file or directory

**Comment by mvarewyck** [comment]
Could you check whether the .tar.gz folder is actually in the folder from which you run the Dockerfile?
```
> ls | grep .tar.gz
reporting-grofwild.tar.gz
```

**Comment by SanderDevisscher** [comment]
I have more than one .tar.gz in my folder :-/

![image](https://user-images.githubusercontent.com/16779320/75253865-ac675c80-57df-11ea-9d14-0ae574481e57.png)

rename the latest ?

**Comment by mvarewyck** [comment]
It's better to create a new tar as in the script
`tar -zcvf reporting-grofwild.tar.gz reporting-grofwild`

**Comment by SanderDevisscher** [comment]
> Good to know: there is a script available (/scripts/reporting-rshiny-grofwildjacht.sh) with all commands to build the latest docker image

**Comment by SanderDevisscher** [comment]
when I use the following commands in powershell

- `cd documents/github/reporting-rshiny-grofwildjacht` 
- `docker pull openanalytics/r-base`
- `rm reporting-grofwild.tar.gz`
- `tar -zcvf reporting-grofwild.tar.gz reporting-grofwild`

I get this error:

> reporting-grofwild/tar (child):
exec: No such file or directory
tar (child): Error is not recoverable: exiting now
reporting-grofwild/DESCRIPTION
reporting-grofwild/inst/
reporting-grofwild/inst/extdata/
reporting-grofwild/inst/extdata/communes.geojson
/Rtools/bin/tar: reporting-grofwild.tar.gz: Cannot write: Broken pipe
/Rtools/bin/tar: Child returned status 2
/Rtools/bin/tar: Error is not recoverable: exiting now

**Comment by mvarewyck** [comment]
Could it be that you can't create the tar file with that command because you are on a Windows machine? 
Then I would just rename the latest, as you suggested before;
or try: https://superuser.com/a/244706

**Comment by SanderDevisscher** [comment]
using R to build the .tar.gz and then renaming it seems to work

**Comment by SanderDevisscher** [comment]
It works
