### ISSUE TITLE
add version identifier to site 

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/reporting-rshiny-grofwildjacht#138]
@mvarewyck @eadriaensen is it possible to add some kind of version indicator to the site to check if building of site was succesfull?

**Comment by eadriaensen** [comment]
Included package version in app title and in title shown on tab in webbrowser

![inboPackageVersion](https://user-images.githubusercontent.com/40824010/75970494-b4ef1f80-5ed0-11ea-8e0f-2dff655b2369.png)

**Comment by SanderDevisscher** [comment]
works
