### ISSUE TITLE
Satelliet foto als achtergrond bij schademeldingen

### ISSUE THREAD

**Issue by RuttenAnneleen** [inbo/reporting-rshiny-grofwildjacht#141]
Misschien is het duidelijker en handiger voor mensen als ze kunnen inzoomen op de locatie van een schadegeval en zich beter kunnen oriënteren als de achtergrond een satellietfoto is ipv een kaart.

**Comment by SanderDevisscher** [comment]
@jimcasaer denk je hier nog eens aan ?

**Comment by SanderDevisscher** [comment]
@mvarewyck @eadriaensen ter verduidelijking, het gaat hier over landkaart 2

**Comment by SanderDevisscher** [comment]
@eadriaensen is it possible to enable this by default ?

**Comment by eadriaensen** [comment]
Done

**Comment by SanderDevisscher** [comment]
Ok in docker
