### ISSUE TITLE
Filter data schadegevallen

### ISSUE THREAD

**Issue by RuttenAnneleen** [inbo/reporting-rshiny-grofwildjacht#142]
Intuïtief lijkt het mij makkelijker om bij de filter data standaard niets ingevuld te hebben en dat de mensen via het dropdown menu zelf moeten kiezen welke soort, welke soort schade etc..
Nu moet je toch wel even de tijd nemen om te bekijken wat er allemaal in de tabellen staat, dit lijkt me makkelijker te begrijpen als je direct zelf kan kiezen wat je in de tabellen zelf wilt zien staan.

**Comment by jimcasaer** [comment]
@RuttenAnneleen : mijn gevoel is dat dit effectief best is zoals jij voorstelt voor wat betreft de wildsoort en het type schade maar eens je die gekozen hebt zou ik de twee filters wel automatisch laten invullen -- wat denk jij ?

**Comment by RuttenAnneleen** [comment]
Ja, die laatste 2 filters zijn inderdaad niet van belang om zelf in te vullen denk ik dus akkoord!

**Comment by eadriaensen** [comment]
Dit is geimplementeerd nu. Plots en maps zijn te zien zodra er een keuze gemaakt is voor "wildsoort" en "type schade"

**Comment by SanderDevisscher** [comment]
fixed, but some explanation needed ! #125

**Comment by jimcasaer** [comment]
stukje tekst aanpassen zodat mensen weten dat ze soort en type schade moeten kiezen voor het opmaken van figuren 
 @RuttenAnneleen : zie jij het zitten van hier een voorstel voor te doen ?

**Comment by RuttenAnneleen** [comment]
@jimcasaer: Komt in orde!

**Comment by RuttenAnneleen** [comment]
@jimcasaer: suggesties zijn toegevoegd in Google docs file. Eventueel nog te bespreken als niet alles duidelijk is

**Comment by SanderDevisscher** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Aanpassen  tekst voor wildschade online](https://trello.com/c/1SlCo8mk/71-aanpassen-tekst-voor-wildschade-online)
