### ISSUE TITLE
Grafiek: Cumulatief aantal uitheemse soorten

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/reporting-rshiny-grofwildjacht#146]
gebaseerd op deze indicator: https://trias-project.github.io/indicators/indicator_cumulative_number.html

gebaseerd op deze data: https://raw.githubusercontent.com/trias-project/indicators/master/data/interim/data_input_checklist_indicators.tsv

en de volgende selectie opties:
- [ ]  periode (slider)
- [ ]  taxonomy (kingdom, phylum, ... t.e.m. family)
- [ ]  locality (België (BE), Vlaanderen (BE-VLG), Brussel (BE-BRU), Wallonië (BE-WAL)) => BE als default
- [ ]  degree of establishment
- [ ]  pathway_level 1 & pathway_level 2
- [ ]  habitat
- [ ]  source

**Comment by eadriaensen** [comment]
De poging om deze grafiek to produceren, met behulp van de `indicator_total_year()` functie van het `trias` pakket, is niet succesvol geweest.

Bij het bekijken van de source-code op https://github.com/trias-project/trias/blob/master/R/indicator_total_year.R kon ik de error manueel reproduceren op lijn 93:

` if (nrow(filter(df, is.na(first_observed)) > 0)) { `

Dit dient volgens mij aangepast te worden naar

` if (nrow(filter(df, is.na(first_observed))) > 0) { `
(positie haakjes aanpassen.)

Heb issue aangemaakt in de trias github: https://github.com/trias-project/trias/issues/55

**Comment by eadriaensen** [comment]
> De poging om deze grafiek to produceren, met behulp van de `indicator_total_year()` functie van het `trias` pakket, is niet succesvol geweest.
> 
> Bij het bekijken van de source-code op https://github.com/trias-project/trias/blob/master/R/indicator_total_year.R kon ik de error manueel reproduceren op lijn 93:
> 
> `if (nrow(filter(df, is.na(first_observed)) > 0)) {`
> 
> Dit dient volgens mij aangepast te worden naar
> 
> `if (nrow(filter(df, is.na(first_observed))) > 0) {`
> (positie haakjes aanpassen.)
> 
> Heb issue aangemaakt in de trias github: [trias-project/trias#55](https://github.com/trias-project/trias/issues/55)

Deze bug is gefixt

**Comment by SanderDevisscher** [comment]
Should be OK after re installation TrIAS Package (#177)
