### ISSUE TITLE
Grafiek: Aantal uitheemse soorten per pathway

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/reporting-rshiny-grofwildjacht#147]
gebaseerd op deze indicator: https://trias-project.github.io/indicators/indicator_pathways.html
maar weergegeven als barchart (x = pathway level 2 & y = aantal introduced taxa) met facet wrap op pathway level 1. Zie ook https://github.com/trias-project/indicators/issues/75.

gebaseerd op deze data: https://raw.githubusercontent.com/trias-project/indicators/master/data/interim/data_input_checklist_indicators.tsv

en de volgende selectie opties:
- [ ]  periode (slider)
- [ ]  taxonomy (kingdom, phylum, ... t.e.m. family)
- [ ]  locality (België (BE), Vlaanderen (BE-VLG), Brussel (BE-BRU), Wallonië (BE-WAL)) => BE als default
- [ ]  degree of establishment
- [ ]  pathway_level 1 & pathway_level 2
- [ ]  habitat
- [ ]  source

**Comment by eadriaensen** [comment]
@SanderDevisscher @damianooldoni 
Is there an available R function that is used to generate the barcharts as dispalyed in [trias-project/indicators#75](https://github.com/trias-project/indicators/issues/75#issuecomment-609445265) that I can use ?.

**Comment by damianooldoni** [comment]
I am implementing it and I am working on making it part of TrIAS package today.

**Comment by eadriaensen** [comment]
@damianooldoni thanks, and thanks for the update.

**Comment by damianooldoni** [comment]
@eadriaensen : as I found an important bug (https://github.com/trias-project/trias/issues/57) in functions `indicator_*_year()` of trias package, I worked today on solving it and as I was working on such functions I finally wrote unit-tests for them (https://github.com/trias-project/trias/issues/57) and I solved some other things (e.g. no ggplot warnings, better documentation). Please, reload `trias` package via `devtools::install_github("trias-project/trias")`.

I will working on pathways on Thursday. However, if you want already see something working, I put my code in a public gist right now: https://gist.github.com/damianooldoni/20e8066c3966bc5ce032f14186a0515c. I have still to implement the suggestions of in https://github.com/trias-project/indicators/issues/75#issuecomment-610293086

**Comment by SanderDevisscher** [comment]
The pathway graphs are ready in the TrIAS package and can be used after reinstalation of the TrIAS package

**Comment by eadriaensen** [comment]
For personal reference: use `visualize_pathways_level2()` function from `trias`  for this graph.

**Comment by eadriaensen** [comment]
Using `visualize_pathways_level2()`-function from `trias` I am able to generate a graph such as asked for a particular pathway_level1 :

![pwlevel2](https://user-images.githubusercontent.com/40824010/86112846-c9cb7080-bac8-11ea-82e1-a8cf5583693f.png)

In the app, the user can select multiple pathways at level 1 to display.
How to deal with this? Do I plot the individual plots below each other (or in a grid)? Or is there a facetting functionality foreseen in the `trias` package that I missed?
