### ISSUE TITLE
Mediaan en min/max toevoegen aan data download jaarlijks afschot

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/reporting-rshiny-grofwildjacht#150]
Momenteel wordt enkel het geobserveerde percentage afschot voor het jaar zelf uitgevoerd. Hier zou de mediaan, min en max van de referentie periode aan toegevoegd moeten worden.

**Comment by eadriaensen** [comment]
Aangepast nu. 

Kolommen hebben momenteel volgende namen:

`Datum (half-maand resolutie) | Geobserveerd percentage | Mediaan (2009-2018) | Min (2009-2018) | Max (2009-2018)`

**Comment by SanderDevisscher** [comment]
I think 5470996ec4d9ae9faf81eb0679930d28240532c4 has caused an error. 
Will revert commit!

**Comment by SanderDevisscher** [comment]
@mvarewyck @eadriaensen is it possible a NA values in type column causes problems ?

**Comment by jimcasaer** [comment]
I was recently also wondering if we should not restyle this figure towards something like this 
![image](https://user-images.githubusercontent.com/17747176/77425719-749a0780-6dd3-11ea-9126-deee19893ac9.png)

**Comment by SanderDevisscher** [comment]
@jimcasaer heb je geen betere afbeelding ?

**Comment by jimcasaer** [comment]
ik ga op zoek -- weet ook niet of het in r kan maar ging over barplotmet data van het jaar en gem + min / max als min/slot/max (komt uit excel)
ik zal er later op de dag een maken

**Comment by SanderDevisscher** [comment]
error is solved, NA - values in type column were the cause.

Also export looks good now. 
@eadriaensen @mvarewyck Only 1 suggestion, is it possible to include type info in export filename ?

**Comment by eadriaensen** [comment]
> @eadriaensen @mvarewyck Only 1 suggestion, is it possible to include type info in export filename ?

Done. Also included in filename for other plots where 'type' is selected

**Comment by SanderDevisscher** [comment]
Ok
