### ISSUE TITLE
Weergeven van gebruikt deel van het totaal aan afschotgegevens voor bepaald jaar

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/reporting-rshiny-grofwildjacht#151]
Doordat het door georeferentie makkelijker is om een geschoten dier een aan een gemeente te koppelen dan aan een UTM 5x5. lijkt het ons een goed idee om onder de eerste kaart van het afschot weer te geven welk aandeel van de gegevens voorzien is van info. Dit zowel voor UTM, gemeente, faunabeheerzone als provincie.

In analogie met FIGUUR: leeftijdscategorie obv onderkaak en meldingsformulier.

**Comment by eadriaensen** [comment]
Dit is geimplementeerd voor alle regio-schalen behalve 'Vlaanderen'

**Comment by SanderDevisscher** [comment]
looks great
