### ISSUE TITLE
Legenda verkeersongelukken upgraden

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/reporting-rshiny-grofwildjacht#152]
Verkeersongelukken zouden als volgt moeten aangepast worden in de verschillende tabellen en legenda van de wildschade pagina:

| Huidige vorm             | Upgrade                       |
|--------------------------|-------------------------------|
| Geen personen met letsel | Verkeersongeluk zonder letsel |
| Personen met letsel      | Verkeersongeluk met letsel    |
| Onbekend                 | Verkeersongeluk onbekend      |

**Comment by eadriaensen** [comment]
Aangepast nu.

**Comment by SanderDevisscher** [comment]
ok
