### ISSUE TITLE
Set Regio-schaal graph y-axis to integer when aantal is selected

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/reporting-rshiny-grofwildjacht#154]
The y-axis displays fractional values when dealing with low numbers this does not make sense !

example:
![newplot](https://user-images.githubusercontent.com/16779320/77310910-70041f00-6cff-11ea-80ab-af9ed72055d3.png)

this should be whole numbers !

In case of number/100ha fractional numbers are to be expected

**Comment by SanderDevisscher** [comment]
Error with fractional numbers is fixed however in docker the height of the graph is number dependant. When low numbers of animals are shot ea <5 the graph displays a reduced height, this is not beautiful. 
@eadriaensen is it possible to at least display up to 5 ?

**Comment by eadriaensen** [comment]
This is now adjusted

![yaxisMinimum](https://user-images.githubusercontent.com/40824010/78115419-15577b00-7403-11ea-97be-a1e98f1fa9ce.png)

**Comment by SanderDevisscher** [comment]
ok
