### ISSUE TITLE
Time scale for UTM5 should be 2014 onwards

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/reporting-rshiny-grofwildjacht#155]
Currently the period for UTM5 goes from 2006 onwards while the georeferencing only takes place from 2014 onwards. This causes the wrong trend to be displayed.
the period for UTM5 should be changed to 2014 onwards.

**Comment by eadriaensen** [comment]
fixed in latest commit ccdfe15

**Comment by SanderDevisscher** [comment]
fixed
