### ISSUE TITLE
Remove "voorlopige versie" watermark

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/reporting-rshiny-grofwildjacht#156]
The "voorlopige versie" watermark (implemented for #131) is still present in the UAT while absent when testing in docker!
This should be disabled for the coming release (asap).

**Comment by eadriaensen** [comment]
This is due to merging of latest update (fbz-overleg branch; without watermark) into master branch (with watermark).
I will remove the watermark both in master branch and in current dev branch (updateApril) such that the watermark is gone for good.

**Comment by SanderDevisscher** [comment]
@eadriaensen have you implemented this allready ?

**Comment by eadriaensen** [comment]
Doing this now.

**Comment by SanderDevisscher** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Reporting-rshiny: Suggestie barplot+errorplot Percentage jaarlijks afschot](https://trello.com/c/MzX6wjne/62-reporting-rshiny-suggestie-barploterrorplot-percentage-jaarlijks-afschot)
