### ISSUE TITLE
All wildschade graphs should start at 2018

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/reporting-rshiny-grofwildjacht#157]
Currently gemeente (binnen faunabeheerzone) & faunabeheerzone have graphs and sliders at landkaart 1 that start at 2014. 

These graphs should start at 2018 instead.

**Comment by eadriaensen** [comment]
Should be fixed now. for these two region levels it was hardcoded on 2014 apparently.

**Comment by SanderDevisscher** [comment]
> Should be fixed now. for these two region levels it was hardcoded on 2014 apparently.

a relic of the hunting page I presume

**Comment by SanderDevisscher** [comment]
fixed
