### ISSUE TITLE
Suggestie barplot+errorplot Percentage jaarlijks afschot

### ISSUE THREAD

**Issue by RuttenAnneleen** [inbo/reporting-rshiny-grofwildjacht#158]
Suggestie uitwerken om huidige grafiek voor percentage jaarlijks afschot duidelijker te maken. 

- Testdataset maken uit ruwe data op grofwildwebsite

- Waarschijnlijk zal de combinatie van een barplot en errorplot een oplossing bieden

**Comment by RuttenAnneleen** [comment]
Branch '158-suggestie-afschotgrafiek' werd hiervoor aangemaakt

**Comment by RuttenAnneleen** [comment]
@jimcasaer: ik heb 2 suggesties gedaan, je bekijkt het maar eens als het nu duidelijker is en dan bespreken we het!

**Comment by SanderDevisscher** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Reporting-rshiny: Suggestie barplot+errorplot Percentage jaarlijks afschot](https://trello.com/c/MzX6wjne/62-reporting-rshiny-suggestie-barploterrorplot-percentage-jaarlijks-afschot)

**Comment by RuttenAnneleen** [comment]
@eadriaensen : In overleg met @SanderDevisscher en @jimcasaer zijn we tot de conclusie gekomen om grafiek suggestie 1 in script [PercentageJaarlijksAfschot_suggestie](https://github.com/inbo/reporting-rshiny-grofwildjacht/blob/158-suggestie-afschotgrafiek/reporting-grofwild/R/PercentageJaarlijksAfschot_suggestie.Rmd] in Branch '158-suggestie-afschotgrafiek' hiervoor te nemen

**Comment by eadriaensen** [comment]
@RuttenAnneleen 
oke, ik ga ermee verder!

**Comment by eadriaensen** [comment]
@RuttenAnneleen @SanderDevisscher @jimcasaer 

Ik ben bezig met de code voor deze grafiek aan te passen cfr het voorstel.
Met het nieuwe voorstel doet de situatie zoals hieronder getoond zich soms voor, nl. zwevend error balken:

![percJaarlijksAfschotZwevend](https://user-images.githubusercontent.com/40824010/78916298-919a3000-7a8d-11ea-8563-d423068a442f.png)


Dit is afhankelijk van het geselecteerde jaar en de referentieperiode (hier 2014-2018).
Dit komt in de grafiek die tot nu werd gebruikt ook voor: `huidig geobserveerd` (paars) ligt dan niet in de `min-max` (groene) regio.
Ter vergelijking:

![percJaarlijksAfschotZwevend_oudePlot](https://user-images.githubusercontent.com/40824010/78916618-08372d80-7a8e-11ea-9ca7-c64139ddfe1b.png)



Ga ik nog steeds verder met het nieuwe voorstel?

**Comment by SanderDevisscher** [comment]
@jimcasaer @RuttenAnneleen Persoonlijk gaat mijn voorkeur uit naar de huidige versie van deze grafiek. Ik heb het overigens ook gevraagd aan mijn vrouw en zij vind de onderstaande grafiek ook duidelijker. Een bedenking echter is dat het kan zijn dat dit het gevolg is van het gebrek aan verschillende kleuren in de bovenste grafiek.  Voorstel hieromtrent, als we hiermee verder gaan, doorzichtig groen voor de balken en paars voor de error vlaggen.

**Comment by jimcasaer** [comment]
dan houden we gewoon de oude versie - wat denk jij anneleen ?

jim


Op do 9 apr. 2020 18:54 schreef Sander Devisscher <notifications@github.com

**Comment by RuttenAnneleen** [comment]
Ik vind geen van beide echt optimaal :) 
Misschien dat extra kleurtjes bij de barplot of minder gegevens op de originele plot het duidelijker maakt?

**Comment by eadriaensen** [comment]
@RuttenAnneleen @SanderDevisscher @jimcasaer 

Hier de versie met aangepaste kleuren (en legende) zodat jullie de keuze kunnen maken:
**LET OP**: het kleurgebruik is nu omgekeerd! Huidig geobserveerd is groen, referentieperiode is paars. In de oude grafiek is dit net omgekeerd: zie onderaan.

![percJaarlijksAfschotZwevend_kleur](https://user-images.githubusercontent.com/40824010/78978280-c6ec5f80-7b19-11ea-8d65-be79e03ed7ff.png)



Opnieuw, ter vergelijking, de grafiek die tot nu werd gebruikt:
![percJaarlijksAfschotZwevend_oudePlot](https://user-images.githubusercontent.com/40824010/78978343-e3889780-7b19-11ea-9dc1-cfe126fd8775.png)

**Comment by SanderDevisscher** [comment]
@eadriaensen met kleuren is een aanzienlijke verbetering qua leesbaarheid. 
Maar de onderste/oude grafiek blijft het duidelijkst vind ik. Een suggestie ter verbetering van de oude grafiek is de positie van de legenda van nieuwe over te nemen. Overigens is de uniforme verdeling van het afschot niet jaar afhankelijk. Of die daardoor wel of niet weergegeven moet worden, laat ik in het midden. 
@jimcasaer @RuttenAnneleen Wat denken jullie ?

**Comment by RuttenAnneleen** [comment]
Ik vind de onderste grafiek nog altijd te veel info/te veel aspecten bevatten. Mijn suggesties als we voor deze grafiek blijven gaan:

- Inderdaad de lijn  van uniforme verdeling weglaten zoals @SanderDevisscher voorstelt

- Geen puntjes op de lijn van Huidig geobserveerd

- Lijn mediaan dunner maken zodat deze meer op de achtergrond komt

- Legende aanpassen zoals @SanderDevisscher voorstelt

**Comment by RuttenAnneleen** [comment]
Na overleg met @jimcasaer denken we misschien toch dat de tweede grafiek-suggestie die ik had gedaan dan beide bovenstaande grafieken het best combineert:
![image](https://user-images.githubusercontent.com/34440484/79226108-20c49080-7e5e-11ea-9da4-cdd902bac986.png)
Dit met bovenstaande kleuren is dan misschien het duidelijkst?

**Comment by eadriaensen** [comment]
Oke, ik ga ernee aan de slag

**Comment by eadriaensen** [comment]
Hierbij de tweede grafiek suggestie van @RuttenAnneleen , uitgewerkt met de kleuren zoals voorheen.
Oude grafiek ter referrentie. De kleuren komen terug overeen.

![percJaarlijksAfschotVoorstel2](https://user-images.githubusercontent.com/40824010/79237874-f5966d00-7e6e-11ea-9615-368ee9c27164.png)

![percJaarlijksAfschotZwevend_oudePlot](https://user-images.githubusercontent.com/40824010/79238059-32626400-7e6f-11ea-806c-ae8342ad2a6e.png)


Versei 2 met omgekeerde kleuren, ter volledigheid:
![percJaarlijksAfschotVoorstel2_inverted](https://user-images.githubusercontent.com/40824010/79238846-29be5d80-7e70-11ea-8685-14ec42074e64.png)

**Comment by SanderDevisscher** [comment]
@eadriaensen kan je van versie 2 van de nieuwe grafiek hetzelfde voorbeeld weergeven ? m.a.w. 2012 vs 2014-2018?

**Comment by eadriaensen** [comment]
@SanderDevisscher ik heb het aangepast. Zie boven.

**Comment by RuttenAnneleen** [comment]
Zou het duidelijker zijn om de balken op de voorgrond te zetten maar een zekere transparantie te geven zodat de min-max op de achtergrond zichtbaar blijft?

**Comment by SanderDevisscher** [comment]
> Zou het duidelijker zijn om de balken op de voorgrond te zetten maar een zekere transparantie te geven zodat de min-max op de achtergrond zichtbaar blijft?

Hangt er volgens mij van af wat je wilt weergeven. 
Ligt de nadruk op de afwijking (meer/minder) ten opzicht van de referentie dan denk ik dat versie 2 het beste is. Dit omdat de afwijking hier duidelijker achter de referentie uitkomt.
Ligt de nadruk echter op het huidige jaar dan denk ik dat je voorstel of de huidige grafiek het beste past. Omdat je dan de referentie naar de achtergrond verhuisd.

**Comment by SanderDevisscher** [comment]
@eadriaensen is het mogelijk de aanpassing van deze grafiek uit de aankomende update (deze week) te halen tot we de knoop finaal hebben doorgehakt ?
@RuttenAnneleen @jimcasaer kunnen we zo snel mogelijk deze knoop doorhakken.

**Comment by eadriaensen** [comment]
@SanderDevisscher 
oke, de initiele grafiek wordt terug getoond voorlopig.

**Comment by RuttenAnneleen** [comment]
@eadriaensen : Na het nog eens besproken te hebben met @jimcasaer en @SanderDevisscher denken we dat de laatste grafiek (dus blauwe balken, paarse min-max wolk) het beste is maar dan wel met de balken naar de voorgrond met transparantie zodat de paarse wolk op de achtergrond zit maar wel duidelijk blijft.

**Comment by eadriaensen** [comment]
Ik heb de aanpassing gedaan en geimplementeerd.
Huidige grafiek:

![percJaarlijksAfschot_newgraph](https://user-images.githubusercontent.com/40824010/79362228-9efc6200-7f46-11ea-810f-24b281a7c8c3.png)

**Comment by RuttenAnneleen** [comment]
Voor mij is deze versie het meest duidelijk!

**Comment by jimcasaer** [comment]
eenmaal andermaal verkocht ! anders kan Sander nooit verder :-)

**Comment by SanderDevisscher** [comment]
oef :-p
