### ISSUE TITLE
Grafiek titels Referentie en Regio-Schaal aanpassen

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/reporting-rshiny-grofwildjacht#161]
De huidige grafiektitels zouden moeten vervangen worden door:
#### Referentie
Gerapporteerd afschot `Wildsoort` in Vlaanderen `Periode`
#### Regio-Schaal
Gerapporteerd afschot `Wildsoort` in `naam geselecteerde regio(‘s)` `Periode`

#### Referentie
Evolutie schademeldingen `Wildsoort` in Vlaanderen `Periode`
#### Regio-Schaal
Evolutie schademeldingen `Wildsoort` in `naam geselecteerde regio(‘s)` `Periode`

Gerelateerd aan #125

**Comment by eadriaensen** [comment]
@SanderDevisscher 
Er zijn twee niveau's van grafiektitels in de app, als het gaat om de figuren bij de eerste landkaart.
Ter verduidelijking - ik focus even op wildschade:

1) Als webpagina tekst 

- bv. "Evolutie schademeldingen Vlaanderen" (voorheen "Referentie (Vlaanderen)")
- bv. "Evolutie schademeldingen `geselecteerde Regio-schaal`" (voorheen "Regio-schaal: `geselecteerde Regio-schaal`")

2) Als deel van de figuur

- bv. " Evolutie schademeldingen `Wildsoort` in Vlaanderen `Periode`" (voorheen "Gerapporteerd aantal voor `Wildsoort` `Periode`")
- bv. " Evolutie schademeldingen `Wildsoort` in `naam geselecteerde regio(‘s)` `Periode`" (voorheen "Gerapporteerd aantal voor `Wildsoort` `Periode`")

Heb ik dat goed begrepen? Doe ik het zo?

**Comment by SanderDevisscher** [comment]
>Heb ik dat goed begrepen? Doe ik het zo?
@eadriaensen ja, zoals je het beschrijft klopt het.

**Comment by eadriaensen** [comment]
oke

**Comment by eadriaensen** [comment]
@SanderDevisscher 

De titels zijn ook aangepast.
Wel belangrijk: soms zijn het aantal keuzes ongelimiteerd vb. `wildsoort` (enkel igv wildschade), vb. `regio('s)` (zowel grofwild als wildschade).
Dit zorgt ervoor dat de titels overladen kunnen worden als het aantal geselecteerde opties oploopt. Dit was voorheen ook al aan de hand, zie hier:
![titleOverload2](https://user-images.githubusercontent.com/40824010/78369081-f0126a80-75c4-11ea-8bc8-cbac98081bcc.png)

Ik heb het momenteel zo gedaan:
![titleLimitedOverload](https://user-images.githubusercontent.com/40824010/78369182-16380a80-75c5-11ea-98f3-72577b07f6e8.png)
Dus: als er meer dan 3 regio's (en meer dan 3 wildsoorten igv wildschade pagina) geselecteerd zijn, dan wordt niet alles in de titel opgenomen, maar geven de `...` dit aan.
-> Alle geselecteerde regio's zijn steeds te vinden in de legende.
-> Alles geselecteerde wildsoorten zijn steeds te zien in de titel boven landkaart 1:

![landkaart1_wildschade](https://user-images.githubusercontent.com/40824010/78369480-8d6d9e80-75c5-11ea-80f6-6a8b549661ec.png)

Bekijk het maar eens en laat maar weten of/wat ik nog verder moet aanpassen.

**Comment by SanderDevisscher** [comment]
@eadriaensen dat is een zeer elegante oplossing. 
Maar is het mogelijk om tussen het laatste en voorlaatste element van de titel boven de landkaart  "en"  te zetten?

**Comment by SanderDevisscher** [comment]
Looks good

**Comment by SanderDevisscher** [comment]
@eadriaensen can you also do the same (add 'en') for the graph titles? and for the regio-schaal graph at grofwildjacht ?

**Comment by eadriaensen** [comment]
@SanderDevisscher 
One choice: wild zwijn
Two choices: wild zwijn en edelhert
Three choices: wild zwijn, edelhert en ree

What is preferred when more than 3 choices are selected?
* wild zwijn, edelhert en ree, ...
*  wild zwijn, edelhert, ree, ...

Will apply same logic for selected _Regio's_

**Comment by SanderDevisscher** [comment]
@eadriaensen I think option 2 (wild zwijn, edelhert, ree, ...) is most elegant.

**Comment by eadriaensen** [comment]
Is done now

**Comment by SanderDevisscher** [comment]
Will check after meeting

**Comment by SanderDevisscher** [comment]
good like this
