### ISSUE TITLE
Error at TABEL: Aantal schademeldingen per type schade

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/reporting-rshiny-grofwildjacht#162]
Tijdens het testen van de aanpassingen voor #125, in docker, kreeg ik onderstaande error:
![image](https://user-images.githubusercontent.com/16779320/78533826-def67300-77e9-11ea-8f83-0c6f8a77cb96.png)

Ik had de eerst enkel voertuig aanstaan, toen ik de error zag heb ik gewas ook aangezet maar de error bleef. Van beide schadetypes had ik alle subcategorieën aan staan.

**Comment by eadriaensen** [comment]
Can reproduce, will look into it

**Comment by eadriaensen** [comment]
Should be fixed now.

**Comment by SanderDevisscher** [comment]
issue is fixed
