### ISSUE TITLE
Update inputs

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/reporting-rshiny-grofwildjacht#163]
- [x] Ecology
- [x] Geography
- [x] Toekenningen_ree
- [x] Test app

Update zal gebeuren in de `pendingissues` - branch

**Comment by eadriaensen** [comment]
Nieuwe wildsoort bij de data update: `Canadese gans`.
Hiervoor zal ik nog kleine aanpassingen doen.

**Comment by SanderDevisscher** [comment]
@eadriaensen heb je het over wildschade ?

**Comment by eadriaensen** [comment]
@SanderDevisscher inderdaad

**Comment by SanderDevisscher** [comment]
Ifso, is het geen mogelijkheid om de soortenlijst dynamisch te maken. Ik vermoed namelijk dat de lijst van soorten atm nog niet volledig is.

**Comment by eadriaensen** [comment]
> Ifso, is het geen mogelijkheid om de soortenlijst dynamisch te maken. Ik vermoed namelijk dat de lijst van soorten atm nog niet volledig is.

Momenteel zijn er checks ingebouwd in de app die een warning geven zodra er nieuwe soorten (of schadetypes) gedetecteerd worden. Die dienen dan toegevoegd te worden aan de keuzelijst.
Slechts kleine aanpassing dus en de warning is duidelijk. Er wordt dus niets gemist.

Mits enkele aanpassing kan dit datadriven gebeuren, maar ik neem aan dat ik best focus op de andere nog openstaande zaken voor de update van deze week? Als er nog ruimte is, bekijk ik dat ook!

**Comment by SanderDevisscher** [comment]
> maar ik neem aan dat ik best focus op de andere nog openstaande zaken voor de update van deze week? Als er nog ruimte is, bekijk ik dat ook!

inderdaad

**Comment by SanderDevisscher** [comment]
app is getest en goed bevonden in docker. na de pull request nog te testen in de UAT!
