### ISSUE TITLE
TABEL: Aantal schademeldingen per type schade locatie missing

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/reporting-rshiny-grofwildjacht#164]
Tijdens het testen in docker stootte ik op de volgende bug:

![image](https://user-images.githubusercontent.com/16779320/79448158-357d6180-7fe1-11ea-982f-6e2868447b7d.png)

Zoals je kan zien is de kolom locatie niet ingevuld. Het probleem komt voor bij de Regio's Provincie en Vlaanderen. Bij de faunabeheerzone is de locatie wel ingevuld enkel de laatste rij "Vlaanderen" ontbreekt. 

In hindsight komt dit probleem ook voor in de UAT omgeving (v0.1.18 data tot 12/03/2020). In productie (zelfde versie/zelfde data) komt het probleem, gelukkig, niet voor.

**Comment by eadriaensen** [comment]
@SanderDevisscher
Bij welke keuzes uit het hoofdmenu doet zich dit exact voor (`wildsoort` en `type schade`)?
Ben jij aan het testen met versie 0.2.1?

Lokaal, bij mij, versie 0.2.1, kan ik dit momenteel niet reproduceren.

**Comment by SanderDevisscher** [comment]
Ik ben aan het testen met versie v0.2.1 en data tot 12/04.  
Qua selectie gebruik is voor `wildsoort`: wild zwijn en `type schade`: Gewas en Voertuig met alle opvolg opties aan.

**Comment by mvarewyck** [comment]
Eerste vermoeden is dat de versie van R-package `DT` verschillend is in productie en test omgeving door docker cache. Zou je dit kunnen bekijken via `packageVersion("DT")`?

**Comment by SanderDevisscher** [comment]
> `packageVersion("DT")`

gewoon als commando in powershell ? Vooraf gegaan door docker ? of as is ?

**Comment by mvarewyck** [comment]
Vb. `sudo docker run -p 3838:3838 openanalytics/pure-shiny R -e 'packageVersion("DT")'`
waarbij `openanalytics/pure-shiny` naam van jouw docker image is.

We hebben ondertussen al met versie 0.9, 0.12 en 0.13 geprobeerd, die tonen allemaal de locaties correct, dus mogelijks ligt het aan iets anders. Ik kijk ondertussen verder.

**Comment by SanderDevisscher** [comment]
Ik heb het, zonder gewenst resultaat, geprobeerd zoals je hierboven beschreef. Ik heb wel de poort moeten wijzigen omdat die bezet was (waarschijnlijk vorige run, ben er nog niet uit hoe je die stopt) en zonder sudo want dat is docker linux.

![image](https://user-images.githubusercontent.com/16779320/79454271-32876e80-7feb-11ea-86cc-e93296924d15.png)

**Comment by mvarewyck** [comment]
"DT" should be in quotes

**Comment by SanderDevisscher** [comment]
> "DT" should be in quotes 

DT is in quotes 

![image](https://user-images.githubusercontent.com/16779320/79454582-c6593a80-7feb-11ea-8f86-98708d62d327.png)

**Comment by eadriaensen** [comment]
I think you might have to escape the double quotes in powershell. Can you try to rerun your command but replacing `packageVersion("DT")` with `packageVersion(\"DT\")` ?

**Comment by SanderDevisscher** [comment]
this works. current local version 0.13

**Comment by SanderDevisscher** [comment]
bestaat er een manier om een lijst van de geladen packages en hun versie te achterhalen ?

**Comment by eadriaensen** [comment]
Je kan het volgende proberen: 
In hetzelfde commando als net `packageVersion(\"DT\")` vervangen door `sessionInfo()`

**Comment by SanderDevisscher** [comment]
was er na wat googlen ook op gekomen.
dit is het resultaat:
![image](https://user-images.githubusercontent.com/16779320/79458054-8dbc5f80-7ff1-11ea-8e0a-5d8a7f3c8701.png)

**Comment by SanderDevisscher** [comment]
voor de volledigheid hoort dit er ook bij:
![image](https://user-images.githubusercontent.com/16779320/79458124-a9c00100-7ff1-11ea-9b66-a9680ed11b9f.png)

**Comment by eadriaensen** [comment]
@SanderDevisscher 
Ik kon het probleem in Docker, met jouw versie van DT (0.13) reproduceren.
Met een vorige versie van DT (0.12) is het probleem in Docker echter opgelost.

Ik heb de Dockerfile dus aangepast om de versie van DT te specifieren.
Kan je opnieuw testen om te bevestigen dat het probleem inderdaad van de baan is zo?

Je moet de Docker image opnieuw builden vooraleer je de image runt:
`docker build -t openanalytics/wildapp .` waarbij ` openanalytics/wildapp` de naam is die je aan de  image geeft

**Comment by SanderDevisscher** [comment]
building

**Comment by SanderDevisscher** [comment]
Lokaal in docker is de issue nu opgelost.
