### ISSUE TITLE
Wrong projection for points on Landkaart 2

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/reporting-rshiny-grofwildjacht#166]
Tijdens het testen op de UAT hebben we gemerkt dat een aantal punten verschoven waren ten opzichte van waar ze gezet waren. De punten in het voorbeeld hieronder werden door @jimcasaer  ingegeven en zouden ongeveer moeten staan waar de pijlen wijzen.

![image](https://user-images.githubusercontent.com/16779320/79560514-054cc600-80a8-11ea-8d1a-4d9b3b179817.png)

Vermoedelijk we de verkeerd proj4s - string gebruikt voor lambert72 coördinaten. In het verleden zijn we hierdoor ook op dergelijke verschuivingen gestoten. 

De juiste proj4s - string == "+proj=lcc +lat_1=51.16666723333333 +lat_2=49.8333339 +lat_0=90 +lon_0=4.367486666666666 +x_0=150000.013 +y_0=5400088.438 +ellps=intl +towgs84=-106.869,52.2978,-103.724,0.3366,-0.457,1.8422,-1.2747 +units=m +no_defs "

Kunnen jullie eens nakijken of dit het probleem oplost ?
Dit wordt best opgelost voordat we in productie gaan!

**Comment by eadriaensen** [comment]
We bekijken het!

**Comment by eadriaensen** [comment]
@SanderDevisscher 

Na enig onderzoek, waarvoor dank @mvarewyck , zou het probleem opgelost moeten zijn.
Ik heb de fix rechtstreeks in de master branch gepusht.
Kan je checken of het is opgelost ?

**Comment by SanderDevisscher** [comment]
fixed
