### ISSUE TITLE
Aanpassing banner en welkomtekst

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/reporting-rshiny-grofwildjacht#167]
Is het mogelijk om de volgende aanpassingen door te voeren ?

- [x] ervoor zorgen dat de banner vast staat boven aan het scherm zodat het steeds zichtbaar is als je scrolt
- [x] Het logo te verhuizen van onderaan de pagina naar de banner 
- [x] en als het vorige mogelijk is het stuk tekst "van het Instituut voor Natuur- en Bosonderzoek (INBO)" te verwijderen uit de titel

**Comment by mvarewyck** [comment]
Could you provide us an official logo with transparent background we can use?
![Screenshot from 2020-06-08 14-37-32](https://user-images.githubusercontent.com/22143743/84031284-b0397c00-a995-11ea-831a-ff3fedb2a797.png)

**Comment by SanderDevisscher** [comment]
@mvarewyck @eadriaensen can you do something with an .eps format logo ?

**Comment by SanderDevisscher** [comment]
Here's the non-lion part of the logo as transparant .png:
![inbo_86929005](https://user-images.githubusercontent.com/16779320/84242977-da0fb180-ab01-11ea-817f-9ed1a275192e.png)

**Comment by SanderDevisscher** [comment]
and the other orientation:
![inbo_54515611](https://user-images.githubusercontent.com/16779320/84243233-2a870f00-ab02-11ea-9997-52cbd68482f6.png)

**Comment by SanderDevisscher** [comment]
I asked our layout team to provide the lion-part but this is pending.

**Comment by SanderDevisscher** [comment]
And here's the lion-part:
![VO_naakt_vlaanderenIsWet](https://user-images.githubusercontent.com/16779320/84247178-fe6e8c80-ab07-11ea-9152-7bc8cb035044.png)

According to the (silly) branding rules the lion logo should only be used on a white background. 
However our layout specialist bended the rules and made a transpararent version. Is it possible to prevent any downloading of this image ? as to limit its spread!

**Comment by eadriaensen** [comment]
![INBObanner](https://user-images.githubusercontent.com/40824010/84250867-dfbec480-ab0c-11ea-9346-f9562c4e2ea8.png)
Thank you.

I'm afraid downloading is not easily disabled on html, as a quick research learns me.
I'll check with @mvarewyck is she has some CSS experience to prevent this.

**Comment by SanderDevisscher** [comment]
The logo's don't load correctly while testing in docker, see below:
![image](https://user-images.githubusercontent.com/16779320/84748272-af69a100-afb8-11ea-9af2-77351ed362ec.png)

**Comment by mvarewyck** [comment]
> ![INBObanner](https://user-images.githubusercontent.com/40824010/84250867-dfbec480-ab0c-11ea-9346-f9562c4e2ea8.png)
> Thank you.
> 
> I'm afraid downloading is not easily disabled on html, as a quick research learns me.
> I'll check with @mvarewyck if she has some CSS experience to prevent this.

Disable download is not possible https://stackoverflow.com/a/30394770
Would it be an option to make the banner white and use official non-transparent images?

![banner](https://user-images.githubusercontent.com/22143743/84757639-ad0d4400-afc4-11ea-878b-2a37a6f83fd3.png)

**Comment by SanderDevisscher** [comment]
@jimcasaer @RuttenAnneleen what do you guys think ? grey or white banner ? 
Personally I think a grey banner is most aesthetic.

**Comment by RuttenAnneleen** [comment]
That's a difficult one :)
I think grey is nicer but if white would solve the downloading issue, I don't think the color matters that much..

**Comment by SanderDevisscher** [comment]
@eadriaensen a white background is ok. But is it possible to move the version number tot the right side of the banner ?
![image](https://user-images.githubusercontent.com/16779320/86138821-3b1e1a00-baef-11ea-8b2e-4db3a3dac825.png)

**Comment by mvarewyck** [comment]
For reference, implemented (d90e2d4b6d435ba4bda5486c61a71d45f29e425d) using this approach
https://stackoverflow.com/a/50991648

**Comment by SanderDevisscher** [comment]
working in docker
