### ISSUE TITLE
Bron filter toevoegen aan leeggewicht  grafiek

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/reporting-rshiny-grofwildjacht#168]
FIGUUR: Leeggewicht per leeftijdscategorie (INBO of Meldingsformulier) en geslacht om specifiek te zijn. 

Hier zouden we graag een bron-filter hebben (zoals FIGUUR: Onderkaaklengte per jaar bij bio-indicatoren ree). Echter met de optie om te kiezen voor enkel INBO of zowel INBO als meldingsformulier. 
Als je enkel INBO kiest zal er gefilterd worden op dieren met een `leeftijd in maanden`  en dus 4 categorieën voor wild zwijn (inclu. frisling (<6m) en frisling (>6m)) en 3 voor ree weergeven worden. Terwijl als je beide kiest er maar 3 categorieën (enkel frisling) voor wild zwijn en ree weergegeven zullen worden. 

Hiernaast zullen wij nog een voorstel doen ter aanpassing van de tekst.

**Comment by SanderDevisscher** [comment]
> Als je **enkel INBO** kiest zal er gefilterd worden op dieren met een leeftijd in maanden en dus 4 categorieën voor wild zwijn (inclu. frisling (<6m) en frisling (>6m)) en 3 voor ree weergeven worden. Terwijl als je **beide** kiest er maar 3 categorieën (enkel frisling) voor wild zwijn en ree weergegeven zullen worden.

Dit deel van de aanpassing is nog niet geïmplementeerd.

**Comment by eadriaensen** [comment]
Alles is nu geimplementeerd.

**Comment by SanderDevisscher** [comment]
> Alles is nu geimplementeerd.

Super, zal het strx nakijken

**Comment by SanderDevisscher** [comment]
looks good in docker
