### ISSUE TITLE
Landkaart 2 voorzien van een jaar-variabele 

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/reporting-rshiny-grofwildjacht#169]
De volgende aanpassingen dienen doorgevoerd te worden:
- [x] De mogelijkheid voorzien om naast type schade en seizoen ook het jaar als variabele te kiezen
- [x] In de tekst  _"Mogelijke variabelen zijn seizoen en type schade."_ vervangen door "_Mogelijke variabelen zijn seizoen, jaar en type schade._"

**Comment by eadriaensen** [comment]
![map2wildschadeYearVar](https://user-images.githubusercontent.com/40824010/81176264-359bcc00-8fa5-11ea-9e5d-f5b6edc0e6cd.png)

Is gebeurd.

**Comment by SanderDevisscher** [comment]
indeed
