### ISSUE TITLE
Memory usage Rshiny app

### ISSUE THREAD

**Issue by stijnvanhoey** [inbo/reporting-rshiny-grofwildjacht#17]
Current memory usage of the Shiny app is rather high:
![image](https://user-images.githubusercontent.com/754862/27545562-64d22336-5a90-11e7-9d84-c0626519db5e.png)

What is the major memory-usage and what are your suggestions to improve this?

**Comment by stijnvanhoey** [comment]
With respect to the data size of the GIS-layers. 
- If the `geojson` is the issue, I would use the data format that is most performant. shapefile, geojson,.. However, I do not expect the datafile to be the memory issue, as it is a SpatialPolygon that needs to be read into memory in both situations.

- the usage of the type of data object 
```
library("jsonlite")
comm_json <- jsonlite::fromJSON(readr::read_file("reporting-grofwild/inst/extdata/communes.geojson"))
```
The resulting size of the object is around 12.2 MB. Loading with rgdal:
```
library(rgdal)
comm_sp <- readOGR("reporting-grofwild/inst/extdata/communes.geojson")
```
is a data object of 13.1 MB, so minor difference.

Furthermore, some options to check:
- sp::spTransform is actually redundant to run on each startup as we can actually prepare the data as such by doing the transformation already and store the data as WGS84 already instead of the Lambert and transforming it in the app on startup (cfr. https://github.com/inbo/reporting-rshiny-grofwildjacht/issues/6). This can be done for both geojson and shapefile (or anything else), so independent from first option.
- provincesVoeren is actually also a data det we could calculate from beforehand and just read in on the startup of the applcation. The code could still be in the package (as a separate function!), so it can be used when required an update, but we can add the provincesVoeren as a data set in the inst/extdata, to be used by the application
- it maybe will be a minor issue (so no priority), but the same can be done for the `raw` data. We can split this up in a calculation phase (run when new data arrive) and the loading (run on the app startup), 
When reading the data with json-reader


I'm also wondering: Would it be an option to bring certain processing to the browser-side in order to minimize the load on the server-side concerning the map visualisation? cfr. http://rpubs.com/bhaskarvk/geojsonv2 in combination with the conditional data?

**Comment by mvarewyck** [comment]
Indeed, it slowed down a lot by using geojson instead of shapefiles. We could save the returned object by loadShapeData() (i.e. list with spatialPolygonsDataFrame) as .Rdata and load it once when starting the app.

**Comment by stijnvanhoey** [comment]
Good idea.

**Comment by mvarewyck** [comment]
We can speed up by using a simplified version of the spatial data using `rgeos::gSimplify` (I was testing this right now) but the downside is then that some polygons are not nicely plotted anymore. So we need to find the right balance between simplification and correct borders.

**Comment by stijnvanhoey** [comment]
Seems indeed a feasible strategy to make further improvements, as this will downsize the number of dots plotted on the leaflet map. Make sure this data is also available as `.Rdata`. As I understand, the major bottleneck in response time is indeed the [provision of the leaflet-map](https://github.com/inbo/reporting-rshiny-grofwildjacht/blob/master/reporting-grofwild/inst/ui/server.R#L561) as `output$map_spacePlot`? Is it actually possible to provide a timer with some information on the map to alert the user on the rendering as a minimal effort or do you think the issue of the response time of leaflet itself can be solved?

**Comment by mvarewyck** [comment]
I have updated, locally it is much faster for me. Could you check whether speed is acceptable now at your server. If not, I will try to give a message to the user.

**Comment by stijnvanhoey** [comment]
Indeed, this provides a great speed increase, nice. Still, I would provide some information to the user while loading, as the response time is still too high to avoid confusion. 
(Memory is also better, around 250Mb/docker)

**Comment by mvarewyck** [comment]
Note that including the information "Kaart laden..." slows down the app a bit.
