### ISSUE TITLE
Uitlopers min-max buiten seizoen aanpakken FIGUUR: Percentage jaarlijks afschot 

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/reporting-rshiny-grofwildjacht#170]
De nieuwe versie van de grafiek is een aanzienlijke verbetering :-)

Het probleem dat de min - max range verder uitloopt ook al is er geen min of max voor die periode blijft bestaan. Dit zorgt voor verwarring omdat het lijkt dat er soms toch nog dieren buiten het seizoen geschoten werden. Op het onderstaande voorbeeld zitten we met 2 scenario's, (1) er is effectief nog afschot gerealiseerd in de 2de helft van september, dit mag blijven. maar (2) zowel in de 2de helft van april als de 1ste helft van oktober werd er geen afschot meer gerealiseerd, zowel de mediaan als de min max vlag zouden hier niet weergegeven moeten worden.   

![image](https://user-images.githubusercontent.com/16779320/79563818-ca4d9100-80ad-11ea-8e74-96ab5169f076.png)

Kunnen jullie eens uitzoeken of het mogelijk is dit op te lossen ?

**Comment by SanderDevisscher** [comment]
Ondanks de fix van #174 blijft deze issue bestaan

**Comment by eadriaensen** [comment]
I adjusted the plot so that it has open-ended 'ribbons' for the min-max region, instead of going to the zero values that you point out may cause confusion:
![percentageYearlyShotAnimalsBok2019](https://user-images.githubusercontent.com/40824010/84150965-ea248400-aa62-11ea-8fb2-68c91c8c6cfe.png)

**Comment by SanderDevisscher** [comment]
ok
