### ISSUE TITLE
x-axis FIGUUR: Percentage jaarlijks afschot in het nederlands

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/reporting-rshiny-grofwildjacht#171]
Momenteel staat de x-as van de grafiek in het engels, kan dit vertaald worden naar het nederlands ?

**Comment by eadriaensen** [comment]
![percYearly_ReeKits2010ref2008-2009_new](https://user-images.githubusercontent.com/40824010/81175955-adb5c200-8fa4-11ea-83e9-7d3edf597133.png)

Is gebeurd.

**Comment by SanderDevisscher** [comment]
check
