### ISSUE TITLE
Screen starts bobbing

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/reporting-rshiny-grofwildjacht#172]
Sometimes when using the app the screen will start bobbing (see gif below) and it will keep bobbing untill you scroll further down:

![Wildapp-ScreenBobbing](https://user-images.githubusercontent.com/16779320/79717301-8dfe7880-82d9-11ea-8a61-9482fb55c2ce.gif)

I'm not sure what triggers the screen to start  bobbing but @jimcasaer has observed the same issue.
It also exists in the UAT, Production and locally in docker.

**Comment by mvarewyck** [comment]
I have seen this before in other apps, most of the time it's due to an internal loop e.g. caused by selecting communes too quickly after each other. 
I've quickly scanned the internet, but didn't find a good solution. 
So we can further inspect, but I'm not sure it's worth the time..

**Comment by SanderDevisscher** [comment]
> So we can further inspect, but I'm not sure it's worth the time..

It's nice to have but certainly not highest priority. So if you or Eva happens to stumble upon a solution, please go ahead but don't waste any time deliberately searching for it.

**Comment by mvarewyck** [comment]
I think it might be due to `shinycssloaders::withSpinner()`.
To be further investigated
