### ISSUE TITLE
trias package lacking 

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/reporting-rshiny-grofwildjacht#173]
When building the exoten - branch in docker I get the following error:

![image](https://user-images.githubusercontent.com/16779320/80484192-9862e700-8957-11ea-9be5-e9cc2c9c10b0.png)

_ps version used == 0.1.23_

**Comment by eadriaensen** [comment]
I updated the dockerfile to include the `trias` install from github, this was lacking.
Should be fixed now.

**Comment by SanderDevisscher** [comment]
> I updated the dockerfile to include the `trias` install from github, this was lacking.
> Should be fixed now.

will test now

**Comment by SanderDevisscher** [comment]
fixed
