### ISSUE TITLE
nakijken einddatum jachtperiodes in grafiek percentage jaarlijks afschot

### ISSUE THREAD

**Issue by jimcasaer** [inbo/reporting-rshiny-grofwildjacht#174]
in deze figuur voor de jaren tot 2014 is 15/03 en 15/09 een einddatum - er staan bijna alle jaren dieren in de laatste blok van maart / september 
er zou eens gecontroleerd moeten worden welke datum als cut-off wordt gebruikt 15/03 zou best in het eerste blok 'maart(01) moeten zitten

![image](https://user-images.githubusercontent.com/17747176/80683687-e5180080-8ac4-11ea-93e2-32bb33aea814.png)

idem voor bokken (15/9) in september(01)
![image](https://user-images.githubusercontent.com/17747176/80683806-0b3da080-8ac5-11ea-9ddf-84b7423961d1.png)

**Comment by eadriaensen** [comment]
>  welke datum als cut-off wordt gebruikt 

Algemeen is het zo dat afschotdata met dagen 1 tem 14 in het eerste blok worden gezet en 15 tem einde maand in het tweede blok.

- Dit werkt probleemloos voor startdata 15/mm/yyy.
- Dit werkt niet perfect voor stopdata 15/mm/yyyy, zoals je beschrijft met de voorbeelden.

>15/03 zou best in het eerste blok 'maart(01) moeten zitten

Ik heb het momenteel zo aangepast dat voor gevallen waar afschotdatum hetzelfde is als stopdatum openingstijd (vb 15/03), deze alsnog worden ingedeeld in het eerste blok en zo dus een uitzondering zijn op de 'algemene' regel.

**Comment by eadriaensen** [comment]
![percYearly_ReeKits2010ref2008-2009_new](https://user-images.githubusercontent.com/40824010/81175911-9d9de280-8fa4-11ea-8cb4-ce93abe5d989.png)

**Comment by jimcasaer** [comment]
ok prima !

Dr.ir. Jim Casaer

Senior Researcher
Research Group wildlife Management / OT  Faunabeheer en Exoten/
Research Institute for Nature and Forest / Instituut voor Natuur- en
Bosonderzoek



Havenlaan 88 bus 73,
1000 Brussel

jim.casaer@inbo.be
** 32 478 281 701
www.inbo.be
orcid : 0000-0001-6788-5876




Op wo 6 mei 2020 om 14:08 schreef eadriaensen <notifications@github.com>:

**Comment by SanderDevisscher** [comment]
Ik zal sebiet controleren

**Comment by SanderDevisscher** [comment]
fix #170

**Comment by SanderDevisscher** [comment]
fixed
