### ISSUE TITLE
Bug: Continent of origin graph displays no legend when only one value in data

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/reporting-rshiny-grofwildjacht#179]
When making a subset with only 1 value as continent of origin (example: taxonomy: animalia > chordata > mammalia and pathway: release > hunting) the legend disappears as seen below:

![mamalia released by hunting](https://user-images.githubusercontent.com/16779320/81283487-0779c300-905d-11ea-9d81-a9ce2107baef.png)

The legend should allways be displayed by default

**Comment by eadriaensen** [comment]
This is fixed now.
