### ISSUE TITLE
add unknowns to graph & tables per region

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/reporting-rshiny-grofwildjacht#189]
Currently data with missing province information is omitted from these graphs:
- TABEL: Gerapporteerd afschot per regio en per leeftijdscategorie
- FIGUUR: Gerapporteerd aantal per jaar en per regio

- [ ] Can you add a row "onbekend" to the table and recalculate the totals (should be the same as Flanders level on the map). 

- [ ] An additional stack should be added to the graph displaying the number of incomplete records.

_both these additions should mainly display missing information for the years 2014 & 2015_

**Comment by eadriaensen** [comment]
This is done now.

**Comment by eadriaensen** [comment]
Note: the Dockerfile has been updated bc a new package was included. Be sure to use the latest version to build the image and run the app within Docker.

**Comment by SanderDevisscher** [comment]
> Note: the Dockerfile has been updated bc a new package was included. Be sure to use the latest version of the Dockerfile to build the image and run the app within Docker.

I'll keep this in mind when testing the app

**Comment by SanderDevisscher** [comment]
fixed
