### ISSUE TITLE
Grafiek ontweid gewicht per jaar voor ree

### ISSUE THREAD

**Issue by Fhuysent** [inbo/reporting-rshiny-grofwildjacht#19]
Deze grafiek geeft nogal rare waarden op de y-as (0-100) terwijl de waarden uit de gedownloade data toch, correct, tussen 0 en 25 kg zitten.
Net als bij de onderkaaklengte mogen hier ook a priori alle onrealistische waarden uit worden verwijderd (alles minder dan 5 kg en alles meer dan 25kg).

**Comment by jimcasaer** [comment]
plak jij de figuur er hier ook even in ?

**Comment by mvarewyck** [comment]
Bedankt om dit te rapporteren, ik zal het bekijken.

![screenshot from 2017-06-27 16 03 18](https://user-images.githubusercontent.com/22143743/27591490-26c1d7ae-5b52-11e7-88a2-8ae4f370659f.png)
