### ISSUE TITLE
add new types of gewas schade 

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/reporting-rshiny-grofwildjacht#190]
When testing the app for an new data update (see `updateJuni` - branch) I stumbled upon new types of gewas schade. These are VGSCHD, or "veegschade" and Gewas - andere. 
Some of these types are species specific, for example VGSCHD only exists for roedeer while gewas - andere can be found with grauwe gans. 

- [x] First of all VGSCHD should be renamed to "Veegschade". 
- [ ] Secondly I think it would be a good idea to limit the options in the "gewas schade" - filter to the types of gewas schade in the data. 
- [ ] Thirdly the same datadriven filtering should be implemented for the "voertuig schade" - filter

@mvarewyck & @eadriaensen step 1, renaming  VGSCHD, should be implemented anyway. 
@jimcasaer what do you think ? about steps 2 & 3?

**Comment by SanderDevisscher** [comment]
implementation should occur in the `updateJuli` - branch

**Comment by eadriaensen** [comment]
Included VGSCHD as "Veegschade".
"Gewas - andere" is not new, but was already there in the previous version. This comes from the original code "GEWASANDR".

changes were implemented in `updateJuli` branch
