### ISSUE TITLE
expand year slider FIGUUR: Leeftijdscategorie op basis van onderkaak & meldingsformulier 

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/reporting-rshiny-grofwildjacht#193]
Met de laatste data update (#187) is er leeftijdcategorie informatie van de autopsies én de meldingsformulieren beschikbaar vanaf 2005.  

Momenteel is de slider van deze figuur beperkt tot 2014 - 2020. Deze mag uitgebreid worden tot 2005 - 2020.

**Comment by eadriaensen** [comment]
> Momenteel is de slider van deze figuur beperkt tot 2014 - 2020. Deze mag uitgebreid worden tot 2005 - 2020.

This was the case for Ree and is now adjusted for Ree

**Comment by SanderDevisscher** [comment]
fixed
