### ISSUE TITLE
Why current year is not displaying for FIGUUR: Percentage jaarlijks afschot?

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/reporting-rshiny-grofwildjacht#194]
@mvarewyck @eadriaensen can you look into why this graph is not displaying 2020 ? 
I checked the [jachtopeningstijden](https://github.com/inbo/reporting-rshiny-grofwildjacht/blob/updateJuli/reporting-grofwild/inst/extdata/Openingstijden_grofwild.csv) file does contain values for 2020.

**Comment by eadriaensen** [comment]
This is fixed now.

It still had manual setting to go 1 year earlier. Probably stems from the time when #132 was current.

**Comment by SanderDevisscher** [comment]
will check when text changes in https://github.com/inbo/reporting-rshiny-grofwildjacht/issues/192#issuecomment-659385843 are implemented.

**Comment by SanderDevisscher** [comment]
> will check when text changes in [#192 (comment)](https://github.com/inbo/reporting-rshiny-grofwildjacht/issues/192#issuecomment-659385843) are implemented.

@eadriaensen @mvarewyck do you think you can still fix it today ?

**Comment by SanderDevisscher** [comment]
done
