### ISSUE TITLE
titel figuren - we are not dealing with numbers of observed animals 

### ISSUE THREAD

**Issue by jimcasaer** [inbo/reporting-rshiny-grofwildjacht#20]
almost all data and figures are dealing with animals shot or found dead (gerapporteerd geschoten of als valwild gerapporteerd) and not observed (geobserveerde) animals 

titles should be adapted given that we have no idea of the number of animals present or observed

**Comment by stijnvanhoey** [comment]
@jimcasaer  should we use `geregistreerd`?

**Comment by jimcasaer** [comment]
"Gerapporteerd aantal (afschot en valwild)"

only for wild boar "valwild" in included, not for the other species - is it possible to have the title being depending of the species ?

**Comment by stijnvanhoey** [comment]
This is possible. However, I propose to use `gerapporteerd aantal` instead of a species dependent title. The latter is a request for further development.

**Comment by jimcasaer** [comment]
if we don't make it species depended I would suggest to use the title used in the previous publications and use " gerapporteerd aantal (afschot en valwild) " thomas ? frank ? what's your opinion @ThomasScheppers @Fhuysent

**Comment by mvarewyck** [comment]
I have changed all "aantal" into "gerapporteerd aantal"

NOTE: In some of the accompanying texts of the figures by @Fhuysent it is indicated "geschoten" while this is not always the case: can be afschot, valwild en/of verdelging ANB. We include all of these unless otherwise stated in the plot title
`> table(ecoData$doodsoorzaak)

       afschot       onbekend        valwild verdelging ANB 
         74924              1            185             48 `

**Comment by ThomasScheppers** [comment]
As suggested by Jim: add '(afschot en valwild)' to this title. This applies to all species, although for roe deer 'valwild' is only a very small proportion, hence Frank did not mentioned this in previous publications.

**Comment by Fhuysent** [comment]
As suggested by Jim: add '(afschot en valwild)' to this title. This applies to all species, except roe deer.

**Comment by stijnvanhoey** [comment]
Thomas and Jim will check the handling of `afschot en valwild` in the titles of the individual figures. There is no need on differences among animal

**Comment by SanderDevisscher** [comment]
@jimcasaer will check
