### ISSUE TITLE
FIX `inbo_palette()` has only 9 colours ERRORS

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/reporting-rshiny-grofwildjacht#204]
Since the last update from INBOTheme (see [#15](https://github.com/inbo/INBOtheme/issues/15)) this error is displayed whenever more than 9 colours are requested
```
`inbo_palette()` has only 9 colours, you requested 21.
Reduce the number of factor levels.
```

The error occurs at the following graphs:
- [ ] FIGUUR: Aantal schademeldingen per jaar en variabele
      - when using "GEWAS" and "WILDSOORT" variabele
- [ ] ...

**Comment by SanderDevisscher** [comment]
https://github.com/inbo/reporting-rshiny-grofwildjacht/blob/7608364a67d5fe8dad881dbdbfd4a96b61c38b69/reporting-grofwild/R/countYearSchade.R#L95

should be replaced by `ggplot2::scale_colour_discrete(length(unique(summaryData$variabele)))`

**Comment by SanderDevisscher** [comment]
Not fixed yet! gives error below:
`names() applied to a non-vector`

**Comment by SanderDevisscher** [comment]
@jimcasaer, @mvarewyck neemt dit van mij over en zal op korte termijn pogen een oplossing ineen te boxen. 

De volgende opties liggen op tafel:

1.  meerdere rcolorbrewer paletten gebruiken om aan een 40-tal kleuren te komen
2. als 1 niet haalbaar blijkt tegen morgenmiddag (14/01) dan de variabele keuze "GEWAS" uitschakelen zodat de grafiek nog weergegeven wordt met de 2 andere variabele keuzes.

**Comment by mvarewyck** [comment]
Ik heb mijn aanpassingen voor `countYearSchade()` plot gepusht. We gebruiken nu 4 paletten van RColorBrewer `c("Set3", "Paired", "Dark2", "Pastel2")`, Categorie 'onbekend' wordt grijs gekleurd.

Het lijkt hiermee opgelost, zou moeten werken tot 40 kleuren.
NB: INBOtheme heeft maar 2 paletten, daarmee kom je zeker niet aan 40 kleuren.

**Comment by SanderDevisscher** [comment]
Ok Super bedankt
Ik ga direct testen of alles naar wens werkt nu

**Comment by SanderDevisscher** [comment]
Op de gecompresseerde  grafieken (#205) na lijkt mij nu alles in orde voor deployment.

**Comment by mvarewyck** [comment]
Running R CMD check, I found the INBO color palette also resulted in an error for some other plots made by `mapSchade`. I have implemented the same fix there.
