### ISSUE TITLE
FIGUUR: Gerapporteerd aantal per jaar en per regio is compressed in docker env.

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/reporting-rshiny-grofwildjacht#205]
The error (see image below) occurs with both roedeer and wild boar.

![image](https://user-images.githubusercontent.com/16779320/104300490-d9d7fa00-54c6-11eb-87c9-524f1f62238d.png)

**Comment by SanderDevisscher** [comment]
To test if error presists in UAT environment

**Comment by SanderDevisscher** [comment]
The same error occurs with `FIGUUR: Afschot per jaar en per leeftijdscategorie (o.b.v. onderkaak)`

**Comment by SanderDevisscher** [comment]
@mvarewyck, @aaikedw vertelt mij dat jullie contract met ons reeds lopende is. 
Ik weet niet of het in je planning past maar zou je eens kunnen kijken naar deze issue ? liefst vandaag of morgen. 

Ik heb poging om de app gebouwd te krijgen, in docker, wel enkele aanpassingen moeten doen aan de dockerfile (zie #203). 

Bij voorbaat bedankt ;-)

**Comment by SanderDevisscher** [comment]
oja ik ben bezig in de `update_jan_2021` - branch

**Comment by SanderDevisscher** [comment]
Zelfde probleem bij FIGUUR: Gerapporteerd aantal embryo's voor vrouwelijke reeën per jaar

**Comment by SanderDevisscher** [comment]
Ik heb een mail verzonden naar @berthuygens om de app te deployen op de UAT. Als de issue hier persist zullen we de deployment naar productie moeten tegenhouden.

**Comment by mvarewyck** [comment]
For me, with plotly version `4.9.2.1`, graphs are displayed correctly, while with (latest) plotly version `4.9.3` the problem occurs indeed.
I would suggest to (temporarily) downgrade plotly, using
```
devtools::install_version('plotly', version = '4.9.2.1', repos = 'http://cran.us.r-project.org')
```
I have updated the Dockerfile accordingly

**Comment by SanderDevisscher** [comment]
I'll rebuild and check

**Comment by SanderDevisscher** [comment]
Issue is fixed in docker environment. 
Thanks @mvarewyck

**Comment by SanderDevisscher** [comment]
When building the exoten branch from the repo in docker somehow plotly 4.9.3 gets installed causing the error to reappear. 
I suspect the installation of trias after plotly  is the cause. I'll check this !

**Comment by SanderDevisscher** [comment]
fixed

**Comment by SanderDevisscher** [comment]
@mvarewyck I'm reopening this error because the issue has reappeared in the UAT environment. 
[FIGUUR: Verdeling afschot over de jaren](https://faunabeheer-dev.inbo.be/app_proxy/a1e6d01f-b4a7-4d23-adf6-72c10782b99a/#) show this error when displaying the per jaar interval. Other intervals display correctly. 

![newplot (2)](https://github.com/inbo/reporting-rshiny-grofwildjacht/assets/16779320/9a1c4a6d-f97d-46de-9d40-c192cf99fcc1)

**Comment by SanderDevisscher** [comment]
Same issue can be found at [FIGUUR: Afschot per jachtmethode](https://faunabeheer-dev.inbo.be/app_proxy/a1e6d01f-b4a7-4d23-adf6-72c10782b99a/#). The issue is also limited to jaar - interval

![newplot (4)](https://github.com/inbo/reporting-rshiny-grofwildjacht/assets/16779320/9f6f11e9-05c8-451b-886d-a2e3285140a1)

**Comment by SanderDevisscher** [comment]
[FIGUUR: Gerapporteerd aantal embryo's voor vrouwelijke wilde zwijnen per jaar](https://faunabeheer-dev.inbo.be/app_proxy/a1e6d01f-b4a7-4d23-adf6-72c10782b99a/#) has the same issue however no "jaar" - interval

**Comment by mvarewyck** [comment]
Sorry, this is because we had to introduce plotly 4.10.1 for the dashboard report.

Fixed for these 3 plots in the branch 205_hotfix, see https://github.com/inbo/reporting-rshiny-grofwildjacht/pull/399
I didn't see it for any other plots, please let me know if you encounter other issues.
