### ISSUE TITLE
Error when building exoten branch in docker

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/reporting-rshiny-grofwildjacht#208]
When building the exoten branch (in docker and R) to take some screenshots to present the current state I get this error:

![image](https://user-images.githubusercontent.com/16779320/104905750-11411d80-5983-11eb-87b8-00a2e19c7abd.png)

Fixing this error is not urgent. The end of the month is ok.
When can you take a look into it ?

**Comment by mvarewyck** [comment]
I can have a look at it later this week.

**Comment by SanderDevisscher** [comment]
Perfect

Op di 19 jan. 2021 09:50 schreef mvarewyck <notifications@github.com>:

**Comment by mvarewyck** [comment]
The error was not where it said it is (like here https://stackoverflow.com/a/62364854)

In `formatData.R` around line 167, there are 2 closing curly brackets missing.
I can just add the brackets, but prefer @SanderDevisscher to have a look at the code to see whether anything else is missing at the end of `exoten_dutchNames()` function

**Comment by SanderDevisscher** [comment]
4841763fc6c28835880ac42c3fd5a0524ce8903a seems to fix the issue. 

However a new error is posted, see below:
```
Error in eval(exprs[i], envir) : object 'result' not found
Error: unable to load R code in package ‘reportingGrofwild’
Execution halted
ERROR: lazy loading failed for package ‘reportingGrofwild’
* removing ‘/usr/local/lib/R/site-library/reportingGrofwild’
The command '/bin/sh -c R CMD INSTALL /root/$latestApp' returned a non-zero code: 1
```

**Comment by SanderDevisscher** [comment]
error is solved now
