### ISSUE TITLE
fixed scale in map

### ISSUE THREAD

**Issue by stijnvanhoey** [inbo/reporting-rshiny-grofwildjacht#21]
By having a fixed scale, useful on the municipality-level, the interpretation of the graph on the province level is hampered:

![image](https://user-images.githubusercontent.com/754862/27624957-22e049cc-5be3-11e7-908d-fec3ceb7b46c.png)

**Comment by mvarewyck** [comment]
Indeed, but this was requested as such in issue #2. There are different options, which I suggest should be discussed before adaptation: Do you want a fixed/adaptive scale? And in the case of fixed scales, how should the classes differ per species and region level?

**Comment by ThomasScheppers** [comment]
Use an adaptive scale with 5 classes for all maps: 0-20%, 20-40%, 40-60%, 60-80%, 80-100%. The values should be rounded to the nearest integer.

**Comment by mvarewyck** [comment]
@ThomasScheppers Not totally clear to me. E.g. for wild zwijn at gemeente level we have 308 counts (of which 39 with value > 0),
  Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  0.000   0.000   0.000   2.701   0.000 134.000 
Do you want to have the first break
(a) at 20% of the whole range [0, 134], so at 20*1.34 = 27. But then we would not have a separate class for 0 counts.
(b) at 20% of sorted counts, so at 0. But then there would only be two classes: 0 or > 0 (as there are only 13% with value > 0)

**Comment by ThomasScheppers** [comment]
@mvarewyck Indeed, 0 should be a separate additional class. So then option (b) but excluding 0-values.

**Comment by mvarewyck** [comment]
To be clear

Option (b) tries to have equal number of subjects in each class, allowing for 5 classes and separate 0-class this results in following maps:

![wild_zwijn_2016_kaart 3](https://user-images.githubusercontent.com/22143743/33764606-71c4576a-dc15-11e7-80f3-b2b3dbe9eea1.png)

![wild_zwijn_2016_kaart](https://user-images.githubusercontent.com/22143743/33764565-2b2ee34c-dc15-11e7-8c50-5618e8a63b83.png)

**Comment by ThomasScheppers** [comment]
the explanation is correct, with the comment that the legend for the 0 class should just be 0, not 0-1 and the next class should be 1-x (6 in this case?)

**Comment by mvarewyck** [comment]
For the provinces: there is no province with 0 counts, one with 1 count, one with 6 counts. Therefore I preferred '0-1'; '2-6' over '0' [while there is no province with 0]; '1-1'; '2-6' in the legend. What do you think?

**Comment by ThomasScheppers** [comment]
Also for edelhert? If indeed not, OK. I assumed same legend criteria should apply to all regio scales.

**Comment by stijnvanhoey** [comment]
meeting:
-> provincie-niveau -> 5 klassen = 5 waarden (dirscreet, geen range)
-> gemeenteniveau -> to be dicussed; schaal zal zowiezo diersoortafhankelijk worden

**Comment by SanderDevisscher** [comment]
Beslissing intern faunabeheer overleg 
-> Gemeenteniveau -> Soortspecifieke klasses
Ree en Everzwijn: 0, 1 - 10, 11 - 20, 21 - 40, 41 - 80, >80
Edelhert en Damhert: 0, 1 - 5, 6 - 10, 11 - 15, 16 - 20, >20

**Comment by Fhuysent** [comment]
Bovengrens is nu 70 ipv 80 maar was eigenlijk arbitrair en de huidige bovengrens geeft mooie weergave van spreiding in afschotdichtheid.
