### ISSUE TITLE
Replace instance of geslacht.MF to geslacht_comp

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/reporting-rshiny-grofwildjacht#210]
After the upcoming februari update (15/2) and before the may update (2/5) we should replace all instances of "geslacht.MF"* in code and documentation by the more correct column name "geslacht_comp".  

@mvarewyck do you have time then to look into it ?  

'* this is an old but confusing name. The MF in the name indicates it should only contain data from the hunters while it also contains lab/field data.  

see also [#619](https://github.com/inbo/backoffice-wild-analyse/issues/619) from the backoffice

**Comment by mvarewyck** [comment]
Sure, I will put it on the planning.

Op wo 27 jan. 2021 om 16:21 schreef Sander Devisscher <
notifications@github.com>:

**Comment by mvarewyck** [comment]
Do you update the data `rshiny_reporting_data_ecology.csv` such that the column `geslacht.MF` is replaced by `geslacht_comp`?

**Comment by SanderDevisscher** [comment]
> Do you update the data `rshiny_reporting_data_ecology.csv` such that the column `geslacht.MF` is replaced by `geslacht_comp`?

I plan to do this rename. I has not yet been done.

**Comment by SanderDevisscher** [comment]
This rename has been done in the backoffice. 2 new columns were added, namely "geslacht_comp" containing the compiled sex data & "geslacht_comp_bron" containing the source of the data (meldingsformulier, inbo, onbekend & NA)*. 
I'll make a branch based on the master and upload the new data. 

* I'll add a check in the backoffice to make sure if the source is.NA means no sex data and source == onbekend means no source is known. I'm not certain this is allready the case.

**Comment by SanderDevisscher** [comment]
@mvarewyck @dbemelmans ik heb er blijkbaar overgekeken dat jullie reeds bezig waren in de `update_mar_2021` - branch
wat doen we hiermee ?

1. Doen we een PR van jullie branch ?
1. sluit ik de `210_geslacht_comp` branch en upload ik de aangepaste data naar jullie branch ?

wat is jullie voorkeur ?

**Comment by mvarewyck** [comment]
I would prefer 3.

**Comment by mvarewyck** [comment]
Currently `geslacht_comp_bron` is not being used in the graphs. Do you want to include it in 'FIGUUR: Leeggewicht per leeftijdscategorie (INBO of Meldingsformulier) en geslacht' ? Currently only source for age and not gender can be selected there.

**Comment by SanderDevisscher** [comment]
> Currently `geslacht_comp_bron` is not being used in the graphs. Do you want to include it in 'FIGUUR: Leeggewicht per leeftijdscategorie (INBO of Meldingsformulier) en geslacht' ? Currently only source for age and not gender can be selected there.

@jimcasaer what do you think ? 

In my opinion if we implement this we should do it as follows. Give the user the choice between 2 source fields: "Bron leeftijd with options (INBO, Meldingsformulier en Beide)" &  "Bron geslacht with options (INBO en Beide<sup>1</sup>)". It would also be nice to display the percentage of the data being used.  

<sup>1</sup> Geslacht data van het meldingsformulier stroomt momenteel enkel door via de compilatie kolom. @jimcasaer indien gewenst kan ik ook deze datastroom toevoegen.

**Comment by jimcasaer** [comment]
- [ ] als we het uitwerken lijkt het me logisch dat de datastroom voor beide variabelen indentiek is -- dus telkens keuze uit 2 of uit drie opties 
- [ ] vraag me af of enkel meldingsformulier als bron zinvol is in deze online tool ?

**Comment by SanderDevisscher** [comment]
> * vraag me af of enkel meldingsformulier als bron zinvol is in deze online tool ? 

It seems logical to use meldingsformulier only data solely for accuracy of determination by hunters graphs like "FIGUUR: Leeftijdscategorie op basis van onderkaak & meldingsformulier". In all other cases I would use the "corrected" data, ea when available INBO data otherwise data from Meldingsformulier. 

So, in conclusion: there will be 2 source fields (leeftijd & geslacht) with 2 options each (INBO & INBO en Meldingsformulier). 
In both cases the comp - column should be used in conjunction with the comp_bron - column, filtering the `comp_bron == "INBO"` rows when INBO is chosen & filtering `!is.na(..._comp)` when INBO en Meldingsformulier is chosen. 
In anycase a percentage of the total dataset (after the other filters like period, Leeftijdscategorie, ...) should be displayed.
