### ISSUE TITLE
Error when opening docker built

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/reporting-rshiny-grofwildjacht#211]
When opening the app in chrome after being (successfully) built in docker I get the following error in the docker console:

![image](https://user-images.githubusercontent.com/16779320/107216374-f7887880-6a0c-11eb-9bd6-19fea090b944.png)

W're doing an extra update in February because this better coincides with the hunting-reporting cycle.  The deadline for this update is 15/02. @mvarewyck can you look into this on short notice ?

**Comment by mvarewyck** [comment]
Sure, on my list this week.

Op ma 8 feb. 2021 12:59 schreef Sander Devisscher <notifications@github.com

**Comment by mvarewyck** [comment]
In latest shiny package the function shiny:::`%OR%` no longer exists.
It should work by replacing in global.R. line 16 by 

```
`%then%` <- function(x, y) {
  if (is.null(x) || isTRUE(is.na(x)))
    y
  else
    x
}
```

On which branch should I make this change?

**Comment by SanderDevisscher** [comment]
@mvarewyck you can implement the changes on the  `EXTRA_update_feb_2021` - branch

**Comment by SanderDevisscher** [comment]
fixed in docker
