### ISSUE TITLE
Add sorting options to tables

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/reporting-rshiny-grofwildjacht#212]
Currently only select tables (ex. TABEL: Aantal schademeldingen per type schade) have the option to sort by column. 
I think it would be usefull to implement this functionality for all tables.

**Comment by mvarewyck** [comment]
Yes, this is possible. We will need to construct the tables in another way (using `renderDT` instead of `renderTable`). Do you want it both for 'Grofwild' and 'Wildschade' tables?

**Comment by SanderDevisscher** [comment]
> Yes, this is possible. We will need to construct the tables in another way (using `renderDT` instead of `renderTable`). Do you want it both for 'Grofwild' and 'Wildschade' tables?

Yes, please

**Comment by SanderDevisscher** [comment]
@mvarewyck @dbemelmans Is this issue ready for testing ? Ifso can you open a Pull request ?
