### ISSUE TITLE
Incorrect warning: when selecting only 2020 for "FIGUUR: Leeftijdscategorie op basis van onderkaak & meldingsformulier"

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/reporting-rshiny-grofwildjacht#213]
Both on the development  and the production environment you get this message when selecting 2020 only:

> Voor 2020 werden tot nu toe onvoldoende onderkaken ingezameld om een zinvolle grafiek te maken.

I suspect the changes in described #74  to be cause. 

@mvarewyck can you take a look after the februari update.

**Comment by SanderDevisscher** [comment]
The message appears both with Wild zwijn en Ree

**Comment by mvarewyck** [comment]
This was hard-coded not showing a graph for 2020.

Now I don't show a graph if the current year (max year in data) is selected. Ok, or do you rather want to check whether number of observations is less than e.g. 20?

**Comment by SanderDevisscher** [comment]
> Now I don't show a graph if the current year (max year in data) is selected. Ok, or do you rather want to check whether number of observations is less than e.g. 20?

Is it possible to check if all age-groups (e.a. frisling, overloper and volwassen for wild boar) are present in the labodata for the selected time range and only then display the graph ?

**Comment by SanderDevisscher** [comment]
@mvarewyck @dbemelmans Is this issue ready for testing ? Ifso can you open a Pull request ?
