### ISSUE TITLE
achtergrond kaart

### ISSUE THREAD

**Issue by jimcasaer** [inbo/reporting-rshiny-grofwildjacht#215]
de knop "voeg landkaart toe" werkt niet voor de het visualiseren van de afschotstatistieken op de grofwild rapporteringspagina

**Comment by dbemelmans** [comment]
De landkaart die voorheen werd gebruikt bestaat niet meer, dus heb ik een andere kaart toegevoegd. Indien deze niet goed is kan u altijd zelf één kiezen: https://leaflet-extras.github.io/leaflet-providers/preview/
Let wel dat er een heel aantal kaarten zijn, die niet gratis zijn. 
Hier is een lijst met de providers die betalend zijn: https://github.com/leaflet-extras/leaflet-providers

**Comment by SanderDevisscher** [comment]
Persoonlijk denk ik dat https://leaflet-extras.github.io/leaflet-providers/preview/#filter=Esri.WorldImagery beter past.
Het is de bedoeling om met de knop een satelliet weergave aan te beiden waarmee het landgebruik "achterhaald" kan worden. 
Dat is bij [Stamen.Terrain](https://leaflet-extras.github.io/leaflet-providers/preview/#filter=Stamen.Terrain) niet het geval.

Zouden we als alternatief de [luchtfoto's van AGIV](http://www.geopunt.be/catalogus/datasetfolder/328d097a-8e13-4ae2-b292-b01712058657) kunnen plukken ?

**Comment by jimcasaer** [comment]
waarom niet een van de openstreetmaps ?OpenStreetMap.Mapnik of OpenStreetMap.DE ?
ik vind dat je daar heel wat info op kan terugvinden

**Comment by SanderDevisscher** [comment]
> Het is de bedoeling om met de knop een satelliet weergave aan te bieden waarmee het landgebruik "achterhaald" kan worden.
> Dat is bij Stamen.Terrain niet het geval.

@jimcasaer dit is dan minder belangrijk ?
