### ISSUE TITLE
Inbo_palette error is back

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/reporting-rshiny-grofwildjacht#216]
When selecting more than 9 municipalities (or other regions) you get this error:

![image](https://user-images.githubusercontent.com/16779320/110453033-10e11b00-80c6-11eb-9071-3bd7c2824c31.png)

This is similar to this issue #204. Only difference is the number of selected municipalities (or regions) rarely exceeds 9. 

I was wondering which solution is best ?

1.  Include the same amount of palettes as the solution for #204 
2.  Reuse the same palette when more than 9 municipalities are selected and add a disclaimer stating somting like "Door het hoog aantal gekozen regio's werden de kleuren van deze grafiek hergebruikt. Hierdoor is verwarring mogelijk. Selecteer minder regio's om dit te voorkomen."
3.  Other suggestions

@jimcasaer which option do you prefer ? 

To prevent a "Inbo_palette error is back **again**" issue I also think its best to sweep all the code for possible future issues with the palette.

**Comment by SanderDevisscher** [comment]
@jimcasaer which option gets your preference ?

**Comment by SanderDevisscher** [comment]
@mvarewyck @dbemelmans I suggest we go for option 2.

**Comment by SanderDevisscher** [comment]
@mvarewyck of @dbemelmans Kunnen jullie hier de komende dagen werk van maken ?

**Comment by dbemelmans** [comment]
> @mvarewyck of @dbemelmans Kunnen jullie hier de komende dagen werk van maken ?

 @SanderDevisscher Ik ben er op dit moment mee bezig (optie 2).

**Comment by SanderDevisscher** [comment]
This error is still present @ "FIGUUR: Aantal schademeldingen per jaar en per regio"

**Comment by SanderDevisscher** [comment]
fixed in docker
