### ISSUE TITLE
Test wbe region view

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/reporting-rshiny-grofwildjacht#218]
- [x] Add WBE - info to geography (see issue #650 from backoffice) @SanderDevisscher 
- [x] Add Wildbeheereenheid as regio-schaal option 
- if selected only aantal/100ha as Eenheid
- every year a new layer

**Comment by mvarewyck** [comment]
@SanderDevisscher Could we have some example geography data with the WBE included?

**Comment by SanderDevisscher** [comment]
> @SanderDevisscher Could we have some example geography data with the WBE included?

I'm working on it

**Comment by SanderDevisscher** [comment]
@mvarewyck @dbemelmans what is the best way to get the shapes for use ? 
Shall I provide them or will you look into using a wfs/wms service ?

**Comment by SanderDevisscher** [comment]
Where can I leave the data ? New branch ? existing branch ? which?

**Comment by mvarewyck** [comment]
Could you create a new branch `wbe` from master?
Shapes are generally sent to us as .shp files which we convert to .geojson and next include into the git repository
Thanks!

**Comment by SanderDevisscher** [comment]
I've created the `218_test_wbe` - branch. I'll upload the data and shapes here.

**Comment by SanderDevisscher** [comment]
I've uploaded the wbe .geojsons and new data (ecology & geography). 

The geography now contains the following columns (for "new" data since 2014): 
- WBE_Naam_Toek
- WBE_Naam_Georef
- KboNummer_Toek
- KboNummer_Georef
- PartijNummer <sup>1</sup> 

<sup>1</sup> Linking with the wbe geojsons can be done with this column. It links the Toek(keningen) - wbe info with the geojsons. Some "wbe's" cannot be linked (mostly with kbonumbers >= 400000000) because these are independent hunters without wbe borders.

**Comment by SanderDevisscher** [comment]
@mvarewyck @dbemelmans have you allready looked at how we can organise the access to the wbe data ? This should be limited to the data from a given wbe.

**Comment by SanderDevisscher** [comment]
Done
