### ISSUE TITLE
Wildschade Landkaart 2 tries to download as html but fails

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/reporting-rshiny-grofwildjacht#219]
When downloading the 2nd map of the wildschade page, the server tries to download a html (instead of a png) and fails.
  
![image](https://user-images.githubusercontent.com/16779320/111963962-666ced00-8af4-11eb-9ba4-9b9184976265.png)

**Comment by dbemelmans** [comment]
The downloadHandler has a default timeout of 45 seconds before the connection breaks, which was exceeded in this case. To avoid the timeout, I generate the image outside the downloadHandler first.

**Comment by SanderDevisscher** [comment]
@mvarewyck @dbemelmans Is this issue ready for testing ? Ifso can you open a Pull request ?
