### ISSUE TITLE
Download map fails

### ISSUE THREAD

**Issue by peterdesmet** [inbo/reporting-rshiny-grofwildjacht#22]
Clicking `Download` under map results in failed download (tested in Chrome / Mac OS X):

![screen shot 2017-06-28 at 10 46 34](https://user-images.githubusercontent.com/600993/27628385-31199ad2-5bef-11e7-8387-ea3ad12de5d2.png)

**Comment by stijnvanhoey** [comment]
checked locally and solved by adding phantomjs (e.g. in R `webshot::install_phantomjs()`). We should adapt the Docker-container?

**Comment by mvarewyck** [comment]
It is commented out in the current dockerfile, I will need to try locally whether this works when uncommented.

**Comment by mvarewyck** [comment]
Using phantomjs I cannot seem to get it working with Docker (locally it does). 

```
QXcbConnection: Could not connect to display 
PhantomJS has crashed. Please read the bug reporting guide at
<http://phantomjs.org/bug-reporting.html> and file a bug report.
Aborted (core dumped)
Warning: Error in webshot::webshot: webshot.js returned failure value: 134
Stack trace (innermost first):
    52: webshot::webshot
    51: download$func [/usr/local/lib/R/site-library/reportingGrofwild/ui/server.R#789]
     2: runApp
     1: reportingGrofwild::runWildApp
Error : webshot.js returned failure value: 134
```


I am now trying [this approach](https://stackoverflow.com/a/34672309) using mapview, but it requires some other installations...

**Comment by mvarewyck** [comment]
I found the bug as it works on my docker, see f6442e1910254fce58dceed6ba0e3ac33deaac74
Could you confirm that it is working at your side too?

**Comment by stijnvanhoey** [comment]
Fixed and running on production
