### ISSUE TITLE
naam tabblad en loading veranderen

### ISSUE THREAD

**Issue by jimcasaer** [inbo/reporting-rshiny-grofwildjacht#222]
de term wildapp staat nu als naam in het tabblad en er wordt aangegeven dat de 'wildapp' wordt geladen 
gezien de commotie rond alle app's (wilder/anb/...) en het feit dat dit geef app is om in te geven maar een dynamische rapporteringstool zou het beter zijn dat de term app hier verdwijnt

suggesties voor nieuw naam zijn welkom (" grofwild & wildschade ", "wildbeheerdata", "wildbeheerrapportering") ?

![image](https://user-images.githubusercontent.com/17747176/116591037-b2def000-a91e-11eb-8b74-96f1ddea4250.png)

**Comment by SanderDevisscher** [comment]
Wat denk je van wildbeheer statistiek ?
