### ISSUE TITLE
Add disclaimer to wildschade pagina

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/reporting-rshiny-grofwildjacht#225]
"Door technische problemen bij de doorstroom van data van het e-loket naar deze website ontbreekt de recentste data van het e-loket" 

@jimcasaer ok ?

**Comment by jimcasaer** [comment]
"wildschade data"

**Comment by SanderDevisscher** [comment]
"Door technische problemen bij de doorstroom van wildschade data van het e-loket naar deze website ontbreekt de recentste data van het e-loket"

**Comment by jimcasaer** [comment]
"Door technische problemen bij de doorstroom van wildschade data van het e-loket naar deze website ontbreekt de recentste **wildsschade** data van het e-loket"👍
