### ISSUE TITLE
New Graph: Afschot over de jaren 

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/reporting-rshiny-grofwildjacht#226]
# Suggested Title: Verdeling afschot over de jaren 

### Position
Extra Figuren en Tabellen > FIGUUR: Afschot per jaar en per leeftijdscategorie (o.b.v. onderkaak) > ...
### Description/Disclaimer
- Verdeling van afschot over de jaren heen opgesplitst per interval
![image](https://user-images.githubusercontent.com/16779320/117417650-dc011100-af1a-11eb-9ed3-3e2299f01b3f.png)
### Datacolumns
- ecology$afschot_datum
### Filters
- Periode 
- Interval (Maandelijks, 2-wekelijks, ...) => te berekenen o.b.v. afschot_datum
- Regio (Vlaanderen, Provincie, fbz)
### Code example
```
nvt
```
### Additional Options
- Download data

**Comment by SanderDevisscher** [comment]
@dbemelmans momenteel is de volgorde van de balken zomer, winter, lente en herfst als je de interval op per seizoen zet. 
Zou je dit kunnen wijzigen in lente, zomer, herfst en winter ? 
verder heb ik nog een vraagje, wat is de begrenzing van deze seizoenen ?

**Comment by SanderDevisscher** [comment]
Verder heb ik ook nog een issue waarbij de grafiek blijft resetten als ik de periode wijzig. 

https://user-images.githubusercontent.com/16779320/128662540-aa62145d-761c-4501-bb0a-b5d6d849a3f7.mp4

=> als een oplossing hiervoor niet voor de hand ligt stel ik voor dat we de toevoeging van deze grafiek uitstellen naar een volgende update.

**Comment by dbemelmans** [comment]
> verder heb ik nog een vraagje, wat is de begrenzing van deze seizoenen ?

Ik neem telkens de 21ste (maart, juni, september, december) als start van elk seizoen.
