### ISSUE TITLE
Removed filter value remains as axis tick label 

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/reporting-rshiny-grofwildjacht#229]
## Title Figuur/Tabel: 
**"FIGUUR: Onderkaaklengte per leeftijdscategorie (INBO of Meldingsformulier) en geslacht" & "FIGUUR: Leeggewicht per leeftijdscategorie (INBO of Meldingsformulier) en geslacht"**
## Bug description:
When unselecting only "Jongvolwassen"/"Overloper" from the "Leeftijdscategorie" - filter, "Jongvolwassen"/"Overloper" remains as a axis - tick label. 
Removing only "Kits"/"Frisling" or "Volwassen" does not result in a similar bug. 
Bug is not species specific, it is present both in Ree & Wild Zwijn
## Screenshot:
![newplot (5)](https://user-images.githubusercontent.com/16779320/117796869-c019aa00-b24f-11eb-9712-efd96cc4e8cb.png)

**Comment by SanderDevisscher** [comment]
This issue is already present in the current production

**Comment by dbemelmans** [comment]
@SanderDevisscher, I had some trouble with pushing to the remote branch due to the two factor authentication system. So I accidentally pushed directly to the master branch. I did not change much in the code, maybe you can check it. I apologise for the inconvenience.

**Comment by SanderDevisscher** [comment]
No problem, I'll check it!

Maybe we could consider "protecting" the master branch by setting a review requirement. Thus disabling commits to the master branch.

**Comment by SanderDevisscher** [comment]
@dbemelmans this issue seems to be fixed and no new issues seem to have been created.
