### ISSUE TITLE
Difference in number of "Leeftijdscategorie op basis van onderkaak" between figures

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/reporting-rshiny-grofwildjacht#230]
# Title Figuur/Tabel: FIGUUR: Leeftijdscategorie op basis van onderkaak & meldingsformulier & FIGUUR: Afschot per jaar en per leeftijdscategorie (o.b.v. onderkaak)
## Bug description:
There is a difference between the age classes according to the lower jaw for the same year between the 2 graphs. 
for example in 2020 @ FIGUUR: Leeftijdscategorie op basis van onderkaak & meldingsformulier we have 407 frislings versus 441 frislings @ FIGUUR: Afschot per jaar en per leeftijdscategorie (o.b.v. onderkaak). 
If I'm correct this is due to some wild boars having age classes according to the lower jaw and no age classes according to the meldingsform being omitted from FIGUUR: Leeftijdscategorie op basis van onderkaak & meldingsformulier. Ifso adding some extra info stating "Onderkaken zonder leeftijdcategorie van het meldingsformulier werden niet opgenomen in deze grafiek" should be sufficient. ifnot further investigation is needed.
## Screenshot:
![image](https://user-images.githubusercontent.com/16779320/118810844-a1995b80-b8ac-11eb-9dce-e2fdfcec7d74.png)
![image](https://user-images.githubusercontent.com/16779320/118810984-c2fa4780-b8ac-11eb-9b58-cd5ba34ee5b1.png)

@jimcasaer do you consider this a breaking issue ea should we postpone the update ? or is fixing this for the next update ok ?

**Comment by jimcasaer** [comment]
I do not consider it as a breaking point given that the explanation of the figure already states that it compares age based on meldingsformulier and jaw -- animals where one of both is missing can therefore not be included

best is to make a issue so we give some more explanation for next update or add now ' voor die dieren waarvoor beide gegevens beschikbaar zijn"

**Comment by SanderDevisscher** [comment]
> I do not consider it as a breaking point given that the explanation of the figure already states that it compares age based on meldingsformulier and jaw -- animals where one of both is missing can therefore not be included
> 
> best is to make a issue so we give some more explanation for next update or add now ' voor die dieren waarvoor beide gegevens beschikbaar zijn"

So, adding "voor die dieren waarvoor beide gegevens beschikbaar zijn" to `FIGUUR: Leeftijdscategorie op basis van onderkaak & meldingsformulier` should happen this before approving this update ? Isn't this sufficient ?

**Comment by SanderDevisscher** [comment]
@mvarewyck @dbemelmans can you look into this ?

**Comment by dbemelmans** [comment]
I checked and the difference comes indeed from the missing data on the MF.

**Comment by SanderDevisscher** [comment]
@dbemelmans can you open a PR ?

**Comment by SanderDevisscher** [comment]
@jimcasaer moet hier nu nog iets voor gebeuren ? of is de extra info voldoende ?
