### ISSUE TITLE
change request : aanmaken van selectievakken voor bron (inbo / meldingsformulier / beide) voor bepaalde figuren

### ISSUE THREAD

**Issue by jimcasaer** [inbo/reporting-rshiny-grofwildjacht#241]
naar analogie met deze figuur (zie hieronder) zou ook bij een aantal reewildfiguren de mogelijkheid best aangemaakt worden om de bron van de leeftijd en waar interessant ook geslacht gekozen kan worden
![image](https://user-images.githubusercontent.com/17747176/129009871-c3b9cbf6-7e63-47e5-8c6c-e4caf8a79c77.png)
gaat dan over volgende figuren 

- [ ] onderkaaklengte per leeftijdscategorie en geslacht
- [ ] onderkaaklengte per jaar (bio-indicatoren)
- [ ] gewicht per jaar (bio-indicatoren)
- [ ] gerapporteerd aantal embryo's voor vrouwelijke reeën per jaar

**Comment by SanderDevisscher** [comment]
fixed in docker

**Comment by SanderDevisscher** [comment]
@jimcasaer dit moeten we volgende week nog eens bekijken
