### ISSUE TITLE
New Feature WBE - page

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/reporting-rshiny-grofwildjacht#245]
Besides a overview at the general grofwild page (see issue #218) we would like to give some more details at wbe level (what, to be discussed by @jimcasaer and myself). First step in this would be working out how to organise the access.  

@mvarewyck @dbemelmans have you allready looked at how we can organise the access to the wbe data ? This should be limited to the data from a given wbe.

_Originally posted by @SanderDevisscher in https://github.com/inbo/reporting-rshiny-grofwildjacht/issues/218#issuecomment-940988891_

**Comment by jimcasaer** [comment]
@mvarewyck 

As promised I contacted the HVV for the temporary solution:
- when we provide a list of KBO-numbers and a pasword for each they can distribute the passwords to each GMU (WBE)
- they ask however that we also add the ESRI - number and the name of the GMU as a doublecheck to the list 

For the second part of the task (the technical analysis of possibilities for direct login from within their intranet) we will best have a second meeting with HVV and openanalytics together

**Comment by SanderDevisscher** [comment]
> * they ask however that we also add the ESRI - number and the name of the GMU as a doublecheck to the list

will HVV provide some list to crossreference the ESRI - Number to the KBONrs ?

**Comment by jimcasaer** [comment]
I will ask :-)

**Comment by SanderDevisscher** [comment]
@jimcasaer can we assume the wbe's in [WBE vs KBO.xlsx](https://github.com/inbo/reporting-rshiny-grofwildjacht/files/7855406/WBE.vs.KBO.xlsx) are all members from HVV ? Meaning we can use this list to generate the list of passwords ?

@mvarewyck where can I/we best save these passwords ? 
In this (public) repo ? ifso which folder? 
or better an other (private) repo like the [backoffice-wild-analyse](https://github.com/inbo/backoffice-wild-analyse/issues/new) ? or even better somewhere else ?

**Comment by SanderDevisscher** [comment]
I'll make the password list place it locally (not version controlled by github) send it to HVV & Batmergen@cloudar.be (to be included into the shinyproxy). Once the list is imported into the shinyproxy it is no longer necessary to keep the local list (all changes will be logged here).

**Comment by SanderDevisscher** [comment]
No longer relevant
