### ISSUE TITLE
Changes to SchadeWildsoorten

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/reporting-rshiny-grofwildjacht#246]
For the next update these species should be added to the SchadeWildsoorten - list:
- patrijs as kleinwild
- damhert as grofwild

Also this species should be removed from the list. 
- Wolf

**Comment by SanderDevisscher** [comment]
fixed in docker and wiki page created to allow future changes to be done by us, see https://github.com/inbo/reporting-rshiny-grofwildjacht/wiki/change-schade-specieslist

**Comment by mvarewyck** [comment]
If easier, we can use (upload) a csv file with two columns specifying the species group and species name, instead of editing the code in ui.R directly.

e.g.

| group | name |
| -------- | -------- |
Grof wild | wild zwijn
Grof wild | edelhert
Grof wild | ree
Klein wild | haas
...

**Comment by SanderDevisscher** [comment]
@mvarewyck I think it will be much safer to limit the amount of direct in code changes one of us has to do. 
Therefor It would be best to indeed to create this csv. And any other lists which group certain values (like datasources for wildschade)

I was also thinking if it would be a good idea to include some kind of boolean display/include column to easily switch on/off species?  

I'll create a new issue for this to be implemented after this update.
