### ISSUE TITLE
Export data format for Excel

### ISSUE THREAD

**Issue by ThomasScheppers** [inbo/reporting-rshiny-grofwildjacht#25]
In general, whenever data is downloadable, the export format should be excel compatible. That is, the decimal separator should be comma.

**Comment by mvarewyck** [comment]
Ok. Should it also be a comma in the percentages of this table? (these are no actual numbers in excel but characters because of the % symbol)
![screenshot from 2017-12-01 14-10-34](https://user-images.githubusercontent.com/22143743/33484217-a0966cf0-d6a1-11e7-85de-b6d694f659fa.png)

**Comment by ThomasScheppers** [comment]
@mvarewyck Yes, change this in the percentages as well. I have just tried to input a value with the % symbol in Excel and it did recognize it as a percentage. So hopefully this will work.

**Comment by SanderDevisscher** [comment]
@Yasmine-Verzelen will check this

**Comment by Yasmine-Verzelen** [comment]
This works, comma as decimal operator, both within the app and after download
