### ISSUE TITLE
TABEL: Aantal schademeldingen per type schade not loading

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/reporting-rshiny-grofwildjacht#252]
# Title Figuur/Tabel: TABEL: Aantal schademeldingen per type schade
## Bug description: 
when trying to view the "TABEL: Aantal schademeldingen per type schade not loading" for everzwijn schade this error is displayed:

`numbers of columns of arguments do not match`

**Comment by mvarewyck** [comment]
I can't reproduce on branch 'update_november'. Which filters do you select at the top?

**Comment by mvarewyck** [comment]
> I can't reproduce on branch 'update_november'. Which filters do you select at the top?

Sorry, I can now with the latest data. Fixing..

**Comment by mvarewyck** [comment]
Due to conflicts of duplicated 'ANDERE'.
We expect:

> _Specify currently used type schades_
> schadeTypes <- c("GEWAS", "VRTG", "ANDERE")
> 
> _Specify currently used types schade subcodes_
> schadeCodes <- c(c("GNPERSLTSL", "PERSLTSL", "ONBEKEND"),           #VRTG
>                  c("WLSCHD", "VRTSCHD", "**GEWASANDR**", "VGSCHD", "GRFSCHD"),     #GEWAS
>                  c("ANDERE", "VALWILD"))                            #ANDERE

While current data contains 'ANDERE' instead of 'GEWASANDR'.

**Comment by SanderDevisscher** [comment]
@mvarewyck any further actions required on our part ?

**Comment by mvarewyck** [comment]
No, seems to work. Maybe test once more at your side?

**Comment by SanderDevisscher** [comment]
Fixed in docker
