### ISSUE TITLE
Add wilder to Sources in info

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/reporting-rshiny-grofwildjacht#257]
> Deze gegevens komen uit het Meldpunt-schaderegistratie van het Agentschap voor Natuur en Bos (E-loket), het project Dieren onder de wielen (Natuurpunt) en meldingen van verkeersongevallen met wilde dieren uit andere bronnen.

zou vervangen moeten worden door:

Deze gegevens komen uit het Meldpunt-schaderegistratie van het e-loket fauna en flora (Agentschap voor Natuur en Bos), het project Dieren onder de wielen (Natuurpunt), Wilder (Limburgse Jagervereniging vzw) en meldingen van verkeersongevallen met wilde dieren uit andere bronnen.

@jimcasaer pas je de tekst aan als je iets hoort van Gert ? en assign je de issue aan @mvarewyck, @eadriaensen en/of @dbemelmans 

@mvarewyck, @eadriaensen en/of @dbemelmans past het voor jullie om dit asap op te nemen ? zodat de deployment niet te lang op zich laat wachten ?

**Comment by SanderDevisscher** [comment]
Wilder is blijkbaar nog steeds intellectueel eigendom van de Limburgse Jagervereniging vzw en moet dus zo vermeld worden.

**Comment by mvarewyck** [comment]
Note: Pushed to update_november branch as I can't directly push to master

**Comment by SanderDevisscher** [comment]
> Note: Pushed to update_november branch as I can't directly push to master

as intended ;-)
