### ISSUE TITLE
NEW GRAPH: FIGUUR: Gerapporteerd aantal embryo's voor vrouwelijke wilde zwijnen per jaar

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/reporting-rshiny-grofwildjacht#262]
### Position
- Onderaan pagina
### Description/Disclaimer
- Evolutie van het gerapporteerd aantal embryo's per geschoten dier doorheen de geselecteerde jaren voor de gekozen regio en types.
### Datacolumns
- "aantal_embryos_onbekend";"aantal_embryos";"aantal_embryos_labo";"aantal_embryos_MF";"geslacht_comp";"geslacht_comp_bron"
### Filters
- Periode
- Regio
- Data bron voor aantal embryo's
- Data bron geslacht
### Layout example
![image](https://user-images.githubusercontent.com/16779320/143838365-9559efce-810f-4a00-ba99-e585d4c132f1.png)

### Additional Options
- Download data

**Comment by mvarewyck** [comment]
Which 'types' should we consider for Wild zwijn? I think "Zeug", "Overloper (v)"
For reference: Ree has "Reegeit", "Smalree"

**Comment by mvarewyck** [comment]
![Screenshot from 2022-04-19 14-25-27](https://user-images.githubusercontent.com/22143743/164003066-69bf7067-eb77-4fd4-86b5-1960e42e8055.png)

**Comment by SanderDevisscher** [comment]
> Which 'types' should we consider for Wild zwijn? I think "Zeug", "Overloper (v)" For reference: Ree has "Reegeit", "Smalree"

In case of Wild zwijn we should also consider frisling (v).

Also in case of wild zwijn the limit of 3 embryos should be removed since wild zwijn has on average 6 embryos.

**Comment by mvarewyck** [comment]
- We automatically remove the 'Opmerking' wrt more than 3 embryos if species is 'Wild zwijn'
- Mind the duplicated colors because > 9 categories are displayed. Alternatively, we could group them, e.g. : <3, 4, ..., 8, > 8
 
![Screenshot from 2022-04-19 14-55-10](https://user-images.githubusercontent.com/22143743/164008806-7514f5ea-6874-4297-9c70-117ee4f5f44a.png)

**Comment by SanderDevisscher** [comment]
I would suggest using 0, <3, 4, 5, 6, 7, 8, 9 & >9. @jimcasaer what do you think ?

**Comment by mvarewyck** [comment]
Categories can still be updated easily.

![Screenshot from 2022-04-19 15-22-51](https://user-images.githubusercontent.com/22143743/164013771-99f3a6a9-edf9-4013-8c94-d73e22901a1f.png)
