### ISSUE TITLE
FIGUUR: Verdeling afschot over de jaren type-filter obv leeftijdcomp ?

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/reporting-rshiny-grofwildjacht#263]
# Title Figuur/Tabel: FIGUUR: Verdeling afschot over de jaren
## Bug description: 
Momenteel filtert de type-filter voor deze figuur o.b.v. het label. Dit zou moeten gewijzigd worden naar een filter o.b.v. de leeftijd_comp.

**Comment by mvarewyck** [comment]
Remarks:
- In parallel with other plots that display leeftijd_comp, we included filter for 'Data bron leeftijd'. Choices are 
   * INBO or 
   * INBO and meldingsformulier
- In parallel with other plots, when selecting Wild zwijn & data bron INBO, we distinguish for Frisling between <6m and >6m

![Screenshot from 2022-04-19 17-16-36](https://user-images.githubusercontent.com/22143743/164037910-a942df6f-2918-4ff9-a643-05bb7498155a.png)

**Comment by SanderDevisscher** [comment]
Looks good
