### ISSUE TITLE
WBE table

### ISSUE THREAD

**Issue by mvarewyck** [inbo/reporting-rshiny-grofwildjacht#266]
Building the summary table
![Screenshot from 2022-01-13 15-30-53](https://user-images.githubusercontent.com/22143743/149349152-1527e4b0-3110-4f9f-99c8-f9bdfe8345b6.png)

When extracting info on type for the summary table, I was wondering whether `type_comp` is up to date. E.g. for the species 'Wild zwijn', the type_comp doesn't distinguish for age/gender. Should I combine both age/gender variables myself or should I read it from `type_comp` which will be updated then at your side?

> tmpData <- ecoData[, c("type_comp", "geslacht_comp", "leeftijd_comp")]
> tmpData[!duplicated(tmpData), ]
![Screenshot from 2022-01-13 15-37-45](https://user-images.githubusercontent.com/22143743/149350247-b41b0610-4ad0-4814-ae69-ed108ab3bd12.png)

**Comment by SanderDevisscher** [comment]
> When extracting info on type for the summary table, I was wondering whether `type_comp` is up to date. E.g. for the species 'Wild zwijn', the type_comp doesn't distinguish for age/gender. Should I combine both age/gender variables myself or should I read it from `type_comp` which will be updated then at your side?

It is correct that 'Wild zwijn' does not distinguish for age/gender in the type_comp column. In matter of fact only 'Ree'  should have this distinction ('Damhert' & 'Edelhert' should have neither). 

I'll discuss with @jimcasaer wheter its usefull to add some logic on our side to combine the age/gender info for the other species. 

> For the summary table with trends at 'Grofwild' page we set a minimum number of observations before we actually report the trend numbers (minForTrend). There we set it to 50, which is then per province the total over all types. Here, we calculate the trend per type. Is it ok to set it here by default to 10 then? If set to 50 we will hardly ever get trend values reported.

It seems only logical to lower the threshold to display a trend, I'm only wondering if we should make it relative (to what is open for discussion) or even just set it to 0.  Certainly for fringe wbe's with only marginal numbers even 10 animals can be quite a hurdle. what do you think @jimcasaer.

**Comment by SanderDevisscher** [comment]
@mvarewyck we came, in meeting with @jimcasaer, to the conclusion it would be best to add the necessary logic to complete the 
type_comp column for the other species (besides roedeer). I'll upload the improved data when its completed at our side. 

Concerning the threshold we came to an agreement a difference of 10 animals shot should be the threshold for the trend values.

**Comment by SanderDevisscher** [comment]
@mvarewyck can you provide a option to display the data based on label_type (only roedeer)<sup>1</sup>, type_comp, geslacht_comp or leeftijd_comp? 

<sup>1</sup>I'll provide this column with the improved type_comp. The new type_comp should only contain data when both leeftijd & geslacht are known otherwise it will be `NA`.

**Comment by SanderDevisscher** [comment]
@mvarewyck I still have one question pending concerning the labeltype column. When it is resolved I'll let you know. I don't expect any large structural/content changes to both columns so you can use it like provided now.

**Comment by SanderDevisscher** [comment]
@mvarewyck is it possible to add/calculate the total trend also ?

> @mvarewyck I still have one question pending concerning the labeltype column. When it is resolved I'll let you know. I don't expect any large structural/content changes to both columns so you can use it like provided now.

This question is resolved and it resulted in no significant changes

**Comment by mvarewyck** [comment]
Included option to choose 'Categorie' and generalized according text in file [uiText.csv](https://github.com/inbo/reporting-rshiny-grofwildjacht/blob/218_test_wbe/reporting-grofwild/inst/extdata/uiText.csv)

Current labels for each variable:
- label_type (only roedeer) = label
- type_comp = type
- geslacht_comp = geslacht
- leeftijd_comp = leeftijd

![Screenshot from 2022-03-29 16-09-43](https://user-images.githubusercontent.com/22143743/160630698-53dd303a-c4fb-444c-9b21-be4946163512.png)
