### ISSUE TITLE
Add KBO for schade data

### ISSUE THREAD

**Issue by mvarewyck** [inbo/reporting-rshiny-grofwildjacht#268]
Can we add the KBO to the [schade data](https://github.com/inbo/reporting-rshiny-grofwildjacht/blob/218_test_wbe/reporting-grofwild/inst/extdata/WildSchade_georef.csv) ?
This would help us to make a subset of the schade data for the current/selected WBE.

**Comment by SanderDevisscher** [comment]
UUID;IndieningID;IndieningStatusID;Commentaar;VersieNummer;SnapshotIndieningID;IndieningTypeVersieID;AttachmentSetID;Jaartal;DossierNummer;indieningTypeSoftDeleted;IndieningSoftDeleted;IndieningType;indieningSchadeId;IndieningSchadeBasisCode;DiepteSchadeTypes;IndieningSchadeCode;SchadeTypeCodeHier;IndieningLocatieID;LocatieTypeID;LocatieTypeCode;locatieSoftDeleted;LocatieType;locatieTypeSoftDeleted;PlantsoortID;SoortNaam;DiersoortID;DiersoortNaam;SchadebedragID;SchadeReportSoftDeleted;DatumVeroorzaakt;SnapshotDatum;VersieDatum;DatumVaststelling;CreateDatum;UpdateDatum;IngediendDatum;BeslissingDatum;SchadeOmschrijvingHier;SchadeBeschrijving;SchadeBedragOmschrijving;SchadeRegistratieBeschrijving;Beschrijving;PuntLocatieWKT;PolyLocatieWKT;LineLocatieWKT;LocatieWKT;ReducedPolyLocatieWKT;NbrVertex;IsNieuw;verbatimCentroidLatitude;verbatimCentroidLongitude;verbatimCentroidUncertainty;fbdz;beheer;fbz;provincie;NisCode_Georef;GemNaam_Georef;UTM5;**KboNummer**;WBE_Naam_Georef;x;y;GemNaam_Original

KboNummer is allready present in the data.

**Comment by mvarewyck** [comment]
Indeed, it was just not read at our side.
