### ISSUE TITLE
WBE gauge

### ISSUE THREAD

**Issue by mvarewyck** [inbo/reporting-rshiny-grofwildjacht#269]
1. For the accuracy graph: we can define 3 color groups. Currently:
0-30: red
30-50: orange
50-100: green

2. For the calculation: we look at the data of the current year. For these records we calculate the percentage that have registered 'leeftijdscategorie_MF' AND 'Leeftijdscategorie_onderkaak'.

3. We show it both for the WBE page and the Grofwild page.

![Screenshot from 2022-02-02 17-00-28](https://user-images.githubusercontent.com/22143743/152190313-db53027d-2c79-436c-8255-532b2fad4260.png)

Is this ok?

**Comment by SanderDevisscher** [comment]
> 1. For the accuracy graph: we can define 3 color groups. Currently:
>    0-30: red
>    30-50: orange
>    50-100: green

with color groups do you mean shades of ... ? for example in the case of red, dark red to orangish red ? 
Or do you use fixed colors ?  

> * For the calculation: we look at the data of the current year. For these records we calculate the percentage that have registered 'leeftijdscategorie_MF' AND 'Leeftijdscategorie_onderkaak'.

for the calculation you should subset the data with both 'leeftijdscategorie_MF' AND 'Leeftijdscategorie_onderkaak', of this subset you should calculate the share where both are the same, thus displaying the rate of accurate age determination by the hunters.  

> We show it both for the WBE page and the Grofwild page.

I would limit it to the WBE page for now.

**Comment by mvarewyck** [comment]
> > 1. For the accuracy graph: we can define 3 color groups. Currently:
> >    0-30: red
> >    30-50: orange
> >    50-100: green
> 
> with color groups do you mean shades of ... ? for example in the case of red, dark red to orangish red ? Or do you use fixed colors ?
It's using fixed colors: see for example https://stackoverflow.com/a/46876686

**Comment by SanderDevisscher** [comment]
> > > 1. For the accuracy graph: we can define 3 color groups. Currently:
> > >    0-30: red
> > >    30-50: orange
> > >    50-100: green
> > 
> > 
> > with color groups do you mean shades of ... ? for example in the case of red, dark red to orangish red ? Or do you use fixed colors ?
> 
> It's using fixed colors: see for example https://stackoverflow.com/a/46876686

That's ok

**Comment by mvarewyck** [comment]
Now, the accuracy is for the selected period instead of the current year.
NOTE: I have removed the label at the bottom indicating the total number as it can not be updated correctly when changing the selected period (previously it was constant).

![Screenshot from 2022-03-03 16-31-47](https://user-images.githubusercontent.com/22143743/156596874-eed8a705-e185-4572-a67b-db60e3c04cd3.png)

**Comment by SanderDevisscher** [comment]
@mvarewyck something weird is happening here somehow the commit c797425 does not show up in my github desktop History.
I'll try restarting my laptop to see if that fixes the issue. I'll keep you posted.

**Comment by SanderDevisscher** [comment]
> @mvarewyck something weird is happening here somehow the commit [c797425](https://github.com/inbo/reporting-rshiny-grofwildjacht/commit/c797425b36f3d4901dad43cfb6170319740401cc) does not show up in my github desktop History. I'll try restarting my laptop to see if that fixes the issue. I'll keep you posted.

This is resolved
