### ISSUE TITLE
Better names for export files

### ISSUE THREAD

**Issue by ThomasScheppers** [inbo/reporting-rshiny-grofwildjacht#27]
Whenever a file or figure can be downloaded, give meaningful names

for example: downloading the 'Landkaart' results in 'plotRuimte.png'. Change this to the title of the figure 'Wild_zwijn_2015_kaart'

for example: the download of 'Gerapporteerd aantal per regio en per leeftijdscategorie': add species name and selected year

-> Suggestion: 3 parts:
1) Species
2) year or range year
3) content

**Comment by mvarewyck** [comment]
Ok, as 'content' we currently use the (English) plot function name, which allows direct reference. If other names are needed, please specify.

**Comment by ThomasScheppers** [comment]
As regards figures, I assume this does not apply to the 'screenshot' functionality for the interactive graphs?
As regards files: English names are OK for me (for now) -> to be discussed with others and perhaps on the to-do-list for next year?

**Comment by mvarewyck** [comment]
For 'screenshot' button there is indeed no option to change file name. If needed, we best provide explicit Download button.

**Comment by stijnvanhoey** [comment]
Decided on meeting: we keep using the default figure export of plotly, no additional download button.
