### ISSUE TITLE
FIGUUR: Toegekende en verwezenlijkte labels WBE

### ISSUE THREAD

**Issue by mvarewyck** [inbo/reporting-rshiny-grofwildjacht#270]
(1) Currently we have data only on province level: 
https://github.com/inbo/reporting-rshiny-grofwildjacht/blob/218_test_wbe/reporting-grofwild/inst/extdata/Toekenningen_ree.csv
Can we also get it on WBE level?

(2) In the graph, actually the blue bar represents the number of non-realized shot animals = assigned - realized. I currently calculated it as suggested, so the total bar height represents the no. of assigned. 
(2a) Can we call the groups in the legend: 'verwezenlijkt' and 'niet-verwezenlijkt'?
(2b) When hovering over a blue bar in the graph, should it report the no. of 'niet-verwezenlijkt' or 'toegekend'?

![Screenshot from 2022-02-09 12-41-04](https://user-images.githubusercontent.com/22143743/153193981-9b91bf97-9554-4e40-a5ef-b33f5c68b19b.png)

**Comment by SanderDevisscher** [comment]
> (1) Currently we have data only on province level: https://github.com/inbo/reporting-rshiny-grofwildjacht/blob/218_test_wbe/reporting-grofwild/inst/extdata/Toekenningen_ree.csv Can we also get it on WBE level?

see e366df8

> (2) In the graph, actually the blue bar represents the number of non-realized shot animals = assigned - realized. I currently calculated it as suggested, so the total bar height represents the no. of assigned. 

perfect

>(2a) Can we call the groups in the legend: 'verwezenlijkt' and 'niet-verwezenlijkt'? 

In my opinion 'verwezenlijkt' and 'niet-verwezenlijkt' do better cover what is displayed so **ok** for me, @jimcasaer what do you think ?

>(2b) When hovering over a blue bar in the graph, should it report the no. of 'niet-verwezenlijkt' or 'toegekend'?

I would say the popup should display  no. of 'niet-verwezenlijkt' when hovering over the blue bar. however I would, if possible, display  no. of 'verwezenlijkt', no. of 'niet-verwezenlijkt', 'toegekend' & 'percentage verwezenlijkt' when using _compare data on hover_ .

> ![Screenshot from 2022-02-09 12-41-04](https://user-images.githubusercontent.com/22143743/153193981-9b91bf97-9554-4e40-a5ef-b33f5c68b19b.png)

**Comment by mvarewyck** [comment]
The 'toegekend' numbers in the old data (Toekenningen_ree.csv) and new data (Verwezenlijkt_categorie_per_afschotplan.csv) differ. 
Should we keep the old data for the `tableProvince()` function while using the new data for `countYearRealizedShot()` function?  Or should the new data replace the old?

```
>  assignedOld <- loadToekenningen()
>     aggregate(Aantal ~ Jaar, data = assignedOld, sum)
   Jaar Aantal
1  2002   3448
2  2003   3803
3  2004   4014
4  2005   4690
5  2006   5026
6  2007   5356
7  2008   5464
8  2009   5892
9  2010   6389
10 2011   6804
11 2012   6706
12 2013   6952
13 2014   7738
14 2015   7303
15 2016   7298
16 2017   7566
17 2018   8035
18 2019   8227
19 2020   8332
20 2021   8725
>     
>     assignedNew <- loadToekenningen2()
>     aggregate(toegekend ~ labeljaar, data = assignedNew, sum)
   labeljaar toegekend
1       2002      4337
2       2003      4720
3       2004      4915
4       2005      5607
5       2006      5813
6       2007      6008
7       2008      6054
8       2009      6496
9       2010      7080
10      2011      7463
11      2012      7399
12      2013      7758
13      2014      7738
14      2015      7303
15      2016      7495
16      2017      7566
17      2018      8035
18      2019      8227
19      2020      8509
20      2021      8757
```

**Comment by SanderDevisscher** [comment]
@mvarewyck I found a mistake in the calculation of the old data, it used an old & incorrect source file. I fixed it, see a7e8ae5.

**Comment by mvarewyck** [comment]
How the plot currently looks for 1 WBE

![Screenshot from 2022-02-10 09-12-24](https://user-images.githubusercontent.com/22143743/153365039-0ed5a208-fb3b-41a2-a758-75388a43a76b.png)

**Comment by mvarewyck** [comment]
Can you provide a text for this graph to be shown in the application?

**Comment by SanderDevisscher** [comment]
A suggestion:

> Vergelijking tussen het verwezenlijkt en het toegekend afschot van ree. 
> Het percentage bovenaan de staven geeft de graad van verwezenlijking weer. 
> Binnen een wbe wordt best gestreefd naar een afschot van 100% van de toegekende labels.

@jimcasaer wat denk jij ?
