### ISSUE TITLE
term : "wildapp"

### ISSUE THREAD

**Issue by jimcasaer** [inbo/reporting-rshiny-grofwildjacht#271]
Op dit moment verschijnt de term "wildapp" als naam van het tabblad 
Gezien alle verschillende app's die al bestaan en nog ontwikkeld worden en de chaos hierover zou het denk ik beter zijn dat we hier voor deze rapporteringspagina een andere term gebruiken (naam voor het tabblad).

Eventueel gewoon "grofwild - inbo" of zoiets ? 
wat denken jullie ?

**Comment by SanderDevisscher** [comment]
@jimcasaer is dit niet iets waar we Koen Vanmuylem bij moeten betrekken ? 
Ik zou persoonlijk voor "inbo - grofwild" gaan (en "inbo - exoten" vr exoten - portaal)

**Comment by jimcasaer** [comment]
ik denk niet dat koen daar ooit bij betrokken is geweest
en volledig akkoord met inbo-grofwild 
dus gaan met die banaan

**Comment by SanderDevisscher** [comment]
"inbo-grofwild" it will be. @mvarewyck can you implement the necessary changes?

**Comment by mvarewyck** [comment]
This is something to be implemented at shinyproxy configuration level.
I'll pass the message to Mergen Batbayar

**Comment by mvarewyck** [comment]
As discussed during the meeting 21st March, also for the WBE app have the name 'inbo-grofwild'

**Comment by SanderDevisscher** [comment]
deze mag terug opgenomen worden
