### ISSUE TITLE
NEW feature: korte biotoopbeschrijving:

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/reporting-rshiny-grofwildjacht#275]
# Suggested Title
Biotoop samenstelling

### Position
- Next to or just below "Gerapporteerd afschot/100ha voor ree in jjjj"
### Description/Disclaimer
- To be dicussed
### Datacolumns
- These files contain per wbe data on the area (in m2, ha, km2) of bos, water, akker, grasland, bebouwing & andere as well as the total area and the respective percentages of the different habitats. These values were calculated by overlay with the [Corine landcover shape](https://ac.ngi.be/client-open/BMHY96YhNcEtKottiR9U/ngi-standard-open/Vectordata/CLC2018/CLC_2018_L08_shp.zip). 
[WBE_habitats_2018.csv](https://github.com/inbo/reporting-rshiny-grofwildjacht/files/8097127/WBE_habitats_2018.csv)
[WBE_habitats_2019.csv](https://github.com/inbo/reporting-rshiny-grofwildjacht/files/8097128/WBE_habitats_2019.csv)
[WBE_habitats_2020.csv](https://github.com/inbo/reporting-rshiny-grofwildjacht/files/8097129/WBE_habitats_2020.csv)
[WBE_habitats_2021.csv](https://github.com/inbo/reporting-rshiny-grofwildjacht/files/8097130/WBE_habitats_2021.csv)
[WBE_habitats_2014.csv](https://github.com/inbo/reporting-rshiny-grofwildjacht/files/8097131/WBE_habitats_2014.csv)
[WBE_habitats_2015.csv](https://github.com/inbo/reporting-rshiny-grofwildjacht/files/8097132/WBE_habitats_2015.csv)
[WBE_habitats_2016.csv](https://github.com/inbo/reporting-rshiny-grofwildjacht/files/8097133/WBE_habitats_2016.csv)
[WBE_habitats_2017.csv](https://github.com/inbo/reporting-rshiny-grofwildjacht/files/8097135/WBE_habitats_2017.csv)

New files will be uploaded together with the data when a update occurs.

### Filters
- same as "Gerapporteerd afschot/100ha voor ree in jjjj"
### Code example
```
nvt
```
### Layout example

![image](https://user-images.githubusercontent.com/16779320/154683482-84e5559f-0570-4f09-b04d-b6167cd85d54.png)

### Additional Options
- Download data

**Comment by SanderDevisscher** [comment]
Currently this is worked out as a popup when clicking on the map. However I think its beter to display it as a seperate graph.

**Comment by mvarewyck** [comment]
Current proposal below. Notes/questions:

1. We don't have 'percentage bebouwd' in the data
2. Currently the bars are always sorted in same order (starting with bos and ending with andere). Another option is to sort them from large to small

![Screenshot from 2022-02-22 14-12-34](https://user-images.githubusercontent.com/22143743/155139306-3e8ab493-07d2-4642-af12-4974610b7f7d.png)

**Comment by SanderDevisscher** [comment]
@mvarewyck I modified the habitat_lists to include the percentage urbanisation (perc_bebouwd) zie 
8375535

**Comment by mvarewyck** [comment]
Thanks, this is automatically picked up by our function `barBiotoop()`: it shows all variables that contain `perc` in the WBE_habitats data.

Open question @SanderDevisscher 
- [ ] Currently the bars are always sorted in same order (starting with bos and ending with andere). Another option is to sort them from large to small

![Screenshot from 2022-03-03 12-43-44](https://user-images.githubusercontent.com/22143743/156558609-b044b6cd-e8ea-44a8-b674-7f229d8ff777.png)

**Comment by SanderDevisscher** [comment]
I would sort them based on their importance for the species.
This would result in the following order: bos > grasland > landbouw > water > bebouwd > andere 

@jimcasaer what do you think ?

**Comment by jimcasaer** [comment]
Sounds perfect
only one comment based on discussion last week => change bos into bos & natuur
