### ISSUE TITLE
Lower case for all species

### ISSUE THREAD

**Issue by ThomasScheppers** [inbo/reporting-rshiny-grofwildjacht#28]
Species names should always be with lower case (expect beginning of title).

Example: in the 'Landkaart': Gerapporteerd aantal voor Wild zwijn in 2015 -> change to Gerapporteerd aantal voor wild zwijn in 2015

**Comment by mvarewyck** [comment]
Ok, actually only the 3 plots in section 'Landkaart' had to be adapted.

**Comment by ThomasScheppers** [comment]
OK
