### ISSUE TITLE
Long term datastorage

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/reporting-rshiny-grofwildjacht#280]
De databagage van deze repo is wat aan het aandikken. Op lange/middellange termijn zou het nuttig zijn om de data (deels) te stockeren op een ander medium dan github (bvb s3 bucket van aws). 

To be seen.

**Comment by mvarewyck** [comment]
For now I've moved all geojson files already outside the R package. They are summarized in a single R object `spatialData.RData` https://github.com/inbo/reporting-rshiny-grofwildjacht/blob/master/reporting-grofwild/inst/extdata/spatialData.RData

**Comment by SanderDevisscher** [comment]
In the future wbe_binnengrenzen & jachtterreinen geojsons will be shared via s3 bucket directly from ANB however I don't know how this will work security wise and if it will be usable for the app. 

@Jo-Loos can we possibly keep the use of these geojsons in mind when setting up the datastorage on aws ?

**Comment by SanderDevisscher** [comment]
Both wbe_binnengrenzen & jachtterreinen need some preprocessing so maybe it is an option to create a "new" bucket accessible by the app where I place my "processed" .geojsons (and all the other datafiles for the app) 

@Jo-Loos  what do you think about this approach ? Do you think its feasible to dump the files in the bucket using R-scripts ?

**Comment by Jo-Loos** [comment]
after some brainstorming, 

conclusion was that setup similar to one in document ( last image ) would be a likely candidate
it gives the flexibility to test code and data before going live with minimal changes

however if intermediary data needs to be more restricted in form & model, a DB is a beter candidate , but needs more code - changes

![image](https://user-images.githubusercontent.com/19706108/170071735-c0da8198-c6a8-4df6-8a13-07b387965792.png)

[Grofwild_externe_data.pdf](https://github.com/inbo/reporting-rshiny-grofwildjacht/files/8764032/Grofwild_externe_data.pdf)

**Comment by Jo-Loos** [comment]
Na kleine bespreking met ontwikkelaars, 

![image](https://user-images.githubusercontent.com/19706108/170250525-5985bd96-0303-4f87-8df1-12f3d4bc24d7.png)
best komt er ook een multistage builing zodat niet al het werk nodig voor R packages te installeren opnieuw moet gebeuren

**Comment by SanderDevisscher** [comment]
@jimcasaer @RuttenAnneleen hier zie je een beetje de reden voor het gebruik van de S3 buckets. Op termijn waren we zonder ook op gelijkaardige problemen gestoten.
