### ISSUE TITLE
Add option Aantal per 100 ha dekking

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/reporting-rshiny-grofwildjacht#281]
@jimcasaer I checked and habitattype "bos" in the habitatlist corresponds with "cover" determined by the OBF (see https://github.com/inbo/backoffice-wild-analyse/issues/756#issuecomment-986633082 & [707d4bb](https://github.com/inbo/backoffice-wild-analyse/commit/707d4bb7ee62fc781db2dd5af9a2555e563eba31))

Does this mean the option "Aantal per ha dekking" should be calculated as follows, `No animals shot/area of bos in 100 ha` ?

ifso this option should be added to the map and graphs at the top of the page (gerapporteerd afschot).

**Comment by mvarewyck** [comment]
Notes

1. This option is currently named 'Aantal/100ha bos & natuur' in the UI. Let me know if it should be changed to  'Aantal/100ha dekking'.
2. If this option should also be available in the public app (later), I will need a dataset with biotoopData (Area_hab_km2_bos per year and per region).

**Comment by SanderDevisscher** [comment]
fixed
