### ISSUE TITLE
Please note that 'maptools' will be retired by the end of 2023,

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/reporting-rshiny-grofwildjacht#287]
### Discussed in https://github.com/inbo/reporting-rshiny-grofwildjacht/discussions/286

<div type='discussions-op-text'>

<sup>Originally posted by **SanderDevisscher** March  4, 2022</sup>
@mvarewyck while building the app in docker I noticed the following text "Please note that 'maptools' will be retired by the end of 2023".
I was wondering if this will be a issue in the future ?</div>

**Comment by SanderDevisscher** [comment]
@mvarewyck can you check which functions from maptools we use and thus need to incorperate into this package ?

**Comment by mvarewyck** [comment]
Currently used in two functions within `reportingGrofwild::readShapeData()`
```
importFrom(maptools,spRbind)
importFrom(maptools,unionSpatialPolygons)
```

**Comment by mvarewyck** [comment]
It might be a good occasion to move to [`sf`](https://r-spatial.org//r/2022/04/12/evolution.html). I'll investigate

**Comment by mvarewyck** [comment]
> It might be a good occasion to move to [`sf`](https://r-spatial.org//r/2022/04/12/evolution.html). I'll investigate

* Seems feasible with limited changes to the code.
* There will be temporarily two types of .Rdata files in the UAT bucket: in the old `SpatialPolygonsDataFrame` format and the new `sf` format
* Read geojson data in sf format directly using an extra package [`geojsonsf`](https://cran.r-project.org/web/packages/geojsonsf/index.html)

**Comment by SanderDevisscher** [comment]
Have you tried using [st_set_crs(x, 31370)](https://www.rdocumentation.org/packages/sf/versions/0.2-4/topics/st_crs) from sf ?

**Comment by mvarewyck** [comment]
> Have you tried using [st_set_crs(x, 31370)](https://www.rdocumentation.org/packages/sf/versions/0.2-4/topics/st_crs) from sf ?

Thanks, that worked!

**Comment by mvarewyck** [comment]
When I calculate the area of the shapes for the WBE's using `sf::st_area()` the values are incorrect (too small).
For all other shapes, it is pre-calculated at your side.

@SanderDevisscher Can you update the files in [here](https://github.com/inbo/reporting-rshiny-grofwildjacht/tree/master/data) to also have the shape area included?
Relevant files are:
```
"WBE_binnengrenzen_2014" "WBE_binnengrenzen_2015" "WBE_binnengrenzen_2016" 
                                                                           
"WBE_binnengrenzen_2017" "WBE_binnengrenzen_2018" "WBE_binnengrenzen_2019" 
                                                                           
"WBE_binnengrenzen_2020" "WBE_binnengrenzen_2021" "WBE_binnengrenzen_2022" 
                                                                           
"Jachtter_2016-2017_dis" "Jachtter_2017-2018_dis" "Jachtter_2018-2019_dis" 
                                                                           
"Jachtter_2019-2020_dis" "Jachtter_2020-2021_dis" "Jachtter_2021-2022_dis" 
```

**Comment by mvarewyck** [comment]
> ~@SanderDevisscher Can you update the files in [here](https://github.com/inbo/reporting-rshiny-grofwildjacht/tree/master/data) to also have the shape area included?~ 

Sth was wrong with the projection, I was able to fix and now also the calculated area is correct. So, no action is required from your side
