### ISSUE TITLE
TABEL: Gerapporteerd aantal per regio en per leeftijdscategorie

### ISSUE THREAD

**Issue by ThomasScheppers** [inbo/reporting-rshiny-grofwildjacht#29]
1) for the columns 'Verandering...': in case of negative values, the '+' should be removed -> solved in ui? solved in export?
2) the name of the first column: with capital: 'provincie'

**Comment by ThomasScheppers** [comment]
@Fhuysent @jimcasaer 
1) Wat klopte er niet met de berekening tov 5 en 10 jaar?
2) Wat met hoge % niet weer te geven?

**Comment by ThomasScheppers** [comment]
@Fhuysent : hoe komt dat er verschil zit in aantal vermeld in: Gerapporteerd aantal afschot per regio en per type?

**Comment by mvarewyck** [comment]
1. I don't see any problems, could you show print screen from your browser?
2. fixed
3. Note that there is a difference in cause of death between two tables: all versus only afschot

**Comment by ThomasScheppers** [comment]
1. Print screen of roe deer to illustrate +- sign:
![image](https://user-images.githubusercontent.com/24563808/33766156-90107df0-dc1c-11e7-8ab2-394e0d02f3bb.png)

**Comment by ThomasScheppers** [comment]
2. OK

**Comment by ThomasScheppers** [comment]
3. @Fhuysent please check is this is correct.

**Comment by stijnvanhoey** [comment]
The source data need to be checked, to be done by Faunabeheer. For the moment, both tables should provide the same selections, to be done by Machteld. Both tables provide `afschot` only.

**Comment by SanderDevisscher** [comment]
@Yasmine-Verzelen will change this
=> "Verdelging" wordt ook "Afschot" (alleen vr data dataviz)
