### ISSUE TITLE
labeltype for wild zwijn in ecodata

### ISSUE THREAD

**Issue by mvarewyck** [inbo/reporting-rshiny-grofwildjacht#293]
![Screenshot from 2022-03-25 12-59-14](https://user-images.githubusercontent.com/22143743/160117059-9017f0a8-1b53-477a-a234-983bde74d80d.png)

NB: Plot as will be on grofwild page.

For wild zwijn there are 2 choices for labeltype: "wild zwijn"  "wild zwijn*"
Is there a reason for the 2nd one? 

1. If not, could it be removed at your side?
2. If so, should we add it as a "Type" choice for the plot?

**Comment by SanderDevisscher** [comment]
> NB: Plot as will be on grofwild page.
> 
> For wild zwijn there are 2 choices for labeltype: "wild zwijn" "wild zwijn*" Is there a reason for the 2nd one?

No there isn't!! probably a typo

> 1. If not, could it be removed at your side?

I'll remove it a our side. see [issue #810](https://github.com/inbo/backoffice-wild-analyse/issues/810) of the backoffice

> 2. If so, should we add it as a "Type" choice for the plot?

the type is less relevant for wild zwijn then for roedeer.  I think its best to disable the type dropdown when the selected species is not roedeer.

**Comment by mvarewyck** [comment]
> the type is less relevant for wild zwijn then for roedeer. I think its best to disable the type dropdown when the selected species is not roedeer.

Currently, the type option is visible but the only choice is 'alle'
