### ISSUE TITLE
FIGUUR: Afschot per jachtmethode

### ISSUE THREAD

**Issue by mvarewyck** [inbo/reporting-rshiny-grofwildjacht#294]
As suggested during last meeting, we include 'Interval' choice for figuur Afschot per jachtmethode
This is the new plot as it will look on the *grofwild* page.
![Screenshot from 2022-03-25 13-06-46](https://user-images.githubusercontent.com/22143743/160118290-cfceae06-8b87-4488-8ee3-89e92c14798c.png)

This is the old plot
![Screenshot from 2022-03-25 13-05-11](https://user-images.githubusercontent.com/22143743/160118303-e96c6694-263f-4db8-8382-80320d495aa2.png)

1. Should we allow to choose as interval 'Year', such that users can still obtain the old plot? Current choices are: maand, seizoen, twee weken
2. Should we move this plot just below FIGUUR: Verdeling afschot over de jaren (see new example here #293) for easy comparison?

**Comment by SanderDevisscher** [comment]
> 1. Should we allow to choose as interval 'Year', such that users can still obtain the old plot? Current choices are: maand, seizoen, twee weken

Yes, I think its a good idea 

> 2. Should we move this plot just below FIGUUR: Verdeling afschot over de jaren (see new example here [labeltype for wild zwijn in ecodata #293](https://github.com/inbo/reporting-rshiny-grofwildjacht/issues/293)) for easy comparison?

I'll discuss this with @jimcasaer
