### ISSUE TITLE
BUG: couldn't find package 'plotly' when building in docker

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/reporting-rshiny-grofwildjacht#296]
@mvarewyck I get the following error when building the app (from the `test_wildschade`- branch) in docker:
```
devtools::install_version('plotly', version = '4.9.2.1', repos = 'http://cran.us.r-project.org')
Warning: unable to access index for repository http://cran.us.r-project.org/src/contrib:
  cannot open URL 'http://cran.us.r-project.org/src/contrib/PACKAGES'
Error in download_version_url(package, version, repos, type) :
  couldn't find package 'plotly'
Calls: <Anonymous> -> <Anonymous> -> download_version_url
Execution halted
The command '/bin/sh -c R -e "devtools::install_version('plotly', version = '4.9.2.1', repos = 'http://cran.us.r-project.org')"' returned a non-zero code: 1
```
when I try to run `devtools::install_version('plotly', version = '4.9.2.1', repos = 'http://cran.us.r-project.org')` directly in R I get a similar error while `devtools::install_version('plotly', version = '4.9.2.1', repos = 'http://cran.r-project.org')` runs just fine. I'm currently testing if the url change works in docker also.

**Comment by SanderDevisscher** [comment]
UPDATE: URL change from _http://cran.us.r-project.org_ to _http://cran.r-project.org_ fixes the issue.

**Comment by mvarewyck** [comment]
For me, the original link still works locally.
However, it's fine to update the link to what you propose if it works.
