### ISSUE TITLE
R-code structure

### ISSUE THREAD

**Issue by stijnvanhoey** [inbo/reporting-rshiny-grofwildjacht#3]
- Elke figuur is een afzonderlijke R-file in de package
- de naam van de file is dezelfde als de plotfunctie in die file (geef logische naam)
- support-functies van dergelijke functie kunnen in zelfde file als specifiek voor die figuur of samengebracht met andere support functies in een R-file.
- een specifieke R-functie en script wordt opgenomen in de package om de Rshiny-app te starten (`runWildApp.R`)

**Comment by SanderDevisscher** [comment]
komt in orde :-)
