### ISSUE TITLE
Add introduction for export files?

### ISSUE THREAD

**Issue by ThomasScheppers** [inbo/reporting-rshiny-grofwildjacht#30]
Would it be a good idea to add an introduction line in the export files that explains the content?

For example:

**toelichting| De leeftijdscategorie voor everzwijn werd bepaald op basis van de ingezamelde onderkaak**
provincie | Frisling | Overloper | Volwassen | Onbekend | Totaal | Verandering tov 1 jaar (2016) | Verandering tov 5 jaar (2012) | Verandering tov 10 jaar (2007)
-- | -- | -- | -- | -- | -- | -- | -- | --
West-Vlaanderen | 4 | 2 | 0 | 0 | 6 |   |   |  
Oost-Vlaanderen | 0 | 0 | 0 | 0 | 0 |   |   |  
Vlaams Brabant | 0 | 0 | 0 | 0 | 0 |   |   |  
Antwerpen | 23 | 28 | 9 | 0 | 60 |   |   |  
Limburg | 138 | 126 | 45 | 0 | 309 | +-47.9% | +-29.0% | +1445.0%
Voeren | 16 | 19 | 18 | 0 | 53 | +-60.4% | +60.6% |  
Vlaanderen | 181 | 175 | 72 | 0 | 428 | +-51.5% | +-20.7% | +558.5%

**Comment by mvarewyck** [comment]
This will mess up the table format, downloaded tables can now easily be loaded in other programs.
I suggest you could either provide this information in the file name, or let the user download a report with more content.

**Comment by ThomasScheppers** [comment]
OK. Suggestion to be discussed.

**Comment by stijnvanhoey** [comment]
We do not take this up.
