### ISSUE TITLE
New Feature verwezenlijkings graphs for public app

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/reporting-rshiny-grofwildjacht#300]
Na overleg zijn we eruit dat we de 2 grafieken willen toevoegen. 

1. Geeft de trend van de realisatiegraad binnen een provincie/vlaanderen weer dmv een boxplot van het percentage_verwezelijkt per wbe uit Verwezenlijkt_categorie_per_afschotplan.csv met de optie om weer te geven per provincie of vlaanderen 
2. Geeft de absolute verwezenlijking weer dmv een barplot van aantal toegekende/ aantal verwezenlijkte labels zoals op de wbepagina met regio niveaus  provincie en Vlaanderen

De gegevens die nodig zijn voor deze grafieken worden doorgestuurd in de vorm van Verwezenlijkt_categorie_per_afschotplan.csv naar de reporting rshiny repo.

_Originally posted by @SanderDevisscher in https://github.com/inbo/backoffice-wild-analyse/discussions/816#discussioncomment-2498787_

**Comment by SanderDevisscher** [comment]
The graphs can only be made for roedeer and should be placed just above bioindicators

**Comment by mvarewyck** [comment]
Screenshot of the 2nd plot request:

![Screenshot from 2022-04-20 17-20-30](https://user-images.githubusercontent.com/22143743/164265513-df458a7a-9ce8-4df4-9e73-d4f3ec336a7d.png)

**Comment by SanderDevisscher** [comment]
> @SanderDevisscher For the 1st plot:
> 
> > Geeft de trend van de realisatiegraad binnen een provincie/vlaanderen weer dmv een boxplot van het percentage_verwezelijkt per wbe uit Verwezenlijkt_categorie_per_afschotplan.csv met de optie om weer te geven per provincie of vlaanderen
> 
> * Can we have a single boxplot for all WBEs over the selected provinces per year (like we have a single bar with total over all provinces in plot above)? Or should we have a single boxplot per selected province?

a single boxplot over the selected provinces per year. The users can compare the different provinces by (un)checking a province.

> * Should we also include the filter for labeltype (like in the plot above)?

Yes

**Comment by mvarewyck** [comment]
How do we summarize over the different labeltypes? For counts we could do the sum but for the percentage I would suggest to take the average.

**Comment by jimcasaer** [comment]
for the boxplots ? 
if we summarize we simply take the total number of animals shot / total number of attributes per wbe and create the boxplot based on those figures - makes sense ?

**Comment by mvarewyck** [comment]
> if we summarize we simply take the total number of animals shot / total number of attributes per wbe and create the boxplot based on those figures - makes sense ?

Makes totally sense.

Screenshot of the 1st plot request:
![Screenshot from 2022-04-22 09-52-07](https://user-images.githubusercontent.com/22143743/164643295-a0d2b819-397c-4b08-943c-4edd472afae7.png)

**Comment by jimcasaer** [comment]
Nice !
En het corona-effect 2020 is heel duidelijk zichtbaar !! 

Ga je kunnen 'hooveren' op deze plots ?

**Comment by mvarewyck** [comment]
Hoover screenshots

![Screenshot from 2022-04-22 10-21-20](https://user-images.githubusercontent.com/22143743/164648771-2afc7169-bcac-4443-b6af-028fedb3a589.png)

![Screenshot from 2022-04-22 10-22-40](https://user-images.githubusercontent.com/22143743/164648757-5fd0b03f-dd02-4385-b7fb-09214f239b00.png)
