### ISSUE TITLE
Update text bio-indicatoren

### ISSUE THREAD

**Issue by mvarewyck** [inbo/reporting-rshiny-grofwildjacht#301]
Related to #262 

Could you please generalize the text in [uiText file](https://github.com/inbo/reporting-rshiny-grofwildjacht/blob/master/reporting-grofwild/inst/extdata/uiText.csv#L3) so that is relevant for wild zwijn too?

**Comment by SanderDevisscher** [comment]
In which branch should I make these changes ?

**Comment by mvarewyck** [comment]
New branch: update_mei_2022

**Comment by SanderDevisscher** [comment]
allready fixed ?

**Comment by mvarewyck** [comment]
The text still focuses on 'Ree' while it should also apply to 'Wild zwijn'
https://github.com/inbo/reporting-rshiny-grofwildjacht/blob/update_mei_2022/reporting-grofwild/inst/extdata/uiText.csv#L3

**Comment by SanderDevisscher** [comment]
Ah, I was looking at the text for the embryo graph. My mistake!

Op di 26 apr. 2022 11:04 schreef Machteld Varewyck ***@***.***

**Comment by SanderDevisscher** [comment]
@jimcasaer can you have a look at https://github.com/inbo/reporting-rshiny-grofwildjacht/blob/update_mei_2022/reporting-grofwild/inst/extdata/uiText.csv#L3

@mvarewyck I've added a text split indicator {=ree}. Can you provide the necessary logic needed to show the part after it when the wildsoort in question is selected ?

**Comment by SanderDevisscher** [comment]
@mvarewyck I've implemented some more changes to the text. Can you check if its ok like this. 
And implement the necessary logic to split the text and display it only when the species in the split indicator is selected ?
