### ISSUE TITLE
New feature: add data bron filter to FIGUUR: Geslachtsverdeling binnen het afschot per leeftijdscategorie

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/reporting-rshiny-grofwildjacht#303]
Add data bron filters for leeftijd and geslacht to `FIGUUR: Geslachtsverdeling binnen het afschot per leeftijdscategorie` like most other graphs. 
This feature may be included in the wbe page as well.

**Comment by mvarewyck** [comment]
@SanderDevisscher I found surprisingly few male Ree with known age from INBO

![Screenshot from 2022-09-20 15-14-32](https://user-images.githubusercontent.com/22143743/191267419-336ce167-da7d-4962-99dc-866999ed819d.png)
