### ISSUE TITLE
BUGs: TABEL: Aantal schademeldingen per type schade

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/reporting-rshiny-grofwildjacht#305]
# Title Figuur/Tabel: _"TABEL: Aantal schademeldingen per type schade"_
## Bug description:
When testing the may update in docker I get the following error @ TABEL: Aantal schademeldingen per type schade
> numbers of columns of arguments do not match

the error occurs when using the provincie & faunabeheerzones regio filters. The regio filter Vlaanderen works but 
something is wrong with the total column (see screenshot below).

## Screenshot:
![image](https://user-images.githubusercontent.com/16779320/167901188-866c4c7a-4531-4f9d-bc7d-7f4a30205460.png)

with regio filter Vlaanderen
![image](https://user-images.githubusercontent.com/16779320/167901645-6efd6b98-85fa-4a37-bbca-0769c4f110b6.png)

**Comment by mvarewyck** [comment]
There was a problem with the header (introduced by https://github.com/inbo/reporting-rshiny-grofwildjacht/issues/254)

**Comment by SanderDevisscher** [comment]
The initial bug seems to be fixed in docker.
However there is still something weird happening, namely the total for Flanders (2787) when using the province region filter is missing 2 notifications (2785) & 3 notifications (2784) when using the fbz region filter. I think this is due to the land plots being on the border of 2 provinces/fbzs and thus not getting assigned to one. They probably have NA as province/fbz value and should be dislayed as "onbekend" in the table.
