### ISSUE TITLE
NEW Feature: Afschot locations

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/reporting-rshiny-grofwildjacht#306]
# Suggested Title: _"KAART: Gerapporteerd afschotlocaties voor {wildsoort} in {periode}"_

## INFO:
This map should display the reported locations of the afschot with a buffer (in m) based on the `verbatimCoordinateUncertainty`

### Position
- Just below habitat information (closed)
### Datacolumns
- `verbatimLatitude`
- `verbatimLongitude`
- `verbatimCoordinateUncertainty `

### Filters
- Periode using `afschotjaar`
- Nauwkeurigheid using `PuntLocatieTypeID` with the following options/translations:

| PuntLocatieTypeID 	| Nauwkeurigheid    	|
|-------------------	|-------------------	|
| 1                 	| Exact             	|
| 3                 	| Binnen 250m       	|
| 5                 	| Binnen een gebied 	|
| NA                	| Onbekend          	|
| 1,3,5,NA         | Alle                  |

Keep in mind there are cases where the PuntLocatieTypeID is known but the coordinates are NA these should be omited. 
There should be a percentage displaying which _**portion of labels that fits the filters & has coordinates**_ compared to the _**total number of labels for the wbe in the period**_.   	

- If possible it would also be nice to have seizoen and jaar as display variables like at Landkaart 2 for wildschade.  
- Default 1 & 3 should be selected

### Code example
```
```
### Additional Options
- Download data
- Download map

**Comment by mvarewyck** [comment]
@SanderDevisscher Are these data variables already available?

**Comment by SanderDevisscher** [comment]
These variables should be added to the geography file

**Comment by SanderDevisscher** [comment]
@mvarewyck de variabelen zijn toegevoegd aan de geography file.

**Comment by mvarewyck** [comment]
Example screenshot below.
I found that for e.g. 'De Zwarte Beek' some locations are outside the region - even when selecting only the 'Exact'

Coordinate range for the polygon
```
[1]  5.217900  5.383367 51.001405 51.129944
```
Coordinate range for the points
```
[1,]          5.163620         50.98907
[2,]          5.434799         51.14406
```
![Screenshot from 2023-01-23 15-52-24](https://user-images.githubusercontent.com/22143743/214074980-9c94cb4f-5b6f-471f-9593-fc2559259e5b.png)

**Comment by SanderDevisscher** [comment]
I'll check

**Comment by SanderDevisscher** [comment]
@mvarewyck klopt het dat je de kolom KboNummer_Toek gebruikt om op te splitsen ? 

Ik krijg namelijk dit beeld met KboNummer_Toek:
![image](https://user-images.githubusercontent.com/16779320/214093097-bfd508ff-2482-4204-b392-4e3603b55c6b.png)

terwijl ik dit beeld krijg met KboNummer_Georef:
![image](https://user-images.githubusercontent.com/16779320/214093286-3bb7fa7a-6558-498d-b59d-306c623c237f.png)

@jimcasaer @RuttenAnneleen @LynnPallemaerts ik zie hier de volgende opties in:

1. We geven het afschot volgens KboNummer_Georef weer met een disclaimer dat afschot dat niet weergegeven word mogelijk weerhouden wordt ten gevolge van plaatsing buiten de wbe. 
2. We geven het afschot volgens KboNummer_Toek weer **inclu.** de buiten de wbe geplaatste punten met een disclaimer dat het afschot geselecteerd word obv de toekenningen. 
3. We geven het afschot volgens KboNummer_Toek weer **exclu.** de buiten de wbe geplaatste punten met een disclaimer dat het afschot geselecteerd word obv de toekenningen en het afschot buiten de wbe weerhouden werd wegens plaatsing buiten de wbe grenzen. (qua code `filter(KboNummer_Toek == KboNummer_Georef)`)
4. We geven de mogelijkheid te kiezen tussen bovenstaande opties. Hoe we dit dan zouden noemen is me wel nog de vraag. 
5. Something completely different

Wat denken jullie ?

**Comment by mvarewyck** [comment]
> @mvarewyck klopt het dat je de kolom KboNummer_Toek gebruikt om op te splitsen ?

Ja, we gebruiken hier KboNummer_Toek (net als voor de andere figuren)
Er zit precies nog een verschil op de getoonde punten. Heeft de data CRS WGS 84 (a.k.a. EPSG:4326)?

**Comment by SanderDevisscher** [comment]
> > @mvarewyck klopt het dat je de kolom KboNummer_Toek gebruikt om op te splitsen ?
> 
> Ja, we gebruiken hier KboNummer_Toek (net als voor de andere figuren)

Ok Prima, ik zou nog ff wachten op feedback van @jimcasaer, @RuttenAnneleen en/of @LynnPallemaerts om hier de knoop rond door te hakken. 

>  Er zit precies nog een verschil op de getoonde punten. Heeft de data CRS WGS 84 (a.k.a. EPSG:4326)?

Mijn oog was er net ook op gevallen, ik heb namelijk geef afschot op het militair domein maar wel in leopoldsburg centrum :/. 
De punten staan idd in CRS WGS 84 (a.k.a. EPSG:4326) hetgeen ik ook gebruik voor mijn kaartjes. Mogelijks is de oorzaak te zoeken in "verouderde data". Ik gebruik namelijk de data die klaar staat voor de volgende update (staat ook al op de s3 bucket)  maar ze staat niet in de repo.  Ik kan ze ook niet aan deze commit hangen wegens te groot (32mb vs limiet van 25mb). 
In welke branch ben je dit aan het uitwerken ?

**Comment by mvarewyck** [comment]
> In welke branch ben je dit aan het uitwerken ?

Dit zit in branch 306-afschot-locations. Ik kan de data van S3 bucket binnen halen om het te vergelijken

**Comment by mvarewyck** [comment]
After a small investigation with data from S3 (bucket **inbo-wbe-uat-data**), I still think the points on my plot are in the data.
E.g. one with coordinates 5.29459159805158E 51.1440587282111N

```
> currentKbo <- unique(geoData$KboNummer_Toek[geoData$WBE_Naam_Toek %in% "De Zwarte Beek"])
> currentKbo
[1] 446912355

> subData <- geoData[geoData$KboNummer_Toek %in% currentKbo, ]
> subData$verbatimLatitude <- gsub("\\,", "\\.", subData$verbatimLatitude)
> subData$verbatimLongitude <- gsub("\\,", "\\.", subData$verbatimLongitude)

> which(subData$verbatimLatitude == "51.1440587282111")
[1] 2639
> subData[2639, "verbatimLongitude"]
[1] "5.29459159805158"

> id <- subData[2639, "ID"]
> subData[2639, ]
                                        ID wildsoort postcode_afschot_locatie
42293 603ab29d-7d4d-4b2d-8b4c-e81301505292       Ree                     3940
      gemeente_afschot_locatie provincie afschotjaar FaunabeheerZone
42293            Hechtel-Eksel   Limburg        2018               9
      FaunabeheerDeelzone  UTM5  WBE_Naam_Toek WBE_Naam_Georef KboNummer_Toek
42293                  9B FS66A De Zwarte Beek     De Zandhaas      446912355
      KboNummer_Georef PartijNummer verbatimLatitude verbatimLongitude
42293        455452216          417 51.1440587282111  5.29459159805158
      verbatimCoordinateUncertainty PuntLocatieTypeID    fbz_gemeente
42293                            10                 1 9_Hechtel-Eksel
> ecoData[ecoData$ID == id, ]
                                        ID wildsoort afschotjaar afschot_datum
42293 603ab29d-7d4d-4b2d-8b4c-e81301505292       Ree        2018    2018-08-05
      provincie geslacht_comp Leeftijdscategorie_onderkaak ontweid_gewicht
42293   Limburg     Mannelijk              Niet ingezameld            19.1
      aantal_embryos_onbekend aantal_embryos aantal_embryos_labo
42293                      NA             NA                  NA
      aantal_embryos_MF onderkaaklengte_links onderkaaklengte_rechts
42293                NA                   153                     NA
      doodsoorzaak leeftijd_maanden leeftijdscategorie_MF onderkaaklengte_comp
42293      afschot             <NA>             Volwassen                  153
      leeftijd_comp leeftijd_comp_bron aantal_embryos_bron
42293     Volwassen  meldingsformulier                <NA>
      onderkaaklengte_comp_bron geslacht_comp_bron type_comp labeltype
42293         meldingsformulier  meldingsformulier    Reebok       Bok
      tijdstip_comp jachtmethode_comp wettelijk_kader periode periode_wettelijk
42293      20:40:00       Aanzitjacht reguliere jacht     dag               dag
      onderkaaklengte_mm leeftijd_comp_inbo
42293                 NA          Volwassen
```

@SanderDevisscher Is it the right bucket? Your afschot data looks much more clustered, is this expected?

**Comment by LynnPallemaerts** [comment]
@SanderDevisscher Beide kaarten hierboven lijken afschotlocaties te hebben binnen de bebouwde kom, zou toch niet mogen? Tenzij dit minder nauwkeurige punten zijn?

**Comment by RuttenAnneleen** [comment]
Mijn voorkeur is 
2. We geven het afschot volgens KboNummer_Toek weer inclu. de buiten de wbe geplaatste punten met een disclaimer dat het afschot geselecteerd word obv de toekenningen.

Want anders zijn er jagers binnen een WBE die hun afschot niet gaan zien als het buiten de WBE grenzen valt zien toch?

**Comment by SanderDevisscher** [comment]
> @SanderDevisscher Beide kaarten hierboven lijken afschotlocaties te hebben binnen de bebouwde kom, zou toch niet mogen? Tenzij dit minder nauwkeurige punten zijn?

In theorie heb je gelijk maar de praktijk leert ons dat er toch nog fout exact aangeduid wordt. Evt. zouden we een deel van deze fouten kunnen detecteren door een laag van de stadskernen of bwk urbaan gebied er tegenaan te gooien.

**Comment by SanderDevisscher** [comment]
> @SanderDevisscher Is it the right bucket? Your afschot data looks much more clustered, is this expected?

Yes its the correct bucket. I suspect something goes wrong when I read the data. I'll Investigate!

**Comment by SanderDevisscher** [comment]
Ik vind geen verschil in mijn kaartjes als ik:

- Inlees dmv read.csv2 vs read_delim
- Inlees als as.character vs as.numeric (wel als ik inlees as.integer)

Ik dacht even dat het resultaat is van een afronding maar dat blijkt toch niet het geval te zijn want volgende code

```
rshiny_reporting_data_geography <- read_delim("Projecten/Grofwild_Dataviz/Output/rshiny_reporting_data_geography.csv", 
                                              delim = ";", escape_double = FALSE, col_types = cols(verbatimLatitude = col_character(), verbatimLongitude = col_character()), trim_ws = TRUE) %>% 
  mutate(verbatimLatitude = as.integer(gsub("\\,", "\\.", verbatimLatitude)),
         verbatimLongitude = gsub("\\,", "\\.", verbatimLongitude))

test2 <- as.data.frame(rshiny_reporting_data_geography) %>% 
  filter(verbatimLatitude == "51.1440587282111")

test2
```
Resulteert in onderstaande data:
```
                                    ID wildsoort postcode_afschot_locatie gemeente_afschot_locatie
1 603ab29d-7d4d-4b2d-8b4c-e81301505292       Ree                     3940            HECHTEL-EKSEL
  provincie afschotjaar FaunabeheerZone FaunabeheerDeelzone  UTM5  WBE_Naam_Toek WBE_Naam_Georef
1   Limburg        2018               9                  9B FS66A De Zwarte Beek     De Zandhaas
  KboNummer_Toek KboNummer_Georef PartijNummer verbatimLatitude verbatimLongitude
1      446912355        455452216          417         51.14406  5.29459159805158
  verbatimCoordinateUncertainty PuntLocatieTypeID
1                            10                 1
```

Merk op dat verbatimLatitude geprint wordt als 51.14406 maar gefilterd werd als "51.1440587282111" 

@mvarewyck hoe visualiseer jij de data ? Ik gebruik momenteel leaflet (2.1.1.) en onderstaande code:

```
zw_zwb_toek <- rshiny_reporting_data_geography %>% 
  filter(wildsoort == "Wild zwijn",
         KboNummer_Toek == 446912355,
         !is.na(verbatimLatitude)) %>% 
  st_as_sf(coords = c("verbatimLongitude", "verbatimLatitude"),
           crs = 4326) %>% 
  leaflet() %>% 
  addTiles() %>% 
  addCircles() %>% 
  addPolylines(data = wbe,
               color = "black",
               popup = ~WBE_NR)

zw_zwb_toek 
```

**Comment by RuttenAnneleen** [comment]
Ik krijg dezelfde resultaten als Sander  bij het runnen van bovenstaand script

**Comment by mvarewyck** [comment]
@SanderDevisscher Ik zie in jouw plot code dat je naar 'Wild zwijn' kijkt, mijn figuur is voor 'Ree' :open_mouth: Dat verklaart het verschil. Hieronder mijn figuur voor 'Wild zwijn'.
Dus: er zijn reeen geschoten op het militair domein, maar geen zwijnen.

![Screenshot from 2023-01-25 14-39-57](https://user-images.githubusercontent.com/22143743/214578525-4d1d8c32-d52e-4afe-9f21-cf3961c6d99b.png)

**Comment by SanderDevisscher** [comment]
> @SanderDevisscher Ik zie in jouw plot code dat je naar 'Wild zwijn' kijkt, mijn figuur is voor 'Ree' 😮 Dat verklaart het verschil. Hieronder mijn figuur voor 'Wild zwijn'. Dus: er zijn reeen geschoten op het militair domein, maar geen zwijnen.
> 
> ![Screenshot from 2023-01-25 14-39-57](https://user-images.githubusercontent.com/22143743/214578525-4d1d8c32-d52e-4afe-9f21-cf3961c6d99b.png)

Oef, ik dacht dat ik gek aan het worden was 😅

**Comment by SanderDevisscher** [comment]
In ieder geval we gaan voor optie 2:

> We geven het afschot volgens KboNummer_Toek weer inclu. de buiten de wbe geplaatste punten met een disclaimer dat het afschot geselecteerd word obv de toekenningen.

als je een placeholder voorziet voor de disclaimer zullen wij hem vullen 😉

**Comment by mvarewyck** [comment]
> als je een placeholder voorziet voor de disclaimer zullen wij hem vullen wink

Disclaimer wordt uitgelezen in [uiText, kolom WBE](https://github.com/inbo/reporting-rshiny-grofwildjacht/blob/356_hotfixWbe/reporting-grofwild/inst/extdata/uiText.csv#L13)
