### ISSUE TITLE
Onbekend does not show on graph 

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/reporting-rshiny-grofwildjacht#307]
# Title Figuur/Tabel: "FIGUUR: Verdeling afschot over de jaren"
## Bug description:
The age category "onbekend" does not show on the graph. I think the same error causes the totals to be incorrect, these should equal the total number of animals shot with a afschotdatum (971 for 2022?). I think adding "Onbekend" tot the Leeftijdscategorie - filter could fix the issue. 
## Screenshot:
![newplot(4)](https://user-images.githubusercontent.com/16779320/168288698-a467dd1b-4c80-4153-815a-1a412e5ed021.png)
![newplot(5)](https://user-images.githubusercontent.com/16779320/168288766-19a06945-5b2a-4975-a07a-5a3c9c1dd654.png)

**Comment by mvarewyck** [comment]
Problem was two-fold: 
- added onbekend to choices of leeftijdscategorie
- no longer exclude records with missing afschot_datum in `countYearShotAnimals()`

For testing: In 2022 there were no missing leeftijd, while for 2021 there are 8

**Comment by SanderDevisscher** [comment]
fixed in docker
