### ISSUE TITLE
BUG: No data available when Data bron leeftijd == INBO

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/reporting-rshiny-grofwildjacht#308]
# Title Figuur/Tabel: "FIGUUR: Leeggewicht per leeftijdscategorie en geslacht (INBO of Meldingsformulier)"
## Bug description:
When setting Data bron leeftijd to INBO only overloper & volwassen are displayed. Since the ecology file does contain wild boar with leeftijd_comp_bron == "inbo" & leeftijd_comp|Leeftijdscategorie_onderkaak == "Frisling" & !is.na(leeftijd_maanden) one would expect the categories Frisling <6m &  Frisling >6m to be displayed on the graph as well. 
## Screenshot:
Data bron leeftijd = INBO  & meldingsformulier
![newplot(6)](https://user-images.githubusercontent.com/16779320/168297772-3d5c4181-378d-4ba9-ba69-909769074d08.png)

Data bron leeftijd = INBO
![newplot(7)](https://user-images.githubusercontent.com/16779320/168297946-fef28ee4-b319-470d-b17f-35b61e1c2c71.png)

[Wild_zwijn_2007-2022_Frisling ( 6m)-Frisling ( 6m)-Overloper-Volwassen_boxAgeWeight_data.csv](https://github.com/inbo/reporting-rshiny-grofwildjacht/files/8688352/Wild_zwijn_2007-2022_Frisling.6m.-Frisling.6m.-Overloper-Volwassen_boxAgeWeight_data.csv)

**Comment by SanderDevisscher** [comment]
similar & possibly linked issue with "FIGUUR: Gerapporteerd aantal embryo's voor vrouwelijke wilde zwijnen per jaar". Here the "onbekend" does not appear on the graph, see screenshot:
![newplot(8)](https://user-images.githubusercontent.com/16779320/168327164-a38b7669-40ea-4a3f-91da-2d197b13dd60.png)

**Comment by mvarewyck** [comment]
@SanderDevisscher  For the embryos graph, I'm not sure what you are missing.
In the data, there are only two subjects in 2022 with leeftijd_comp_bron "inbo". The female one with 5 embryos is displayed in the graph. The one for which we don't know gender and type_comp is not. Do you also want to display the latter?

```
> ecoData <- loadRawData(type = "eco")
> data <- ecoData[ecoData$wildsoort == "Wild zwijn", ]
> data[data$leeftijd_comp_bron == "inbo" & data$afschotjaar == 2022, c("geslacht_comp", "type_comp", "aantal_embryos")]
      geslacht_comp    type_comp aantal_embryos
22922      Onbekend     Onbekend             NA
22923     Mannelijk Frisling (m)             NA
22924    Vrouwelijk Frisling (v)              5
22925     Mannelijk Frisling (m)             NA
```

**Comment by SanderDevisscher** [comment]
@mvarewyck you are correct, the graph is correct !

**Comment by SanderDevisscher** [comment]
fixed in docker
