### ISSUE TITLE
FIGUUR: Afschot per jaar en per leeftijdscategorie (o.b.v. onderkaak)

### ISSUE THREAD

**Issue by ThomasScheppers** [inbo/reporting-rshiny-grofwildjacht#31]
1) The type of the plot based on the number (all data) (first option) should be switched to a stacked bar plot
2) change 'Percentage (subset van ingezamelde onderkaken)' to 'Percentage (enkel ingezamelde onderkaken)'
3) for wild zwijn there is a mismatch in the categories from the beginning until 2013. Frisling should be the highest, than overloper and the lowest should be volwassen (as from 2014 onwards).
4) @Fhuysent @jimcasaer How meaningful is this for roe deer? Only data from 2014/2015, only for kits-geit?

**Comment by ThomasScheppers** [comment]
@Fhuysent @jimcasaer : cijfers 2015 geiten en smalreeën nog bekijken

**Comment by Fhuysent** [comment]
For roe deer, the categories 'jongvolwassen' and 'volwassen' for all animals labelled 'mannelijk' should be removed from this graph.

**Comment by mvarewyck** [comment]
1. OK
2. OK
3. The numbers in the plots correspond with those obtained from the raw data we received.
> table(subset(data, subset = afschotjaar == 2013, select = Leeftijdscategorie_onderkaak))

       Frisling Niet ingezameld       Overloper       Volwassen 
             63             184             260             122 
> table(subset(data, subset = afschotjaar == 2014, select = Leeftijdscategorie_onderkaak))

       Frisling Niet ingezameld       Overloper       Volwassen 
            291             175              90              49 
4. OK. Could you give more context why these "Mannelijk" and "(Jong)volwassen" are removed?

**Comment by ThomasScheppers** [comment]
for wild boar, something goes wrong:
![image](https://user-images.githubusercontent.com/24563808/33767092-932ae2d8-dc20-11e7-8d2a-1c25e88c7417.png)

**Comment by ThomasScheppers** [comment]
2. OK
3. Data to be checked by me.
4. Data for adult and young adult males are not systematically collected and hence not meaningful. This is not a bio-indicator.

**Comment by mvarewyck** [comment]
For plotting issue: I found the error is fixed with latest shiny. Issue is there when using shiny_1.0.3 but not with shiny_1.0.5
@stijnvanhoey To install on your docker server you could use `--no-cache` when building the image.

**Comment by stijnvanhoey** [comment]
Faunabeheer bekijkt dit in de brondata...

**Comment by stijnvanhoey** [comment]
`--no-cache` option added to configuration.

**Comment by Yasmine-Verzelen** [comment]
@Fhuysent will check
