### ISSUE TITLE
nakijken : verschil tussen afschot per gemeente en afschot per gemeente binnen FBZ -- raar in FBZ8 

### ISSUE THREAD

**Issue by jimcasaer** [inbo/reporting-rshiny-grofwildjacht#319]
er gaat afschot verloren dan ook niet op niveau FBZ terug te vinden is

**Comment by jimcasaer** [comment]
@mvarewyck ik zet jou hier ook bij want weet niet op welk niveau de fout gebeurt

**Comment by mvarewyck** [comment]
@jimcasaer Kan je een voorbeeld geven? Dat helpt om te achterhalen waar het eventueel fout loopt
Mogelijks is de FBZ onbekend en dan wordt het afschot wel weergegeven voor de gemeente maar niet bij selectie van FBZ.

**Comment by jimcasaer** [comment]
Machteld,

als ik voor 2021 kijk naar Huldenberg en Oud Heverlee als gemeente kom ik op respectievelijk 41 en 57 geschoten evers
kies ik bovenaan gemeente binnen FBZ en kies ik dezelfde twee gemeenten (alle twee volledige in FBZ 8) dan kom ik op respectievelijk 25 en 44 stuks ?

**Comment by mvarewyck** [comment]
Zoals ik vermoedde, wordt het verschil verklaard door observaties waarvoor de gemeente wel gekend is maar FBZ niet.

**Oud-Heverlee**
```
library(reportingGrofwild)
geoData <- loadRawData(type = "geo")
subData <- geoData[geoData$wildsoort == "Wild zwijn" & geoData$afschotjaar == 2021, ]

sum(grepl("Oud-Heverlee", subData$gemeente_afschot_locatie))
# [1] 57
sum(grepl("Oud-Heverlee", subData$fbz_gemeente))
# [1] 44
table(subData[subData$gemeente_afschot_locatie == "Oud-Heverlee", 
    c("gemeente_afschot_locatie", "fbz_gemeente")], useNA = "always")
#                         fbz_gemeente
# gemeente_afschot_locatie 8_Oud-Heverlee <NA>
#             Oud-Heverlee             44   13
#             <NA>                      0   19
```

**Huldenberg**
```
library(reportingGrofwild)
geoData <- loadRawData(type = "geo")
subData <- geoData[geoData$wildsoort == "Wild zwijn" & geoData$afschotjaar == 2021, ]

sum(grepl("Huldenberg", subData$gemeente_afschot_locatie))
# [1] 41
sum(grepl("Huldenberg", subData$fbz_gemeente))
# [1] 25
table(subData[subData$gemeente_afschot_locatie == "Huldenberg", 
    c("gemeente_afschot_locatie", "fbz_gemeente")], useNA = "always")
#                         fbz_gemeente
# gemeente_afschot_locatie 8_Huldenberg <NA>
#               Huldenberg           25   16
#               <NA>                  0   19
```

- Voor Oud-Heverlee bestaat er een 7 en 8 FBZ, dus we kunnen niet zomaar alle ontbrekende FBZ aan 8 toekennen.
- Voor Huldenberg bestaat er enkel een 8 FBZ, dus daar zouden we wel de ontbrekende FBZ kunnen invullen.
```
dataDir <- system.file("extdata", package = "reportingGrofwild")
load(file = file.path(dataDir, "spatialData.RData"))

unique(grep("Oud-Heverlee", spatialData$fbz_gemeentes$NAAM, value = TRUE))
# [1] "8_Oud-Heverlee" "7_Oud-Heverlee"
unique(grep("Huldenberg", spatialData$fbz_gemeentes$NAAM, value = TRUE))
# [1] "8_Huldenberg"
```
@SanderDevisscher Vullen jullie ontbrekende FBZ aan (indien mogelijk) in de back-office [rshiny_reporting_data_geography.csv](https://github.com/inbo/reporting-rshiny-grofwildjacht/blob/master/reporting-grofwild/inst/extdata/rshiny_reporting_data_geography.csv) of kijken wij hiervoor?

**Comment by SanderDevisscher** [comment]
Dit stond reeds op mijn radar zie [issue #805](https://github.com/inbo/backoffice-wild-analyse/issues/805) van de backoffice

**Comment by SanderDevisscher** [comment]
backend issue
