### ISSUE TITLE
FIGUUR: Percentage jaarlijks afschot

### ISSUE THREAD

**Issue by ThomasScheppers** [inbo/reporting-rshiny-grofwildjacht#32]
1) X-as laten snijden op 0 bij de Y-as (vastzetten)
2) kleur mediaan niet goed zichtbaar
3) in de legende: 'gemiddelde' vervangen door 'uniforme verdeling'
4) for roe deer: make it possible to select multiple types (eg. geit and kits)

**Comment by ThomasScheppers** [comment]
@Fhuysent @jimcasaer :
1. Berekening hoogste en gemiddelden laatste jaren: betekenis van % in jaren dat afschot niet mocht?

**Comment by Fhuysent** [comment]
X-axis in all three types should be the entire year.
Uniform distribution should be different and separate for hunting period of 'geit en kits' and 'bok'.

**Comment by mvarewyck** [comment]
1. OK
2. Adapted to inbo.grijsblauw
3. OK
4. TODO. Still some questions:
* Each type has its own opening season. Do you want to combine multiple opening seasons in one plot (not recommended)? Or do you want to allow following choices: bok; geit; kits; geit and kits? 
* When showing on x-axis entire year, should the uniform distribution (gemiddelde) still be calculated during opening season only?

**Comment by ThomasScheppers** [comment]
1. OK.
2. OK.
3. OK.
4. @Fhuysent @jimcasaer please comment on questions.

**Comment by stijnvanhoey** [comment]
- outliers out (based on info on opening season + 
- x-as is altijd het volledige jaar => enkel data van het geselecteerde type/jachtseizoen getoond
- 100% is calculated on the label-type
-> we do not plot 2 types (lines) together...

**Comment by SanderDevisscher** [comment]
@Fhuysent will post method in git
