### ISSUE TITLE
F16_1: Reproductie onbekend

### ISSUE THREAD

**Issue by mvarewyck** [inbo/reporting-rshiny-grofwildjacht#322]
Bij [het script](https://github.com/inbo/reporting-rshiny-grofwildjacht/blob/318-dashboard-figuren-code/dashboard/scripts/F16_1_deelname_reproductie.Rmd#L28-L29) worden records met onbekend aantal embryo's geclasseerd als niet-drachtig. 

Ik zie 2 geldige (alternatieve) opties:

1. extra categorie waarvoor reproductiestatus "Onbekend" is. Die kleuren we dan grijs in figuur
2. de observaties met onbekende reproductiestatus uitsluiten. Onder de figuur vermelden welk percentage we hierdoor uitsluiten.

**Comment by LynnINBO** [comment]
@mvarewyck Ik zou leunen naar een extra categorie "Onbekend", zodat het ook duidelijk is dat we meer zouden moeten inzetten op het tellen van embryo's bij de jacht.

@RuttenAnneleen , wat denk jij?

**Comment by RuttenAnneleen** [comment]
@mvarewyck & @LynnINBO: Ik denk inderdaad dat een extra categorie "Onbekend" hier de beste opties is!

Misschien na @jimcasaer zijn verlof nog even vragen of hij ons hier in volgt

**Comment by SanderDevisscher** [comment]
@RuttenAnneleen @LynnINBO ik volg de piste van een extra categorie "onbekend"

**Comment by mvarewyck** [comment]
> let wel dat het hier enkel over de vrouwelijke dieren gaat. van de mannetjes worden geen gegevens van voortplantingsstaat bijgehouden.

Jazeker, er wordt gefilterd op vrouwelijk
