### ISSUE TITLE
FIGUUR: Geslachtsverdeling binnen het afschot per leeftijdscategorie

### ISSUE THREAD

**Issue by ThomasScheppers** [inbo/reporting-rshiny-grofwildjacht#33]
1) voor everzwijn enkel voor de ingezamelde onderkaken waarbij de leeftijdscategorie bepaald werd. Dus niet de leeftijdscategorie op basis van het meldingsformulier

**Comment by mvarewyck** [comment]
1. OK

**Comment by ThomasScheppers** [comment]
1. To be checked by me.

**Comment by SanderDevisscher** [comment]
Should be OK @Yasmine-Verzelen will check
