### ISSUE TITLE
studiegebied info

### ISSUE THREAD

**Issue by mvarewyck** [inbo/reporting-rshiny-grofwildjacht#330]
Sander heeft nieuwe data toegevoegd voor de bos gegevens, zoals weergegeven in onderstaande tabel.
Kunnen jullie eens controleren of de eenheid, labels en data zijn zoals verwacht?

* Voor mij zijn de zeer grote getallen van bos perimeter moeilijk vergelijkbaar.
* Weg densiteit en bos perimeter hebben dezelfde eenheid. Ik zou verwachten dat densiteit altijd dezelfde eenheid heeft (voor weg en bos)

![studiegebied](https://user-images.githubusercontent.com/22143743/187716187-82699261-ba6d-4150-a191-c24e4b64ac22.png)

**Comment by SanderDevisscher** [comment]
@mvarewyck 
- bos perimeter is in m =>` /1000/area_km2` als je het wilt uitdrukken in deze eenheid. 
- bos densiteit is het absoluut aantal => `/area_km2` om het uit te drukken in deze eenheid.
- bos oppervlakte lijkt me correct voor gemiddelde oppervlakte van de bospatches al vind ik wel dat de kolomkop deze lading niet dekt. Ik zou hier `Gemiddelde bos oppervlakte` of `Gem. bos opp.` van maken.
