### ISSUE TITLE
Plot bioindicator onderkaaklengte - Onderkaaklengte bron #867

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/reporting-rshiny-grofwildjacht#332]
Specific example for WBE page - but applies to other pages/regions too

* KBO: 452846379
 * Species: Ree
 
 I found that when switching 'onderkaaklengte_bron' more records are available for 'meldingsformulier' then both 'inbo en meldingsformulier'. This is present in the data as such (not due to coding), see e.g. line 69525 for ecology data. **Is this an issue or expected behavior?**
 
 Comparison in the plots below for year 2017
 
 * onderkaaklengte_bron: INBO en meldingsformulier: 9 records -> we read from onderkaaklengte_comp
 * onderkaaklengte_bron: meldingsformulier: 10 records -> we calculate from onderkaaklengte_links and onderkaaklengte_rechts
 
 ![Screenshot from 2022-09-20 11-25-30](https://user-images.githubusercontent.com/22143743/191222929-36d274f6-5247-48ca-8b8b-a5d0cdd3f583.png) ![Screenshot from 2022-09-20 11-25-18](https://user-images.githubusercontent.com/22143743/191222936-9cc9ef02-3c4d-4bcd-a5c0-bcc9a108ffd1.png)

=> issue transfered to backoffice see https://github.com/inbo/backoffice-wild-analyse/issues/867

**Comment by SanderDevisscher** [comment]
@mvarewyck deze discrepantie heeft te maken met het feit dat onderkaaklengte_links en onderkaaklengte_rechts geen verbetering is voor te korte en te lange onderkaaklengtes terwijl die er in onderkaaklengte_comp wel is. Te korte en te lange labels worden in onderkaaklengte_comp omgezet naar NA terwijl dit in onderkaaklengte_links en onderkaaklengte_rechts niet gebeurd. Hierdoor worden er minder onderkaken weergegeven bij inbo en meldingsformulier (NA's in onderkaaklengte_comp) dan bij enkel meldingsformulier. 

We zouden dezelfde logica als onderkaaklengte_comp kunnen toepassen op onderkaaklengte_links en onderkaaklengte_rechts maar ik zou hier graag de "fout" van de melder behouden. 
Ik stel daarom voor dat we hier een soort accuraatheid gauge voorzien die onderkaaklengte_comp vergelijkt met onderkaaklengte_links en onderkaaklengte_rechts. Als 1 van de 2 kaken dezelfde afmeting heeft (+-3mm) dan die van de  onderkaaklengte_comp dan is zien we het als correct. Verder zou ik enkel de onderkaken op de grafiek weergeven die niet NA hebben in de kolom onderkaaklengte_comp. 

@jimcasaer wat denk jij ?

**Comment by RuttenAnneleen** [comment]
@jimcasaer: bekijk jij dit asap?

**Comment by SanderDevisscher** [comment]
@jimcasaer zegt voeg dezelfde limieten als onderkaaklengte_comp toe aan onderkaaklengte_links & rechts.

**Comment by SanderDevisscher** [comment]
@mvarewyck de accuraatheid gauge mag ook weergegeven worden voor heel vlaanderen/regio op de publieke pagina

**Comment by mvarewyck** [comment]
> @jimcasaer zegt voeg dezelfde limieten als onderkaaklengte_comp toe aan onderkaaklengte_links & rechts.

@SanderDevisscher Jullie doen deze data filtering obv limieten backend?

Ivm accuraatheid gauge
* Tonen we die enkel als de bron voor onderkaaklengte = "meldingsformulier"?
* Welke titel willen jullie hiervoor? Nu 'accuraatheid onderkaak meldingsformulier'

![Screenshot from 2024-06-03 17-34-08](https://github.com/inbo/reporting-rshiny-grofwildjacht/assets/22143743/5ab16039-9047-46f3-8b0c-7244eeb2eb6a)

**Comment by SanderDevisscher** [comment]
> > @jimcasaer zegt voeg dezelfde limieten als onderkaaklengte_comp toe aan onderkaaklengte_links & rechts.
> 
> @SanderDevisscher Jullie doen deze data filtering obv limieten backend? 

Er worden idd enkele onderkaaklengtes op NA gezet omdat de opgegeven waardes niet correct kunnen zijn. Daarvoor wordt er echter een kolom "onderkaaklengte_correct" berekend in ecology. Deze kolom kan je gebruiken voor deze gauge.
> 
> Ivm accuraatheid gauge
> 
> * Tonen we die enkel als de bron voor onderkaaklengte = "meldingsformulier"?

Neen, de gauge zou de waardes in de kolom "onderkaaklengte_correct" gefilterd volgens de bron moeten weergeven. In het geval van bron = "meldingsformulier" zou je een hoger percentage correcte onderkaaklengtes verwachten dan bij bron = "meldingsformulier & inbo" die op zijn beurt hoger is dan die van bron = "inbo".

> * Welke titel willen jullie hiervoor? Nu 'accuraatheid onderkaak meldingsformulier'

ok voor mij, @jimcasaer wat denk jij ?

**Comment by mvarewyck** [comment]
Als je de figuur voor alle bronnen toont, zou ik de titel veralgemenen naar 'Accuraatheid onderkaaklengte'

![Screenshot from 2024-06-03 19-45-12](https://github.com/inbo/reporting-rshiny-grofwildjacht/assets/22143743/52fe75fb-e1e9-46c1-a356-4c9322908681)
