### ISSUE TITLE
Aanpassingen dashboard

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/reporting-rshiny-grofwildjacht#334]
@mvarewyck, @LynnINBO, @RuttenAnneleen en mezelf hebben zijn net even door de versie [3f399cf](https://github.com/inbo/reporting-rshiny-grofwildjacht/commit/3f399cf1dcbd1b974b8ef7fc44ea653f43eeafed) van het dashboard gegaan en hebben de volgende suggesties ter verbetering geformuleerd:

### Algemeen
- [x] Sterretjes, voor ontbrekende data, die bij de indicator staan bovenaan zouden ook weergegeven moeten worden bij de indicator zelf. 
- [x] Voorzien ruimte voor uitleg bij indicatoren

### Achtergrondinformatie
- [x] Kaartje van het geselecteerde gebied mag de volledige eerste rij beslaan
- [x] Biotoop grafiek en de tabel zouden op 1 rij moeten komen met de titel Biotoop beschrijving 
- [x] Bij de biotoop beschrijving zou plaats voorzien moeten worden voor een stukje uitleg

### Populatie
- [x] #335
- [x] BUG: Info beschikbaar en weergegeven voor 298.8% van de totale gegevens (738/247) bij Verspreidingsgebied a.d.h.v. waarnemingen.be lijkt me niet te kloppen.
- [x] Toekomstig verspreidingsgebied zou het predictiejaar in de titel opgenomen moeten worden. Hiervoor zullen wij de inhoud van de dataset van het juiste predictiejaar voorzien.
- [x] Bij Toekomstig verspreidingsgebied zou de uitleg die nu op de shinyapp staat toegevoegd moeten worden. @RuttenAnneleen zal deze bezorgen. 

### Jacht
- [x] `Absoluut afschot` hernoemen naar `Afschot`
- [x] De optie aantal/100ha bos zou toegevoegd moeten worden aan `Afschot`

### Schade ipv Verkeer, Landbouw en Private en publieke gebieden
- [x] @RuttenAnneleen heb jij weet of de data voor preventieve maatregelen aangeleverd kan worden/is ? 
- [x] De verschillende schade types dienen samengevoegd te worden tot `Schade`
-  Hieronder vinden we de volgende grafieken met de mogelijkheid het type schade (Verkeer, Landbouw en Private en publieke gebieden) te (de)activeren:
- [x] `preventieve maatregelen`
- [x] `aantal meldingen` (totaal/seizoen/subtype/gewas)
- [x] `inschatting van de kosten` (bedragen in euro)
- [x] `omvang van de schade` dit is de grafiek die nu onder o.a. kosten van verkeersongevallen staat

### Maatschappelijk draagvlak
- [x] is dit inbotheme ?
- [x] de schaal zou omgedraaid moeten worden zodat de negatieve antwoorden links staan en positieve rechts
- [x] de assen van `Houding v.h. publiek t.o.v. everzwijnen` en `Aantrekkingskracht v. everzwijnengebied` zouden omgewisseld moeten worden
- [x] Wij zoeken ondertussen naar een betere titel, beschrijving en inhoud van de indicator communicatie

**Comment by mvarewyck** [comment]
*meeting 21/09*

FIGUUR: Toekomstig verspreidingsgebied
* verwijder filter eenheid -> risico klasse (beide)
* vermelding predictiejaar; geen filter

**Comment by mvarewyck** [comment]
> Toekomstig verspreidingsgebied zou het predictiejaar in de titel opgenomen moeten worden. Hiervoor zullen wij de inhoud van de dataset van het juiste predictiejaar voorzien.

Ik heb (voorlopig) het jaartal uit bestandsnaam gehaald.

**Comment by SanderDevisscher** [comment]
> > Toekomstig verspreidingsgebied zou het predictiejaar in de titel opgenomen moeten worden. Hiervoor zullen wij de inhoud van de dataset van het juiste predictiejaar voorzien.
> 
> Ik heb (voorlopig) het jaartal uit bestandsnaam gehaald.

@mvarewyck wat is het beste voor de toekomst ?

1. Een "modeljaar" kolom toevoegen aan de data?
2. nieuwe bestanden in een filename_jjjj.csv aanleveren?
3. ...

**Comment by mvarewyck** [comment]
> > > Toekomstig verspreidingsgebied zou het predictiejaar in de titel opgenomen moeten worden. Hiervoor zullen wij de inhoud van de dataset van het juiste predictiejaar voorzien.
> > 
> > 
> > Ik heb (voorlopig) het jaartal uit bestandsnaam gehaald.
> 
> @mvarewyck wat is het beste voor de toekomst ?
> 
> 1. Een "modeljaar" kolom toevoegen aan de data?
> 2. nieuwe bestanden in een filename_jjjj.csv aanleveren?
> 3. ...

Momenteel doe ik optie 2: jaartal staat net voor de bestandsextensie. Dat lijkt me prima voor de toekomst. 
Optie 1, jaartal toevoegen aan de data geeft een kolom met allemaal hetzelfde jaartal, dit maakt de data onnodig zwaarder.

**Comment by SanderDevisscher** [comment]
Optie 2 dus

**Comment by mvarewyck** [comment]
Voorstel met `INBOtheme::traffic_palette`

![Screenshot from 2022-10-04 09-44-18](https://user-images.githubusercontent.com/22143743/193763351-e7ca5bf4-a27e-4460-946d-f2788c2d8f1c.png)

Ter vervanging van:

![Screenshot from 2022-10-04 09-44-11](https://user-images.githubusercontent.com/22143743/193763524-bd21ec76-2cb7-4d8a-8283-14b9362322b7.png)

**Comment by SanderDevisscher** [comment]
Persoonlijk vind ik het origineel duidelijker en mooier

**Comment by mvarewyck** [comment]
Automatisch palet van `INBOtheme::inbo_rood` naar `INBOtheme::inbo_groen`

![Screenshot from 2022-10-04 10-36-42](https://user-images.githubusercontent.com/22143743/193773947-f0be6824-087b-40b3-9f22-e31402ca92f0.png)

**Comment by SanderDevisscher** [comment]
miz geen verbetering :-/

**Comment by SanderDevisscher** [comment]
Maak je een PR als je zover bent ?

**Comment by SanderDevisscher** [comment]
@mvarewyck is het mogelijk om aantal waarnemingen en aantal geschoten dieren afzonderlijk weer te geven in de popup bij het huidig verspreidingsgebied ?

De titel van het kaartje moet ook nog veranderd worden in verspreiding van everzwijn in jjjj ipv geraporteerd afschot

**Comment by SanderDevisscher** [comment]
@mvarewyck kan bij de bevragingen steeds de steekproefgrote weergegeven worden? best bij de jaartallen met (n=x).
