### ISSUE TITLE
`Verspreidingsgebied a.d.h.v. afschotgegevens` & `Verspreidingsgebied a.d.h.v. waarnemingen.be` zouden samengevoegd moeten worden tot 1 kaartje voorzien van een bron selectie vak met als opties `afschot` en `waarnemingen.be`.  Default zouden ze beiden "aan" moeten staan. De aantallen zou dan de som van beide moeten zijn.

### ISSUE THREAD

**Issue by mvarewyck** [inbo/reporting-rshiny-grofwildjacht#335]

**Comment by mvarewyck** [comment]
Voorstel nieuwe titel beide plots: "Huidig verspreidingsgebied"

Data beschikbaarheid voor 
* waarnemingen.be: 2008 tem 2018
* afschot: 2006 tem 2022

Wat doen we als gebruiker bvb 2021 selecteert? 
Ofwel alleen optie 'afschot' tonen voor databron ofwel waarschuwing printen dat er geen data is voor waarnemingen.be ofwel zonder meer de figuur tonen (gebruiker selecteert beide bronnen maar figuur toont eigl maar 1 bron)

**Comment by SanderDevisscher** [comment]
> Voorstel nieuwe titel beide plots: "Huidig verspreidingsgebied"

Ok
 
> Data beschikbaarheid voor
> 
> * waarnemingen.be: 2008 tem 2018
> * afschot: 2006 tem 2022
> 
> Wat doen we als gebruiker bvb 2021 selecteert? Ofwel alleen optie 'afschot' tonen voor databron ofwel waarschuwing printen dat er geen data is voor waarnemingen.be ofwel zonder meer de figuur tonen (gebruiker selecteert beide bronnen maar figuur toont eigl maar 1 bron)

In het geval er geen data voorhanden is voor 1 bron zou ik die bron sowieso uit het databron selectie vak verwijderen. In het geval van 2021 zou dus enkel afschot een optie mogen zijn voor de databronnen. Nu omdat de oorzaak van het ontbreken van data bronnen vooral aan onze werkdruk ligt en niet zozeer gaten in de dekking van de databronnen zou ik
daarnaast ook een disclaimer toevoegen aan de beschrijvende tekst dat de data voor bepaalde bron ontbreekt en dat dit mogelijk een gevolg is van vertragingen van de dataflow. 

@LynnINBO wat denk jij ?

**Comment by LynnINBO** [comment]
> Wat doen we als gebruiker bvb 2021 selecteert? Ofwel alleen optie 'afschot' tonen voor databron ofwel waarschuwing printen dat er geen data is voor waarnemingen.be ofwel zonder meer de figuur tonen (gebruiker selecteert beide bronnen maar figuur toont eigl maar 1 bron)

@SanderDevisscher @mvarewyck Ik zou persoonlijk gaan voor de disclaimer, zodat we ook kunnen aangeven dat de data wel bestaat, maar dat we die 'door omstandigheden' hier niet kunnen leveren.

**Comment by SanderDevisscher** [comment]
@LynnINBO zou je de "ontbrekende" databron dan ook uit het selectie vak verwijderen (niet weergeven) voor de jaren dat die ontbreekt? Of enkel de disclaimer ?

**Comment by LynnINBO** [comment]
@mvarewyck Ik zou beide doen, dan is er zeker geen misverstand mogelijk?

**Comment by RuttenAnneleen** [comment]
Ik heb de meest recente gegevens van waarnemingen.be doorgekregen. Ik zal de data klaarmaken en een seintje geven zodat het probleem van selectie van bepaalde jaartallen zich minder voordoet :)

**Comment by mvarewyck** [comment]
> Ik heb de meest recente gegevens van waarnemingen.be doorgekregen. Ik zal de data klaarmaken en een seintje geven zodat het probleem van selectie van bepaalde jaartallen zich minder voordoet :)

@RuttenAnneleen de nieuwe waarnemingen.be data heeft niet langer een kolom met UTM5. enkel UTM1, maar deze gebruiken we niet.

**Comment by RuttenAnneleen** [comment]
> @RuttenAnneleen de nieuwe waarnemingen.be data heeft niet langer een kolom met UTM5. enkel UTM1, maar deze gebruiken we niet.

@mvarewyck: ik bekijk het!

**Comment by RuttenAnneleen** [comment]
@mvarewyck: ben je zeker dat je de juist file had voor de waarnemingen.be data? 
("../reporting-rshiny-grofwildjacht/reporting-grofwild/inst/extdata/waarnemingen_2022.csv")
Want in mijn voorbereidingsscript gebruik ik de geojson file van de UTM5 dus ik weet niet waar die UTM1 zouden vandaan komen.
Ik heb het in ieder geval nog eens opnieuw gerund en gepushed. Voor zover ik kan zien zijn de tags van de UTM5-hokken

**Comment by mvarewyck** [comment]
@RuttenAnneleen Ik denk dat er ergens een misverstand is. Volgens de history heb je laatste versie op deze branch gepusht op 4 november: https://github.com/inbo/reporting-rshiny-grofwildjacht/commits/318-dashboard-figuren-code/reporting-grofwild/inst/extdata/waarnemingen_2022.csv
Deze data bevat een kolom utm1, maar geen kolom utm5: https://raw.githubusercontent.com/inbo/reporting-rshiny-grofwildjacht/cb2e0e57ce8b3afed819930be986b1f40fc813f5/reporting-grofwild/inst/extdata/waarnemingen_2022.csv
Zijn het mss utm5 waarden? In die kolom staan volgende waarden: 

```
> everWaarnemingen <- fread(file = file.path(dataDir, "waarnemingen_2022.csv"), drop = 1)[, 
  c("wildsoort", "dataSource") := list("Wild zwijn", "waarnemingen.be")]
> head(everWaarnemingen$utm1)
[1] "FS6436" "FS6436" "ES9663" "FS3528" "FS9428" "FS9427"
> colnames(everWaarnemingen)
 [1] "naam_nl"         "naam_lat"        "speciesid"       "datum"          
 [5] "invoerdatum"     "aantal"          "gedrag"          "methode"        
 [9] "kleed"           "geslacht"        "x"               "y"              
[13] "lon"             "lat"             "utm1"            "gebied"         
[17] "gemeente"        "deelgemeente"    "provincie"       "typewaarneming" 
[21] "status"          "embargo_datum"   "toestemming_wnr" "bijzonderheden" 
[25] "precisie"        "soortgroep"      "familie"         "aanleverdatum"  
[29] "jaar"            "TAG"             "Shape_Leng"      "Shape_Area"     
[33] "UIDN"            "OIDN"            "TERRID"          "NISCODE"        
[37] "NAAM"            "DATPUBLBS"       "NUMAC"           "LENGTE"         
[41] "OPPERVL"         "geometry"        "V44"             "wildsoort"      
[45] "dataSource"   
```

**Comment by RuttenAnneleen** [comment]
@mvarewyck: Ohja, nu begrijp ik de verwarring.
De kolomnaam utm1 komt van de originele file van natuurpunt, die moet je niet gebruiken. Ik heb een spatial join gedaan met onze utm5 geojson. Het is de kolom "TAG" die de juiste UTM5-hokken bevat.
