### ISSUE TITLE
FIGUUR: Verdeling van leeggewicht per leeftijdscategorie (o.b.v. onderkaak) en geslacht

### ISSUE THREAD

**Issue by ThomasScheppers** [inbo/reporting-rshiny-grofwildjacht#34]
1) voor everzwijn is er opnieuw een foute toewijzing van de leeftijdscategorie (waarschijnlijk van tot en met 2013).
2) data export niet duidelijk: provincie ontbreekt
3) voor ree is er slechts data vanaf 2014: geen nut vorige jaren te vermelden in slider

**Comment by mvarewyck** [comment]
1. TODO: Related to #31 (see comments there)
2. OK, added provincie to data download
3. OK, hard-coded fix. Hard-coded because slider is normally irrespective of (and shown before) selecting data for plotting. Added small text to UI to notify user that Ree has only data from 2014 onwards.

**Comment by ThomasScheppers** [comment]
1. To be checked.
2. OK.
3. OK.

**Comment by SanderDevisscher** [comment]
@Yasmine-Verzelen will check

**Comment by SanderDevisscher** [comment]
@stijnvanhoey  Issue 1 (leeftijdscategorie) remains. Recap of the error: For data prior 2014 Adult (volwassen) pigs get labeled as piglets (frisling), juveniles (overloper) get labeled as adult and piglets as juveniles in the graph. After 2014 everything is ok.

We, Thomas and I,  tried to fix this error in the ["test_grofwild_files" - branch](https://github.com/inbo/reporting-rshiny-grofwildjacht/tree/test_grofwild_files)  with no success

We suspect errror occurs in [boxAgeWeight.R](https://github.com/inbo/reporting-rshiny-grofwildjacht/blob/test_grofwild_files/reporting-grofwild/R/boxAgeWeight.R) when new levels get applied. see: 
row 69: newLevelsLeeftijd <- c("Frisling (<6m)", "Frisling (>6m)", "Overloper", "Volwassen")

Extra:
also frisling (<6m) is missing for these years (<2014) we suspect rows 71 to 77 to be the culprit. 

=> files (eco and geo) have been updated and checked for inconsistencies in age/weigth. None where found. 

Method: Change script -> Push & Pull -> in console: library(reporting...) + runWildApp

**Comment by SanderDevisscher** [comment]
@stijnvanhoey better?
