### ISSUE TITLE
add "onbekend" to type filter

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/reporting-rshiny-grofwildjacht#342]
This concerns: FIGUUR: Gerapporteerd aantal embryo's voor vrouwelijke wilde zwijnen per jaar

Currently only frisling(v), overloper(v) & zeug are possible in the type filter. Is it possible to add "onbekend" as well ? 
Especially when you select Data bron voor aantal embryo's = "INBO" the bar is mainly "onbekend". 
It would be nice to be able to omit this part of the data. 

This is already the case with most other graphs.

**Comment by mvarewyck** [comment]
Indien we 'onbekend' toevoegen als keuze voor Type filter, zal je 'onbekend' kunnen uitsluiten voor Type, niet voor aantal embryo's. 
Als je 'onbekend' aantal embryo's wil uitschakelen, kan je 
* ofwel hierop klikken in de legende,
* ofwel een extra checkbox toevoegen waarmee je 'onbekend aantal embryo's uitsluiten' kan aanvinken

In andere figuren denk ik dat je ook maar 'onbekend' kan uitschakelen voor de selectie-variabele en niet voor een andere variabele, bvb 'Afschot per jachtmethode'
