### ISSUE TITLE
FIGUUR: Gerapporteerd aantal per jaar en per regio

### ISSUE THREAD

**Issue by ThomasScheppers** [inbo/reporting-rshiny-grofwildjacht#35]
1) Voor edelhert: het jaar 2008 ontbreekt (geen afschot). Hoewel geen afschot klopt dat en mag het jaar dus ook vermeld worden.
2. Voor everzwijn: verdeliging ANB ontbreekt hierin. Vandaar afwijking (bv. 2007, 2008) -> nog opnemen bij afschot

**Comment by mvarewyck** [comment]
1. OK. Not intuitive from data, hard-coded fix as in #34 
2. Added "verdelging ANB" to possible doodsoorzaak for all species, so reported as separate cause of death, ok?
Question @ThomasScheppers : Is "verdelging ANB" for all plots considered as "afschot"? Then we will need to adapt the data.

**Comment by ThomasScheppers** [comment]
1. OK
2. Not to be mentioned separately -> please remove. To be checked by me when to be included and when not. In general, if we want to look at recreational hunting verdelging ANB should not be included.

**Comment by stijnvanhoey** [comment]
Niet afzonderlijk te vermelden in naam.  Aldus: `verdelging ANB` is eigenlijk `afschot` voor alle figuren te gebruiken.

**Comment by SanderDevisscher** [comment]
@Yasmine-Verzelen will check

**Comment by Yasmine-Verzelen** [comment]
Same as issue 29
