### ISSUE TITLE
Add link logic

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/reporting-rshiny-grofwildjacht#350]
Tegen dat we live voor iedereen gaan zou de logica voorzien moeten worden die toelaat om van het private deel naar het publieke deel te gaan en visa versa. 

- [x] tab voor wbe actief op publieke deel 
- [x] als je op grofwild/wildschade tab klikt in wbe kom je uit op resp. pagina van publieke deel

**Comment by mvarewyck** [comment]
Implemented [alternative approach](https://stackoverflow.com/a/50837163) using JS instead of R
