### ISSUE TITLE
Checking data when uploaded from S3

### ISSUE THREAD

**Issue by mvarewyck** [inbo/reporting-rshiny-grofwildjacht#355]
Ik heb als test de data upgeload met een foute bestand extensie maar ik krijg dan een onleesbare error.
@mvarewyck is het mogelijk om in de error message weer te geven welk bestand de error veroorzaakt ?

_Originally posted by @SanderDevisscher in https://github.com/inbo/reporting-rshiny-grofwildjacht/issues/352#issuecomment-1318478581_

**Comment by mvarewyck** [comment]
@SanderDevisscher 

Er zijn een paar opties hiervoor, maar ik denk dat iets als volgt het best is:

Ik kan een script schrijven dat alle data test. Gebaseerd op https://github.com/inbo/reporting-rshiny-grofwildjacht/blob/data_s3/reporting-grofwild/tests/testthat/testData.R Dan zou je R moeten opstarten vanop de UAT en dat script manueel sourcen.

Alternatief is om de tests *altijd* te lopen voordat de applicatie start. Maar dit zal alles vertragen.
Ander alternatief is om een lijn toe te voegen aan docker dat de tests loopt, maar we willen docker en data updates juist gescheiden houden.

Had jij iets specifiek in gedachten? Waar zie je de error message nu? In bash of in de app/web page?

**Comment by SanderDevisscher** [comment]
Ik krijg de error in de app/wbe page. 

Bestaat er geen mogelijkheid om de tests altijd te laten lopen wanneer de UAT opgestart wordt ? en niet als de PRD wordt opgestart ? 
In een ideale wereld is de PRD bucket een mirror van de UAT (na de nodige checks).

**Comment by mvarewyck** [comment]
> Bestaat er geen mogelijkheid om de tests altijd te laten lopen wanneer de UAT opgestart wordt ? en niet als de PRD wordt opgestart ?

Ja, ik zal de tests lopen in de niet-productie omgeving. We hebben nu toch die setup met het `config` package.
Voordat de app start, zullen er tests gelopen worden. Wil je dan de errors tonen in een popup window in de app of geprint in bash/R?

**Comment by mvarewyck** [comment]
Ik voer [testData.R](https://github.com/inbo/reporting-rshiny-grofwildjacht/blob/data_s3/reporting-grofwild/tests/testthat/testData.R) uit voordat de app start 
- Indien ergens faalt: error message + relevante files geprint in de R console. App start niet.
- Indien nergens faalt: message "finished successfully" in R console en app start

**Comment by SanderDevisscher** [comment]
@mvarewyck is het mogelijk om de error message weer te geven in de app ?

**Comment by mvarewyck** [comment]
Indien ergens faalt, start er nu een alternatieve app met bvb volgende foutmelding.
Het vermeldt welke test er faalt en voor welke data.
Is dit ok?

![Screenshot from 2022-11-23 14-09-16](https://user-images.githubusercontent.com/22143743/203555195-888a5892-629f-4b5c-99a8-adff6356fdf7.png)
