### ISSUE TITLE
Increase server capacity or change docker workflow

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/reporting-rshiny-grofwildjacht#357]
De huidige schaal is niet werkbaar. We zijn nu met hooguit 5 gebruikers ingelogd en het ligt plat !! 

@stenmigerode vergt het een grote meerkost om een zwaardere server te voorzien ? Is het mogelijk hier een (automatisch) schaalbare server voor te voorzien ? 
Ik verwacht namelijk een zeer onregelmatig gebruik van de app met periodes van relatieve rust en andere (vnl. rond de 3-maandelijkse updates en de release) met piekgebruik. 
@mvarewyck zijn er mogelijkheden om te voorkomen dat er niet steeds een docker container opgestart moet worden per ingelogde gebruiker ? wat zijn steeds de pro's en de cons ?

_Originally posted by @SanderDevisscher in https://github.com/inbo/reporting-rshiny-grofwildjacht/issues/356#issuecomment-1323447406_

**Comment by SanderDevisscher** [comment]
@SanderDevisscher ik ben java ontwikkelaar en tech lead en ook een externe consultant voor het INBO. Ik kan me niet uitspreken over de kosten en wat er aanvaardbaar is.

In afwezigheid van een AWS specialist op dit moment, kan ik wel zeggen dat een "automatisch" schaalbaar systeem een een complexe opzet binnen AWS met Elastic Container Services vraagt: we moeten dan een cluster aanmaken van docker containers, maar mogen niet zomaar gaan loadbalancen naar eender welke container. Want zoals ik het begrijp is 1 container specifiek voor 1 gebruiker, want de KBO nummers die keycloak doorgeeft worden als Environment Variable binnen de container opgeslagen. De shiny proxy zou dus naar een docker daemon moeten verwijzen die op zijn beurt meerdere machines kan aanspreken en zelf opstarten als er te veel concurrent logins zijn.

_Originally posted by @stenmigerode in https://github.com/inbo/reporting-rshiny-grofwildjacht/issues/356#issuecomment-1323477679_

**Comment by SanderDevisscher** [comment]
@SanderDevisscher 
Per ingelogde gebruiker wordt er 1 GB geheugen extra gereserveerd op de server, zie ik.
Dit betekent als er bijvoorbeeld een piek van 90 gebruikers is, dat er 90 GB extra nodig is. Dat zijn enorm dure servers, tenzij dat het INBO een mooie korting heeft bij AWS. Dat weet ik niet. @berthuygens ?

Ik kan van mijn kant niet veel meer doen.

_Originally posted by @stenmigerode in https://github.com/inbo/reporting-rshiny-grofwildjacht/issues/356#issuecomment-1323566538_

**Comment by mvarewyck** [comment]
Dit komt (wellicht) omdat de geografische data voor de WBE's zo groot is (131 Mb). 

Momenteel worden de geodata van alle WBE's ingeladen in R, daarna bekijken we welke data er effectief nodig zijn volgens login. 
Aangezien gebruikers slechts 1 WBE tegelijk kunnen bekijken, zouden we de geo data kunnen opsplitsen in 1 file per WBE en dan code aanpassen zodat enkel geodata van geselecteerde WBE wordt geladen. 

@SanderDevisscher Is het correct dat jullie (ook in de toekomst) slechts 1 WBE tegelijk willen bekijken? Zoniet, hou ik hier best rekening mee bij het uitwerken van dit alternatief.

Ik zal eerst testen of het inladen van geodata voor slechts 1 WBE beterschap oplevert.

**Comment by mvarewyck** [comment]
Ik heb voor 1 WBE de app gestart met subset van de grootste datasets (ecoData, geoData, spatialData, schadeData)
Dan gebruikt de app nog 550 Mb.

- Dit is bijna halvering, maar die winst zal kleiner zijn naarmate de login toegang heeft tot meer wbe's
- Als we dit operationeel willen, zouden we voor elke WBE een set van data moeten aanmaken, zodat enkel deze files kunnen ingeladen worden (best wachten op S3 branch)
- Normale shiny app zit al snel aan 200 - 250 Mb, dus we kunnen eventueel verder onderzoeken of dit in ons geval nog verder gereduceerd kan worden (packages, helper data)

**Comment by SanderDevisscher** [comment]
@mvarewyck zeker in de nabije toekomst zal het niet de bedoeling zijn om buiten enkele uitzonderlijke gevallen en de admins om meer dan 1 wbe te raadplegen. 

Wat zou het verschil zijn als we deze opsplitsing enkel doen voor de spatialData ? tov de 1GB nu ?

**Comment by mvarewyck** [comment]
> Wat zou het verschil zijn als we deze opsplitsing enkel doen voor de spatialData ? tov de 1GB nu ?

Indien enkel spatialData opsplitsing, gebruikt docker image 600 Mb (getest voor 'Westhoek', partijnr 101).
Grootste reductie zit dus in spatialData (zoals verwacht).
Dezelfde code met alle spatialData voor alle WBEs zit op 1GB

**Comment by SanderDevisscher** [comment]
@mvarewyck is dit nog relevant nu we met s3 buckets werken ?

**Comment by mvarewyck** [comment]
> @mvarewyck is dit nog relevant nu we met s3 buckets werken ?

@SanderDevisscher Normaal wel (zou het moeten testen). Dit heeft te maken met _welke data_ worden geladen in de app en dat is nog steeds hetzelfde.

**Comment by mvarewyck** [comment]
I will create a single spatial file for each available WBE number. 

@SanderDevisscher Can you confirm realistic WBE_NR values are between 0 and 600 (not including 0)?
I saw WBE_NR 0, 601 and 999 are available in the spatial data for WBE. Can I filter these out? Or do you think it is safer to not hard-code this, for future WBE_NR updates?

**Comment by SanderDevisscher** [comment]
0 and 999 are not connected to any wbe and can be filtered out. 
The case of 601 is not as clear. In which years does this occur ? 
However I would not hardcode 600 as an upper limit.

**Comment by mvarewyck** [comment]
> The case of 601 is not as clear. In which years does this occur ? 
WBE_NR 601 is available for "WBE_buitengrenzen_2014" "WBE_buitengrenzen_2015" "WBE_buitengrenzen_2016"

So, I will only exclude 0 and 999.

**Comment by mvarewyck** [comment]
For reference: I tried to save all spatial data (WBE and non-WBE) in a single .gpkg file. We can then read the relevant layers and WBE regions using an SQL query in `sf::st_read()`
Same memory reduction for single WBE and avoids overload of single file per WBE.
Unfortunately, this slows down reading all layers for single WBE (via S3, locally speed is fine)
-> I created a single spatial RData file for each available WBE number: pattern "spatialDataWBE/531.RData"

Links
- [read gpkg using SQL filters](https://gis.stackexchange.com/a/341727)
- [read GIS data from S3](https://github.com/r-spatial/sf/issues/1935); Don't use `s3_read_using(FUN = sf::st_read, ...)` which is _extremely slow_

@SanderDevisscher no changes required at your side, you can use the updated `createShapeData()`
There is a file `spatialData.gpkg` on "inbo-wbe-uat-data" which should be removed

**Comment by mvarewyck** [comment]
I found out reading .RData files is much faster than .csv from S3
I will investigate speed improvement by creating ".RData" instead of csv files in `createRawData()`
 (nothing to do with memory, but increases startup time of the app)
