### ISSUE TITLE
Meer tekst en uitleg

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/reporting-rshiny-grofwildjacht#358]
### ALGEMEEN
- [ ] Ergens vermelden dat de cijfers gebaseerd zijn op afschotmeldingen door de WBE’s of OJ in het eloket. Niet te vergeten dat ze aangevuld worden met gegevens uit de autopsiedb. zie #364.

### Achtergrond info
- [x] Vermelden dat de Biotoop beschrijving gebaseerd is op de Corinne landgebruik laag 

#### tabel gerapporteerd afschot:
- [x] legende van de kolom categorie wat meer omschrijven voor de duidelijkheid (bv. 'volgens het label', 'volgens leeftijd en geslacht')
- [x] Deze tabel toont het door de WBE gerapporteerd aantal geschoten dieren per gekozen categorie voor het geselecteerde jaar. De laatste kolommen tonen de verandering in het afschot ten opzichte van de voorbije 1, 5 en 10 jaren. Indien de categorie door INBO bepaald kan worden, wordt deze gebruikt, anders wordt de categorie volgens het meldingsformulier bepaald. 
LET OP! Wanneer de trend oranje of rood gekleurd is, is ze gebaseerd op minder dan 10 geschoten dieren en is de berekende waarde minder betekenisvol.

**Comment by SanderDevisscher** [comment]
@mvarewyck wij werken dit uit in de `356_hotfixWbe` - branch

Voor de zekerheid: we mogen de aanpassingen uitvoeren in dit bestand [uiText.csv](https://github.com/inbo/reporting-rshiny-grofwildjacht/blob/356_hotfixWbe/reporting-grofwild/inst/extdata/uiText.csv) ?

**Comment by SanderDevisscher** [comment]
@mvarewyck kan je placeholders toevoegen voor beide grafieken van de Achtergrondinfo ?

**Comment by mvarewyck** [comment]
> @mvarewyck wij werken dit uit in de `356_hotfixWbe` - branch
> 
> Voor de zekerheid: we mogen de aanpassingen uitvoeren in dit bestand [uiText.csv](https://github.com/inbo/reporting-rshiny-grofwildjacht/blob/356_hotfixWbe/reporting-grofwild/inst/extdata/uiText.csv) ?

Ja, kolom WBE

**Comment by mvarewyck** [comment]
> @mvarewyck kan je placeholders toevoegen voor beide grafieken van de Achtergrondinfo ?

Wil je tekst kunnen toevoegen onder "WBE grenzen en jachtterreinen in 2022"?

![Screenshot from 2023-01-19 10-37-55](https://user-images.githubusercontent.com/22143743/213407842-1642b2e4-88a5-4a07-baf9-0568e4f33442.png)

**Comment by SanderDevisscher** [comment]
@mvarewyck ja graag!!

**Comment by mvarewyck** [comment]
Tekst onder biotoop beschrijving is voorzien in #346, [hier](https://github.com/inbo/reporting-rshiny-grofwildjacht/blob/318-dashboard-figuren-code/reporting-grofwild/R/mapFlanders.R#L1213-L1217)
Voorlopig kan je hiervoor een lijn toevoegen met title 'barBiootoop' in uiText.csv
