### ISSUE TITLE
Datum aanmaak dataset vermelden?

### ISSUE THREAD

**Issue by ThomasScheppers** [inbo/reporting-rshiny-grofwildjacht#36]
Zouden we onder de inleidende tekst geen vermelding maken van de datum van aanmaak van de dataset?

Vb. 'Laatste update: 15/10/2017'

Kwestie van de gebruiker te laten zien dat de data toch regelmatig ge-update wordt?

Wie past dit dan aan? Stijn, kan dit via jouw scriptje om de data over te zetten?

**Comment by Fhuysent** [comment]
In page heading include date field (from most recent data load) as follows: "Onderstaande tabellen en figuren zijn gebaseerd op de beschikbare gegevens op dd/mm/yyyy".

**Comment by stijnvanhoey** [comment]
Basically: zorgen dat de datum van de commit message opgenomen wordt in de package. Dat kan ook low-level zijn met een changelog in de `inst/ext` folder, die dan ingelezen worden door de package en gerenderd worden op de pagina.

**Comment by mvarewyck** [comment]
1. Currently the data are inside the package `inst/extdata` but where will they be in the future? We can refer to a data folder from where to load the data. 
2. We could extract the creation date of the data file, or will this differ from the date you would like to have displayed? The date can also be part of the file name.
3. There are different data sources: openingstijdendata, toekenningsdata, geography and ecology data. But I think you would only like to display the date for the observations (ecology data)?

**Comment by ThomasScheppers** [comment]
1. @stijnvanhoey ?
2. Creation date is OK.
3. Indeed, ecology or geography (which will be the same date).
4. Can you add a point behind the data?

**Comment by stijnvanhoey** [comment]
We'll keep the data in the `inst/extdata` for the moment and I'll add updates there (incremental data, and we'll have the commit history on it). If there will be a more automated procedure for the preprocessing section, we still can adapt the loading ourselve.
