### ISSUE TITLE
Improve no data disclaimers 

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/reporting-rshiny-grofwildjacht#362]
> Momenteel zijn er voor deze WBE geen afschotgegevens van de grofwildsoorten beschikbaar. Hierdoor kunnen er geen figuren/tabellen worden getoond m.b.t. afschot. Indien dit niet klopt, kijkt u best eerst na of de gegevens juist in het e-loket van ANB zitten. _Zijn uw gegevens juist ingevoerd en ingediend dan laat u best iets weten op faunabeheer@inbo.be_

Zou vervangen moet worden door:

Momenteel zijn er voor deze WBE geen afschotgegevens van de grofwildsoorten beschikbaar. Hierdoor kunnen er geen figuren/tabellen worden getoond m.b.t. afschot. Indien dit niet klopt, kijkt u best eerst na of de gegevens juist in het e-loket van ANB zitten. _Zijn uw gegevens toch ingegeven in het e-loket en hier worden ze hier niet weergegeven dan laat u best iets weten op faunabeheer@inbo.be_

en 

> Momenteel zijn er voor deze WBE geen schadegegevens van de grofwildsoorten beschikbaar. Hierdoor kunnen er geen figuren/tabellen worden getoond m.b.t. schademeldingen. Indien u denkt dat dit niet klopt, raden wij u aan gebruik te maken van het e-loket van ANB, de Wilderapp ( ios of android ) van HVV of waarnemingen.be van Natuurpunt. _Bent u zeker dat er toch gegevens bij één van de partners ingevoerd werden, dan laat u best iets weten op faunabeheer@inbo.be_

zou vervangen moeten worden door:

Momenteel zijn er voor deze WBE geen schadegegevens van de grofwildsoorten beschikbaar. Hierdoor kunnen er geen figuren/tabellen worden getoond m.b.t. schademeldingen. Indien u denkt dat dit niet klopt, raden wij u aan gebruik te maken van het e-loket van ANB, de Wilderapp ( ios of android ) van HVV of waarnemingen.be van Natuurpunt. _Bent u zeker dat er toch gegevens bij één van de partners ingevoerd werden die hier niet worden weergegeven, dan laat u best iets weten op faunabeheer@inbo.be_

Deze aanpassing is zeker niet dringend.

**Comment by mvarewyck** [comment]
TODO move to other branch + merge with master

**Comment by SanderDevisscher** [comment]
@mvarewyck er zijn nog steeds enkele wbe's die geen afschot hebben maar geen disclaimer krijgen !

bvb everzwijn afschot van Berg en Dal
