### ISSUE TITLE
Groepeer gewassoorten

### ISSUE THREAD

**Issue by mvarewyck** [inbo/reporting-rshiny-grofwildjacht#366]
Zoals gestart in #347, willen we de verschillende gewassen groeperen. (dashboard pagina)
Ik heb alles samengezet in een file die ik al had voor wildschade.
Wanneer we ook ander wildsoorten dan 'Wild zwijn' toelaten, zijn er nog meer keuzes. (wildschade pagina)

@RuttenAnneleen kan je de groepnamen aanvullen in [deze file](https://github.com/inbo/reporting-rshiny-grofwildjacht/blob/318-dashboard-figuren-code/reporting-grofwild/inst/extdata/meta_schade.csv)? **ENKEL** 2de kolom voor de laatste rijen (nieuwe gewassen)

**Comment by RuttenAnneleen** [comment]
@mvarewyck : ik heb het aangevuld en gepushed in de 318 branch

**Comment by mvarewyck** [comment]
NOTE to myself: Check how plots look on page 'wildschade' with these changes.

**Comment by mvarewyck** [comment]
Wildschade looks fine in branch #346
Remaining issue in #372
