### ISSUE TITLE
Improve Rapport

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/reporting-rshiny-grofwildjacht#368]
> [Example current report](https://github.com/inbo/reporting-rshiny-grofwildjacht/files/10290275/rapportDashboard.14.pdf)

Ziet er al heel goed uit. 

Buiten de scope van deze PR denk ik dat we zeker de volgende aanpassingen moeten meenemen bij de opmaak van het rapport. 
- [x] Toevoegen van filter en selectie opties (zoals tijdens meet besproken)
- [x] Page break voor hoofdstuk (ACHTERGRONDINFORMATIE, POPULATIE, JACHT, SCHADE, ...) 
- [x] Elke subtitel misschien ook met aparte page break doen? Nu is het soms onduidelijk als de (sub)titel op de ene pagina staat en de grafiek op de andere)
- [x] Bij kaartjes de zoom nog eens bekijken (bij gemeentes ligt de zoom bij elk kaartje anders)
- [x] Gebiedsselectie op titelpagina zetten
- [x]  * specifiëren (of bij elke figuur apart bijzetten als het over onvolledige data gaat)

_Originally posted by @SanderDevisscher in https://github.com/inbo/reporting-rshiny-grofwildjacht/issues/347#issuecomment-1363833705_

**Comment by mvarewyck** [comment]
> Toevoegen van filter en selectie opties (zoals tijdens meet besproken)

Hoe gedetailleerd willen jullie dit? Bvb.
* Positie legende (voor maps): moet dit expliciet vermeld worden?
* Draagkracht figuren: oplijsting van alle geselecteerde maatregelen/impacts/belangen? 

Deze zijn normaal ook duidelijk uit de figuur zelf, maar kan wel reproductie vereenvoudigen.
