### ISSUE TITLE
Verbeterpuntjes dashboard

### ISSUE THREAD

**Issue by RuttenAnneleen** [inbo/reporting-rshiny-grofwildjacht#369]
- [x] Bij grafiek schadegevallen hebben sommige jaren een label, sommige jaren niet. Ik zou voorstellen om de vaste labels weg te laten --> ook nakijken bij alle andere figuren dat er nergens geen vaste labels staan (issue plotly 4.10.1)
![newplot](https://user-images.githubusercontent.com/34440484/210232599-67a84e84-02b1-4bf6-8c37-4243177edd3a.png)

- [x] Bij grafiek schadegevallen selectie 'alle' staat er een klasse "andere". Wat is dit? Lijk mij niet logisch dat hier nog iets bijkomt
![newplot (1)](https://user-images.githubusercontent.com/34440484/210232686-a6861ffe-6aed-450e-9c9b-5867cab3454b.png)

- [x] Bij alle grafieken maatschappelijk draagvlak mogen de labels van de negatieve percentage ook gewoon positief zijn (dus '-' weglaten)
![newplot (2)](https://user-images.githubusercontent.com/34440484/210232878-1306c1dd-bc6d-4001-8e69-98d8f9839ea9.png)

- [x] Bij grafiek inschatting impacts staat het label 'schade aan private en publieke gebieden' er niet volledig op. Eventueel afkorten naar 'schade priv./pub. eigendom'
![newplot (3)](https://user-images.githubusercontent.com/34440484/210232892-013b68b7-5f0c-4e44-b13d-c64c71b93242.png)

- [x] De grafieken van maatschappelijk draagvlak zijn eigenlijk alleen op niveau Vlaanderen maar worden ook bij alle andere niveau's weergeven. Hadden we niet afgesproken dat de mogelijk grafieken niveau-afhankelijk zijn (zie excelfile databeschikbaarheid)?

- [x] Bij grafiek drukjachten gaat er nog iets fout (issue plotly 4.10.1)
![image](https://user-images.githubusercontent.com/34440484/214272314-510aa186-e87c-4ca3-8cde-0413bd13e012.png)

- [x] Bij grafiek afschot gaat er nog iets fout (issue plotly 4.10.1)
![newplot (3) (1)](https://user-images.githubusercontent.com/34440484/214272417-05b9adac-8953-48e2-ac3b-11e3a6df7a3e.png)

- [x] * bij grafieken zelf vind ik niet duidelijk genoeg, zouden we daar niet altijd de disclaimer nog eens bijschrijven dat de data onvolledig zijn?

- [x] Onderscheid maken tussen beschikbaarheid data op bepaald niveau (volgens tabel) en als er effectief geen gegevens zijn voor bijvoorbeeld faunabeheerzone 3 waar er geen afschot gemeld werd --> nu wordt er geen figuur gemaakt maar best een disclaimer op de plaats van de figuur zetten 'Er zijn voor deze keuze geen gegevens beschikbaar'.
- [x] y-as bij schademeldingen: kommagetallen zijn niet logisch dus weglaten
- [x] @SanderDevisscher : nakijken als gegevens van waarnemingen.be enkel goedgekeurde waarnemingen bevatten 
- [x] Toekomstig verspreidingsgebied: Voeren toevoegen als 'al aanwezig' (is misschien al gebeurd ondertussen)
- [x] Bij keuze regioschaal 'faunabeheerzones' staat optie 'inschatting populatiegroei' --> moet weg
- [x] @RuttenAnneleen: disclaimers aanpassen (6-jaarlijks weg, vraag in vet zetten, bij schademeldingen wilder en waarnemingen.be toevoegen, bosfragmentatie ipv bosdensiteit en bosfragmenten ipv bospatches)
- [x] figuur inschatting impacts: groot en klein omwisselen van volgorde (klein links, groot rechts van de 0)
- [x] figuur draagkracht beheermaatregelen: legende moet zijn 'Aanvaardbaar' - 'Niet aanvaardbaar' ipv 'Belangrijk' en 'Onbelangrijk'
- [x] Figuur aantal schademeldingen: bij type schade 'andere' toevoegen en ook grafiek van enkel 'andere' aanmaken
- [x] Tabel achtergrondinfo: aanpassing kolomnamen --> bosfragmentatie ipv bosdensiteit en bosfragmenten ipv bospatches
- [x] Bosperimeter: nakijken als er wordt afgerond (is heel vaak 1) en hoe komen we aan 168 voor Vlaanderen (som of gemiddelde?)
- [x] @RuttenAnneleen: script wegdensiteit nakijken --> klopt niet
- [x] Tabel achtergrondinfo: kolom toevoegen 'totale oppervlakte km²' 
- [x] Figuur biotoop beschrijving: optie 'Combineer alle geselecteerde regio's' toevoegen  + titel figuur verwijderen
- [x] Helemaal bovenaan pagina: tekstvlak toevoegen met inleidende tekst (@RuttenAnneleen doet voorzet tekst)
- [x] Rapport: zin 'Voor indicatoren met (*)....' onder tabel achtergrond info staat niet op zijn plaats
- [x] Rapport: bij grafieken gridlines verwijderen
- [x] Knop maak pdf ook helemaal onderaan zetten (is logischer omdat dan al alle keuzes zijn gemaakt)
- [x] Toekomstige verspreiding: 2023 erop zetten (@RuttenAnneleen runt eerst het model nog) 
- [x] Figuur draagvlak beheermaatregelen: fix drukjacht ipv drijfjacht  @RuttenAnneleen 
- [x] Overal het woord 'schaal' gebruiken ipv niveau
- [x] Aanpassing verspreiding 'VAN' everzwijn ipv VOOR
- [x] figuur verspreiding everzwijn: 'Aantal' in legende toevoegen
- [x] Figuur huidig verspreidingsgebied: 'Regio-schaal' vervangen door 'Schaal'
- [x] Disclaimer huidig verspreidingsgebied: X, Y en Z vervangen door cijfers onderaan figuur (de zin onderaan figuur mag dan weg)
- [x] disclaimer toekomstig verspreidingsgebied aanpassen @RuttenAnneleen 
- [x] Toekomstig verspreidingsgebied legende: 'startlocatie' vervangen door 'bevestigde aanwezigheid in'
- [x] Drukjachtfiguur: disclaimer toevoegen @RuttenAnneleen 
- [x] Drukjachtfiguur: titel aanpassen naar 'Aantal drukjachten Jaar X tot Jaar Y'
- [x] Figuur afschot: gerapporteerd afschot 'VAN' ipv 'VOOR' wild zwijn

**Comment by RuttenAnneleen** [comment]
Specifieke verbeterpuntjes rapport:

- [ ] Toevoegen van filter en selectie opties (zoals tijdens meet besproken)
- [ ] Page break voor hoofdstuk (ACHTERGRONDINFORMATIE, POPULATIE, JACHT, SCHADE, ...)
- [ ] Elke subtitel misschien ook met aparte page break doen? Nu is het soms onduidelijk als de (sub)titel op de ene pagina staat en de grafiek op de andere)
- [ ] Bij kaartjes de zoom nog eens bekijken (bij gemeentes ligt de zoom bij elk kaartje anders)
- [ ] Gebiedsselectie op titelpagina zetten
- [ ] * specifiëren (of bij elke figuur apart bijzetten als het over onvolledige data gaat)

**Comment by SanderDevisscher** [comment]
> Specifieke verbeterpuntjes rapport:
> 
> * [ ]  Toevoegen van filter en selectie opties (zoals tijdens meet besproken)
> * [ ]  Page break voor hoofdstuk (ACHTERGRONDINFORMATIE, POPULATIE, JACHT, SCHADE, ...)
> * [ ]  Elke subtitel misschien ook met aparte page break doen? Nu is het soms onduidelijk als de (sub)titel op de ene pagina staat en de grafiek op de andere)
> * [ ]  Bij kaartjes de zoom nog eens bekijken (bij gemeentes ligt de zoom bij elk kaartje anders)
> * [ ]  Gebiedsselectie op titelpagina zetten
> * [ ]  * specifiëren (of bij elke figuur apart bijzetten als het over onvolledige data gaat)

deze mag je in de body van #368 toevoegen ;-)

**Comment by RuttenAnneleen** [comment]
> > Specifieke verbeterpuntjes rapport:
> > 
> > * [ ]   Toevoegen van filter en selectie opties (zoals tijdens meet besproken)
> > * [ ]   Page break voor hoofdstuk (ACHTERGRONDINFORMATIE, POPULATIE, JACHT, SCHADE, ...)
> > * [ ]   Elke subtitel misschien ook met aparte page break doen? Nu is het soms onduidelijk als de (sub)titel op de ene pagina staat en de grafiek op de andere)
> > * [ ]   Bij kaartjes de zoom nog eens bekijken (bij gemeentes ligt de zoom bij elk kaartje anders)
> > * [ ]   Gebiedsselectie op titelpagina zetten
> > * [ ]   * specifiëren (of bij elke figuur apart bijzetten als het over onvolledige data gaat)
> 
> deze mag je in de body van #368 toevoegen ;-)

Had ik niet gezien dat daar al een issue voor was :) ik verplaats het!

**Comment by LynnPallemaerts** [comment]
@RuttenAnneleen Is hier een specifieke branch voor geopend, of wachten we nog tot na #346 ?

**Comment by RuttenAnneleen** [comment]
Ik stel voor om te wachten tot nadat alles van #346 in de master zit. Dan weten we dat de UAT versie de masterversie is en kunnen we van daaruit verder werken

**Comment by SanderDevisscher** [comment]
#346 is momenteel nog on hold tot de goedkeuring van #352 en de nodige aanpassingen om over te schakelen naar s3 buckets voor de data. In de tussentijd lijkt het me een goed idee op te lijsten welke files op de s3 bucket moeten komen (zal hiervoor een issue aanmaken in fis-projecten en hier refereren).

**Comment by LynnPallemaerts** [comment]
Too many buckets... :-P Laat maar weten wanneer die gefixt zijn :-)

**Comment by RuttenAnneleen** [comment]
@mvarewyck: Wij (@jimcasaer, @SanderDevisscher en @LynnPallemaerts) hebben net de UAT versie besproken. Het ziet er echt al super uit! Ik heb het TODO lijstje hierboven aangevuld met de nodige aanpassingen voor we live kunnen gaan. We gaan de pagina ook nog laten testen door ANB dus het kan zijn dat het lijstje nog aangevuld wordt maar dan geef ik nog een seintje.

**Comment by mvarewyck** [comment]
> De grafieken van maatschappelijk draagvlak zijn eigenlijk alleen op niveau Vlaanderen maar worden ook bij alle andere niveau's weergeven. Hadden we niet afgesproken dat de mogelijk grafieken niveau-afhankelijk zijn (zie excelfile databeschikbaarheid)?

@RuttenAnneleen Momenteel hanteer ik volgende aanpak volgens beschikbaarheidscode
2 = toon zonder *
1 = toon met *
0 = niet tonen
Dit lijkt dus te kloppen voor de fign van maatschappelijk draagvlak in [dit bestand](https://github.com/inbo/reporting-rshiny-grofwildjacht/blob/318-dashboard-figuren-code/reporting-grofwild/inst/extdata/Data_beschikbaarheid.csv#L24-L30)

**Comment by SanderDevisscher** [comment]
>  @RuttenAnneleen: nakijken als gegevens van waarnemingen.be enkel goedgekeurde waarnemingen bevatten

Ik zal dit samen met de aanpassingen van de dataflow behandelen (zie #377)

**Comment by mvarewyck** [comment]
> Tabel achtergrondinfo: aanpassing kolomnamen --> bosfragmentatie ipv bosdensiteit en bosfragmenten ipv bospatches

@RuttenAnneleen Wat zijn bospatches?
![Screenshot from 2023-01-25 21-25-01](https://user-images.githubusercontent.com/22143743/214682241-9a2ef4e7-3c1d-4ab5-b607-4c53986f29d0.png)

**Comment by mvarewyck** [comment]
> Helemaal bovenaan pagina: tekstvlak toevoegen met inleidende tekst (@RuttenAnneleen doet voorzet tekst)

Momenteel hier voorzien [rij 'welcomeSection', kolom 'dash'](https://github.com/inbo/reporting-rshiny-grofwildjacht/blob/318-dashboard-figuren-code/reporting-grofwild/inst/extdata/uiText.csv)

**Comment by RuttenAnneleen** [comment]
> > Tabel achtergrondinfo: aanpassing kolomnamen --> bosfragmentatie ipv bosdensiteit en bosfragmenten ipv bospatches
> 
> @RuttenAnneleen Wat zijn bospatches? ![Screenshot from 2023-01-25 21-25-01](https://user-images.githubusercontent.com/22143743/214682241-9a2ef4e7-3c1d-4ab5-b607-4c53986f29d0.png)

Ahja, bospatches moest ik enkel aanpassen in de disclaimer, staat inderdaad niet in de kolomnamen :)

**Comment by RuttenAnneleen** [comment]
> > De grafieken van maatschappelijk draagvlak zijn eigenlijk alleen op niveau Vlaanderen maar worden ook bij alle andere niveau's weergeven. Hadden we niet afgesproken dat de mogelijk grafieken niveau-afhankelijk zijn (zie excelfile databeschikbaarheid)?
> 
> @RuttenAnneleen Momenteel hanteer ik volgende aanpak volgens beschikbaarheidscode 2 = toon zonder * 1 = toon met * 0 = niet tonen Dit lijkt dus te kloppen voor de fign van maatschappelijk draagvlak in [dit bestand](https://github.com/inbo/reporting-rshiny-grofwildjacht/blob/318-dashboard-figuren-code/reporting-grofwild/inst/extdata/Data_beschikbaarheid.csv#L24-L30)

@jimcasaer: moeten we dan voor de indicatoren van maatschappelijk draagvlak niet alles naar 0 zetten ipv op niveau Vlaanderen? Want echt juist is het niet dat die nu op 1 (gedeeltelijk beschikbaar) staan, toch?

**Comment by mvarewyck** [comment]
> Bosperimeter: nakijken als er wordt afgerond (is heel vaak 1) en hoe komen we aan 168 voor Vlaanderen (som of gemiddelde?)
> @RuttenAnneleen: script wegdensiteit nakijken --> klopt niet

De kolom labels waren fout [in code](https://github.com/inbo/reporting-rshiny-grofwildjacht/blob/318-dashboard-figuren-code/reporting-grofwild/R/tableBackground.R#L16)! Daardoor stond wegdensiteit boven 2de kolom ipv achteraan.

**Comment by mvarewyck** [comment]
> @mvarewyck: Ik begrijp het niet helemaal. Denk je dat er dan geen fout zit in mijn berekenen van wegdensiteit?

Precies, ik denk dat de berekeningen wel correct (kunnen) zijn. Hieronder vb met juiste kolom labels
![Screenshot from 2023-01-26 15-14-17](https://user-images.githubusercontent.com/22143743/214858129-d14ef799-baf4-4c8d-a0b7-60d4d77ca38e.png)

**Comment by RuttenAnneleen** [comment]
@mvarewyck: ik heb weer enkele todo's toegevoegd na overleg over de helderheid van de teksten, titels,... van het dashboard. 
Hier gaan nog een aantal puntjes bijkomen maar hier kan altijd al mee gestart worden :)

**Comment by mvarewyck** [comment]
> Korte uitleg toevoegen bij tabbladtitels 'Grofwild', 'Wildschade' en 'Dashboard' om beetje meer uitleg te geven op welk tabblad wat staat

@RuttenAnneleen Waar/hoe willen jullie deze uitleg toevoegen?
* In de tabbladtitels zelf - dan moet het zeer kort zijn
* Als hover-text bij de tabbladtitels
* Is het een idee om met een eerste algemene pagina te werken, waar je tekst kan toevoegen (zoals voor [alien-species](https://github.com/inbo/alien-species-portal))

**Comment by RuttenAnneleen** [comment]
> > Korte uitleg toevoegen bij tabbladtitels 'Grofwild', 'Wildschade' en 'Dashboard' om beetje meer uitleg te geven op welk tabblad wat staat
> 
> @RuttenAnneleen Waar/hoe willen jullie deze uitleg toevoegen?
> 
> * In de tabbladtitels zelf - dan moet het zeer kort zijn
> * Als hover-text bij de tabbladtitels
> * Is het een idee om met een eerste algemene pagina te werken, waar je tekst kan toevoegen (zoals voor [alien-species](https://github.com/inbo/alien-species-portal))

Het idee was als hover-tekst maar misschien is een eerste algemene pagina een beter idee, zeker omdat er ook al ter sprake is gekomen dat een terminologie pagina nodig gaat zijn. Maar misschien nu best achterwege laten tot de we eerste versie online hebben staan. Niet @jimcasaer en @SanderDevisscher?

**Comment by SanderDevisscher** [comment]
Persoonlijk ben ik geen voorstander van een algemene welkomspagina omdat we hiermee de vertrouwde gebruikers vertragen, de app is nu al niet super snel. Bovendien staat bovenaan iedere pagina beschreven wat de gebruiker erop zal terugvinden. Daarom zou ik opteren voor, indien het mogelijk is, hovertekstjes met een korte uitleg per tab aangevuld met een nieuwe terminologie tab. Qua timing zou ik dit idd zien als iets om uit te werken voor **na** de eerste release.

**Comment by mvarewyck** [comment]
> Drukjachtfiguur: titel aanpassen naar 'Aantal drukjachten Jaar X tot Jaar Y'

@RuttenAnneleen Is het onderstaande ok? Deze code wordt ook op Grofwild pagina gebruikt. Voor pagina Grofwild blijft dan enkel de tweede lijn in titel zichtbaar
![Screenshot from 2023-02-10 16-38-36](https://user-images.githubusercontent.com/22143743/218132766-70125ba3-d4b0-454b-bd73-7778aca87a0e.png)

**Comment by mvarewyck** [comment]
> > > Korte uitleg toevoegen bij tabbladtitels 'Grofwild', 'Wildschade' en 'Dashboard' om beetje meer uitleg te geven op welk tabblad wat staat
> > 
> > 
> > @RuttenAnneleen Waar/hoe willen jullie deze uitleg toevoegen?
> > 
> > * In de tabbladtitels zelf - dan moet het zeer kort zijn
> > * Als hover-text bij de tabbladtitels
> > * Is het een idee om met een eerste algemene pagina te werken, waar je tekst kan toevoegen (zoals voor [alien-species](https://github.com/inbo/alien-species-portal))
> 
> Het idee was als hover-tekst maar misschien is een eerste algemene pagina een beter idee, zeker omdat er ook al ter sprake is gekomen dat een terminologie pagina nodig gaat zijn. Maar misschien nu best achterwege laten tot de we eerste versie online hebben staan. Niet @jimcasaer en @SanderDevisscher?

Note: hover-text is [simpel](https://www.w3docs.com/snippets/html/how-to-add-a-mouseover-text-with-html.html) te implementeren als jullie de tekst voorzien

**Comment by RuttenAnneleen** [comment]
@mvarewyck: ik heb de correcte file voor wegdensiteit toegevoegd
(sorry voor de timing, ik zie dat je gisteren net een temp exclude hebt gedaan van deze indicator)

**Comment by mvarewyck** [comment]
> Drukjachtfiguur: disclaimer toevoegen @RuttenAnneleen

Dit mag [hier](https://github.com/inbo/reporting-rshiny-grofwildjacht/blob/318-dashboard-figuren-code/reporting-grofwild/inst/extdata/uiText.csv) in rij 'F04_3' kolom 'dash'

**Comment by RuttenAnneleen** [comment]
> > Drukjachtfiguur: disclaimer toevoegen @RuttenAnneleen
> 
> Dit mag [hier](https://github.com/inbo/reporting-rshiny-grofwildjacht/blob/318-dashboard-figuren-code/reporting-grofwild/inst/extdata/uiText.csv) in rij 'F04_3' kolom 'dash'

Top!! Ik heb het toegevoegd. 
Dan zijn alle To Do's afgerond :)
