### ISSUE TITLE
TABEL: Percentage gerealiseerd afschot per regio en per type

### ISSUE THREAD

**Issue by ThomasScheppers** [inbo/reporting-rshiny-grofwildjacht#37]
@Fhuysent @jimcasaer : zouden we hier niet beter een figuur van maken ipv een tabel?

**Comment by Fhuysent** [comment]
Fout bij berekening van de percentages, trend 1, 5 en 10 jaar zijn telkens gelijk.
Wat met zeer hoge percentages? (percentages op absolute cijfers onder de 50 niet weergeven).

**Comment by mvarewyck** [comment]
Fout verbeterd, was wegens gedupliceerde variabelen bij berekening, hierdoor werd bij verschil in percentages altijd waarde van 1j terug herhaald. We selecteerden op absoluut aantal 10, nu verhoogd naar 50.

**Comment by ThomasScheppers** [comment]
Ok. Check ook +- teken (mogelijks andere issue):
![image](https://user-images.githubusercontent.com/24563808/33769129-3e7fdfa0-dc29-11e7-8d77-609348c3b2b4.png)

**Comment by mvarewyck** [comment]
The +- should be fixed now (see #29)
