### ISSUE TITLE
[BUG] Voeren not present for F17_4 (toekomstig verspreidingsgebied)

### ISSUE THREAD

**Issue by mvarewyck** [inbo/reporting-rshiny-grofwildjacht#374]
**Describe the bug**
Voeren is not present in F17_4 (toekomst) while it is in F17_1 (huidig)

**To Reproduce**
Run https://github.com/inbo/reporting-rshiny-grofwildjacht/blob/318-dashboard-figuren-code/dashboard/scripts/F17_4_toekomstige_verspreiding.R#L16-L18
```
> Gemeentemap@data[Gemeentemap@data$Communs == "Voeren", ]
 [1] Communs  OBJECTI  ADMUNAF  ADMUNAD  ADMUNAG  CODE_IN  arrond   Frms_gm 
 [9] Md_EP__G M_EP__G_ Md_OH__G M_OH__G_ Md_EP_G  M_EP_C_  M_EP_A_  Md_OH_G 
[17] M_OH_C_  M_OH_A_ 
<0 rows> (or 0-length row.names)
```

Or in the app select 'Provinces' -> Voeren

**Expected behavior**
I would expect Voeren to be colored gray.

**Screenshots**
![Screenshot from 2023-01-12 20-44-01](https://user-images.githubusercontent.com/22143743/212165842-220103f9-03f7-4b5d-b4c3-8d4294b757a2.png)

![Screenshot from 2023-01-12 20-44-19](https://user-images.githubusercontent.com/22143743/212165833-bf553d66-fa84-448e-a0d9-6144a3012f76.png)

**Comment by RuttenAnneleen** [comment]
@mvarewyck: Voeren zit inderdaad niet in de toekomstige  verspreiding, dat is een gevolg van de opbouw van dit model. Aangezien everzwijnen altijd aanwezig zijn in Voeren, mag Voeren inderdaad grijs worden gekleurd indien mogelijk.

**Comment by mvarewyck** [comment]
Ik zou dit kunnen doen voor de gemeente Voeren (die kan ik uit de algemene shapefile halen), maar voor de pixels kan ik dit niet. 
Ik heb hiervoor de 2x2 UTM squares nodig die overlappen met Voeren.

**Comment by RuttenAnneleen** [comment]
Hmm, @jimcasaer: Wat denk jij ervan om Voeren erbij te zetten? Want in de pixeloutput is dat moeilijker te zeggen dat daar een startpopulatie was omdat die gemeente niet wordt meegenomen in het model en voorspellingen zijn er dus niet voor Voeren

**Comment by mvarewyck** [comment]
> Ik zou dit kunnen doen voor de gemeente Voeren (die kan ik uit de algemene shapefile halen), ~~maar voor de pixels kan ik dit niet. Ik heb hiervoor de 2x2 UTM squares nodig die overlappen met Voeren.~~

Net gerealiseerd dat als ik Voeren in zn geheel grijs moet kleuren, dit ook kan voor de pixels - op dezelfde manier als voor gemeentes.
Laat maar weten wat jullie beslissen.

**Comment by RuttenAnneleen** [comment]
Het probleem is dat Voeren bij de pixels hetzelfde inkleuren als bij de gemeentes niet helemaal correct is volgens de effectieve data (op gemeenteniveau is het wel prima om het gewoon in te kleuren als 'al aanwezig'). Ik bespreek het nog met Jim!

**Comment by RuttenAnneleen** [comment]
@mvarewyck: Ik heb het net even met Jim besproken. We hebben besloten om bij de pixelkaart Voeren effectief niet mee te nemen en bij de disclaimer zetten dat Voeren niet werd meegenomen in de analyse. 
Bij de gemeentekaart mag Voeren vanaf nu wel gewoon als 'al aanwezig' worden aangeduid

**Comment by mvarewyck** [comment]
Voeren is toegevoegd voor gemeentes, niet voor pixels. 
@RuttenAnneleen pas jij de disclaimer aan voor [F17_4](https://github.com/inbo/reporting-rshiny-grofwildjacht/blob/318-dashboard-figuren-code/reporting-grofwild/inst/extdata/uiText.csv) ?

**Comment by RuttenAnneleen** [comment]
De Disclaimer is aangepast!
