### ISSUE TITLE
Update toekomstige verspreiding 2023 (and future years)

### ISSUE THREAD

**Issue by RuttenAnneleen** [inbo/reporting-rshiny-grofwildjacht#378]
De nodige scripts van het verspreidingsmodel werden al aangepast voor jaarlijkse reruns in https://github.com/inbo/verspreiding-everzwijn/issues/22.

Wat we nu nog moeten doen om da jaarlijkse update in het dashboard te verzekeren is:

- [x] Navragen exacte files voor Dashboard aan @mvarewyck 
- [x] Check met @SanderDevisscher waar deze scripts het best terecht komen en deze verplaatsen
- [x] Run model met 100 iteraties voor 2023
- [x] Files toevoegen aan S3-bucket lijst
- [x] Check met @SanderDevisscher waar deze scripts het best terecht komen en deze verplaatsen
- [x] Check met @SanderDevisscher voor automatische Github reruns

**Comment by RuttenAnneleen** [comment]
@mvarewyck: Om de figuur van het de toekomstige verspreiding jaarlijks te updaten wou ik eens even vragen welke files jij exact nodig hebt want omdat jij deze figuur vanuit ons shiny-script hebt gemaakt ben ik niet zeker wat de opbouw van de files moet zijn.

Momenteel geeft het model de [pixel output](https://github.com/inbo/verspreiding-everzwijn/blob/22-run-2023/Yearly%20rerun/Output/2023/Model_output_Pixels_2023.csv) en de [gemeente output](https://github.com/inbo/verspreiding-everzwijn/blob/22-run-2023/Yearly%20rerun/Output/2023/Model_output_Municipalities_2023.csv) op deze manier. Ik denk dat ze zo ook in onze shiny app werden ingelezen maar aan jou dus om te bevestigen :)

**Comment by mvarewyck** [comment]
@RuttenAnneleen Ik lees een csv file in: [waarnemingen_2022.csv](https://github.com/inbo/reporting-rshiny-grofwildjacht/blob/318-dashboard-figuren-code/reporting-grofwild/inst/extdata/waarnemingen_2022.csv). Laat maar weten als er iets verandert. Bestandsnaam zal al aangepast worden #377

**Comment by RuttenAnneleen** [comment]
> @RuttenAnneleen Ik lees een csv file in: [waarnemingen_2022.csv](https://github.com/inbo/reporting-rshiny-grofwildjacht/blob/318-dashboard-figuren-code/reporting-grofwild/inst/extdata/waarnemingen_2022.csv). Laat maar weten als er iets verandert. Bestandsnaam zal al aangepast worden #377

@mvarewyck: dat is de file voor het huidige verspreidingsgebied, ik bedoel het toekomstige verspreidingsgebied F17_4

**Comment by mvarewyck** [comment]
Oeps, voor toekomstige verspreiding gebruik ik [(code ref)](https://github.com/inbo/reporting-rshiny-grofwildjacht/blob/318-dashboard-figuren-code/reporting-grofwild/R/data_load.R#L525-L530)

- pixels = "Pixels_ModelOutput_toekomst_verspr_2022.shp",
- municipalities = "Municipalities_ModelOutput_toekomst_verspr_2022.shp"

Alle files [hier](https://github.com/inbo/reporting-rshiny-grofwildjacht/tree/318-dashboard-figuren-code/reporting-grofwild/inst/extdata/futureSpread) te plaatsen

**Comment by RuttenAnneleen** [comment]
> Oeps, voor toekomstige verspreiding gebruik ik [(code ref)](https://github.com/inbo/reporting-rshiny-grofwildjacht/blob/318-dashboard-figuren-code/reporting-grofwild/R/data_load.R#L525-L530)
> 
> * pixels = "Pixels_ModelOutput_toekomst_verspr_2022.shp",
> * municipalities = "Municipalities_ModelOutput_toekomst_verspr_2022.shp"
> 
> Alle files [hier](https://github.com/inbo/reporting-rshiny-grofwildjacht/tree/318-dashboard-figuren-code/reporting-grofwild/inst/extdata/futureSpread) te plaatsen

Top! Dan maak ik er nog shapefiles van! Ik geef een seintje als ze klaar staan

**Comment by SanderDevisscher** [comment]
@mvarewyck moeten deze files niet in een .Rdata pakket komen ?

**Comment by mvarewyck** [comment]
> @mvarewyck moeten deze files niet in een .Rdata pakket komen ?

Voorlopig lezen we deze shape files rechtstreeks in zonder er een .Rdata object van te maken.

**Comment by mvarewyck** [comment]
Wegens manuele toevoeging Voeren #374, wordt nu een .Rdata file aangemaakt [(code)](https://github.com/inbo/reporting-rshiny-grofwildjacht/blob/318-dashboard-figuren-code/reporting-grofwild/R/data_create.R#L265-L342)

- Input files komen in "~/git/reporting-rshiny-grofwildjacht/data". Indien er meerdere input files staan, nemen we de meest recente: e.g. Municipalities_ModelOutput_toekomst_verspr_2022.shp en Municipalities_ModelOutput_toekomst_verspr_2023.shp. De code moet dus niet aangepast worden bij data updates.
- Output (.RData) file wordt aangemaakt via commando `createSpreadData(spatialData = spatialData)` en automatisch weggeschreven naar "~git/reporting-rshiny-grofwildjacht/reporting-grofwild/inst/extdata"
- Voorlopig wordt de .RData file gewoon in git meegenomen, maar file verhuist mee naar S3 buckets.

**Comment by SanderDevisscher** [comment]
> Wegens manuele toevoeging Voeren #374, wordt nu een .Rdata file aangemaakt [(code)](https://github.com/inbo/reporting-rshiny-grofwildjacht/blob/318-dashboard-figuren-code/reporting-grofwild/R/data_create.R#L265-L342)
> 
> * Input files komen in "~/git/reporting-rshiny-grofwildjacht/data". Indien er meerdere input files staan, nemen we de meest recente: e.g. Municipalities_ModelOutput_toekomst_verspr_2022.shp en Municipalities_ModelOutput_toekomst_verspr_2023.shp. De code moet dus niet aangepast worden bij data updates.
> * Output (.RData) file wordt aangemaakt via commando `createSpreadData(spatialData = spatialData)` en automatisch weggeschreven naar "~git/reporting-rshiny-grofwildjacht/reporting-grofwild/inst/extdata"
> * Voorlopig wordt de .RData file gewoon in git meegenomen, maar file verhuist mee naar S3 buckets.

Gewoon even voor de zekerheid:
Klopt het dat dit wilt zeggen dat wij het `createSpreadData` manueel moeten laten lopen om dit deel van de spatiale data up te daten? 
Klopt het dat  `createSpreadData` een functie is die parallel aan `readShapeData`  gebruikt moet worden? 
De werkwijze van beide functies is ook dezelfde ? maw (1) zet de bestanden in een tijdelijke folder, (2) point de functie in de richting van die folder en (3) de functie packaged de files en plaatst ze (op termijn) op de s3 Bucket?

**Comment by mvarewyck** [comment]
> Gewoon even voor de zekerheid: Klopt het dat dit wilt zeggen dat wij het `createSpreadData` manueel moeten laten lopen om dit deel van de spatiale data up te daten? 

Ja, in de S3-toekomst best wel. Momenteel heb ik deze laten lopen en toegevoegd aan GIT.

> Klopt het dat `createSpreadData` een functie is die parallel aan `readShapeData` gebruikt moet worden? 

Ja

> De werkwijze van beide functies is ook dezelfde ? maw (1) zet de bestanden in een tijdelijke folder, (2) point de functie in de richting van die folder en (3) de functie packaged de files en plaatst ze (op termijn) op de s3 Bucket?

Merk op dat `createSpreadData()` pas kan aangemaakt worden NA `createShapeData()` omdat de polygon voor Voeren uit deze laatste komen. Voor de rest zijn ze idd gelijkaardig. Vb. van huidige manier van updaten staat [hier](https://github.com/inbo/reporting-rshiny-grofwildjacht/blob/318-dashboard-figuren-code/reporting-grofwild/tests/testthat/testData.R#L10-L30)
