### ISSUE TITLE
[BUG] Text duplicated

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/reporting-rshiny-grofwildjacht#382]
**Describe the bug**
De tekst boven de landkaart van de wbepagina komt 2 keer voor (zie screenshot)

**Expected behavior**
er zijn 3 opties 
1. De tekst staat enkel bij de WBE grenzen en jachtterreinen
2. De tekst staat enkel bovenaan
3. Het is helemaal geen probleem dat de tekst er 2 keer staat.

@jimcasaer @RuttenAnneleen wat denken jullie ?

**Screenshots**
![image](https://user-images.githubusercontent.com/16779320/219024320-d9f8d1be-35e7-4d07-8583-1737547386f5.png)

**Additional context**
Dit is zeker geen breaking issue => oplossen na release

**Comment by jimcasaer** [comment]
@SanderDevisscher  de tekst enkel vlak boven de kaart zou mijn voorkeur zijn 
jim

**Comment by SanderDevisscher** [comment]
> @SanderDevisscher de tekst enkel vlak boven de kaart zou mijn voorkeur zijn jim

optie 1 dus

**Comment by mvarewyck** [comment]
(fixed in #346, to be tested after merging)
