### ISSUE TITLE
S3 migration for dashboard data

### ISSUE THREAD

**Issue by mvarewyck** [inbo/reporting-rshiny-grofwildjacht#383]
@mvarewyck kan je eens snel checken of alle nodige files op de UAT bucket staan ?

_Originally posted by @SanderDevisscher in https://github.com/inbo/reporting-rshiny-grofwildjacht/issues/346#issuecomment-1431360814_

I checked for all files in the /inst/extdata folder. The following are missing. 
_Unless you didn't want to put these on S3, i.e. if you want to have a new deployment if these data change_

* [Data_beschikbaarheid.csv](https://github.com/inbo/reporting-rshiny-grofwildjacht/blob/318-dashboard-figuren-code/reporting-grofwild/inst/extdata/Data_beschikbaarheid.csv)
* [spreadData.RData](https://github.com/inbo/reporting-rshiny-grofwildjacht/blob/318-dashboard-figuren-code/reporting-grofwild/inst/extdata/spreadData.RData). Created e.g. [here](https://github.com/inbo/reporting-rshiny-grofwildjacht/blob/318-dashboard-figuren-code/reporting-grofwild/tests/testthat/testData.R#L29-L30)
* [waarnemingen_wild_zwijn_processed.csv](https://github.com/inbo/reporting-rshiny-grofwildjacht/blob/318-dashboard-figuren-code/reporting-grofwild/inst/extdata/waarnemingen_wild_zwijn_processed.csv). This one should replace the file `waarnemingen_2022.csv` currently on S3.  Created e.g. [here](https://github.com/inbo/reporting-rshiny-grofwildjacht/blob/318-dashboard-figuren-code/reporting-grofwild/tests/testthat/testData.R#L29-L30)

Note: I still need to update the code to actually read the data from S3

**Comment by mvarewyck** [comment]
I can upload these data on S3, but it would be good if you update the scripts on your side for the future.

**Comment by SanderDevisscher** [comment]
- [Data_beschikbaarheid.csv](https://github.com/inbo/reporting-rshiny-grofwildjacht/blob/318-dashboard-figuren-code/reporting-grofwild/inst/extdata/Data_beschikbaarheid.csv) 

I think its best to handle this file like the `meta_schade.csv` and thus keep it outside of the S3 bucket. This is a file that's maintained and updated in this repo only if I'm not mistaken. @RuttenAnneleen what do you think ?

- [spreadData.RData](https://github.com/inbo/reporting-rshiny-grofwildjacht/blob/318-dashboard-figuren-code/reporting-grofwild/inst/extdata/spreadData.RData). Created e.g. [here](https://github.com/inbo/reporting-rshiny-grofwildjacht/blob/318-dashboard-figuren-code/reporting-grofwild/tests/testthat/testData.R#L29-L30)

I'll implement some logic to create this file in the backoffice (allready an issue https://github.com/inbo/backoffice-wild-analyse/issues/950) but before I can do this I think you need to update the function so it places the rdata package on the UAT bucket, like `readShapeData()` does. 

- [waarnemingen_wild_zwijn_processed.csv](https://github.com/inbo/reporting-rshiny-grofwildjacht/blob/318-dashboard-figuren-code/reporting-grofwild/inst/extdata/waarnemingen_wild_zwijn_processed.csv). This one should replace the file waarnemingen_2022.csv currently on S3. Created e.g. [here](https://github.com/inbo/reporting-rshiny-grofwildjacht/blob/318-dashboard-figuren-code/reporting-grofwild/tests/testthat/testData.R#L29-L30)

I'll look into why `waarnemingen_wild_zwijn_processed.csv` is missing because it should be present on the UAT bucket.

**Comment by RuttenAnneleen** [comment]
> * [Data_beschikbaarheid.csv](https://github.com/inbo/reporting-rshiny-grofwildjacht/blob/318-dashboard-figuren-code/reporting-grofwild/inst/extdata/Data_beschikbaarheid.csv)
> 
> I think its best to handle this file like the `meta_schade.csv` and thus keep it outside of the S3 bucket. This is a file that's maintained and updated in this repo only if I'm not mistaken. @RuttenAnneleen what do you think ?
> 

Akkoord!

**Comment by RuttenAnneleen** [comment]
> (1) @RuttenAnneleen Ik denk dat er aan de kolomnamen van de 'maatschappelijk draagvlak' files soms wat veranderd is op S3 versus GIT. Ik denk dat 'Aantal_tot' hernoemd is naar 'aantal'. Kijk jij dit even na?
> 
> E.g. F14_4 heeft op S3 volgende kolommen
> 
> ```
>  [1] "V1"               "Year"             "Groep"            "Score"           
>  [5] "Question"         "aantal"           "Antwoord"         "Question_label"  
>  [9] "onderwerp"        "totaal"           "percentage"       "Antwoord_reclass"
> ```
> 
> Versus GIT [hier](https://github.com/inbo/reporting-rshiny-grofwildjacht/blob/318-dashboard-figuren-code/reporting-grofwild/inst/extdata/maatschappelijke_draagkracht/F14_4_data.csv) `Groep | Antwoord_reclass | Question_label | Aantal_tot | totaal`
> 

Hmm raar! In mijn voorbereidingsscript schrijf die effectief de kolomnamen weg zoals op de GIT (dus met Aantal_tot). En het moet ook effectief Aantal_tot zijn, geen idee waar het dan misloopt want de UAT_filelist verwijst ook naar het juiste bestand.
Enig idee waar het dan fout loopt?

**Comment by SanderDevisscher** [comment]
@mvarewyck which function do I need to run to prep `waarnemingen_wild_zwijn_processed.csv`?

**Comment by mvarewyck** [comment]
> @mvarewyck which function do I need to run to prep `waarnemingen_wild_zwijn_processed.csv`?

[link to code](https://github.com/inbo/reporting-rshiny-grofwildjacht/blob/318-dashboard-figuren-code/reporting-grofwild/R/data_create.R#L209-L211)
E.g. to update on UAT bucket, you can run

`createWaarnemingenData(dataFile = "~/git/reporting-rshiny-grofwildjacht/data/waarnemingen_2022.csv",
  bucket = "inbo-wbe-uat-data")`

**Comment by mvarewyck** [comment]
> > (1) @RuttenAnneleen Ik denk dat er aan de kolomnamen van de 'maatschappelijk draagvlak' files soms wat veranderd is op S3 versus GIT. Ik denk dat 'Aantal_tot' hernoemd is naar 'aantal'. Kijk jij dit even na?
> > E.g. F14_4 heeft op S3 volgende kolommen
> > ```
> >  [1] "V1"               "Year"             "Groep"            "Score"           
> >  [5] "Question"         "aantal"           "Antwoord"         "Question_label"  
> >  [9] "onderwerp"        "totaal"           "percentage"       "Antwoord_reclass"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Versus GIT [hier](https://github.com/inbo/reporting-rshiny-grofwildjacht/blob/318-dashboard-figuren-code/reporting-grofwild/inst/extdata/maatschappelijke_draagkracht/F14_4_data.csv) `Groep | Antwoord_reclass | Question_label | Aantal_tot | totaal`
> 
> Hmm raar! In mijn voorbereidingsscript schrijf die effectief de kolomnamen weg zoals op de GIT (dus met Aantal_tot). En het moet ook effectief Aantal_tot zijn, geen idee waar het dan misloopt want de UAT_filelist verwijst ook naar het juiste bestand. Enig idee waar het dan fout loopt?

@RuttenAnneleen Nee, ik heb helaas niet direct een idee waar het fout loopt :)

Ik heb hieronder wat tests gedaan
* Kan je eens nakijken wanneer je dit bestand laatst hebt aangepast op S3?
* Kan je het bestand F17_4 nog eens opnieuw proberen uploaden?
* Kan je zelf eens het bestand proberen inlezen van S3 in R en kolomnamen opvragen via de code hieronder?

```
    # Last modified
    tmpTable <- data.table::rbindlist(aws.s3::get_bucket(bucket = "inbo-wbe-uat-data"))
    unique(tmpTable$LastModified[tmpTable$Key == "F14_4_data.csv"])
    # [1] "2023-01-20T09:51:18.000Z"

    # Read data
    tmpData <- aws.s3::s3read_using(FUN = read.csv, bucket = "inbo-wbe-uat-data", object = "F14_4_data.csv")
    colnames(tmpData)
    #  [1] "X"              "Year"           "Groep"          "Score"         
    #  [5] "Question"       "aantal"         "Antwoord"       "Question_label"
    #  [9] "onderwerp"      "totaal"         "percentage"    

    head(tmpData)
    #   X Year                          Groep Score Question aantal
    # 1 1 2017 Publiek buiten everzwijngebied    -2     Q19a     47
    # 2 2 2017 Publiek buiten everzwijngebied    -2     Q19b    192
    # 3 3 2017 Publiek buiten everzwijngebied    -2     Q19c    260
    # 4 4 2017 Publiek buiten everzwijngebied    -2     Q19d    479
    # 5 5 2017 Publiek buiten everzwijngebied    -1     Q19a     87
    # 6 6 2017 Publiek buiten everzwijngebied    -1     Q19b    267
    #                   Antwoord             Question_label   onderwerp totaal
    # 1 Helemaal niet belangrijk Niet-elektrische omheining Maatregelen   1018
    # 2 Helemaal niet belangrijk      Elektrische omheining Maatregelen   1018
    # 3 Helemaal niet belangrijk                      Jacht       Jacht   1018
    # 4 Helemaal niet belangrijk                     Kooien      Kooien   1018
    # 5          Niet belangrijk Niet-elektrische omheining Maatregelen   1018
    # 6          Niet belangrijk      Elektrische omheining Maatregelen   1018
    #   percentage
    # 1        4.6
    # 2       18.9
    # 3       25.5
    # 4       47.1
    # 5        8.5
    # 6       26.2
```

**Comment by RuttenAnneleen** [comment]
@mvarewyck: ik denk dat ik weet waar het probleem zit.
De nodige file staat nog in de 355-dashboard-jachtdagboekjes branch van de fis-projecten repo, in de master staat de oude file zoals jij ze inleest.
Doe ik best een tussentijdse pull-request van de 355-branch om dit op te lossen?

**Comment by SanderDevisscher** [comment]
Ik kan de 355-branch binnenhalen en de  F17_4 van daaruit uploaden naar de S3 bucket

**Comment by mvarewyck** [comment]
> Ik kan de 355-branch binnenhalen en de F17_4 van daaruit uploaden naar de S3 bucket

@SanderDevisscher Zou je dan meteen alle draagkracht files kunnen updaten? Mogelijks ook bij de andere files problemen.
```
"Data_inschatting.csv",
      "F12_1_data.csv",
      "F14_1_data.csv",
      "F14_2_data.csv",
      "F14_3_data.csv",
      "F14_4_data.csv",
      "F14_5_data.csv"
```

**Comment by SanderDevisscher** [comment]
@mvarewyck Ik heb onderstaande bestanden upgeload van de 355 branch naar de UAT bucket. 

![image](https://user-images.githubusercontent.com/16779320/220108723-04f3d8e8-a90f-4718-81e8-9b2239687308.png)

merk op dat `F14_1`, `F14_4` en `wegdensiteit` kleiner zijn na de upload dan voor de upload.

**Comment by mvarewyck** [comment]
@RuttenAnneleen Nieuwe versie van wegdensiteit.csv heeft decimal separator komma ipv punt. Code is aangepast, dus gelieve dit zo te houden bij data updates.

**Comment by SanderDevisscher** [comment]
> > @mvarewyck which function do I need to run to prep `waarnemingen_wild_zwijn_processed.csv`?
> 
> [link to code](https://github.com/inbo/reporting-rshiny-grofwildjacht/blob/318-dashboard-figuren-code/reporting-grofwild/R/data_create.R#L209-L211) E.g. to update on UAT bucket, you can run
> 
> `createWaarnemingenData(dataFile = "~/git/reporting-rshiny-grofwildjacht/data/waarnemingen_2022.csv", bucket = "inbo-wbe-uat-data")`

@mvarewyck ik heb waarnemingen_wild_zwijn_processed.csv aangemaakt met onderstaande code:

```
createWaarnemingenData(dataFile = "../fis-projecten/Grofwild/Dashboard/Output/Data/waarnemingen_wild_zwijn_processed.csv", 
                         bucket = "inbo-wbe-uat-data")
```

Hierbij krijg ik onderstaande warning:

```
Warning message:
In data.table::fread(dataFile, select = c("jaar", "NAAM", "TAG",  :
  Detected 44 column names but the data has 45 columns (i.e. invalid file). Added 1 extra default column name for the first column which is guessed to be row names or an index. Use setnames() afterwards if this guess is not correct, or fix the file write command that created the file to create a valid file.
```

Kan je eens nakijken of dit een issue vormt ?

**Comment by mvarewyck** [comment]
> @mvarewyck ik heb waarnemingen_wild_zwijn_processed.csv aangemaakt met onderstaande code:
> 
> ```
> createWaarnemingenData(dataFile = "../fis-projecten/Grofwild/Dashboard/Output/Data/waarnemingen_wild_zwijn_processed.csv", 
>                          bucket = "inbo-wbe-uat-data")
> ```

@SanderDevisscher Volgens jouw code heb je `createWaarnemingenData()` gelopen op processed data ipv op de ruwe data `waarnemingen_2022.csv`. Dat veroorzaakt wsl de warning

**Comment by SanderDevisscher** [comment]
@mvarewyck bij het uitvoeren van onderstaande code om de files voor het verspreidingsmodel up te daten krijg ik onderstaande error:

`createSpreadData(tempdir_spread)` 
```
Error in names(toReturn) <- paste0(spatialLevel, "_", sapply(strsplit(tools::file_path_sans_ext(spatialFile),  : 
  'names' attribute [1] must be the same length as the vector [0]
```
PS. dit is de inhoud van tempdir_spread
![image](https://user-images.githubusercontent.com/16779320/220870646-b4cca62f-dbe2-40ad-8edc-730d7af8b16d.png)

**Comment by SanderDevisscher** [comment]
> @SanderDevisscher Volgens jouw code heb je `createWaarnemingenData()` gelopen op processed data ipv op de ruwe data `waarnemingen_2022.csv`. Dat veroorzaakt wsl de warning

Idd ik had de data geplukt van de verkeerde branch

**Comment by mvarewyck** [comment]
> @mvarewyck bij het uitvoeren van onderstaande code om de files voor het verspreidingsmodel up te daten krijg ik onderstaande error:
> 
> `createSpreadData(tempdir_spread)`
> 
> ```
> Error in names(toReturn) <- paste0(spatialLevel, "_", sapply(strsplit(tools::file_path_sans_ext(spatialFile),  : 
>   'names' attribute [1] must be the same length as the vector [0]
> ```
> 
> PS. dit is de inhoud van tempdir_spread ![image](https://user-images.githubusercontent.com/16779320/220870646-b4cca62f-dbe2-40ad-8edc-730d7af8b16d.png)

De bestandsnamen zijn veranderd. Ik zoek momenteel op volgende patronen in bestandsnaam van files in `jsonDir`

- pixels = "Pixels_ModelOutput_toekomst_verspr",
- municipalities = "Municipalities_ModelOutput_toekomst_verspr"

Zal ik de code aanpassen om naar jouw bestandsnamen te zoeken?

**Comment by mvarewyck** [comment]
> > @SanderDevisscher Volgens jouw code heb je `createWaarnemingenData()` gelopen op processed data ipv op de ruwe data `waarnemingen_2022.csv`. Dat veroorzaakt wsl de warning
> 
> `waarnemingen_wild_zwijn_processed.csv` is reeds door een script van @RuttenAnneleen geprocesste waarnemingen van waarnemingen.be.
> 
> `waarnemingen_wild_zwijn_processed` heeft deze kolomnamen:
> 
> ```
> [1] "X"               "id"              "naam_nl"         "naam_lat"        "speciesid"      
>  [6] "datum"           "invoerdatum"     "aantal"          "gedrag"          "methode"        
> [11] "kleed"           "geslacht"        "x"               "y"               "lon"            
> [16] "lat"             "utm1"            "gebied"          "gemeente"        "deelgemeente"   
> [21] "provincie"       "typewaarneming"  "status"          "embargo_datum"   "toestemming_wnr"
> [26] "bijzonderheden"  "precisie"        "soortgroep"      "familie"         "aanleverdatum"  
> [31] "jaar"            "TAG"             "Shape_Leng"      "Shape_Area"      "UIDN"           
> [36] "OIDN"            "TERRID"          "NISCODE"         "NAAM"            "DATPUBLBS"      
> [41] "NUMAC"           "LENGTE"          "OPPERVL"         "geometry"      
> ```

@SanderDevisscher [hier](https://github.com/inbo/reporting-rshiny-grofwildjacht/blob/318-dashboard-figuren-code/data/waarnemingen_2022.csv) is de meest recente data die ik gebruik en die heeft geen kolom 'X'. Jouw data heeft dus idd die eerste kolom teveel.

**Comment by SanderDevisscher** [comment]
@mvarewyck kan je de functie zo laten werken als `readShapeData` ? Ik bedoel hiermee dat de functie de files in de tempdir behandelt ongeacht wat de naam is ? 
Ik vraag dit omdat de filenames doorheen te tijd van naam zullen veranderen zie #378.  Ik heb nu logica voorzien waardoor de files van huidigjaar -1 niet worden gekopieerd naar de tempdir als de files van huidigjaar +1 bestaan.

**Comment by SanderDevisscher** [comment]
@mvarewyck sorry misverstandje ik zal de filenames aan onze kant aanpassen.

**Comment by mvarewyck** [comment]
@SanderDevisscher Geen probleem, laat maar weten als het nog niet duidelijk is!

Denk wel dat het belangrijk is om te weten dat ook `createShapeData()` op bestandsnamen werkt. We kunnen niet zomaar alle files uit folder inlezen omdat we op een bepaalde manier wel het 'spatiale niveau' moeten kunnen koppelen aan elke file (e.g. communes.geojson = gemeentes). 

- Jaartallen of andere extra info in de bestandsnaam wordt genegeerd voor _sommige files_ , nl. WBE, jachtter en modelOutput. Voor alle andere, moet de bestandsnaam exact zijn, eg. 'communes.geojson' voor gemeentes.
- De `jsonDir` mag meer files bevatten dan nodig voor de `createXX()` functies, enkel de matching files worden ingelezen & gebruikt.
- Voor toekomstige verspreiding worden enkel de _2 meest recente_ jaartallen ingelezen https://github.com/inbo/reporting-rshiny-grofwildjacht/issues/378#issuecomment-1410177224

**Comment by SanderDevisscher** [comment]
> @SanderDevisscher Geen probleem, laat maar weten als het nog niet duidelijk is!
> 
> Denk wel dat het belangrijk is om te weten dat ook `createShapeData()` op bestandsnamen werkt. We kunnen niet zomaar alle files uit folder inlezen omdat we op een bepaalde manier wel het 'spatiale niveau' moeten kunnen koppelen aan elke file (e.g. communes.geojson = gemeentes).

makes sense !!
> 
> * Jaartallen of andere extra info in de bestandsnaam wordt genegeerd voor _sommige files_ , nl. WBE, jachtter en modelOutput. Voor alle andere, moet de bestandsnaam exact zijn, eg. 'communes.geojson' voor gemeentes.

Dat had ik initieel fout begrepen maar zou nu in orde moeten zijn. 

> * De `jsonDir` mag meer files bevatten dan nodig voor de `createXX()` functies, enkel de matching files worden ingelezen & gebruikt. 
> * Voor toekomstige verspreiding worden enkel de _2 meest recente_ jaartallen ingelezen [Update toekomstige verspreiding 2023 (and future years) #378 (comment)](https://github.com/inbo/reporting-rshiny-grofwildjacht/issues/378#issuecomment-1410177224)

Lijkt me het veiligst maar om de bucket een beetje proper te houden heb ik toch wat logica voorzien om de oude files voor verspreidingsmodel te verwijderen.

**Comment by SanderDevisscher** [comment]
Ik krijg een nieuwe error:

```
OGR data source with driver: ESRI Shapefile 
Source: "C:\Users\sander_devisscher\AppData\Local\Temp\Rtmpq4VO9C\spreadData\Pixels_ModelOutput_toekomst_verspreiding_2023.shp", layer: "Pixels_ModelOutput_toekomst_verspreiding_2023"
with 3551 features
It has 32 fields
Error in `[[<-.data.frame`(`*tmp*`, name, value = integer(0)) : 
  replacement has 0 rows, data has 3551
In addition: Warning messages:
1: OGR support is provided by the sf and terra packages among others 
2: OGR support is provided by the sf and terra packages among others 
3: OGR support is provided by the sf and terra packages among others 
4: OGR support is provided by the sf and terra packages among others 
5: OGR support is provided by the sf and terra packages among others 
6: OGR support is provided by the sf and terra packages among others 
7: OGR support is provided by the sf and terra packages among others 
```

de inhoud van de tempdir is nu:
![image](https://user-images.githubusercontent.com/16779320/220885514-fcf7d766-84bb-4e81-bdd3-7cf734989bb6.png)

**Comment by SanderDevisscher** [comment]
> > > @SanderDevisscher Volgens jouw code heb je `createWaarnemingenData()` gelopen op processed data ipv op de ruwe data `waarnemingen_2022.csv`. Dat veroorzaakt wsl de warning
> > 
> > 
> > `waarnemingen_wild_zwijn_processed.csv` is reeds door een script van @RuttenAnneleen geprocesste waarnemingen van waarnemingen.be.
> > `waarnemingen_wild_zwijn_processed` heeft deze kolomnamen:
> > ```
> > [1] "X"               "id"              "naam_nl"         "naam_lat"        "speciesid"      
> >  [6] "datum"           "invoerdatum"     "aantal"          "gedrag"          "methode"        
> > [11] "kleed"           "geslacht"        "x"               "y"               "lon"            
> > [16] "lat"             "utm1"            "gebied"          "gemeente"        "deelgemeente"   
> > [21] "provincie"       "typewaarneming"  "status"          "embargo_datum"   "toestemming_wnr"
> > [26] "bijzonderheden"  "precisie"        "soortgroep"      "familie"         "aanleverdatum"  
> > [31] "jaar"            "TAG"             "Shape_Leng"      "Shape_Area"      "UIDN"           
> > [36] "OIDN"            "TERRID"          "NISCODE"         "NAAM"            "DATPUBLBS"      
> > [41] "NUMAC"           "LENGTE"          "OPPERVL"         "geometry"      
> > ```
> 
> @SanderDevisscher [hier](https://github.com/inbo/reporting-rshiny-grofwildjacht/blob/318-dashboard-figuren-code/data/waarnemingen_2022.csv) is de meest recente data die ik gebruik en die heeft geen kolom 'X'. Jouw data heeft dus idd die eerste kolom teveel.

fixed

**Comment by mvarewyck** [comment]
> Ik krijg een nieuwe error:
> 
> ```
> OGR data source with driver: ESRI Shapefile 
> Source: "C:\Users\sander_devisscher\AppData\Local\Temp\Rtmpq4VO9C\spreadData\Pixels_ModelOutput_toekomst_verspreiding_2023.shp", layer: "Pixels_ModelOutput_toekomst_verspreiding_2023"
> with 3551 features
> It has 32 fields
> Error in `[[<-.data.frame`(`*tmp*`, name, value = integer(0)) : 
>   replacement has 0 rows, data has 3551
> In addition: Warning messages:
> 1: OGR support is provided by the sf and terra packages among others 
> 2: OGR support is provided by the sf and terra packages among others 
> 3: OGR support is provided by the sf and terra packages among others 
> 4: OGR support is provided by the sf and terra packages among others 
> 5: OGR support is provided by the sf and terra packages among others 
> 6: OGR support is provided by the sf and terra packages among others 
> 7: OGR support is provided by the sf and terra packages among others 
> ```
> 
> de inhoud van de tempdir is nu: ![image](https://user-images.githubusercontent.com/16779320/220885514-fcf7d766-84bb-4e81-bdd3-7cf734989bb6.png)

@SanderDevisscher Ik vermoed dat er iets aan de data structuur is veranderd (kolomnamen). Zou je de data [hier](https://github.com/inbo/reporting-rshiny-grofwildjacht/tree/master/data) kunnen droppen, dan bekijk ik het.

**Comment by SanderDevisscher** [comment]
[spreadData.zip](https://github.com/inbo/reporting-rshiny-grofwildjacht/files/10812981/spreadData.zip)

**Comment by mvarewyck** [comment]
@SanderDevisscher Er zijn nog paar hickups langs mijn kant (nog niet getest met 2 jaartallen).

Langs jullie kant is er idd een verandering van kolom met gemeente naam: 'Communs' in "Municipalities_ModelOutput_toekomst_verspr_2022.shp" is 'NAAM' geworden in "Municipalities_ModelOutput_toekomst_verspreiding_2023.shp" 

Hoe maken we dit best uniform? Passen jullie de nieuwe/oude shape file aan? Of lees ik altijd de eerste kolom in als de spatial IDs (gemeente/pixel naam), nu doe ik dit obv kolomnaam ipv positie.

```
> head(modelShape2022@data)
     Communs OBJECTI   ADMUNAF   ADMUNAD   ADMUNAG CODE_IN arrond Frms_gm
43  Arendonk      44  ARENDONK  ARENDONK  ARENDONK   13001     13      12
45     Balen      46     BALEN     BALEN     BALEN   13003     13      20
47    Dessel      48    DESSEL    DESSEL    DESSEL   13006     13       5
48      Geel      49      GEEL      GEEL      GEEL   13008     13      13
50 Herentals      51 HERENTALS HERENTALS HERENTALS   13011     13      12
52   Herselt      53   HERSELT   HERSELT   HERSELT   13013     13       4
```

**Comment by SanderDevisscher** [comment]
@mvarewyck ik stel voor dat we de oude (22) shape conform met de nieuwe (23) maken. dwz de kolom "Communs" eenmalig hernoemen naar "NAAM". In de toekomst zullen de shapes (automatisch) aangemaakt worden op dezelfde wijze als die van 23 (met de kolom NAAM).

**Comment by mvarewyck** [comment]
@SanderDevisscher code is geupdatet. de oude (22) shape file passen jullie aan?

**Comment by SanderDevisscher** [comment]
Zullen we doen

**Comment by SanderDevisscher** [comment]
@RuttenAnneleen waar vind ik de model outputs voor het modeljaar 2022 ?

**Comment by SanderDevisscher** [comment]
@mvarewyck I've renamed "Communs" to "Naam". However I still get an error when running `createSpreadData` (see below) when the function processes "Municipalities_ModelOutput_toekomst_verspreiding_2022".

```
Error in FUN(X[[i]], ...) : 
  trying to get slot "data" from an object of a basic class ("NULL") with no slots
```
these are my steps:

1. Downloaded [this file](https://github.com/inbo/reporting-rshiny-grofwildjacht/blob/318-dashboard-figuren-code/data/Municipalities_ModelOutput_toekomst_verspr_2022.shp) & all related files. 
2. Opened the file using `readOGR`
3. renamed the column 
4. saved the file using `writeOGR`
5. used the upload flow to copy the file into a temporary directory 
6. ran `createSpreadData`

The function works fine for "Pixels_ModelOutput_toekomst_verspreiding_2022" & "Pixels_ModelOutput_toekomst_verspreiding_2023" but fails with "Municipalities_ModelOutput_toekomst_verspreiding_2022". 

I did notice a difference in colnames between the old (2022) & the new (2023). 

2022: 
```
 [1] "NAAM"     "OBJECTI"  "ADMUNAF"  "ADMUNAD"  "ADMUNAG"  "CODE_IN"  "arrond"   "Frms_gm"  "Md_EP__G" "M_EP__G_" "Md_OH__G"
[12] "M_OH__G_" "Md_EP_G"  "M_EP_C_"  "M_EP_A_"  "Md_OH_G"  "M_OH_C_"  "M_OH_A_" 
```

2023:
```
[1] "NAAM"    "OIDN"    "UIDN"    "TERRID"  "NISCODE" "DATPUBL" "NUMAC"   "LENGTE"  "OPPERVL" "ar_sqk_" "Md_EP_G" "M_EP_C_"
[13] "M_EP_A_"
```
@mvarewyck @RuttenAnneleen which columns do we need for the maps ? 
@RuttenAnneleen we should implement some logic to drop unneeded columns like "OIDN",    "UIDN" ,   "TERRID",  "DATPUBL", "NUMAC" &  "LENGTE" in future updates

**Comment by mvarewyck** [comment]
I think your error has no longer to do with the renaming, but with the connection to S3.

Within the function we need the [spatialData](https://github.com/inbo/reporting-rshiny-grofwildjacht/blob/318-dashboard-figuren-code/reporting-grofwild/R/data_create.R#L285-L286) to attach data for Voeren.
Can you try to add the spatialData as a function argument? Or make sure your connection to S3 is set up correctly?
I'll write an extra check in the `createSpreadData()` function for this

NOTE 1: On my side it works when I do the following (very similar to @SanderDevisscher)
I add on [line 351](https://github.com/inbo/reporting-rshiny-grofwildjacht/blob/318-dashboard-figuren-code/reporting-grofwild/R/data_create.R#L351)

```
      if (iFile == "municipalities_2022")
        colnames(modelShape@data)[1] <- "NAAM"
```

NOTE2: The advantage of this preprocessing is that we indeed drop all unnecessary columns for S3.

**Comment by SanderDevisscher** [comment]
@mvarewyck which argument should I use ? 

I tried downloading the spatialData.rdata into the temporary folder but this didn't help :-/

**Comment by SanderDevisscher** [comment]
I now use the following code:

```
 createSpreadData(tempdir_spread, 
                   spatialData = "./spatialData.RData")
```

which produces a new error, namely:
`Error in spatialData$communes : $ operator is invalid for atomic vectors `

**Comment by mvarewyck** [comment]
I think we won't get there. Just checked and if there is no connection to S3, it throws a different error on my side (so you would have noticed). 
`createSpreadData(jsonDir = tempdir(), spatialData = readS3(file = "spatialData.RData"))`

Then it still has to do with the renaming. The spatial binding seems to be lost.

> Error in FUN(X[[i]], ...) : 
>   trying to get slot "data" from an object of a basic class ("NULL") with no slots

This error indicates typically a spatialPolygonsDataFrame object from which we try to extract the data slot and doesn't exist.

Should I just push my code with the [two lines](https://github.com/inbo/reporting-rshiny-grofwildjacht/issues/383#issuecomment-1443656689) to fix this?

**Comment by SanderDevisscher** [comment]
yes let try that

**Comment by SanderDevisscher** [comment]
With the hotfix I now get this error:

```
Error in `[.data.frame`(modelShape@data, , c(if (grepl("pixels", iFile)) "ID" else "NAAM",  : 
  undefined columns selected
```

**Comment by SanderDevisscher** [comment]
I could force the model to run again for 2022 thus resulting in a file like the one for 2023, but this might take a while.

**Comment by mvarewyck** [comment]
I'm sure we'll get there somehow, sometime..  ;)

> With the hotfix I now get this error:
> 
> ```
> Error in `[.data.frame`(modelShape@data, , c(if (grepl("pixels", iFile)) "ID" else "NAAM",  : 
>   undefined columns selected
> ```

Are you sure you loaded latest code? Can you print in R `createSpreadData` and search for the lines I added?

> 
> when using the shape without the rename or
> 
> ```
> Error in spatialData$communes : $ operator is invalid for atomic vectors
> ```
> 
> with the rename

Can you print your output of this?
```
> readS3(file = "spatialData.RData")
> names(spatialData)
[1] "flanders"         "provinces"        "communes"         "faunabeheerzones"
[5] "fbz_gemeentes"    "utm5"             "provincesVoeren" 
> class(spatialData)
[1] "list"

```

**Comment by SanderDevisscher** [comment]
This seems to missing

**Comment by mvarewyck** [comment]
A `devtools::load_all()` or R CMD install and `library(reportingGrofwild)` should work then with the latest changes from GIT.

**Comment by SanderDevisscher** [comment]
I reinstalled the reporting-grofwild pacakage using this code:

```
devtools::install_github("inbo/reporting-rshiny-grofwildjacht@318-dashboard-figuren-code", 
                           subdir = "reporting-grofwild", force = TRUE)
```
I now have this code in the function:
```
if (iFile == "municipalities_2022")
        colnames(modelShape@data)[1] <- "NAAM"
```
however I still get this error:
```
Error in FUN(X[[i]], ...) : 
  trying to get slot "data" from an object of a basic class ("NULL") with no slots
```

**Comment by SanderDevisscher** [comment]
using this code:

```
test1 <- readOGR(paste0(tempdir_spread, "Municipalities_ModelOutput_toekomst_verspreiding_2022.shp"))
colnames(test1@data)[1] <- "NAAM"
```
I get :
```
        NAAM OBJECTI    ADMUNAF    ADMUNAD    ADMUNAG CODE_IN arrond Frms_gm Md_EP__G
0 Aartselaar       1 AARTSELAAR AARTSELAAR AARTSELAAR   11001     11       0        0
1  Antwerpen       2     ANVERS  ANTWERPEN  ANTWERPEN   11002     11       8        1
2   Boechout       3   BOECHOUT   BOECHOUT   BOECHOUT   11004     11       0        0
3       Boom       4       BOOM       BOOM       BOOM   11005     11       0        0
4   Borsbeek       5   BORSBEEK   BORSBEEK   BORSBEEK   11007     11       1        1
5 Brasschaat       6 BRASSCHAAT BRASSCHAAT BRASSCHAAT   11008     11       3        1
```

**Comment by SanderDevisscher** [comment]
@mvarewyck we dropped the nameless columns (read as X, V1, ...) from the dashboard data (fxx_x files) and w've reuploaded them to the UAT bucket. Can you confirm the data is still ok ?

**Comment by mvarewyck** [comment]
> @mvarewyck we dropped the nameless columns (read as X, V1, ...) from the dashboard data (fxx_x files) and w've reuploaded them to the UAT bucket. Can you confirm the data is still ok ?

Ja, de maatschappelijk draagkracht figuren werken nog

**Comment by mvarewyck** [comment]
> > @mvarewyck we dropped the nameless columns (read as X, V1, ...) from the dashboard data (fxx_x files) and w've reuploaded them to the UAT bucket. Can you confirm the data is still ok ?
> 
> Ja, de maatschappelijk draagkracht figuren werken nog

@SanderDevisscher @RuttenAnneleen 
Ik zie nu dat de klasse 'neutraal' opnieuw dubbele rijen heeft voor negatieve en positieve percentages.
De kolom percentage is eigl niet nodig, want deze wordt aan onze kant (her)berekend.

Ik kuis de data nu op aan onze kant, in de functie `barDraagkracht()`, dus langs jullie kant is er geen actie nodig.
