### ISSUE TITLE
Include unit choice "aantal/100ha bos & natuur" for map Flanders

### ISSUE THREAD

**Issue by mvarewyck** [inbo/reporting-rshiny-grofwildjacht#385]
Add unit for mapFlanders on all pages where the map is shown.

In mapFlandersUI: Set
`unitChoices = c("Aantal" = "absolute", "Aantal/100ha" = "relative", "Aantal/100ha bos & natuur" = "relativeDekking")`

**Comment by mvarewyck** [comment]
@SanderDevisscher Some regions have 0 for the forest area. This results in relative counts being NA (divide by 0).
They are currently colored darkgray in the maps. How do you want to handle these cases?

E.g. Oudenburg

```
> biotoopData$communes[biotoopData$communes$regio == "Oudenburg", ]
        regio  Area_m2  Area_ha Area_km2 Area_hab_m2_bebouwd Area_hab_m2_bos
176 Oudenburg 35615236 3561.524 35.61524             4860604               0
    Area_hab_m2_grasland Area_hab_m2_landbouw Area_hab_m2_water
176              5224150             25299305            231177
    Area_hab_m2_andere Area_hab_ha_bebouwd Area_hab_ha_bos Area_hab_ha_grasland
176                  0            486.0604               0              522.415
    Area_hab_ha_landbouw Area_hab_ha_water Area_hab_ha_andere
176              2529.93           23.1177                  0
    Area_hab_km2_bebouwd Area_hab_km2_bos Area_hab_km2_grasland
176             4.860604                0               5.22415
    Area_hab_km2_landbouw Area_hab_km2_water Area_hab_km2_andere perc_bos
176               25.2993           0.231177                   0        0
     perc_water perc_landbouw perc_grasland perc_bebouwd perc_andere
176 0.006490958     0.7103506      0.146683    0.1364754           0
    densiteit_bos gem_opp_bos_m2 perimeter_bos_m gem_opp_bos_ha gem_opp_bos_km2
176            NA             NA              NA             NA              NA
```
![Screenshot from 2023-02-16 12-33-44](https://user-images.githubusercontent.com/22143743/219354052-142f01b0-ae36-4c8e-af9b-b4fdf5fbc22f.png)

**Comment by RuttenAnneleen** [comment]
@mvarewyck: volgens mij moeten de gemeentes met afschot maar zonder bos/natuur effectief NA zijn omdat hier geen waarde voor berekend kan worden (en mogen dus ook grijs ingekleurd blijven). Gemeentes zonder afschot en zonder bos/natuur zijn gewoon 0 en wit van kleur

**Comment by SanderDevisscher** [comment]
@mvarewyck kan je ons eens een download van de data bezorgen ?

**Comment by mvarewyck** [comment]
As discussed: 
* When `area_hab_km2_bos < 1` we set the area to NA
* When number of shot is 0 we color white (irrespective of area). Only when no. shot > 0 and area NA we color gray (NA) with label "bos & natuur < 100ha"
* Example to test: Diksmuide in 2007 for Wild zwijn
