### ISSUE TITLE
[BUG] PRD tries to access UAT - bucket & fails

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/reporting-rshiny-grofwildjacht#386]
**Describe the bug**
When deploying to the PRD we get an error (see screenshot) which raises suspicion that PRD server tries to access the UAT  - bucket for data checks and fails in doing so.

**To Reproduce**
1. Deploy docker in PRD environment
2. open app (@berthuygens can you confirm ?)
3. See error

**Expected behavior**
app works in PRD

**Screenshots**
![image](https://user-images.githubusercontent.com/16779320/219617723-13490ac4-77ba-4f7f-be39-fe07f134d97f.png)

**Comment by mvarewyck** [comment]
@berthuygens Could it be that the environment is misspecified in the shinyproxy yaml file (I don't have access to it)?

For UAT it should have sth like `R_CONFIG_ACTIVE = "uat"`
While for production this should be `R_CONFIG_ACTIVE = "production"`

See our [config file](https://github.com/inbo/reporting-rshiny-grofwildjacht/blob/master/reporting-grofwild/inst/config.yml#L9-L15)
See [shinyproxy configuration `container-env`](https://shinyproxy.io/documentation/configuration/#apps)

**Comment by mvarewyck** [comment]
I had a look at the yaml files and they seem correct, so I have no clue why for production it looks in the wrong bucket

* Is it failing for both the public & private (wbe) app in production?
* Can you try again with my latest changes [here](https://github.com/inbo/reporting-rshiny-grofwildjacht/pull/389)? I updated the code to start an alternative app when it fails to start `reportingGrofwild::runWildApp()` which prints the configuration settings: the current configuration name, bucket and whether there's a datacheck. 
* Could you send me the log files? Maybe I can see from there why it goes wrong.

**Comment by stenmigerode** [comment]
Hi @mvarewyck,

This problem was fixed on Monday. This ticket should have been closed

**Comment by mvarewyck** [comment]
@stenmigerode Can you please specify how this was fixed? - for future reference

**Comment by stenmigerode** [comment]
@mvarewyck There was a problem with the deploy on Friday, which was fixed later on, which is why it tried to access the UAT bucket.

Also the IAM Roles for accessing the PRD S3 bucket from the PRD Shiny Proxy server was not yet configured previously, so we added those policies in AWS.
