### ISSUE TITLE
[BUG] WBE page link fails in chrome & unexpected behaviour in Firefox

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/reporting-rshiny-grofwildjacht#390]
**Describe the bug**
When using the tablink between faunabeheer.inbo.be and wbe.inbo.be in chrome many users (me included) get the following screen:

![image](https://user-images.githubusercontent.com/16779320/220641544-933fb0e5-27eb-48d8-857f-35d57acf5bca.png)

When you do the same in firefox you get this screen first 

![image](https://user-images.githubusercontent.com/16779320/220641887-20763806-c9f2-4f05-b626-6199a0a950d1.png)

And if you press "website openen in een nieuw venster" it works as it should.

I also noticed that if you login to keycloak before you open the app you first get this screen 

![image](https://user-images.githubusercontent.com/16779320/220642917-890bb56d-8411-4b1f-8f8c-e9ebfda90e7f.png)

but if you open app the link works like it should in chrome (bypassing the login screen)

**To Reproduce**
1. Go to https://faunabeheer.inbo.be in chrome
2. Click on 'wbe' tab

**Expected behavior**
Go to login for keycloak

**Comment by SanderDevisscher** [comment]
@stenmigerode can you summarise any internal checks you already did ?

**Comment by SanderDevisscher** [comment]
Restarting chrome and laptop has no effect nor does removing cookies

**Comment by stenmigerode** [comment]
Aan de systeemkant is alles OK. Ik vermoed dat dit geen gewone link naar de url https://wbe.inbo.be is dat daar gebruikt wordt. Enkel wbe.inbo.be mag inloggen op de keycloak server.

Die link werkt ook in de UAT omgeving trouwens. Wat altijd werkt is de URL van de wbe applicatie in te tikken.

**Comment by mvarewyck** [comment]
I can't seem to open the page in the current window (within shinyproxy).
@SanderDevisscher Is it an option that the WBE page is shown in a new window? Then I can get it work.

**Comment by mvarewyck** [comment]
> I can't seem to open the page in the current window (within shinyproxy). @SanderDevisscher Is it an option that the WBE page is shown in a new window? Then I can get it work.

Never mind, I found the way to open it in the [current window](https://github.com/openanalytics/shinyproxy/issues/113)
