### ISSUE TITLE
[BUG] species active while no afschot nor schade

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/reporting-rshiny-grofwildjacht#392]
**Describe the bug**
In some cases species get activated while there is no afschot nor schade for the specific wbe. An example of this would be Wild Zwijn for "Antwerpse Polders Noord" 

**To Reproduce**
1. Go to 'wbe page as admin or superuser'
2. Click on 'Antwerpse Polders Noord'
3. Scroll down 

**Expected behavior**
Species without data should be grayed out 

**Screenshots**
![image](https://user-images.githubusercontent.com/16779320/220828172-9c627d65-bac5-4010-a9eb-4a961edc08ea.png)
![image](https://user-images.githubusercontent.com/16779320/220828204-0a794404-9118-48c5-9b42-c093dc16d38f.png)

**Comment by mvarewyck** [comment]
Actually, there is 1 observation in 2014 for schade. But we restrict the time slider to start at 2018, therefore it is not picked up later.

![Screenshot from 2023-03-24 10-05-54](https://user-images.githubusercontent.com/22143743/227509630-de8ea4bd-8377-4c0f-ae69-4dbe979f7b6b.png)

@SanderDevisscher Should I restrict the check for schadedata records to start from 2018? This will disable the Wild zwijn tile automatically

**Comment by SanderDevisscher** [comment]
I think its logical to restrict the data to what we show, in this case that would be starting from 2018 (option 1). However we can opt to move the start year to 2014 but without e-loket data since it started from 2018 onwards (option 2).

@jimcasaer @LynnPallemaerts @RuttenAnneleen what do you guys think ?

**Comment by LynnPallemaerts** [comment]
@SanderDevisscher I would go for option 2, with only Eloket

**Comment by RuttenAnneleen** [comment]
Ja, ik ga ook voor optie 2!

**Comment by mvarewyck** [comment]
> So option 2 it will be: @mvarewyck the damage data start date should be moved to 2014.

@SanderDevisscher I've updated on WBE page. Should this also be updated on the page 'Wildschade'?

**Comment by RuttenAnneleen** [comment]
@mvarewyck: Je mag dit effectief ook voor de Wildschade pagina doen!

**Comment by SanderDevisscher** [comment]
@mvarewyck was this implemented for wildschade ?
