### ISSUE TITLE
[BUG] keycloak throws error when trying to login 

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/reporting-rshiny-grofwildjacht#394]
**Describe the bug**
When trying to login to wbe.inbo.be using chrome we (I and at least 1 user (wbe.tussenvoerenyse@hvv.be)) get the error below

**To Reproduce**
1. Go to 'wbe.inbo.be' using chrome
2. Provide credentials
3. click sign in

**Expected behavior**
wbe page gets displayed

**Screenshots**
![image](https://user-images.githubusercontent.com/16779320/224010220-546e6b08-fd25-46ce-b6fb-858b7c69219d.png)

**Additional context**
@stenmigerode you can remove your assignment if the error is caused by something else then keycloak.

**Comment by SanderDevisscher** [comment]
also issue while using firefox

**Comment by mvarewyck** [comment]
Is anyone looking into this? I also get the error when logging in.

**Comment by SanderDevisscher** [comment]
If I understand correctly the issue is due to some issue of keycloak. @gertvanspaendonk made sure login in has been re-enabled however the lost password procedure is still not working and needs intervention from @stenmigerode.

**Comment by SanderDevisscher** [comment]
I can confirm the initial error when loging into keycloak has been fixed. However we get a new error:

![image](https://user-images.githubusercontent.com/16779320/224328324-0c18166c-9227-4f11-810e-07cc7eb6d1c1.png)

**Comment by mvarewyck** [comment]
First time I get a timeout error, but when I refresh the page loads correctly (2nd time).

It takes some time to load the data for the WBE app, so I think increasing the timeout will solve this issue.
@stenmigerode Can the timeout be increased to 1 minute? See [here](https://github.com/inbo/reporting-rshiny-grofwildjacht/issues/379#issuecomment-1429481737)
Locally it takes about 45 seconds.

**Comment by SanderDevisscher** [comment]
Has been fixed
