### ISSUE TITLE
huidige verspreiding disclaimer

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/reporting-rshiny-grofwildjacht#395]
In de huidige versie staat er "Opmerking: Data voor de bron waarnemingen.be is beperkt wegens vertragingen in de dataflow."
Beetje raar als er wel waarnemingen zijn voor 2023 en geen afschot. 

Hier zie ik 2 opties: 

1. We laten  "Opmerking: Data voor de bron waarnemingen.be is beperkt wegens vertragingen in de dataflow." vallen (snelste en makkelijkste oplossing)
2. Het ontbreken van het afschot is een gevolg van het ontbreken van de wbe_binnengrenzen shape van 2023 (georef loopt hierop vast). Met de aanpassingen van https://github.com/inbo/backoffice-wild-analyse/pull/968 en toepassing van [#967](https://github.com/inbo/backoffice-wild-analyse/issues/967) kunnen we een update doen van het afschot zodat het gedeelte van 2023 er toch bij zit. (miz traagste maar correctste oplossing)

@jimcasaer @LynnPallemaerts @RuttenAnneleen wat denken jullie ?

@mvarewyck is het mogelijk om dit data driven te maken ? ea dat de disclaimer verschijnt als er voor een bepaald jaar geen waarnemingen zijn ? een gebrek aan afschot zou na de fixes in de backoffice niet meer mogen voorkomen.

_Originally posted by @SanderDevisscher in https://github.com/inbo/reporting-rshiny-grofwildjacht/issues/346#issuecomment-1458206941_

**Comment by SanderDevisscher** [comment]
> @mvarewyck is het mogelijk om dit data driven te maken ? ea dat de disclaimer verschijnt als er voor een bepaald jaar geen waarnemingen zijn ? een gebrek aan afschot zou na de fixes in de backoffice niet meer mogen voorkomen.
 
(1) Dit is geen simpele fix en aangezien het slechts tijdelijk is, zou ik opteren voor een aanpassing van de disclaimer: "Data voor 2023 kan beperkt zijn wegens vertragingen in de dataflow." 
(2) Of zelfs de disclaimer verwijderen alsook data van 2023 voor waarnemingen. Want bovenaan de pagina staat "De tabellen en figuren zijn gebaseerd op gegevens die beschikbaar waren op 31/12/2022.". Deze datum wordt (momenteel) bepaald door de laatste afschotdatum in ecology data.

Originally posted by @mvarewyck in https://github.com/inbo/reporting-rshiny-grofwildjacht/pull/346#issuecomment-1460001568

**Comment by SanderDevisscher** [comment]
> > > @mvarewyck is het mogelijk om dit data driven te maken ? ea dat de disclaimer verschijnt als er voor een bepaald jaar geen waarnemingen zijn ? een gebrek aan afschot zou na de fixes in de backoffice niet meer mogen voorkomen.
> > 
> > 
 > (1) Dit is geen simpele fix en aangezien het slechts tijdelijk is, zou ik opteren voor een aanpassing van de disclaimer: "Data voor 2023 kan beperkt zijn wegens vertragingen in de dataflow." (2) Of zelfs de disclaimer verwijderen alsook data van 2023 voor waarnemingen. Want bovenaan de pagina staat "De tabellen en figuren zijn gebaseerd op gegevens die beschikbaar waren op 31/12/2022.". Deze datum wordt (momenteel) bepaald door de laatste afschotdatum in ecology data.

Persoonlijk zou ik gaan voor optie 2. @jimcasaer @LynnPallemaerts @RuttenAnneleen wat denken jullie ?

_Originally posted by @SanderDevisscher in https://github.com/inbo/reporting-rshiny-grofwildjacht/pull/346#issuecomment-1460003454_

**Comment by LynnPallemaerts** [comment]
@SanderDevisscher Kunnen we niet voor beide een datum meegeven, bv "De tabellen en figuren zijn gebaseerd op gegevens die beschikbaar waren op 31/12/2022" voor afschot en dan gelijkaardig voor waarnemingen.be?.

**Comment by SanderDevisscher** [comment]
Dat is zeker een optie maar ik vraag me af of het zo niet te verwarrend wordt.

**Comment by RuttenAnneleen** [comment]
Ik zou idd gewoon bij de waarnemingen een filter toevoegen tem 2023 en de disclaimer verwijderen
