### ISSUE TITLE
Can the app cope with a list of sources ? 

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/reporting-rshiny-grofwildjacht#397]
@mvarewyck ik ben bezig met het toevoegen van logica om dubbele schademeldingen te verwijderen uit de data (https://github.com/inbo/backoffice-wild-analyse/issues/866). Hierdoor bestaat de kans dat er een schadegeval in meerdere datasets voorkomt. Graag hadden we alle bronnen uitgelicht. Daarom vroeg ik me af hoe ik best de bronnen oplijst ? 

1. Een character list `as.list(paste(x, collapse = ","))` ?
2. Enkele kolommen in de trend van `isEloket`, `isWilder`, `isNatuurpunt`, `isAndere` ?
3. Een ander suggestie ?

**Comment by mvarewyck** [comment]
> @mvarewyck ik ben bezig met het toevoegen van logica om dubbele schademeldingen te verwijderen uit de data (https://github.com/inbo/backoffice-wild-analyse/issues/866). Hierdoor bestaat de kans dat er een schadegeval in meerdere datasets voorkomt. Graag hadden we alle bronnen uitgelicht. Daarom vroeg ik me af hoe ik best de bronnen oplijst ?
> 
> 1. Een character list `as.list(paste(x, collapse = ","))` ?
> 2. Enkele kolommen in de trend van `isEloket`, `isWilder`, `isNatuurpunt`, `isAndere` ?
> 3. Een ander suggestie ?

Optie 1 is prima.

**Comment by SanderDevisscher** [comment]
@mvarewyck we're planning to do a huge rework concerning wildschade. Mainly the definition of a schadegeval is going to change. We will try to reduce the number of duplicate records by giving records of the same species and the same damagetype-damaged crop - combo within a certain range both temporally as spatially the same schadegeval_id. This results in some schadegeval_ids having multiple sources however these will be all present in the data as seperate rows since they are still seperate schademeldingen. This info is still needed for #422. So no need for changes in the code for this issue.
