### ISSUE TITLE
[BUG] app crashes when selecting "De Zandhaas"

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/reporting-rshiny-grofwildjacht#401]
**Describe the bug**
The private part of the app, build & run locally using docker, crashed (grey screen) when I selected "De Zandhaas". 

**To Reproduce**
1. build & run app locally as admin
2. switch to "De Zandhaas"

**Expected behavior**
A wbepage for "De Zandhaas" is loaded or an disclaimer is shown

**Additional context**
The docker log:
```
Warning: Error in <Anonymous>: error in evaluating the argument 'i' in selecting a method for function '[':
  120: <Anonymous>
Warning: Error in $<-.data.frame: replacement has 1 row, data has 0
  72: stop
  71: $<-.data.frame
  69: mapFlanders
  68: <reactive>
  52: spacePlot
  45: <observer>
   2: runApp
   1: reportingGrofwild::runWildApp
Warning: Error in $<-.data.frame: replacement has 1 row, data has 0
  100: <Anonymous>
```
The issue is new, it does not occur in the PRD - version.

**Comment by SanderDevisscher** [comment]
Same issue occurs with "Hesbania"

**Comment by SanderDevisscher** [comment]
While "De zwarte beek" is ok

**Comment by mvarewyck** [comment]
'Jachtterrein aangesloten' was missing for these regions in 2022. Now the code can handle this.
