### ISSUE TITLE
[BUG] WBE renamed => no longer selectable

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/reporting-rshiny-grofwildjacht#405]
**Describe the bug**
I've renamed WBE Zuid-Vlaamse Valleien Regio 1 (wbenr: 247 & kbonr: 455431529) into Hemelrijk but when I try to select it from the list (after login as admin) it is no longer available.  

**To Reproduce**
1. Go to 'private page as admin'
2. Click on 'list'
3. Scroll down to 'He'
4. See absence of Hemelrijk

**Expected behavior**
Hemelrijk should be available for selection.

**Additional context**
WBE_nr & kbonr remain unchanged. Zuid-Vlaamse Valleien Regio 1 is not available as well.

**Comment by mvarewyck** [comment]
@SanderDevisscher Did you check in docker with the `kbo = 'admin'` argument explicitly?
It looks like 'Hemelrijk' is in the list then for me.

If you don't use the argument, there is a default subset of KBO's shown in the list which doesn't contain 'Hemelrijk'.

```
docker run -p 3001:3838 -it inbo/grofwild R -e "Sys.setenv('AWS_DEFAULT_REGION'='eu-west-1','AWS_ACCESS_KEY_ID'='XXX,'AWS_SECRET_ACCESS_KEY'='XXX'); reportingGrofwild::runWildApp(public=FALSE, kbo ='admin')"
```

**Comment by SanderDevisscher** [comment]
What should be done to include 'Hemelrijk' in the default list ?

**Comment by mvarewyck** [comment]
> What should be done to include 'Hemelrijk' in the default list ?

Then I have to add its KBO to the list [here](https://github.com/inbo/reporting-rshiny-grofwildjacht/blob/master/reporting-grofwild/inst/ui/app_private/global.R#L75)
I can change the default to anything: Would you prefer to have the default to be 'admin'?

**Comment by SanderDevisscher** [comment]
I'll rebuild the app using the admin credentials

**Comment by SanderDevisscher** [comment]
Hemelrijk is displayed as it should
