### ISSUE TITLE
[BUG] code deploy fails for 4bebff97f0e84146e2a702b057bf671716df1fc8

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/reporting-rshiny-grofwildjacht#406]
**Describe the bug**
When the code is deployed using the hash `4bebff97f0e84146e2a702b057bf671716df1fc8` we get the following error:

![PastedGraphic-1](https://github.com/inbo/reporting-rshiny-grofwildjacht/assets/16779320/cbb6f3e8-d52e-4797-8ca9-d563617595d6)

While a deployment using `bcf3edf8472038fcdf4da7b4911522b4d3e2984a` succeeds. 

**Expected behavior**
Succesfull deployment

**Comment by SanderDevisscher** [comment]
@TheJenne18 aka Jens will be better placed to answer any questions ;-)

**Comment by TheJenne18** [comment]
Hi,

Thank you for the heads up. I've already rebuilt the image and it's coming through correctly now. We've launched the new tag on AWS as well. Thanks for your assistance.
