### ISSUE TITLE
Display commit hash somewhere on page

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/reporting-rshiny-grofwildjacht#407]
Currently we only display a version number but this is not dynamic and requires manual bumping. This makes troubleshooting more complex. Is there a way to automatically add the commit hash to the page ? This would enable more directed troubleshooting.

I leave the positioning to you.

Some code to get you started:
https://gist.github.com/bodhi/2c2152bb69dd2ef769002bf175a3d509

**Comment by mvarewyck** [comment]
I've updated the code for this.

To run locally, via R it should work directly. Via docker, you will need to set a docker build argument. I've updated the [README](https://github.com/inbo/reporting-rshiny-grofwildjacht/blob/update_august_2023/README.md#troubleshooting)
`sudo docker build --build-arg GIT_SHA=$(git rev-parse HEAD) -t inbo/grofwild .`

To make it work on your server, you will need to update the deploy scripts such that they pass the git commit hash to the `GIT_SHA` variable @berthuygens? If not, it will just show 'Niet beschikbaar'

**Comment by SanderDevisscher** [comment]
@mvarewyck ik vind de gekozen oplossing zeer elegant 👍 

Er loopt echter nog iets mis. 
Ik krijg bij de build command deze melding:
```
git : The term 'git' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:36
+ docker build --build-arg GIT_SHA=$(git rev-parse HEAD) -t inbo/grofwi ...
+                                    ~~~
    + CategoryInfo          : ObjectNotFound: (git:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

**Comment by SanderDevisscher** [comment]
Ik vermoed dat dit te maken heeft met een "foutieve" git installatie. Ik los het op!

**Comment by SanderDevisscher** [comment]
In R zelf werkt het ook niet

**Comment by mvarewyck** [comment]
> In R zelf werkt het ook niet

@SanderDevisscher `git` should be installed on the system to make this work - both in R and docker. 
You can check whether this is the case by running `git version` in the command line where the `docker build` command is run.
If not, see https://github.com/git-guides/install-git

**Comment by SanderDevisscher** [comment]
I works now! also nice to see the hash is a url 😎👍

**Comment by TheJenne18** [comment]
Hi, We've just build the image with the above command and the build was successful.

**Comment by SanderDevisscher** [comment]
@TheJenne18 is it currently running at the UAT ?

**Comment by TheJenne18** [comment]
@SanderDevisscher you first have to update this docker build command: https://github.com/inbo/reporting-rshiny-grofwildjacht/blob/master/scripts/reporting-rshiny-grofwildjacht.sh

**Comment by SanderDevisscher** [comment]
@mvarewyck can you look into updating the build command ? 
@TheJenne18 correct but I would still expect a version bump to v0.2.9 or am I overlooking something ?

**Comment by TheJenne18** [comment]
I thought I had to wait until the build command was updated. We just deployed the v0.2.9 version in uat.

**Comment by SanderDevisscher** [comment]
This is a case of miscommunication ! I thought you had already build the hash of v0.2.9 and thus I expected the version bump. 
But since you had not yet built v0.2.9. we could have (maybe even should have) waited on the change to the build command.

**Comment by SanderDevisscher** [comment]
@TheJenne18 & @mvarewyck any progress ?

**Comment by mvarewyck** [comment]
> @mvarewyck can you look into updating the build command ?

Build command is updated and tested docker image -> all OK

**Comment by RuttenAnneleen** [comment]
Werkt niet bij mij met dezelfde code als Sander

**Comment by mvarewyck** [comment]
> Werkt niet bij mij met dezelfde code als Sander

Krijg je de app te zien, maar dan zonder de hash link?

@RuttenAnneleen Gebruik je [dit build command](https://github.com/inbo/reporting-rshiny-grofwildjacht/blob/master/scripts/reporting-rshiny-grofwildjacht.sh#L5)?

Wat krijg je als je in de terminal, waar je de build doet, hetvolgende opvraagt: `git rev-parse HEAD`

**Comment by RuttenAnneleen** [comment]
> > Werkt niet bij mij met dezelfde code als Sander
> 
> Krijg je de app te zien, maar dan zonder de hash link?
> 
> @RuttenAnneleen Gebruik je [dit build command](https://github.com/inbo/reporting-rshiny-grofwildjacht/blob/master/scripts/reporting-rshiny-grofwildjacht.sh#L5)?
> 
> Wat krijg je als je in de terminal, waar je de build doet, hetvolgende opvraagt: `git rev-parse HEAD`

In de app krijg ik: GIT: Niet beschikbaar

en in de terminal krijg ik: /bin/sh: 1: git: not found

**Comment by mvarewyck** [comment]
> > > Werkt niet bij mij met dezelfde code als Sander
> > 
> > 
> > Krijg je de app te zien, maar dan zonder de hash link?
> > @RuttenAnneleen Gebruik je [dit build command](https://github.com/inbo/reporting-rshiny-grofwildjacht/blob/master/scripts/reporting-rshiny-grofwildjacht.sh#L5)?
> > Wat krijg je als je in de terminal, waar je de build doet, hetvolgende opvraagt: `git rev-parse HEAD`
> 
> In de app krijg ik: GIT: Niet beschikbaar
> 
> en in de terminal krijg ik: /bin/sh: 1: git: not found

@RuttenAnneleen De installatie van git op je pc is niet correct. Sander had hetzelfde probleem [hier](https://github.com/inbo/reporting-rshiny-grofwildjacht/issues/407#issuecomment-1687635580)

**Comment by SanderDevisscher** [comment]
This has been fixed. I added some documentation to prevent a bad installation of git to be an issue in the future.
