### ISSUE TITLE
[BUG] warning in docker logs

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/reporting-rshiny-grofwildjacht#408]
**Describe the bug**
as reported by @TheJenne18 we get the following warning in the docker logs while running it on the UAT

```
Listening on http://0.0.0.0:3838/
Warning: Error in <Anonymous>: error in evaluating the argument 'i' in selecting a method for function '[': 
  120: <Anonymous>
```

**To Reproduce**
@TheJenne18 can you complete ?

**Expected behavior**
No warning

**Comment by TheJenne18** [comment]
When tailing the docker log with `docker logs -f <container_id>` you can see this the described log entry

**Comment by mvarewyck** [comment]
@TheJenne18 Thanks for reporting. I've noticed the warning locally too. It's rather cryptic and I don't know directly where it comes from. Therefore I ignored it for now as it doesn't affect functioning of the app.

**Comment by SanderDevisscher** [comment]
@TheJenne18 @mvarewyck still relevant ?
