### ISSUE TITLE
Add 'Info' link to the apps

### ISSUE THREAD

**Issue by mvarewyck** [inbo/reporting-rshiny-grofwildjacht#409]
### Position: 

right top of the webpage, next to the 'Contact' link. Should be available on both the public and private page.

### Description/Disclaimer: 

link to Rmd file that will be provided by INBO. The rmd file needs to be rendered to pdf. Rmd file contains extra info on abbreviations etc.

**Comment by SanderDevisscher** [comment]
@mvarewyck we're looking into getting some funds for next year to make our website more appealing. 

How much do think we need to secure to implement the following:

1. add new landing page with buttons to go to the current tabs and some explanation about them.
2. add tooltips if possible 
3. implement logic described in this issue but as new tab 
4. some textual changes (mainly write how to)

**Comment by mvarewyck** [comment]
> @mvarewyck we're looking into getting some funds for next year to make our website more appealing.
> 
> How much do think we need secure to have openanalytics implement the following:
> 
> 1. add new landing page with buttons to go to the current tabs and some explanation about them.
> 2. add tooltips if possible
I would suggest to do this together (INBO and OA) one day of live coding in Brussels. For each label you want we can add an identifier and label in a csv file like we currently do for the explanations (uiText.csv)
> 3. implement logic described in this issue but as new tab
If you provide an Rmd this can be rather straightforward. Much more work if you want to include direct links to plots/tables in the app.
> 4. some textual changes (mainly write how to)

@SanderDevisscher hard to estimate. I would count between 5 and 10 working days.

**Comment by SanderDevisscher** [comment]
zie #454
