### ISSUE TITLE
FIGUUR: Gewicht per jaar

### ISSUE THREAD

**Issue by ThomasScheppers** [inbo/reporting-rshiny-grofwildjacht#41]
1) 'smoother' vervangen door 'Gemiddelde'
2) aantal aangeven per jaar
3) Y-as vast zetten op nul? Te nauwe waarden Y-as...

**Comment by mvarewyck** [comment]
OK, all fixed by implementing changes for #40

**Comment by ThomasScheppers** [comment]
OK
