### ISSUE TITLE
de afschotaantallen verschijnen niet als men kiest voor een ANB domein[BUG]

### ISSUE THREAD

**Issue by jimcasaer** [inbo/reporting-rshiny-grofwildjacht#416]
De figuur voor het afschot kan logischerwijze niet aangemaakt worden per 100 ha of per 100ha bos gezien de grenzen van de terreinen niet gekend zijn -- het absoluut afschot zou echter wel moeten verschijnen 

- [x] korte termijn : absolute cijfers laten verschijnen op de "wbe pagina"
- [ ] middenlange termijn : werkwijze uitwerken om jachtvelden mee in te brengen zodat ook per 100 ha en 100 ha natuur en bos gevisualiseerd kan worden (backoffice issue [#1021](https://github.com/inbo/backoffice-wild-analyse/issues/1021))

**Comment by SanderDevisscher** [comment]
dit is ook van toepassing voor de [KAART: Gerapporteerde afschotlocaties](https://wbe.inbo.be/app_direct_i/wildapp/_/#). Hier mogen de afschotlocaties op de kaart weergegeven worden zonder wbe grenzen.

**Comment by mvarewyck** [comment]
![Screenshot from 2023-09-29 10-41-18](https://github.com/inbo/reporting-rshiny-grofwildjacht/assets/22143743/ac152a3b-8e93-485e-95a5-f514a3761c59)

**Comment by SanderDevisscher** [comment]
Issue remains with 0d25a18b4a7c872f77ef6b995a85ee517dc528b6 however a incorrect graph is shown now: 

![image](https://github.com/inbo/reporting-rshiny-grofwildjacht/assets/16779320/0df80b39-ed38-4c5e-9171-d6b554f73b1b)

somewhat expected no graph since no changes were implemented

**Comment by mvarewyck** [comment]
@SanderDevisscher I know why the plot is not displayed: PartijNummer is missing for ANB regions. 
Within the function we only retain data with a known 'PartijNummer' which is used for matching to the biotoop data later.

How do you plan to add the biotoop info for ANB regions in the future? Currently biotoop data for WBE regions contain as region identifier 'PartijNummer'. If I know how it will be done for ANB, I will be able to implement a more future-proof fix such that relative percentages will also be displayed correctly.

**Comment by SanderDevisscher** [comment]
> @SanderDevisscher I know why the plot is not displayed: PartijNummer is missing for ANB regions. Within the function we only retain data with a known 'PartijNummer' which is used for matching to the biotoop data later.
> 
> How do you plan to add the biotoop info for ANB regions in the future? Currently biotoop data for WBE regions contain as region identifier 'PartijNummer'. If I know how it will be done for ANB, I will be able to implement a more future-proof fix such that relative percentages will also be displayed correctly.

@mvarewyck there is an intention to add something like a partijnummer<sup>1</sup> for the onafhankelijke jachtrechthouders (like ANB). However this is something for the "far" future rather than the "near" future. This issue is actually about the absolute number of animals shot (unit == aantal).  In these cases no biotoop data is provided yet. 

<sup>1</sup>currently the onafhankelijke jachtrechthouders (like ANB) and their afschot allready have a kbonumber (starting with 3). Is it preferable to add a partijnummer ? and add this partijnummer to the wbe_binnengrenzen files ? and add them to kbo_wbe ?

**Comment by SanderDevisscher** [comment]
perfect

**Comment by mvarewyck** [comment]
> * For now I have assigned the KBO number as PartijNummer for the ANB regions

Extended to all regions starting with either `"ANB_|Afwijking Jachtdecreet_|Bestrijding_|OJ_"`
