### ISSUE TITLE
FIGUUR: Gerapporteerd aantal embryo's voor vrouwelijke reeën per jaar

### ISSUE THREAD

**Issue by ThomasScheppers** [inbo/reporting-rshiny-grofwildjacht#42]
1) 0 embryo's verschijnt en verdwijnt in de legende ifv de jaren
2) aantal per jaar weergeven
3) @jimcasaer @Fhuysent : volgens mij moet dit procentueel bekeken worden en niet in aantallen. Ofwel een combinatie zoals in de publicatie -> nakijken!

**Comment by Fhuysent** [comment]
Change back to bar graph with percentual values (check publication).

**Comment by mvarewyck** [comment]
1-3: OK

**Comment by ThomasScheppers** [comment]
something goes wrong:
![image](https://user-images.githubusercontent.com/24563808/33769324-0357928c-dc2a-11e7-9a8f-4271875363d7.png)

**Comment by mvarewyck** [comment]
Should be fixed by installing latest shiny R-package, see #31

**Comment by SanderDevisscher** [comment]
@Fhuysent will check
