### ISSUE TITLE
[BUG] st_drop_geometry only works with objects of class sf

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/reporting-rshiny-grofwildjacht#424]
**Describe the bug**
When you expand the slider at Evolutie gerapporteerd afschot to include 2023 on the wbe page I get this error:
`st_drop_geometry only works with objects of class sf`. 

The error does not occur on the PRD. It does occur when docker building 1038bd0 
issue is present in multiple wbe's & species

_Originally posted by @SanderDevisscher in https://github.com/inbo/reporting-rshiny-grofwildjacht/issues/421#issuecomment-1759647735_

**To Reproduce**
1. sync 1038bd0 
2. build docker
3. run docker
4. log into wbe page
5. change "Evolutie gerapporteerd afschot" - periode slider
6. see error

**Expected behavior**
Graph is displayed with a 0 when missing

**Screenshots**
IS:
![image](https://github.com/inbo/reporting-rshiny-grofwildjacht/assets/16779320/c458af52-b052-4871-8ccf-810c88a1b8b8)

Should be:
![image](https://github.com/inbo/reporting-rshiny-grofwildjacht/assets/16779320/44db9799-142f-4aa1-9c0d-43625befffd3)

**Additional context**
might be related but when I switch the landkaart slider to 2023 it crashes.

_Originally posted by @SanderDevisscher in https://github.com/inbo/reporting-rshiny-grofwildjacht/issues/421#issuecomment-1759664120_

**Comment by mvarewyck** [comment]
I'm on it. 
Via docker I can reproduce your bug, but locally it works fine.
R package `sf` has local version `1.0.13` while in docker `0.9.8`

**Comment by mvarewyck** [comment]
@SanderDevisscher Should be fixed now.
