### ISSUE TITLE
[BUG] timeout when filtering schade by source

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/reporting-rshiny-grofwildjacht#426]
**Describe the bug**
Filtering by source results in a timeout

**To Reproduce**
1. Go to 'faunabeheer.inbo.be'
2. Click on 'wildschade'
3. select 'verwilderde kat' & all types of damage
4. Scroll down to 'Landkaart 1'
5. select a source
6. See error

**Expected behavior**
Map get filtered by source 

**Additional context**
Issue occurs on PRD and 96c9494eba79821d4afd515295af971559799820
I have not checked whether the issue occurs at other graphs/maps.

**Comment by mvarewyck** [comment]
~> @SanderDevisscher Could you check what you did differently?~

I can reproduce the error in docker now (not in local R version)

**Comment by mvarewyck** [comment]
Docker runs with R 4.0.5, while locally I have 4.2.2

From [NEWS](https://cran.r-project.org/doc/manuals/r-devel/NEWS.html)
> mapply() and hence Map() now also obey the “max-or-0-if-any” recycling rule, such that, e.g., Map(`+`, 1:3, 1[0]) is valid 
now.

This explains the error in docker & I could fix it.
