### ISSUE TITLE
[BUG] timeout when running private app locally using docker

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/reporting-rshiny-grofwildjacht#432]
**Describe the bug**
The private part of the app times out when you run it in docker. 

**To Reproduce**
Build app locally using docker.
Run app using docker.
See error

docker log:
```
Warning: Error in [[<-.data.frame: replacement has 1 row, data has 0
  77: stop
  76: [[<-.data.frame
  71: $<-.sf
  69: mapFlanders
  68: <reactive>
  52: spacePlot
  45: <observer>
   2: runApp
   1: reportingGrofwild::runWildApp
Warning: Error in [[<-.data.frame: replacement has 1 row, data has 0
  100: <Anonymous>
```

**Expected behavior**
App starts without timeout

**Additional context**
Possibly related to #429 
issue occurs also when @RuttenAnneleen builds the app.

**Git SHA (after 0.3.1)**
https://github.com/inbo/reporting-rshiny-grofwildjacht/commit/cdfb47e297d2ce6a2b877441b578f164f1cbd5df

**Comment by mvarewyck** [comment]
@SanderDevisscher I'm building the docker image to reproduce.

**Comment by mvarewyck** [comment]
I found the problem, it's a border case where we have only 'niet-aangesloten' WBE areas for 2022 and 'Langs de Hoge Kale' (maybe also for other regions/years, but this is the default setting for admin users). I'll create a branch from master and do a pull request.
