### ISSUE TITLE
[Feature] Tabel kencijfers

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/reporting-rshiny-grofwildjacht#438]
# Suggested Title
Tabel kencijfers

## INFO:
ANB asked us to add the following information in table form (1 row per item):
- **Totaal aantal gemeenten:** Number of communes with reported observations<sup>1</sup> above the threshold<sup>2</sup> for the selected year.
- **Dezelfde gemeentes:** Number of communes with reported observations<sup>1</sup> above the threshold<sup>2</sup> for the selected year and the previous year followed by a list of the communes. 
- **Nieuwe gemeentes:** Number of communes with reported observations<sup>1</sup> above the threshold<sup>2</sup> for the selected year and below the threshold for the previous year followed by a list of the communes.
- **Niet meer in deze gemeentes:** Number of communes with reported observations<sup>1</sup> below the threshold<sup>2</sup> for the selected year and above the threshold for the previous year followed by a list of the communes.

<sup>1</sup> both afschot & observations 
<sup>2</sup> I suggest we add a threshold slider for observations allowing the user to decide how much weight they give to the observations. Default 1? min: 1 -> max: 10 ?
### Position
- Dashboard > populatie > Tabel kencijfers (levels province\flanders)
### Description/Disclaimer
- To discuss
### Datacolumns
- afschotjaar/jaar
- provincie
- ID/id
- wildsoort/naam_nl
- gemeente_afschot_locatie/gemeente
### Filters
- Jaar
- Bron (afschot/waarnemingen) 
- Waarnemingen drempel (verdwijnt als `!"waarnemingen" %in% Bron`)
### Code example
```
```
### Layout example
<div class="tg-wrap"><table><thead><tr><th>Totaal aantal gemeenten</th><th colspan="2">31</th></tr></thead><tbody><tr><td rowspan="3">Dezelfde gemeentes</td><td rowspan="3">29</td><td>As</td></tr><tr><td>Beringen</td></tr><tr><td>...</td></tr><tr><td rowspan="2">Nieuwe gemeentes</td><td rowspan="2">2</td><td>Alken</td></tr><tr><td>Borgloon</td></tr><tr><td>Niet meer in deze gemeentes</td><td>1</td><td>Tongeren</td></tr></tbody></table></div>

*dummy data
### Additional Options
- Download data
- ...

Some related questions:
@mvarewyck how much time would you need to add this table ? 
@mvarewyck is it possible to add this this year or at the latest early next year ?
@mvarewyck what is your current day cost ? I need this info to because ANB indicated they are willing to pay for additional features.

@jimcasaer @RuttenAnneleen @LynnPallemaerts can you help me with good descriptions ? 
Do you have any additional suggestions/remarks ?

**Comment by mvarewyck** [comment]
> Some related questions:
> @mvarewyck how much time would you need to add this table ?
3 days
> @mvarewyck is it possible to add this this year or at the latest early next year ?
Yes we can.
> @mvarewyck what is your current day cost ? I need this info to because ANB indicated they are willing to pay for additional features.
Tobias will contact you about this.

**Comment by mvarewyck** [comment]
> Some related questions:
> @mvarewyck how much time would you need to add this table ?

3 days

> @mvarewyck is it possible to add this this year or at the latest early next year ?

Yes we can.

> @mvarewyck what is your current day cost ? I need this info to because ANB indicated they are willing to pay for additional features.

Tobias will contact you about this (PM).

**Comment by SanderDevisscher** [comment]
I'll for finances from ANB for extra table

**Comment by Yingjie-ZhangOA** [comment]
![Screenshot 2023-12-05 at 10 35 30](https://github.com/inbo/reporting-rshiny-grofwildjacht/assets/50108790/17538080-422a-47dd-9abf-f4b390491024)
![Screenshot 2023-12-05 at 10 34 53](https://github.com/inbo/reporting-rshiny-grofwildjacht/assets/50108790/42c6ad5b-4c3a-4f41-b5e8-716f33ecf2c1)

**Comment by Yingjie-ZhangOA** [comment]
In branch _feature#438_ the following features are implemented

* Slider input for both data source "waarnemingen" and "afschot",  data is filtered `>=` threshold
  * for  "waarnemingen", slider range is fixed at 1 to 10
  * for  "afschot", slide range is 1 to `max(10, maximum of the afschot aantal)`.  This is pure cosmetic, as in the current data, the "afschot aantal" is always 1.
<img width="813" alt="Screenshot 2023-12-07 at 09 43 24" src="https://github.com/inbo/reporting-rshiny-grofwildjacht/assets/50108790/ca5afda9-9ddc-4402-a2f0-bf986092506a">

* If a municipality in the table exclusively from data source "waarnemingen", it gets a green background (color picked from inbo theme)

<img width="844" alt="Screenshot 2023-12-07 at 09 44 37" src="https://github.com/inbo/reporting-rshiny-grofwildjacht/assets/50108790/0176e043-5e0b-47e3-885c-d52b754f894a">

* The downloaded data now contains also the count for "waarnemingen" and "afschot" if available 
<img width="532" alt="Screenshot 2023-12-07 at 10 35 57" src="https://github.com/inbo/reporting-rshiny-grofwildjacht/assets/50108790/085d32e8-3bd7-49f2-bc39-2aa3c755b0b3">

* In the report, the table is present the same way as in the application 

- [ ] add detailed explanation of the table in "uiText.csv" (row: plotFunction "F18_8", column: "dash") @SanderDevisscher

**Comment by Yingjie-ZhangOA** [comment]
I don't have the data prior to process @mvarewyck can you double check this?

```
> unique(geoData[geoData$dataSource == "afschot", "aantal"])
1
```

**Comment by SanderDevisscher** [comment]
One tiny remark, we should be consequent with gemeentes & gemeenten both are viable but it should be on or the other. I would opt for gemeentes meaning "Totaal aantal gemeente**n**" should become "Totaal aantal gemeente**s**"

**Comment by Yingjie-ZhangOA** [comment]
> One tiny remark, we should be consequent with gemeentes & gemeenten both are viable but it should be on or the other. I would opt for gemeentes, meaning "Totaal aantal gemeente**n**" should become "Totaal aantal gemeente**s**"

Ok, I thought the same while making the table,

**Comment by mvarewyck** [comment]
> I don't have the data prior to process @mvarewyck can you double check this?
> 
> ```
> > unique(geoData[geoData$dataSource == "afschot", "aantal"])
> 1
> ```

It is correct that for geoData the `aantal` is always 1, as each row represents a single record in the data (
><waarnemingen). So, for the kencijfers table, we should now first calculate the total per region level of interest (i.e. calculating the sum of 'aantal' for each province/municipality selected). 

Note: Previously this was no problem, as there was no threshold, so the actual 'afschot aantal' did not matter.

**Comment by Yingjie-ZhangOA** [comment]
> > I don't have the data prior to process @mvarewyck can you double check this?
> > ```
> > > unique(geoData[geoData$dataSource == "afschot", "aantal"])
> > 1
> > ```
> 
> It is correct that for geoData the `aantal` is always 1, as each row represents a single record in the data ( in contrast to waarnemingen). So, for the kencijfers table, we should now first calculate the total per region level of interest (i.e. calculating the sum of 'aantal' for each province/municipality selected).
> 
> Note: Previously this was no problem, as there was no threshold, so the actual 'afschot aantal' did not matter.

I see, thanks for spotting, I'll adapt the code.
