### ISSUE TITLE
Aanmaak nieuwe figuur trend % gerealiseerd afschot

### ISSUE THREAD

**Issue by Fhuysent** [inbo/reporting-rshiny-grofwildjacht#44]

**Comment by stijnvanhoey** [comment]
Enkel voor ree,
keuze-opties 
* regioschaal, 
* keuze voor types (geit, kit, bok of combi) 
* range van de jaren om naar te kijken

figuur:
x: year, y is gerealiseerd

**Comment by mvarewyck** [comment]
This figure is now available. Could you check whether it looks like expected?

**Comment by SanderDevisscher** [comment]
@Fhuysent & @jimcasaer will check figure

**Comment by Fhuysent** [comment]
Figuur ziet er goed uit, gegevens 2016/2017 ontbreken nog voor berekening realisatie maar staat los van deze figuur.
