### ISSUE TITLE
[BUG] timeout when selecting "omvang van de schade" @dashboard 

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/reporting-rshiny-grofwildjacht#443]
**Describe the bug**
When selecting "omvang van de schade" at the dashboard page I get a timeout. 

**To Reproduce**
1. Go to 'faunabeheer.inbo.be'
2. Click on 'dashboard'
3. Select 'Gemeente == Ravels'
4. Select 'Omvang van de schade *'
5. See error

**Expected behavior**
Dashboard page loads without timeout

**Additional context**
If you select a province first & then switch to commune the issue does not occur.

**Comment by mvarewyck** [comment]
I can't reproduce with git commit 70dc96dee7a8796b1aedf440fed3066b1c6102dd
@SanderDevisscher Please re-open this issue if still occurs
