### ISSUE TITLE
datasource for mapFlanders()

### ISSUE THREAD

**Issue by mvarewyck** [inbo/reporting-rshiny-grofwildjacht#449]
> For the dashboard page, selecting no source for the map in "huidige waarnemingen" results in a timeout. 

See _Originally posted by @SanderDevisscher in https://github.com/inbo/reporting-rshiny-grofwildjacht/pull/440#pullrequestreview-1836805252_
 
Updating the code for mapFlanders() also affects the map for schade page.     
@SanderDevisscher What should be done with the source `Hist_PZ_CARMA`? Should this be added to the choice list, ifso please provide a label.

```
> table(rawData$dataSource)

      E_Loket Hist_PZ_CARMA    HVV_Wilder    Natuurpunt 
         6331          2332          1034          3227 
```

Currently, we allow the user to choose for
```
> sourcesSchade
$`Dieren onder de wielen (NP)`
[1] "Natuurpunt"

$`Wilder (LJV)`
[1] "HVV_Wilder"

$`E-loket (ANB)`
[1] "E_Loket"
```

**Comment by SanderDevisscher** [comment]
'Hist_PZ_CARMA' en eventuele andere hist bronnen die in de toekomst zullen voorkomen mogen het label 'andere' krijgen miz. 

@LynnPallemaerts @RuttenAnneleen jullie mening ?

**Comment by RuttenAnneleen** [comment]
> 'Hist_PZ_CARMA' en eventuele andere hist bronnen die in de toekomst zullen voorkomen mogen het label 'andere' krijgen miz.
> 
> @LynnPallemaerts @RuttenAnneleen jullie mening ?

Akkoord met een label 'andere'!
Misschien dan in de toekomst wel ergens uitleggen wat mogelijke andere bronnen zijn
