### ISSUE TITLE
Translate index.html to RShiny tags

### ISSUE THREAD

**Issue by mvarewyck** [inbo/reporting-rshiny-grofwildjacht#45]
Update UI with suggestions by @peterdesmet

**Comment by mvarewyck** [comment]
Currently, I still use fluid container instead of fixed to use optimal page width for showing images.
However, we can also adapt this to fixed if you would like us to.

**Comment by peterdesmet** [comment]
Cool! Bit difficult to assess how it looks from the code, but I trust it looks OK. @stijnvanhoey can you redeploy the app?

**Comment by stijnvanhoey** [comment]
done!

**Comment by peterdesmet** [comment]
@mvarewyck just tested it: I prefer the the fixed container. 😁 It looks about the same on smaller screens and better on larger screens. Tried to see where I can update it myself, but not sure if I should update `fluidPage, `fluidRow` or both, so better if you do it.

**Comment by mvarewyck** [comment]
Ok, I now use `bootstrapPage()` and `fixedRow()` instead of `fluidPage()` [More info](http://shiny.rstudio.com/articles/layout-guide.html)
