### ISSUE TITLE
[BUG] admin login loads 3 wbe's instead of all

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/reporting-rshiny-grofwildjacht#450]
**Describe the bug**
When I log into wbe-dev.inbo.be as admin (wbe_admin according to keycloak) I can only see 3 wbe's (In flanders fiels, westhoek & westland)

**To Reproduce**
1. Go to 'wbe-dev.inbo.be'
2. Login as admin

**Expected behavior**
Get a list of all wbe's available as admin 

**Screenshots**
Currently deployed on UAT ([9286fea381ec714508f803bfc22d0806bbe02f54](https://github.com/inbo/reporting-rshiny-grofwildjacht/commit/9286fea381ec714508f803bfc22d0806bbe02f54)):
![image](https://github.com/inbo/reporting-rshiny-grofwildjacht/assets/16779320/04ad3f4e-7ffa-4498-99e3-fdb792020ef0)

Expected (as on PRD):
![image](https://github.com/inbo/reporting-rshiny-grofwildjacht/assets/16779320/a25c3fdf-98b7-4e11-ae12-b0117247ca6d)

On docker ([0d25a18b4a7c872f77ef6b995a85ee517dc528b6](https://github.com/inbo/reporting-rshiny-grofwildjacht/commit/0d25a18b4a7c872f77ef6b995a85ee517dc528b6)) => maybe fixed by deploying to UAT ???

![image](https://github.com/inbo/reporting-rshiny-grofwildjacht/assets/16779320/4d52e47e-13f5-46ff-a744-d8aa0f21319c)

**Comment by SanderDevisscher** [comment]
@LynnPallemaerts @jimcasaer can you guys confirm having the same issue when login into wbe-dev.inbo.be ?

**Comment by SanderDevisscher** [comment]
@LynnPallemaerts, @jimcasaer & @gertvanspaendonk all get a timeout after login into their admin account. While I get access to the mentioned wbe's.

**Comment by SanderDevisscher** [comment]
Login as superuser or Regio Lier works without a hitch

**Comment by SanderDevisscher** [comment]
running the app in docker as Sys.setenv(SHINYPROXY_USERGROUPS = 'wbe_admin') or kbo = 'admin' using 0d25a18b4a7c872f77ef6b995a85ee517dc528b6 work like a charm as well.

**Comment by mvarewyck** [comment]
> @mvarewyck what string/info does the app expect in case of an admin user ?

The app expects ENV variable "SHINYPROXY_USERGROUPS" equal to "WBE_ADMIN". This should be configured as such in the shinyproxy yaml file.

When running the app locally/via docker, it doesn't get info from shinyproxy. Then you can either: 
* Set `Sys.setenv(SHINYPROXY_USERGROUPS = 'WBE_ADMIN')` before starting the app
* Start the app via `runWildApp(public = FALSE, kbo = 'admin')`
