### ISSUE TITLE
[BUG] Shinapp.js throws error

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/reporting-rshiny-grofwildjacht#464]
**Describe the bug**
When starting the app on PRD while viewing it using devtools I see the following error:
![image](https://github.com/inbo/reporting-rshiny-grofwildjacht/assets/16779320/14e89aa7-cfcb-4cf0-b0ef-c159678a983f)

it refers to this line of code in shinyapp.js: 

```
      if (!/\/$/.test(defaultPath))
        defaultPath += '/';
      defaultPath += 'websocket/';

      var ws = new WebSocket(protocol + '//' + window.location.host + defaultPath);
      ws.binaryType = 'arraybuffer';

      return ws;
    };
```

**To Reproduce**
1. Go to 'faunabeheer.inbo.be'
2. Click on 'F12'
3. Click on 'Network'
4. Wait
5. See error

**Expected behavior**
App loads without errors nor timeouts 

**Screenshots**
![image](https://github.com/inbo/reporting-rshiny-grofwildjacht/assets/16779320/e55ca285-0d43-4b86-ae94-3c1dd9f326ad)

**Additional context**
Deployment on UAT and PRD with the same hash works just fine when the internet connection is not throttled. Whenever the connection gets throttled ea 'fast 3G' the error occurs.
If needed, because of issues with shinyproxy, please include Tobia!

Please give me a signal when you did your investigations so I can ask to revert to the previous hash.

**Git SHA (after 0.3.1)**
253e3d65227d4da71cb306553e5c2eb126dbf1d0

**Comment by SanderDevisscher** [comment]
Googling the issue led me to this https://github.com/openanalytics/shinyproxy/issues/222 🤔

**Comment by mvarewyck** [comment]
@SanderDevisscher I can reproduce locally but only when inspecting (F12) the Network. Do you know whether this issue was also present in earlier versions of the app?

**Comment by LEDfan** [comment]
Hi Sander

When did this problem start occurring? E.g. did you first notice this after an update of the app?

In any case, this could be an issue in ShinyProxy, when a (relatively) big amount of data is send over the websocket connection, e.g. when having a lot of plots. The good news is that this has been fixed in ShinyProxy in 12/2020, but it seems that you are running a version of ShinyProxy released in 2019. So it could be worth trying to update and hopefully this is issue is then fixed.

**Comment by LEDfan** [comment]
Okay, then I think it makes sense to try to update.
I created a PR here: https://github.com/inbo/shinyproxy/pull/4 , this just a small upgrade, so not using the latest ShinyProxy release.
But since I don't have access to AWS or really know how this deployment works, I cannot test or deploy the change. Let me know if you run into issues.

**Comment by TheJenne18** [comment]
For uat we use the following repo's where we use other shintyproxy versions:
[https://github.com/inbo/shinyproxy-wbe/blob/uat/install_shinyproxy.sh#L14](https://github.com/inbo/shinyproxy-wbe/blob/uat/install_shinyproxy.sh#L14)
[https://github.com/inbo/shinyproxyV3/blob/main/install_shinyproxy.sh#L13](https://github.com/inbo/shinyproxyV3/blob/main/install_shinyproxy.sh#L13)

**Comment by SanderDevisscher** [comment]
@LEDfan can you check if the error also exists in these versions ? ifso can you fix it ?

**Comment by SanderDevisscher** [comment]
@TheJenne18 do we use the same shinyproxies for the PRD ?

**Comment by SanderDevisscher** [comment]
faunabeheer-dev.inbo.be

**Comment by SanderDevisscher** [comment]
@LEDfan I'm currently also unable recreate the initial issue. However I'm experiencing a timeout on both UAT & PRD when using any throttle (fast 3G and slower). @mvarewyck initial loading goes fast and then it stalls on the first map & related graphs.

I do get these errors when loading faunabeheer.inbo.be using fast 3G throttle: 
![image](https://github.com/inbo/reporting-rshiny-grofwildjacht/assets/16779320/51871dc1-d7ec-4398-a3db-8d511eff743a)

When loading faunabeheer-dev.inbo.be using fast 3G throttle I get: 
![image](https://github.com/inbo/reporting-rshiny-grofwildjacht/assets/16779320/127967e2-dcb7-4833-aacc-622acf64ab9f)

both errors take a while to manifest.

**Comment by SanderDevisscher** [comment]
hmm something strange is going on, 10min ago I was unable to recreate the issue. Now 20h43 after running it on my private account I get the error all the time on both private and work accounts. Clearing the cookies seems to fix the issue for a while.

**Comment by mvarewyck** [comment]
@TheJenne18 Could you send us the log files from the PRD server? Something seems to go wrong in R causing a timeout, but I can't guess what as it works on UAT.

**Comment by SanderDevisscher** [comment]
The initial issue is back on chrome and now for some reason even clearing the cookies doesn't help anymore.

**Comment by SanderDevisscher** [comment]
Op firefox krijg ik toch deze error : De verbinding met wss://faunabeheer.inbo.be/app_direct/wildapp/websocket/ werd onderbroken tijdens het laden van de pagina.
Er lijkt me effectief iets mis met de websocket.

**Comment by SanderDevisscher** [comment]
@TheJenne18 can you answer @mvarewyck ?

**Comment by SanderDevisscher** [comment]
> For me, the PRD website works in Firefox but not in Chrome. Could the Websocket error be [this issue](https://github.com/openanalytics/shinyproxy/issues/233)? Is PRD running a different version of Shinyproxy than UAT (that could help me to understand why it doesn't fail on UAT)

@TheJenne18 tells me currently UAT is running v3 while PRD is still running v2.3

**Comment by mvarewyck** [comment]
> > For me, the PRD website works in Firefox but not in Chrome. Could the Websocket error be [this issue](https://github.com/openanalytics/shinyproxy/issues/233)? Is PRD running a different version of Shinyproxy than UAT (that could help me to understand why it doesn't fail on UAT)
> 
> @TheJenne18 tells me currently UAT is running v3 while PRD is still running v2.3

This throttle issue was indeed fixed since [ShinyProxy 2.4.2](https://github.com/inbo/reporting-rshiny-grofwildjacht/issues/464#issuecomment-2145435882)

**Comment by SanderDevisscher** [comment]
@TheJenne18 is deploying shinyproxy 2.5.1. to PRD. Deploying to v3 is more complex.

**Comment by SanderDevisscher** [comment]
@mvarewyck @LEDfan when looking at the waterfall on firefox<sup>1</sup> I notice plotly-latest.min.js to be the largest time consumer (>1min)

<sup>1</sup>while loading v0.3.4. in PRD with shinyproxy v2.5.1 and

**Comment by mvarewyck** [comment]
To investigate: https://plotly-r.com/performance

**Comment by mvarewyck** [comment]
> @mvarewyck @LEDfan when looking at the waterfall on firefox1 I notice plotly-latest.min.js to be the largest time consumer (>1min). The app is also noticeably faster on firefox then chrome (where it still crashes when throttled).

I throttled the app on Chrome, but didn't result in a timeout. Wrt plotly-latest.min.js it is a file that is served from local server: clicking on the file we can see the source is localhost. 

![Screenshot from 2024-07-09 17-14-26](https://github.com/inbo/reporting-rshiny-grofwildjacht/assets/22143743/72b058fc-1ee0-430f-b03b-ede758cdef57)

* I tried the option `plotl_ly() %>% partial_bundle()` which has smaller js files but downloads it from CDN by default. I would need to find a hack which might only work locally and not on shinyproxy.
* I tried the option `toWebGL()` but that didn't improve time and memory usage.

@SanderDevisscher Do you think we should further investigate on this or wait for the [restructuring](https://github.com/inbo/reporting-rshiny-grofwildjacht/issues/454)

**Comment by SanderDevisscher** [comment]
@mvarewyck I got news the app now loads even with less favorable internet connections. So I would suggest waiting until after the restructure.
