### ISSUE TITLE
[BUG] createSpreadData throws an error

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/reporting-rshiny-grofwildjacht#466]
**Describe the bug**
When running the code below:
```
 createSpreadData(tempdir_spread, 
                   spatialData = spatialData)
```

i get the following error:

```
Error in `[.data.frame`(x@data, i, j, ..., drop = FALSE) : 
  undefined columns selected
```

**To Reproduce**
1. move [these files](https://github.com/inbo/reporting-rshiny-grofwildjacht/files/14788206/spreadData.zip) to a folder 
2. reference the chosen folder as `tempdir_spread <- %path to chosen folder%`
3. run:
```
s3load(object = "spatialData.RData",
         bucket = bucket)
```
4. run:  
```
createSpreadData(tempdir_spread, 
                   spatialData = spatialData)
```
5. see error

**Expected behavior**
Spreadmodel files are uploaded to UAT bucket without error.

**Comment by mvarewyck** [comment]
We moved away from `sp` into `sf` since https://github.com/inbo/reporting-rshiny-grofwildjacht/issues/287. 
The correct instructions now are
```
library(reportingGrofwild)
setupS3()   # or any other way to set credentials
readS3(file = "spatialData_sf.RData")
createSpreadData(tempdir_spread, spatialData = spatialData)
```

**Comment by SanderDevisscher** [comment]
fixed
