### ISSUE TITLE
[BUG] error in data check for wildschade

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/reporting-rshiny-grofwildjacht#472]
**Describe the bug**
when running `testS3()` we get the following error:

```
Error in testS3() : 
</br>Please check data in S3 bucket: inbo-wbe-uat-data </br>Following tests in tests/testData.R failed. Please fix in order of occurrence.</br> <h4>Test: Schade data & metadata </h4>Error message:</br> `schadeData` inherits from `'tbl_df'/'tbl'/'data.frame'` not `'character'`.</br>WildSchade_georef.csv </br> <h4>Test: Schade data & metadata </h4>
```
I think this is a relic of the transfer to parquet files. 
@mvarewyck can you confirm the data for the app is extracted from the wildschade parquet file ?  

**Expected behavior**
Only the warning is shown

**Comment by mvarewyck** [comment]
> @mvarewyck can you confirm the data for the app is extracted from the wildschade parquet file ?

Yes, [here](https://github.com/inbo/reporting-rshiny-grofwildjacht/blob/master/reporting-grofwild/R/data_load.R#L62)
The test was failing because after transforming the wildschade file to a parquet file we load the data as a data.frame rather than `sf` object
