### ISSUE TITLE
[BUG] Spreadmodel is not updated correctly on UAT

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/reporting-rshiny-grofwildjacht#475]
**Describe the bug**
I've updated & uploaded the spread model for wild boar but it seems to be unchanged (Jaar options %in% c(2023, 2024)) on UAT even after application restart and cookie removal.

**To Reproduce**
1. Go to 'faunabeheer-dev.inbo.be'
2. Click on 'dashboard'
3. Select a province or other region
4. Activate 'Toekomstig verspreidingsgebied'
5. Scroll down to 'FIGUUR: Toekomstig verspreidingsgebied'
6. See error

**Expected behavior**
The 'Jaar' dropdown should allow 2024 & 2025 as options.

**Screenshots**
![image](https://github.com/inbo/reporting-rshiny-grofwildjacht/assets/16779320/b5ecc978-7759-4aa6-a7cd-4dc18795c29d)

**Additional context**
nvt

**Git SHA (after 0.3.1)**
[d6d14c6037ed6b3462988acbc0e282f4b8f0ae0f](https://github.com/inbo/reporting-rshiny-grofwildjacht/commit/d6d14c6037ed6b3462988acbc0e282f4b8f0ae0f)

**Comment by mvarewyck** [comment]
@SanderDevisscher How did you update & upload the data?
The most file contains indeed data for year 2023, 2024 and the file was last modified in 2023.

```
>     readS3(file = "spreadData_sf.RData")
Loading required package: sp
> names(spreadData)
[1] "pixels_2023"         "pixels_2024"         "municipalities_2023"
[4] "municipalities_2024"
> tmpTable <- aws.s3::get_bucket_df(
+       bucket = config::get("bucket", file = system.file("config.yml", package = "reportingGrofwild")))
> tmpTable[grepl('spread', tmpTable$Key), ]
                    Key             LastModified
249    spreadData.RData 2023-09-20T04:37:48.000Z
250 spreadData_sf.RData 2023-10-18T08:57:48.000Z
                                  ETag    Size
249 "98c91ca79f446a85f0e26462d212c53e" 6659874
250 "aa3061998bafa7f76ba49e45072aad75" 6665027
                                                            Owner_ID
249 9708c73bf11e6dff17cd9156c7529130529451488100ed3b2321c0b67cab98da
250 9708c73bf11e6dff17cd9156c7529130529451488100ed3b2321c0b67cab98da
      Owner_DisplayName StorageClass            Bucket
249 vo-aws-226308051916     STANDARD inbo-wbe-uat-data
250 vo-aws-226308051916     STANDARD inbo-wbe-uat-data
```

**Comment by SanderDevisscher** [comment]
@mvarewyck I use the following code:

```
# Get spatialData.Rdata from bucket
  readS3(file = "spatialData_sf.RData")
  
# Package files in temp directory & place them on the UAT Bucket
  createSpreadData(tempdir_spread, 
                   spatialData = spatialData)
  
```

**Comment by SanderDevisscher** [comment]
This is the content of tempdir_spread:

![image](https://github.com/inbo/reporting-rshiny-grofwildjacht/assets/16779320/3450bee5-9a2a-4782-af2e-c17afb6e845c)

[spreadData.zip](https://github.com/user-attachments/files/15608257/spreadData.zip)
