### ISSUE TITLE
FIGUUR: Leeftijdscategorie op basis van onderkaak & meldingsformulieren &  FIGUUR: Afschot per jaar en per leeftijdscategorie (o.b.v. onderkaak)

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/reporting-rshiny-grofwildjacht#59]
Hoe kan het dat het totaal aantal ingezamelde onderkaken verschilt tussen de grafieken ? 
Dit probleem komt zowel voor in de app als lokaal met de nieuwe data. 
Als dit te verklaren is, kan ik het negeren anders moeten we zoeken naar het probleem en een oplossing vinden. 

Beeld zoals in de app ATM:

![image](https://user-images.githubusercontent.com/16779320/43954264-1f28d880-9c9c-11e8-839b-43e5d542609d.png)

![image](https://user-images.githubusercontent.com/16779320/43954283-343f0bea-9c9c-11e8-8e47-30045dd023cd.png)

**Comment by jimcasaer** [comment]
is dit enkel voor ree of ook voor everzwijn 
de 20ste samen even bekijken want ik begrijp figuur 2 niet helemaal 

jim

**Comment by SanderDevisscher** [comment]
Conclusie van overleg 20ste, totalen zijn (zouden moeten zijn) berekend op basis van dezelfde data namelijk [rshiny_reporting_data_ecology.csv](https://github.com/inbo/reporting-rshiny-grofwildjacht/blob/Update_Source_Data/reporting-grofwild/inst/extdata/rshiny_reporting_data_ecology.csv) .

Vermoedelijk worden er in de code voor de grafieken subsets genomen die niet kloppen.
Ik zal eens kijken in de code van de grafiekjes of er iets mis berekend wordt !

**Comment by SanderDevisscher** [comment]
De doodsoorzaak subset lag aan de basis van dit probleem.

@jimcasaer moet het aandeel ingezamelde onderkaken ook hetzelfde zijn? of kan hier verschil op zitten ? bvb bij *"FIGUUR: Leeftijdscategorie op basis van onderkaak & meldingsformulieren"* enkel die onderkakden die een leeftijdscategorie hebben op meldingsformulier vs bij *"FIGUUR: Afschot per jaar en per leeftijdscategorie (o.b.v. onderkaak)"* enkel de die onderkaken met leeftijdscategorie onderkaak ?

**Comment by SanderDevisscher** [comment]
Te herbekijken na staging van JO
