### ISSUE TITLE
Clean GIS reference data sets

### ISSUE THREAD

**Issue by stijnvanhoey** [inbo/reporting-rshiny-grofwildjacht#6]
At the moment, we have following GIS data sets and information:

Tabular:
* `Fusiegemeenten_2006.csv`
* `gemeentecodes.csv`
* `deelgemeenten_GIS.csv`

@ThomasScheppers @Fhuysent do we need all of these data sets or can we clean up some of these? Certainly `Fusiegemeenten_2006.csv` seems just an extract of an existinf vector-gis-file?

Shapefiles:
* `communes.zip`
* `flanders.zip`
* `provinces.zip`

@mvarewyck, I would propose to use `geojson` as data format instead of shapefile unless there is a specific requirement. Neverhteless the increasing data format, this will render the data sets on Github directly and can be versioned as it is essentially a textfile instead of a binary format.

Conversion is straightforward using [gdal](http://www.gdal.org/) and should more or less look like, assuming WGS84 as your data projection):
```
ogr2ogr -f "GeoJSON"  -t_srs "EPSG:4326" -s_srs "EPSG:4326" "provinces.geojson" "provinces/Refprv.shp"
```
(see branch `gisdata`, e.g. https://github.com/inbo/reporting-rshiny-grofwildjacht/blob/gisdata/reporting-grofwild/inst/extdata/flanders.geojson)

Moreover, make sure to add the projection information (as part of the readme file in the [data readme](https://github.com/inbo/reporting-rshiny-grofwildjacht/blob/master/reporting-grofwild/inst/extdata/readme.md) file)

**Comment by mvarewyck** [comment]
For tabular data, currently I only need `gemeentecodes.csv` to match postcodes (in `rshiny_reporting_data_geography.csv`) with NIScodes in `communes.zip`. Matching on commune names resulted in many errors.

**Comment by mvarewyck** [comment]
Conversion to geojson was successful, see commit e89d3e2c572f24eda08938cb1ffc4f4175f43591
Is the description in readme clear enough?

**Comment by stijnvanhoey** [comment]
Nice work and clear to me. As I understand well, the branch [gisdata](https://github.com/inbo/reporting-rshiny-grofwildjacht/tree/gisdata) is not required anymore as the GIS-data is updated by the commit itself. I'll close the issue here and remove the `gisdata`-branch.
