### ISSUE TITLE
Wat met geschoten dieren zonder provincie? 

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/reporting-rshiny-grofwildjacht#60]
Momenteel zitten er verschillen en onmogelijkheden op de verschillende totalen. 
als we bvb 2017 pakken dan zijn er voor heel Vlaanderen 5741 reeën geschoten volgens *TABEL: Gerapporteerd afschot per regio en per leeftijdscategorie*, 5730 reeën geschoten volgens *TABEL: Gerapporteerd afschot per regio en per type* en 5834 geschoten volgens *FIGUUR: Leeftijdscategorie op basis van onderkaak & meldingsformulieren*. 

Waarschijnlijk is subsetten van dieren zonder provincie het (of een deel van het) probleem. 
Voor de berekening van het totaal aantal ingezamelde onderkaken wordt hier geen rekening mee gehouden, voor de tabellen wel. 

Bij datamining van de brondata werden er in 2017 93 reeën teruggevonden zonder provincie. Als we er van uitgaan dat 5834 het maximum is dan klopt 5741 geschoten reeën (*TABEL: Gerapporteerd afschot per regio en per leeftijdscategorie*) wel. Een disclaimer toevoegen aan de figuur of de subset aanpassen lijkt me hier wel nuttig. 

Wat  **TABEL: Gerapporteerd afschot per regio en per type** betreft missen er nog steeds 11 reeën waarschijnlijk ligt een gebrek aan gegevens ivm het geslacht. Volgens  *TABEL: Gerapporteerd afschot per regio en per leeftijdscategorie* zijn er 7 reeën zonder bekend geslacht deze worden er in de *TABEL: Gerapporteerd afschot per regio en per type* uitgegooid (5741 - 7 = 5734). maar zelfs dan klopt het totaal niet en missen er nog steeds  4 reeën.  

Dus wat moet er nog gebeuren:
- [ ] Disclaimer toevoegen aan de Figuren met onderkaken of de subset van deze aanpassen of wachten op georef/staging om wonderbaarlijk alles op te lossen.
- [ ] Knoop hierboven doorhakken. 
- [ ] Zoeken waar de 4 reeën gebleven zijn

**Comment by mvarewyck** [comment]
Current status voor ree in 2017

- TABEL: Gerapporteerd afschot per regio en per leeftijdscategorie: 5776
- TABEL: Gerapporteerd afschot per regio en per type: 5776
- FIGUUR: Leeftijdscategorie op basis van onderkaak & meldingsformulieren: 5782 (incl. 6 met missing provincie in 2017)

**Comment by SanderDevisscher** [comment]
zie #151
