### ISSUE TITLE
Figures giving an error

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/reporting-rshiny-grofwildjacht#63]
These figures: 
- FIGUUR: Onderkaaklengte per jaar
- FIGUUR: Gewicht per jaar
Give the following error when loading:
 "arguments imply differing number of rows: 44547, 0" and "arguments imply differing number of rows: 28467, 0"

**Comment by stijnvanhoey** [comment]
@SanderDevisscher Is this not due to the latest data update? Have you checked this local? I can reverse the latest deployment if required, but you should solve the data issue

**Comment by SanderDevisscher** [comment]
@stijnvanhoey I'look into the possibility of a data error.

**Comment by SanderDevisscher** [comment]
@stijnvanhoey fix by setting the model results to numeric (see [commit fb9af9bac01116fa8ce89568ddea5b60e6359039](https://github.com/inbo/reporting-rshiny-grofwildjacht/commit/fb9af9bac01116fa8ce89568ddea5b60e6359039))
