### ISSUE TITLE
flemish reference-graph includes NA - provinces 

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/reporting-rshiny-grofwildjacht#67]
The reference - graph includes the NA - provinces while all subsequent graphs and tables don't

**Comment by SanderDevisscher** [comment]
However new georeferenced data reduces the problem it still exists. 

| Jaar | Number Online With NA's | Number New Data With NA's | Number Online Without NA's | Number New Data Without NA's | Difference Online | Difference New Data |
|:----:|:-----------------------:|:-------------------------:|:--------------------------:|:----------------------------:|:-----------------:|:-------------------:|
| 2016 |           941           |            943            |             746            |              932             |        195        |          11         |
| 2017 |           1561          |            1549           |            1496            |             1542             |        65         |          7          |
| 2018 |           770           |            1615           |             708            |             1614             |         62        |          1          |

@jimcasaer delay release untill fix is found? 
@stijnvanhoey do you know where the script is that makes the reference graph ?

**Comment by stijnvanhoey** [comment]
https://github.com/inbo/reporting-rshiny-grofwildjacht/blob/master/reporting-grofwild/inst/ui/server.R#L840

**Comment by SanderDevisscher** [comment]
Row 852 of the script sets all "locatie == Vlaams Gewest" & Row 855  subsets on this.

**Comment by jimcasaer** [comment]
@SanderDevisscher current situation of issue unclear to me

**Comment by SanderDevisscher** [comment]
@machteld how do we handle animals without province atm?

**Comment by mvarewyck** [comment]
For the map, we currently exclude data with missing "afschotjaar" or location (one of province, commune, ... as selected by the user).
When selecting "provincie", this results in the following total Number wild boars shot

| year | total |
|---|---|
| 2016 | 910 |
| 2017 | 1561 |
| 2018 | 1688 |

These numbers match exactly those for "TABEL: Gerapporteerd afschot per regio en per leeftijdscategorie".
