### ISSUE TITLE
Set correct datasource for labeltype graphs and tables

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/reporting-rshiny-grofwildjacht#69]
related to [#164](https://github.com/inbo/backoffice-wild-analyse/issues/164) from backoffice wild - analyse

Check and fix sourcedata from these tables & graphs:
- TABEL: Gerapporteerd afschot per regio en per type
- TABEL: Percentage gerealiseerd afschot per regio en per type
- FIGUUR: Percentage gerealiseerd afschot per jaar en per type

**Comment by jimcasaer** [comment]
@SanderDevisscher staat deze nu nog open of opgelost en closed ?

**Comment by SanderDevisscher** [comment]
@jimcasaer dit is in orde
