### ISSUE TITLE
Is it possible to disable some faulty graphs/tables before publishing?

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/reporting-rshiny-grofwildjacht#72]
@stijnvanhoey the graphs below are currently still incorrect (see #71 & #69). However they are not the most important ones, so we were wondering if it is possible to disable these until the problems are fixed? 
All other graphs/tables are correct. 

- [x] FIGUUR: Percentage jaarlijks afschot
- [x] FIGUUR: Percentage gerealiseerd afschot per jaar en per type
- [x] TABEL: Percentage gerealiseerd afschot per regio en per type
- [x] TABEL: Gerapporteerd afschot per regio en per type
- [x] FIGUUR: Gerapporteerd aantal embryo's voor vrouwelijke reeën per jaar

**Comment by stijnvanhoey** [comment]
Yes, you can remove or comment out the code in the [ui.R](https://github.com/inbo/reporting-rshiny-grofwildjacht/blob/master/reporting-grofwild/inst/ui/ui.R) file

**Comment by SanderDevisscher** [comment]
Commit (3a4081d) is named incorrectly. It actually should be Disable FIGUUR: Percentage gerealiseerd afschot per jaar en per type,  TABEL: Percentage gerealiseerd afschot per regio en per type &  TABEL: Gerapporteerd afschot per regio en per type
