### ISSUE TITLE
Bronnen omvormen naar compilatie kolommen

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/reporting-rshiny-grofwildjacht#79]
Als INBO en Meldingsformulier.

**Comment by SanderDevisscher** [comment]
FIGUUR: Geslachtsverdeling binnen het afschot per leeftijdscategorie
FIGUUR: Leeggewicht per leeftijdscategorie (o.b.v. onderkaak) en geslacht
FIGUUR: Onderkaaklengte per leeftijdscategorie (o.b.v. onderkaak) en geslacht
FIGUUR: Onderkaaklengte per jaar (INBO en Meldingsformulier)

**Comment by SanderDevisscher** [comment]
Leeftijdcategorie == leeftijd_comp 
Onderkaaklengte == onderkaaklengte_comp 
Geslacht == geslacht_comp

**Comment by SanderDevisscher** [comment]
@mvarewyck blijkbaar omvat geslacht.MF reeds een compilatie van de geslachten. Je kan de kolom geslacht.MF dus blijven gebruiken.

**Comment by mvarewyck** [comment]
Needs double-check:
For which plots do we **(not)** want to use the compiled variables?
e.g. FIGUUR: Percentage jaarlijks afschot voor "Ree" gebruikt nu leeftijd_comp om "type" te bepalen.
Was not in original list:

> FIGUUR: Geslachtsverdeling binnen het afschot per leeftijdscategorie
> FIGUUR: Leeggewicht per leeftijdscategorie (o.b.v. onderkaak) en geslacht
> FIGUUR: Onderkaaklengte per leeftijdscategorie (o.b.v. onderkaak) en geslacht
> FIGUUR: Onderkaaklengte per jaar (INBO en Meldingsformulier)
