### ISSUE TITLE
reproduce plots wildschade from powerpoint

### ISSUE THREAD

**Issue by mvarewyck** [inbo/reporting-rshiny-grofwildjacht#88]
@jimcasaer Zou je de powerpoint kunnen bezorgen met de figuren die in de applicatie zouden moeten komen?

**Comment by jimcasaer** [comment]
@mvarewyck 

- [ ] hang ik de ppt hier ergens aan of stuur ik je die gewoon door ? 

- [ ] eventueel eerst nog even bekijken binnen het team : binnen welke termijn wil je de voorstellen voor figuren krijgen ? 

- [ ] betreft dit ook de kaarten ? was dit vroeger niet al een besproken (ben even de draad kwijt)

**Comment by mvarewyck** [comment]
> * [ ]  hang ik de ppt hier ergens aan of stuur ik je die gewoon door ?
best hierbij voegen, dan blijft alles samen
> * [ ]  eventueel eerst nog even bekijken binnen het team : binnen welke termijn wil je de voorstellen voor figuren krijgen ?
zodra jullie groen licht geven, werk ik hieraan
> * [ ]  betreft dit ook de kaarten ? was dit vroeger niet al een besproken (ben even de draad kwijt)
Kaarten hadden we idd besproken 
(1) Gelijkaardig aan grofwild. Bijkomende opties zijn keuze voor diersoort en eenheid: aantal cases of aantal beschadigde percelen.
(2) Bijkomende kaart met meer detail, welk perceel schade plaats vond. Hierover was nog discussie ivm privacy.

**Comment by SanderDevisscher** [comment]
@mvarewyck heb je de ppt ondertussen ontvangen ?

**Comment by mvarewyck** [comment]
@jimcasaer @SanderDevisscher Nee, niet ontvangen :)

**Comment by SanderDevisscher** [comment]
@jimcasaer kan je die ppt dringend hier eens uploaden ?

bestand draggen en droppen in een comment ;-)

**Comment by jimcasaer** [comment]
dit zijn de figuren
ik heb ze even uit de ppt geplukt
![diersoort](https://user-images.githubusercontent.com/17747176/69268715-f4b72300-0bcf-11ea-819b-7315c792741b.png)
![plantensoort](https://user-images.githubusercontent.com/17747176/69268716-f54fb980-0bcf-11ea-9b85-2350bd4af3d2.png)
![type schade](https://user-images.githubusercontent.com/17747176/69268717-f54fb980-0bcf-11ea-8a6c-84018af32a89.png)
![Verkeersslachtoffers everzwijn 2018 (eloket, NP)](https://user-images.githubusercontent.com/17747176/69268718-f54fb980-0bcf-11ea-89f0-44d220b05672.jpg)
![Wildschade everzwijn 2018](https://user-images.githubusercontent.com/17747176/69268719-f54fb980-0bcf-11ea-853f-9fbeeea97d8a.jpg)

**Comment by SanderDevisscher** [comment]
done
