### ISSUE TITLE
Fix missing faunabeheerzone

### ISSUE THREAD

**Issue by mvarewyck** [inbo/reporting-rshiny-grofwildjacht#89]
In `rshiny_reporting_data_geography.csv` many values are missing (60%) for variable faunabeheerzone. Some of these might be reproduced from available `gemeente_afschot_locatie` if gemeente lies entirely within faunabeheerzone?

```
> sum(is.na(geoData$FaunabeheerZone))
[1] 55063
> nrow(geoData)
[1] 92281
```

**Comment by SanderDevisscher** [comment]
Most of the missing values concern data prior to 2014, correct ? 
The rest are individuals with no sufficient information to determine the Faunabeheerzone with any certainty. 
The goeref script looks at gemeente_afschot_locatie, wbe, xy, etc... and tries to determine the Faunabeheerzone but it is limited to labels post 2014. 
We could, once, using the  gemeente_afschot_locatie try to do this with data prior to 2014. The question however is, is this relevant/usefull?

What do you think @jimcasaer ?

**Comment by SanderDevisscher** [comment]
fixed
