### ISSUE TITLE
copying of files on `runWildApp`

### ISSUE THREAD

**Issue by stijnvanhoey** [inbo/reporting-rshiny-grofwildjacht#9]
Looking at https://github.com/inbo/reporting-rshiny-grofwildjacht/blob/master/reporting-grofwild/R/runWildApp.R#L37 the `runWildApp` will always copy the files before running the app. I wonder if this is really required, as it will execute this as well [in the Docker container ](https://github.com/inbo/reporting-rshiny-grofwildjacht/blob/master/Dockerfile#L47), whereas the data is already available by installing the package itself. As such, this will increase the initial loading time of the app?

**Comment by mvarewyck** [comment]
Good remark, for local use it is sometimes needed e.g. when creating a report and the ui folder is not writeable. I tested, but for this application it is not needed, so I adapted the code accordingly.

**Comment by stijnvanhoey** [comment]
fixed
