### ISSUE TITLE
update readme.md for extdata

### ISSUE THREAD

**Issue by mvarewyck** [inbo/reporting-rshiny-grofwildjacht#90]
For ecology/geography data
- include info on computed variables 
- include info on faunabeheerzone

For wildschade
- include info on available variables

Also clean these data files, some variables became redundant.

**Comment by SanderDevisscher** [comment]
@mvarewyck done ?

**Comment by mvarewyck** [comment]
Doing so, I found

* In `rshiny_reporting_data_geography.csv`: One observation with provincie == "#N/B" is now replaced with NA.
* How to define these? And are/will they ever be used?
| WBE_Naam_Georef              | factor        | wildbeheereenheid                        |
| KboNummer_Georef             | factor        | KBO nummer voor WBE                      |
| WBE_Naam_Toek                 | factor        | wildbeheereenheid                        |
| KboNummer_Toek                 | factor        | KBO nummer voor WBE                      |

**Comment by SanderDevisscher** [comment]
> In rshiny_reporting_data_geography.csv: One observation with provincie == "#N/B" is now replaced with NA.

ok

> How to define these? And are/will they ever be used?
> | WBE_Naam_Georef | factor | wildbeheereenheid |
> | KboNummer_Georef | factor | KBO nummer voor WBE |
> | WBE_Naam_Toek | factor | wildbeheereenheid |
> | KboNummer_Toek | factor | KBO nummer voor WBE |

They will not be used for this app since these columns contain delicate information. I shall remove them from geography!

> geslacht.MF: Just double-checking, this is the computed combination, i.e. INBO if known and otherwise MF?

correct

**Comment by eadriaensen** [comment]
> They will not be used for this app since these columns contain delicate information. I shall remove them from geography!

I removed them from the readme.md file.
When removed from the geography.csv file this issue can be closed.
