### ISSUE TITLE
schaal afschot per 100ha

### ISSUE THREAD

**Issue by jimcasaer** [inbo/reporting-rshiny-grofwildjacht#91]
de actuele schaal op de kaartjes met afschot per 100 ha resulteert in heel veel gemeenten met dezelfde schaal 0-1 
mijn voorstel zou zijn van de schaal te herwerken naar 
0
0-0.25
0.25 - 0.5
0.5-1
1-2
2-3
3-4
>4 (komt nog zo goed als niet voor dus eventueel niet nodig en >3 nemen

**Comment by SanderDevisscher** [comment]
dus laatste schaal zou 3+ moeten worden dan.
