### ISSUE TITLE
Show polygon instead of point on wildschade map

### ISSUE THREAD

**Issue by mvarewyck** [inbo/reporting-rshiny-grofwildjacht#93]
If available, show polygon instead of point on Landkaart 2.

```
> sum(!is.na(schadeData@data$perceelPolygon))
[1] 641
> nrow(schadeData@data)
[1] 873
> table(schadeData@data$schadeBasisCode)

ANDERE  GEWAS   VRTG 
   236    447    190 
```

**Comment by SanderDevisscher** [comment]
@mvarewyck polygons should be used only in case of gewasschade in all other cases it should be points

**Comment by jimcasaer** [comment]
@SanderDevisscher @mvarewyck zouden we niet ook voor de schade aan percelen gewoon het punt weergeven (midden van polygon ?) lijkt me eenduidiger ? niet ?

**Comment by SanderDevisscher** [comment]
@jimcasaer ik ben van mening dat de polygoon leuker/overzichtelijker is dan een centroid. Bovendien is het onderscheid tussen gewasschade en verkeersongevallen/andere wel relevant.

**Comment by jimcasaer** [comment]
maar je zet ze toch niet op dezelfde kaart ?

Dr.ir. Jim Casaer

Senior Researcher
Research Group wildlife Management / OT  Faunabeheer en Exoten/
Research Institute for Nature and Forest / Instituut voor Natuur- en
Bosonderzoek



Havenlaan 88 bus 73,
1000 Brussel

jim.casaer@inbo.be
** 32 478 281 701
www.inbo.be
orcid : 0000-0001-6788-5876




Op do 10 okt. 2019 om 14:10 schreef Sander Devisscher <
notifications@github.com>:

**Comment by SanderDevisscher** [comment]
feit, Anneleen is het met je eens ;-)
pak maar centroides => er veranderd niets
