### ISSUE TITLE
Barplot for no. cases per region and year

### ISSUE THREAD

**Issue by mvarewyck** [inbo/reporting-rshiny-grofwildjacht#95]
* Similar to the graph as for Grofwild:
* Add option to select region-level: Vlaanderen, Provincie, Faunabeheerzone

![histogram](https://user-images.githubusercontent.com/22143743/66573343-cd058180-eb72-11e9-83fc-cf1f94fe57a0.png)

**Comment by SanderDevisscher** [comment]
@mvarewyck best to rename graph to "Gerapporteerd aantal *schadeclaims* per jaar per regio"
