### ISSUE TITLE
Color points by season

### ISSUE THREAD

**Issue by mvarewyck** [inbo/reporting-rshiny-grofwildjacht#96]
In this map, the points should be given a color code according to the season. This to see a potential moving trend during the year.

![map](https://user-images.githubusercontent.com/22143743/66574175-10142480-eb74-11e9-9ee8-18b116700160.png)

Howto: See section Awesome Icons at https://rstudio.github.io/leaflet/markers.html

**Comment by mvarewyck** [comment]
Seasons start at
winter: 21/12
lente: 21/3
zomer: 21/6
herfst: 21/9

**Comment by mvarewyck** [comment]
`DatumVeroorzaakt` is used to extract the season. What if missing? Currently colored gray.
Then sometimes other dates are known: `IngediendDatum` or `DatumVaststelling`

Screenshot from 2019-11-18 17-06-05
![image](https://user-images.githubusercontent.com/22143743/69068834-bc73e100-0a25-11ea-9cda-2248e55b6547.png)

**Comment by mvarewyck** [comment]
Another question on these maps: Is the case ID confidential? Or redundant in popup window?
@jimcasaer @SanderDevisscher 

![image](https://user-images.githubusercontent.com/22143743/69150430-f0f4a500-0ad8-11ea-9c1e-83a2437f1cee.png)

**Comment by jimcasaer** [comment]
for me it is redundant for the pop-up
jim

Dr.ir. Jim Casaer

Senior Researcher
Research Group wildlife Management / OT  Faunabeheer en Exoten/
Research Institute for Nature and Forest / Instituut voor Natuur- en
Bosonderzoek



Havenlaan 88 bus 73,
1000 Brussel

jim.casaer@inbo.be
** 32 478 281 701
www.inbo.be
orcid : 0000-0001-6788-5876




Op di 19 nov. 2019 om 14:30 schreef mvarewyck <notifications@github.com>:

**Comment by SanderDevisscher** [comment]
@mvarewyck I reduced the number of NA's in `DatumVeroorzaakt` by correcting the mapping for the different datasources. This was implemented in the last pull request to the master (#99).  
Should be fixed with a rebase.

Concerning the id dropping it is best choice.

**Comment by mvarewyck** [comment]
Ok, I will check again when the wildschade branch is ready to be merged with master.

**Comment by eadriaensen** [comment]
Upon checking this map with the newest data, a bunch of cases were assigned to `zomer 2020`, which is in the future..
![zomer2020](https://user-images.githubusercontent.com/40824010/73930484-db706980-48d6-11ea-9578-573a61ccfd87.png)

Looking at the raw data file (WildSchade_georef.csv) there seems to be a discrepancy between `Jaartal` and `DatumVeroorzaakt` for some cases.
There are cases for which `Jaartal = 2020` while `DatumVeroorzaakt = 2019-..-..`

Which date and/or year variable should be used?

**Comment by SanderDevisscher** [comment]
Blijkbaar slaat Jaartal in sommige gevallen op de dossier datum. 
In het kader van deze kaartjes kan je best DatumVeroorzaakt gebruiken.

Ik zal het Jaartal herbereken o.b.v. DatumVeroorzaakt  zodat het probleem zich niet meer voordoet.
Morgen nieuwe data ;-)

**Comment by eadriaensen** [comment]
Ok!

**Comment by SanderDevisscher** [comment]
Met nieuwe data ziet het er zo uit:
![image](https://user-images.githubusercontent.com/16779320/74011755-dff55a80-4988-11ea-84ae-bef15615b1b1.png)

in orde dus
